### ISSUE TITLE
Create cg workflow for MUTANT pipeline

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#1036]
## Description

Mutant pipeline should be automatically configured and started by cg

## Suggested solution
 Create workflow

## This can be closed when

- [x] Create a workflow that links and concatenates analysis files
- [x] Create config for running the workflow
- [x] Automatically start analysis
- [ ] Track progress in Trailblazer

**Comment by henrikstranneheim** [comment]
@Mropat The top three in the checklist are completed right?

**Comment by Mropat** [comment]
@henrikstranneheim yes!
