### ISSUE TITLE
Demultiplex from CG

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#1037]
## Description

Right now the demultiplex package is a mixture of python code and bash scripts. We should move the functionality to CG and convert it all to python to get better control of one of the most crucial processes at CG.

## Suggested solution

Create a demultiplex api that handles creation of sample sheets and starting of demultiplexing on Slurm. There should be a CLI function that loops over the directories and find the flow cells that are ready for demultiplexing.

## This can be closed when

- [x] CG can demultiplex all flow cells that are ready with command `cg demultiplex all`

**Comment by henrikstranneheim** [comment]
@moonso Done?

**Comment by moonso** [comment]
Yes!!
