### ISSUE TITLE
Wrong scout link in delivery reports

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#1049]
## Description

link in delivery report becomes https://scout.scilifelab.se/cust000/21222/scout.scilifelab.se/cust000/21222.0 

## Suggested solution

Should become https://scout.scilifelab.se/cust000/21222

## This can be closed when

- [ ] link becomes usable

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ivadym** [comment]
The links are working:

<img width="591" alt="Screen Shot 2022-06-13 at 10 29 20" src="https://user-images.githubusercontent.com/26309194/173312358-32dace30-277a-4203-bd4b-552f44bbc2a7.png">
