### ISSUE TITLE
Handling of pre-CASAVA 1.8 fastq files

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#106]
DN wants to be able to import pre-CASAVA 1.8 fastq files into our analysis workflow. This used to work and we need to investigate why it stopped working.

- Did this used to work?
  - yes: bring it back, sing it back.
  - no: Change "Transfer files to/from CG - user manual" to highlight we only handle post-CASAVA 1.8 fastq files.

**Comment by emiliaol** [comment]
There has been some effort to make this happen. The quality scores needs to be converted as well as the headers. Might be a script somewhere described in the processing of external files in AM

**Comment by henrikstranneheim** [comment]
I will close this! We can open a new issue when if this happens again with a better description and a new case that needs to be fixed.
