### ISSUE TITLE
CG use deprecated packages as dependencies

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#1069]
## Description

CG is built on packages that are deprecated or not maintained. The result of this is potential security issues, unresolvable dependency trees etc.

## List of dependencies

- [Alchy](https://github.com/dgilland/alchy/) has not been updated in 4 years and are forcing CG to update SQLAlchemy which is the database engine
- [Flask-Alchy](https://github.com/dgilland/flask-alchy) not been updated in 5 years
- `requests[sequrity]` seems to [make requests more brittle](https://github.com/psf/requests/issues/5267)
- [colorclass](https://github.com/Robpol86/colorclass) archived and not updated in 4 years
- [petname](https://pypi.org/project/petname/2.6/) no releases in 2 years
- [pyschemes](https://github.com/spy16/pyschemes) not updated in 3-4 years
- [python-dateutil](https://github.com/dateutil/dateutil) Not released in 2 years

## Suggested solution

Replace/remove the deprecated packages

## This can be closed when

- [ ] Each of the packages above is not a dependency of CG anymore

**Comment by patrikgrenfeldt** [comment]
This issue has been broken into smaller ones, closing this one
