### ISSUE TITLE
Dependency tree should be resolved during development

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#1070]
## Description

Dependencies gets added and sometimes they get updated. Other times the dependency of a dependency changes etc. This will eventually lead to something known as [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell). There are a number of ways to attack this problem. The way we tackle it in CG today is to manually lock or set a constraint on a dependency when the build fails for some reason, often at runtime or when CG is installed on one of the servers.
Another way to handle this problem is to use a dependency resolver, there are a number to choose from in python with the most well used being [poetry](https://python-poetry.org) and [pipenv](https://pipenv-fork.readthedocs.io/en/latest/).

## Suggested solution

Suggest to use poetry so that the dependency tree is resolved at development time instead of installation time with the result that the dependencies that are installed when developing is the exact same as the ones that are running in the continuous testing environment and also in production. 

## This can be closed when

- [ ] CG is using a dependency resolver that produces a lock file. 
- [ ] The lock file should be used in the installation
- [ ] This solution should be possible to implement on all servers where cg is installed at Clinical Genomics
- [ ] It needs to be able to install cg somehow on clinical-db until it is decommissioned

**Comment by Mropat** [comment]
Will not be fixed in this version of orderportal/cg
