### ISSUE TITLE
Investigate how to install cg using Poetry on Hasta and Clinical-db

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1073]
## Description
Cg needs to be installed on both Hasta and Clinical-db using either poetry or pip, but preferentially using poetry.

## This can be closed when
- [ ] When there is a solution to install cg with locked dependencies on Hasta and Clinical-db.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Mropat** [comment]
Closing this:
Issue will not be worked on since we are retiring clinical-db. Once retired, we will install same versions of dependencies on hasta and inside containers on CGVS
