### ISSUE TITLE
Remove ancient dependency to Alchy

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#1074]
## Description

CG has an old package dependency that needs a resolution

## Suggested solution

Replace/remove the deprecated packages 
- [Alchy](https://github.com/dgilland/alchy/) has not been updated in 4 years and are forcing CG to update SQLAlchemy which is the database engine

## This can be closed when

- [ ] The packages above is not a dependency of CG anymore

**Comment by Mropat** [comment]
Will not be a dependency in new orderportal
