### ISSUE TITLE
Remove archived dependency colorclass

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#1077]
## Description

CG has an old package dependency that needs a resolution

## Suggested solution

Replace/remove the deprecated packages 
- [colorclass](https://github.com/Robpol86/colorclass) archived and not updated in 4 years

## This can be closed when

- [x] The packages above is not a dependency of CG anymore

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt Great work! I will close this!
