### ISSUE TITLE
Remove old dependency petname

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#1078]
## Description

CG has an old package dependency that needs a resolution

## Suggested solution

Replace/remove the deprecated packages 
- [petname](https://pypi.org/project/petname/2.6/) no releases in 2 years

## This can be closed when
~The packages above is not a dependency of CG anymore~
- [x] This is not a problem to CG

**Comment by patrikgrenfeldt** [comment]
I looked into the code and I think it is more or less as @Mropat says, it's not touched because it is already perfect. It seems to me to lack dependencies as well. 

I suggest we close this issue, ok?

**Comment by moonso** [comment]
Yes I was also in contact with the maintainer and he has not dropped it 😄
