### ISSUE TITLE
Validate post lab information coming from LIMS

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#108]
As a production person, I want to know as early as possible that data is missing so that I can minimize the turnaround time for the samples.

Problem: information is added in LIMS in two occasions: from the order portal and from the lab during the prep. The order portal validates and checks for completion of the information.

Steps to reproduce
  1. Create a MIP order in the order portal
  2. Complete the preparation in LIMS but don't fill in all information relevant for MIP to start

Expected outcome:
dunno

Actual outcome:
MIP fails to start

Suggested solution:
Add crontab entry to validate the data of prepped samples
`cg validate preped`
email team production when samples fail validation

We should validate and check for completion after the lab is finished with the sample (after prep).
Check for completion means the check that all fields are filled in for automatic start of the analysis.

How to demo:
1. create a MIP order in OP
2. set it as received in LIMS
3. set it as preped in LIMS
4. run `cg validate preped`
5. show the output

Questions: 
Q1: Should we close this issue and let MIP continue to fail to start?
A1:

**Comment by emiliaol** [comment]
@patrikgrenfeldt Wanna flesh this out a bit? If needed we can think about it together

**Comment by emiliaol** [comment]
@patrikgrenfeldt Something you think we should spend time on? Then add it to the backlog please

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt Still relevant?

**Comment by patrikgrenfeldt** [comment]
@emmser , would having this add anything for you in production? If not, please close this issue

**Comment by emmser** [comment]
I don't know what this is about
