### ISSUE TITLE
SAWarning on relationship Demux.samples

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#1081]
## Description

Whenever we start cg we get the warning:
```
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
```

## Suggested solution

investigate why we get the warning and fix the issue (or silence the warning if it should be silenced)

## This can be closed when

- [ ] cg can be started without getting the warning above

**Comment by Mropat** [comment]
Non-critical bug, reopen if this is interfering significantly with operations
