### ISSUE TITLE
Finish up after demultiplexing

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#1090]
## Description

CG now has the ability to start demultiplexing of flow cells and run the jobs on slurm. However there are some work being done when demultiplexing ends that is currently taken care of by a combination of the [demultiplex](https://github.com/Clinical-Genomics/demultiplexing) package [here](https://github.com/Clinical-Genomics/demultiplexing/blob/ba52030d83dcd70fa72d7f3f121ceac75275f302/scripts/novaseq/demux-novaseq.bash#L58) and by the [delivery](https://github.com/Clinical-Genomics/deliver) package [here](https://github.com/Clinical-Genomics/deliver/blob/2406ca49d5206a53ef2ec4763b407e30185db9a3/scripts/checkfornewdemuxonhasta.bash)

To be able to drop the other packages this functionality should be transferred into CG

## Suggested solution

Replicate the functionality from these packages so that CG does the same thing.

## This can be closed when

- [x] Demultiplexing of novasseq flow cells can be completely run by CG

**Comment by henrikstranneheim** [comment]
@moonso and @barrystokman Great work! I think this is done -would you agree!
