### ISSUE TITLE
Enable BALSAMIC Chanjo upload

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#1092]
## Description

The cancer track currently receive static coverage reports to Scout for each delivered case. For the RD track, dynamic coverage reports via Chanjo are available. Chanjo upload is run from CG on MIP output for the RD side. A similar mechanism for Chanjo loading for Balsamic is envisioned. 

See e.g. https://github.com/Clinical-Genomics/cg/issues/880 for some discussion.

## Suggested solution

Implement upload of chanjo data for balsamic cases in cg. A separate chanjo instance will likely be needed to cater to panels and possibly exomes. 

## This can be closed when

Chanjo coverage data is available for display on Balsamic cancer cases in Scout. 

## Blocked by

May depend on Clinical-Genomics/project-planning#81 if gene model definitions differ.

**Comment by Mropat** [comment]
Chanjo2 is under development and new functionality will not be added to current chanjo
