### ISSUE TITLE
CG needs to be able to backup fastq files

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#110]
Problem: CG needs to be able to send encrypted fastq files to slow storage.
Reason: Externally sequenced fastq files do in some cases not exist anywhere else than on our servers once they are delivered to us for analysis.
 
This includes:

- Encrypting + sending them to PDC
- Marking fastq files as "archived" denoting they are not on disk in HK
- Being able to retrieve fastq back from PDC (what is hte interface?)
- Invoice the customer for storage

**Comment by emiliaol** [comment]
I will try to split this up in several user stories to make it more bit sized tasks. I'll add them as related cards but not put this original story on the backlog.
