### ISSUE TITLE
Alembic fails on stage with msg "Can't locate revision identified by ..."

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1106]
## Description

The update script fail often when testing new branches on stage with:
```
Already on 'master'
Already up-to-date.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.util.messaging] Can't locate revision identified by '49ded71bd1a1'
  FAILED: Can't locate revision identified by '49ded71bd1a1'
```

The solution is usually to log in to clinical-db and copy the cg database from prod to stage on Hasta. However, sometimes there are processes that lock the database copy process and these processes needs to be killed before a database copy can be successfully comlepleted. This makes the testing process more cumbersome than it needs to be.

## Suggested solution

- Document how to find any potential processes that stales the copy and how to safely kill them.
- Consider solutions to not end up in the situation leading to the revision error by modifying the update scripts

## This can be closed when

- [ ] You can checkout a branch in cg on stage and not find it broken by previous testing/updates

**Comment by Mropat** [comment]
Branch is still updated, alembic fails after installation
We need to manually copy prod to stage on clinical-db to get rid of the message
