### ISSUE TITLE
Fluffy data_analysis field from rml json is parsed as FASTQ in StatusDB

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#1110]
## Description
NIPT/FLUFFY rml orders get the wrong analysis type in statrusDB
![image](https://user-images.githubusercontent.com/35531751/114864320-234f2280-9df1-11eb-9fc5-cac5b0c6af99.png)

## This can be closed when
Data analysis field is parsed as "fluffy" instead

**Comment by patrikgrenfeldt** [comment]
resolved by https://github.com/Clinical-Genomics/cgweb/pull/306
