### ISSUE TITLE
New fields on LIMS sample for cov - GISAID upload

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#1115]
## Description

We need two new fields that should be populated via orderportal and avalible to cg for gisaid upload of covid samples.

The fields will be saved as sample udfs in lims

**UDF names:**
- Collection Date _(date when sample was taken)_ Format: "2020-11-22"
- Original Lab _(lab that originaly took the sample)_

The fields need to be added to the orderform for covid samples. They should be requiered in the covid order form.

We are waiting for the optional fields for Original Lab 

Probably @patrikgrenfeldt and @JessicaHillert are the once that would be working on this

**Comment by Mropat** [comment]
will be stored in lims, closing. Issue about orderportal field has been made

**Comment by mayabrandi** [comment]
@JessicaHillert @moedarrah @patrikgrenfeldt I just got to know that there will be another field; Region. I will get information about the allowed values for the fields today.

**Comment by patrikgrenfeldt** [comment]
What is the difference between "Region Code" and "Region"? 
![image](https://user-images.githubusercontent.com/6697636/116506144-ec7f0f00-a8bc-11eb-8d89-a6f24c8946b3.png)

**Comment by mayabrandi** [comment]
Yes! It looks like that! We need to have a meeting about this. @patrikgrenfeldt Ill slack you!

**Comment by annagellerbring** [comment]
> Yes! It looks like that! We need to have a meeting about this. @patrikgrenfeldt Ill slack you!

Let me know also if there will be changed to the OF or not

**Comment by mayabrandi** [comment]
Hej. I now have all the information we need. We will have to do changes to the orderform:

- Change the **Region Code** column
- Add a **Region** column
- Add a **Collection Date** column
- Add a **Original Lab** collumn
- Add a **Original Lab Address** collumn

The lab address and region code will be autop generated in the order form. 

I made the requiered changes to a orderform where you can have a look. Ill attach it here. Lets have a meeting and talk about it soon.

**Comment by mayabrandi** [comment]
[sarscov2_new_version.xlsx](https://github.com/Clinical-Genomics/cg/files/6415188/sarscov2_new_version.xlsx)

**Comment by JessicaHillert** [comment]
> * Change the **Region Code** column
> * Add a **Region** column

Change the **Region Code** to **Region**?

**Comment by mayabrandi** [comment]
@patrikgrenfeldt will explain to you! @JessicaHillert @moedarrah

**Comment by mayabrandi** [comment]
Column mapping:
https://docs.google.com/spreadsheets/d/1AK7X2zelLyOL1N9uJ6gaEKawJdin4K9a09pfGe7TVeo/edit#gid=611360557

@patrikgrenfeldt @annagellerbring

**Comment by JessicaHillert** [comment]
To summarize:
New fields that the user can edit:
- Region (dropdown, i.e. Stockholm, Uppsala)
- Original Lab (dropdown with name of labs)
- Collection date (format?)

Calculated fields (which the user cannot manually edit):
- (Exists as editable currently) Region code
- (New) Original Lab Address

**Comment by annagellerbring** [comment]
> To summarize:
> New fields that the user can edit:
> 
> * Region (dropdown, i.e. Stockholm, Uppsala)
> * Original Lab (dropdown with name of labs)
> * Collection date (format?)
> 
> Calculated fields (which the user cannot manually edit):
> 
> * (Exists as editable currently) Region code
> * (New) Original Lab Address

@mayabrandi what about the old UDF Lab code, is it still of value? It looks like that information is included in Original Lab?

**Comment by mayabrandi** [comment]
@Mropat Can you awnser the question above about lab code?

**Comment by mayabrandi** [comment]
I made a[ new orderform](https://docs.google.com/spreadsheets/d/1VEuPqOG0KMUSF37rOdkhlvJEVgUwW6aDnLGeVouzVKs/edit#gid=1089744947) @annagellerbring @patrikgrenfeldt

**Comment by annagellerbring** [comment]
> I made a[ new orderform](https://docs.google.com/spreadsheets/d/1VEuPqOG0KMUSF37rOdkhlvJEVgUwW6aDnLGeVouzVKs/edit#gid=1089744947) @annagellerbring @patrikgrenfeldt

Orderform and AM-doc updated and sent for review

**Comment by Mropat** [comment]
@mayabrandi @annagellerbring We still need the lab code UDF for renaming of the deliverable files! SO it needs to stay

**Comment by annagellerbring** [comment]
> @mayabrandi @annagellerbring We still need the lab code UDF for renaming of the deliverable files! SO it needs to stay

yes, it's there now

**Comment by JessicaHillert** [comment]
@annagellerbring @mayabrandi Can I get the new orderForm with Lab code or access to the drive file?

**Comment by patrikgrenfeldt** [comment]
Resolved by #1155
