### ISSUE TITLE
Fastq files needs to be encrypted to prepare for longterm storage (in-house or external data)

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#112]
Some customers send us externally sequenced data in the form of fastq files for us to do the analysis. This data is not backed up anywhere and should therefor be sent to PDC. This might also be applicable to in-house data when we need to delete specific Bcl files (to comply with GDPR). Before sending to external storage we need to encrypt the files.

Actions:
* Define a storage/processing place for these types of fastq files on our servers
* Write script to easily encrypt selected files/folders using the cli
* Automate the encryption
* ...

Questions:
* Do we need to be able to mark these fastq files in any way to allow for automatic processing? Perhaps marking the sample for fastq-storage?

**Comment by henrikstranneheim** [comment]
The external fastq files should be added to StatusDb and HK and then handled by the usual fastq to spring compression. Spring files will then be transferred to PDC or other archive with the rest of the spring files, when that system is in place.
