### ISSUE TITLE
Can not write any organism we want in status DB, the organism name is selected from a drop down menu

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#1126]
## Description

When setting the organism name in status DB the organism is selected via a drop down menue. Sometimes production want to set an organism name that can not be selected from the drop down menue.

## Suggested solution

Being able to set the organism name by just writing the organism name in free text

## This can be closed when

Organism name can be set via free text, or someone describe why my suggestion is a bad idea.

**Comment by patrikgrenfeldt** [comment]
@henningonsbring Is it in the Orderportal that you can't set the organism name as free text?

**Comment by Mropat** [comment]
Not possible to implement currently:
Organisms are stored in statusdb along with the refseq genome id which microsalt will use for analysis
It is possible to use new organism by adding the organism with all the associated fields in statusdb, and adding a reference genome somewhere in microsalt working directory,

It will take too much work to re-architect how this process work in the current version of cg

**Comment by patrikgrenfeldt** [comment]
New Organisms for the drop-down can be created here: https://cg-statusdb.scilifelab.se/admin/organism
