### ISSUE TITLE
A pricing chart needs to be created for storage and analysis of externally sequenced samples

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#113]
Problem: Customers delivering externally sequenced fastq files does not pay for the storage of the fastq files at CG. Some customers depend on us backing the files up because they do not have a local copy. 

Solution: We can offer this as a service but need to be able to invoice this service.

Actions and questions:
* Define how to charge for this service. By size or per item or other measurements?
* Add the pricing information in status DB

**Comment by emiliaol** [comment]
I also need to figure out if invoices needs to be re-designed for these samples or if the current interface is good enough (question for VW).

**Comment by ChrOertlin** [comment]
Is this a discussion that is ongoing @vwirta, @henrikstranneheim or can we close this issue? It has been open since 2018.

**Comment by henrikstranneheim** [comment]
Agreed, very stale. Let's reopen if needed.

**Comment by vwirta** [comment]
I agree.
I can provide this pricing information using our already established mechanisms when needed. No need to develop anything special in cg.
