### ISSUE TITLE
Both cram and bam are linked with cg deliver analysis 

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/cg#1133]
## Description

Both `cram` and `bam` files are linked to the inbox dir when running `cg deliver analysis` for balsamic cases

## Suggested solution

Only `cram` and `cram.crai` should be linked

## This can be closed when

bam-files are removed from the linking process

**Comment by henrikstranneheim** [comment]
@Clinical-Genomics/cancer Since we are not delivering BAMs anymore - would it be possible to also stop storing them in Housekeeper to save some storage space? We will run out before Christmas so we need to try to save only data that is really required.
