### ISSUE TITLE
Samples with less than 15% of ordered reads are not included in the analysis (cases problem for mikro)

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#1137]
## Description

Samples that got less than 15% of the ordered reads will never be included in the mikroSALT analysis.

This unwanted feature cases two problems:
1) Production use the QC report from mikrosalt to identify which samples that fail, and then we report about the fail to the customers. If we do not see the fails in the report we will assume everything went well and then report that to the customer (even when things went wrong).
2) The customers want to see negative controls in the report.

## Suggested solution

Include all samples in the mikroSALT analysis and reports.

## This can be closed when

All samples are included in the mikroSALT analysis and reports.

**Comment by Mropat** [comment]
Fix deployed. will now send all samples
