### ISSUE TITLE
Externally sequenced samples needs an entry point to the invoicing

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#114]
Today all samples that are to be invoiced are processed in LIMS and end up in the invoicing step in LIMS from where an external process (invoicing in cg) picks them up and creates invoices. 
Tomorrow we need to add externally sequenced samples that are not processed through LIMS to the invoicing process.

Requirements: Externally sequenced samples are automatically or with some manual intervention through a web interface added to the invoicing interface in cg admin.

Actions:
* Add functionality to cg code to pick up samples from other places than LIMS
* Add functionality to web interface to mark samples for invoicing

minor update DoDs

**Comment by henrikstranneheim** [comment]
@vwirta @mayabrandi How is this handled today? Is this still an issue

**Comment by mayabrandi** [comment]
I believe there is a hardcoded exception for cust001 in the code. I can handle this issue as I’m integrating NIPT in the invoicing.

**Comment by henrikstranneheim** [comment]
@mayabrandi What is the status of this?

**Comment by mayabrandi** [comment]
I have not done anything on this. What is the deadline?

**Comment by henrikstranneheim** [comment]
I do not know - maybe @emmser or @vwirta know how much this affects the invoicing procedure or if it is more a code refactoring issue

**Comment by Mropat** [comment]
@henrikstranneheim need help evaluating whether this will be done

**Comment by ChrOertlin** [comment]
@henrikstranneheim is this still relevant?

**Comment by henrikstranneheim** [comment]
I think so, bu ideally we should refine the entire invoicing process instead of cleaning small pieces - closing
