### ISSUE TITLE
Some more edits to the NIPT samplesheet!

### ISSUE THREAD

**Issue by J35P312** [Clinical-Genomics/cg#1142]
Hello!
I have gotten some requests from Agne et al!
We want to have the sequencing date and "starlims arbetslista-nummer" in the fluffy output, to do so, we need to add it to the samplesheet.

Could you add the following to the samplesheet (i.e the file used as samplesheet input for fluffy):

1: we want the "Project" column to be set to the "starlims arbetslista-nummer". Currently the values of this column is set to the ticketnumber.
The "starlims arbetslista-nummer" is found in the json order file, in the "name" field, and in the "pool" field.

2: We would like to have the SequencingDate column! We used ot have this column in the old NIPT analyses, can we use it again?

Thanks!
//JEsper

**Comment by Mropat** [comment]
done
