### ISSUE TITLE
cg backup fetch-flowcell cronjob needs to look for available disk space

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#119]
The cronjob that fetches requested flow cells automatically from PDC now hos a limit of a set number of flow cells with status "ondisk". It's just an arbitrary number and the limit should rather be available disk space.

Requirements: The automatic fetching of backed-up flowcells only happens when there is 10% or more available disk space on rasta.

Actions:
* Add a method that checks disk space to the backup api 
* Change method fetch_flowcell to use the new method

DoD for minor update.

**Comment by henrikstranneheim** [comment]
@barrystokman Still relevant or should we close this one?

**Comment by barrystokman** [comment]
It's relevant, the current and very arbitrary number of maximum flowcells is not a very solid solution. However, I don't think we ever ran into problems with disk space due to fetching from PDC, so I wouldn't make this a very high priority.

**Comment by Mropat** [comment]
Stale issue. Will not be completed within current planning schedule
