### ISSUE TITLE
Updated order-api for starlims mip-dna-json

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#1190]
## Description

At a meeting 2021-06-04 it was decided:
To make changes to the mip-dna-json-api in the Orderportal. The contact person is PG at our end. The new files will be sent to PG in September for testing.

## Suggested solution

1. Change cg/tests/fixtures/orderforms/mip-json.json with new spec.
2. Change tests for new spec.
3. Fix implementation

## This can be closed when

- [x] change synopsis: [str] -> synopsis: str
- [x] new phenotype_groups: [str]
- [x] new subject_id: str (maybe change also for mip-rna 'for-sample'?)
- [ ] new volume: str
- [x] phenotype groups are shown in cgweb
- [x] synopsis is treated as text in cgweb
- [ ] synopsis: str is sent to scout
- [ ] phenotype_groups is sent to scout
- [ ] (subject_id is sent to scout?)

## Blocked by

If the api can handle the old fixture as well as the new then it is OK to deploy it to production

**Comment by patrikgrenfeldt** [comment]
@dnil @northwestwitch Should 'subject_id' be sent to Scout?

**Comment by dnil** [comment]
Yeah, we don't parse it yet, but will add it: https://github.com/Clinical-Genomics/scout/issues/2693. It will not break anything, so feel free to add at any time.
