### ISSUE TITLE
Select multiple (delivery) types in OP/OF

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#120]
A customer needs to be able to select from following options in an OF and the OP:
- fastq
- bam
- vcf
- scout
- merged fastq

We need to be able to select one or more in both OF and OP. This information needs to be stored in status db, most likely candidate is in table family. We might want to add an additional table and needs further discussion.

**Comment by emiliaol** [comment]
@ingkebil @patrikgrenfeldt @emmser Didn't we solve this with the new orderform?

**Comment by patrikgrenfeldt** [comment]
It is currently not possible to mix delivery-types

**Comment by emiliaol** [comment]
Except we mix balsamic and mip

**Comment by patrikgrenfeldt** [comment]
I thought you ment having one row in the OF with data_analysis='MIP' and one row in the same OF with data_analysis='MIP+Balsamic'?

**Comment by vwirta** [comment]
Let me know if you’d like to involve me into this discussion.

For some samples, we will run two different analyses (MIP + BALSAMIC) and deliver results to different places.
'

**Comment by ingkebil** [comment]
Yes, having samples going through one or more pipelines is fixed in the OP. In statusDB, the family now has a data_analysis field which can be set to the pipeline that needs to run.

Deliver what files and whereto has not been addressed yet.

**Comment by emiliaol** [comment]
Now that I think about this I have a feeling it's also about what's possible for the customer to order. Some customers should only be able to order certain types of analysis. @vwirta Wasn't that the discussion? That would make it easier for them to chose.

**Comment by vwirta** [comment]
@emiliaol correct, I think part of this was to help customer choose the appropriate analysis.
Terms such as MIP and BALSAMIC are not necessarily easily understood for new customers.

I am not sure where the different levels of logic are most easy to implement. We can always prepare better description of the various analysis options, or we could perhaps even renamne MIP to 'inherited diseases' or 'rare diseases', and balsamic to 'cancer' or 'somatic analysis' or something like that.

I also agree with KB's comment that there are two questions to this
1) what analysis
2) what to deliver

What to deliver can be addresses in OF/OP, but could also be set in a customer specific config?

**Comment by emiliaol** [comment]
Yeah, that's what I thought. I'll put it on the backlog.

**Comment by Mropat** [comment]
@patrikgrenfeldt is this still relevant?

**Comment by henrikstranneheim** [comment]
I am going to close this since as far as I know the customers are not complaining and are not confused about this. Reopen if you disagree
