### ISSUE TITLE
Fix flowstatus status to be synced between file system and StatusDB

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1207]
## Description
Currently, the flowcells recorded as `ondisk` might not be ondisk and vice versa

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Mropat** [comment]
@barrystokman @henrikstranneheim is this still an issue?

**Comment by barrystokman** [comment]
No, this has been fixed, closing issue.
