### ISSUE TITLE
Move delivery excel into cg

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#122]
Now CG personnel relies on an outdated excel sheet with delivery information. That information should find its place in status db, on customer level.

See also Clinical-Genomics/cg#121 and Clinical-Genomics/cg#120

**Comment by emiliaol** [comment]
https://docs.google.com/spreadsheets/d/1188xcgz24kiXwXtj5we6iT7aK2FUKNswHSZPtJBt76o/edit#gid=0

**Comment by henrikstranneheim** [comment]
@emmser Is this still relevant?

**Comment by emmser** [comment]
It's not relevant if we have all delivery options for all customers in cg, maybe the split of analysis and delivery in cg will solve this issue, at least for most of cases
