### ISSUE TITLE
Should we really deliver both .bam and .cram files?

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#1221]
## Description

Right now when using delivery type "balsamic" when running `cg deliver analysis -d balsamic -t ticket` we deliver both .cram and .bam see for example:
`/home/proj/production/customers/cust127/inbox/402807/GMSB-ST003/MOL1405-21G/normal.merged.bam`
`/home/proj/production/customers/cust127/inbox/402807/GMSB-ST003/MOL1405-21G/normal.merged.cram`

## Suggested solution

We only deliver cram

## This can be closed when

We close this ticket when either:
1) We deliver only .cram
2) Someone explain in the comment section why both files are needed

Probably it will be enough to remove some lines from cg/constants/delivery.py:
```
BALSAMIC_ANALYSIS_SAMPLE_TAGS = [
    {"cram", "normal"},
    {"cram-index"},
    {"cram", "tumor"},
    {"cram-index", "tumor"},
    {"bam"}, # Remove this line?
    {"bam-index"}, # Remove this line?
]
```

**Comment by henningonsbring** [comment]
@hassanfa do we need both .bam and .cram? They should be the same right, just one is compressed?

**Comment by Mropat** [comment]
if balsamic creates cram for all analysis types (T, TN, panel, wgs) then we can just stop storing bam in hk, and deliver only cram :+1:

**Comment by hassanfa** [comment]
CRAM storing is produced and ok to store. I'll add reference fasta to BALSAMIC's store as well for reproducibility purposes.

Let me know if you want some changes with Hermes tag changes.

**Comment by Mropat** [comment]
If reference fasta is small then ok. But if its human reference fats, thats a few G of same kind of file in every bundle

**Comment by henrikstranneheim** [comment]
Was this solved by: https://github.com/Clinical-Genomics/cg/pull/1254?

**Comment by Mropat** [comment]
@henrikstranneheim we are still storing the bam files in HK - but this is something to fix in hermes.
