### ISSUE TITLE
New Fluffy output file

### ISSUE THREAD

**Issue by J35P312** [Clinical-Genomics/cg#1224]
## Description
Hello!
We are running the NIPT analysis in a two-pass mode: essentially this means that the pipeline is run twice internally.
The current output is produced in the second iteration; however sometimes it is necessary to check the results of the first pass.

Would it be possible to load the results of the first pass into the nipt-viewer?

i.e we will produce two csv files per run.

## Suggested solution

load two csv files per batch into the nipt viewer: first and second (current) pass

**Comment by Mropat** [comment]
done!
