### ISSUE TITLE
Add BALSAMIC's UMI validation cases to no compression list

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#1230]
**What:**
There are SeraCare samples for validation `equalbug` `stableraven` `sunnyiguana` that should not be compressed and we can use these for validating UMI workflow.

**How:**
Add these to list of cases to ignore compression.

Here is a similar PR: https://github.com/Clinical-Genomics/cg/pull/1169

**Comment by ashwini06** [comment]
Done in PR https://github.com/Clinical-Genomics/cg/pull/1233
