### ISSUE TITLE
BALSAMIC: deliver UMI for all TGS and WES cases

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#1238]
## Description

Hermes PR here: https://github.com/Clinical-Genomics/hermes/pull/32

We'd like to deliver UMI for TGS and WES runs to customer folder as well.

## Suggested solution

Update delivery tags for BALSAMIC

## This can be closed when

We can delivery BALSAMIC's UMI results

## Blocked by

https://github.com/Clinical-Genomics/hermes/pull/32

**Comment by hassanfa** [comment]
@ivadym I created this issue which is part of delivery for BALSAMIC. Good first issue to warmup. Hopefully after you get access to Hasta we can discuss this and possibly expand it.

I assigned you as well.

**Comment by ivadym** [comment]
Done: https://github.com/Clinical-Genomics/cg/pull/1477
