### ISSUE TITLE
BALSAMIC: Deliver SV results to Scout and customer folder

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#1239]
## Description

We'd like to upload SV results to Scout and deliver them to customer folder as well

## Suggested solution

- Update tags in Hermes to cover rest of SV calls, similar to: https://github.com/Clinical-Genomics/hermes/pull/26
- Update Scout upload api for balsamic
- Update delivery of SV for balsamic

## This can be closed when

We can deliver SV calls to customer folder and upload SV calls to Scout

## Blocked by

None.

**Comment by hassanfa** [comment]
@ivadym second issue regarding balsamic deliveries, and good warmup issue to get to know cg+hk+balsamicdeliveries+scout

Again, lets wait for access to hasta and we can discuss this further.

**Comment by ivadym** [comment]
Addressed here: https://github.com/Clinical-Genomics/cg/pull/1477
