### ISSUE TITLE
Upload UMI variants to Scout

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#1268]
## Description

BALSAMIC is producing UMI corrected list of variants and stores them in housekeeper via cg+hermes: https://github.com/Clinical-Genomics/hermes/pull/32

## Suggested solution

96 samples will be run this week (Sep 8th I think) and they will all require UMI corrected VCF to be uploaded to Scout. For all these samples UMI VCF have to be uploaded to Scout.

## This can be closed when

when UMI corrected variants can be uploaded to Scout.

## Blocked by

N/A

**Comment by hassanfa** [comment]
@emmser @henrikstranneheim this is a fairly urgent one. As it came up recently, customer needs 96 samples' UMI corrected VCF to be uploaded instead of our usual upload. Maybe something you could discuss internally between prod and developers? UMI will be successfully stored for these samples, so it is just Scout upload needs to be decided.

**Comment by Mropat** [comment]
@henrikstranneheim Need help deciding whether this will be implemented within next quarter.

**Comment by ivadym** [comment]
Closing, UMI `tnscope` variants are uploaded to Scout https://github.com/Clinical-Genomics/cg/pull/1493
