### ISSUE TITLE
/POST https://clinical-api.scilifelab.se/api/v1/submit_order/balsamic returning conflicting messages

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/cg#1276]
**Describe the bug**
When submitting a sample on clinical, a /POST https://clinical-api.scilifelab.se/api/v1/submit_order/balsamic call returned:

`401 "message": "at key 'samples' (at key 'container' (value did not pass 'Any' validation))"
`
**To Reproduce**
Unfortunately, I am not sure how to reproduce it :(

**Expected behavior**
401 one is a HTTP status which means the call is not going through because the user is not authenticated.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
but the message seems to show some kind of validation problem. The status should be https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

A bonus, would be to get a clearer validation message.

**Comment by Mropat** [comment]
@henrikstranneheim  need help estimating effort and gain and whether this is to be done in current version of cg

**Comment by ChrOertlin** [comment]
@Vince-janv Is this still relevant?

**Comment by Vince-janv** [comment]
Closing as it has not been replicated
