### ISSUE TITLE
Incorrect read count in statusDB and conflicting samples in cgstats when samples are re-preped.

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#1286]
## Description
Sometimes the number of reads listed for a sample in statusDB is incorrect and cgstats says "conflicting samples". I think this is caused by samples being re-preped = the samples get a new barcode combination. It is fairly often that we do a new prep of microbial samples, almost every week. 

One example:
```
[114|291|0] θ63° 6d/3z [hiseq.clinical@hasta:~] [P_main] 6s 1 $ cgstats sample ACC8201A4
conflicting samples: ACC8201A4, ACC8201A4
Aborted!
```
Reads according to statusDB for ACC8201A4: 6183358
Reads according to LIMS for ACC8201A4: 10 M
Reads from the different flowcells:
```
210716_A00689_0310_AHVH5JDSXY/ 1673834
210813_A00187_0551_AH2322DSX2/ 1765432
210820_A00689_0328_AHYF2WDMXX/ 1269778
210825_A00621_0474_AHF3HCDRXY/ 4913580
```
The number of reads in statusDB is from the 2 last flowcells, the sample was re-preped before the two last NovaSeq runs. 

Some more samples that are affected by this:
```
ACC8422A1
ACC8422A26
ACC8415A4
ACC8418A1
```

## This can be closed when

The read count is correct.

**Comment by henrikstranneheim** [comment]
Resolved
