### ISSUE TITLE
Prevent uploading cases with more than X amount of reads to Scout

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#1290]
## Description

Related issue: https://github.com/Clinical-Genomics/Deviations/issues/125#issuecomment-932039808

## Suggested solution

Count variants in a `VCF` file and if it is more than X number, do not proceed with Scout upload.

**Note** this can happen in `cg` and in Scout API maybe..

There are many ways to count variants in a VCF file:
1. If there is an index `bcftools +counts $VCF` This will print per "Variant Type"
2. If there is an index `gatk CountVariants -v $VCF` This one is from GATK and prints variants to output
3. If there is no index `zcat $VCF | grep -v -c '^#'` This is universal and works irregardless of bioinfo tool
4. **best solution (easiest and fastest) **  if there is an index `bcftools index --nrecords $VCF` This print number of variants to stdout

## This can be closed when

When uploading large variants doesn't cause a problem

## Blocked by

None

**Comment by hassanfa** [comment]
These commands have different runtime and output. Here is a summary:

``` bash
$ time gatk CountVariants -V SNV.somatic.upwardosprey.tnscope.all.vcf.gz 2> /dev/null
Tool returned:
1005807

real	0m24.886s
user	0m32.652s
sys	0m3.806s

$ time bcftools +counts SNV.somatic.upwardosprey.tnscope.all.vcf.gz 2> /dev/null
Number of samples: 2
Number of SNPs:    965159
Number of INDELs:  40648
Number of MNPs:    0
Number of others:  0
Number of sites:   1005807

real	0m24.733s
user	0m24.011s
sys	0m0.096s

$ time (zcat SNV.somatic.upwardosprey.tnscope.all.vcf.gz | grep -v -c '^#')
1005807

real	0m9.044s
user	0m14.636s
sys	0m1.071s

$ time bcftools index --nrecords SNV.somatic.upwardosprey.tnscope.all.vcf.gz 2> /dev/null
1005807

real	0m0.379s
user	0m0.139s
sys	0m0.024s
```

**Comment by hassanfa** [comment]
@Vince-janv fyi

**Comment by henrikstranneheim** [comment]
If you add the rank score with genmod then there is already systems in place in Scout to halt the upload after a certain threshold. I think that would be preferable since we do not need to introduce different systems and add more complexity. And from the meeting with Teresita and Felix they wanted the ranking as well so this will be a bonus.

**Comment by hassanfa** [comment]
Complex systems are good, complicated systems are bad . I think we should not be afraid of creating complex systems that are capable.

Two things:
- Ranks are removed from Scout, and they are not shown anymore.
- Rankscore is arbitrary and not practical for somatic mutations sometimes. If we could back up by peer reviewed articles that ranked variants for cancer is useful, then why not. Go for it!

**Comment by moahaegglund** [comment]
I will close this issue as we have added a check for number of variants in BALSAMIC instead.
