### ISSUE TITLE
Add retry, then timeout for establishing connections to LIMS

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#130]
Sometimes, we get a `Read timeout` error when trying to connect to e.g. LIMS.
Sometimes, we get a `WARNING Connection could not be established` error when connecting to mongodb.

Instead of trowing an error right away, the script should wait and retry an arbitrary number of times.

For more info, see emails with `$CRONIC ${HISEQ_HOME}/servers/crontab/transfer-lims-received.sh` and `$CRONIC ${HISEQ_HOME}/servers/crontab/cron-add-research.sh`

Todo:
- Look up best practices regarding repeated reconnects
- When none found, take following values: 30secs wait, retry 3 times, then raise exception.

Affected connectors:
- all `cg transfer lims --status {received,prepared,delivered}` commands
- `scout load research`

DoD:
- patch. Unit test could try to connect to loopback and observe described behaviour above.

**Comment by emiliaol** [comment]
@ingkebil @patrikgrenfeldt Something we should put on the backlog or did we already do something about this?

**Comment by ingkebil** [comment]
Added to backlog

**Comment by henrikstranneheim** [comment]
@mayabrandi Is there a retry in place and/or is this still an issue?

**Comment by mayabrandi** [comment]
I don’t know anything bout this. Probably @patrikgrenfeldt  knows more!

**Comment by henrikstranneheim** [comment]
Let's close this and revisit if needed
