### ISSUE TITLE
Hasta storage space: demultiplexed-runs stocktaking

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#1307]
## Description

Hasta is running out of storage space. Before we can start cleaning up, we want to know the status of the `demutliplexed-runs` directory: we need to compare the status of the flowcells in `demultiplexed-runs` with the status in statusdb and where possible fix any discrepancies.

## Suggested solution

1. Iterate over the flowcell directories in `demultiplexed-runs`. All flowcells should be `ondisk`, meaning after demultiplexing has finished successfully, fastq files have been stored in HK and a flowcell object exists in statusdb with the status `ondisk`
2. 

## This can be closed when
PR https://github.com/Clinical-Genomics/cg/pull/1334 has been merged and deployed

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@barrystokman Done?

**Comment by barrystokman** [comment]
It's still running, maybe keep it open until everything is finished?

**Comment by barrystokman** [comment]
The dry run, which took 4 hours to completed, flagged 799 out of 1780 flow cell dirs in demultiplexed-runs for removal, which is a LOT more than I expected. I'd like to check a couple of random flagged flow cell dirs before I start actually removing stuff.
[failed-flow-cells.log](https://github.com/Clinical-Genomics/cg/files/7856809/failed-flow-cells.log)

**Comment by barrystokman** [comment]
PR https://github.com/Clinical-Genomics/cg/pull/1334 (and subsequent fix PRs) has been deployed and the script has run.

The script cleared up roughly 42T of data (archiving 416 sample sheets in the process). demultiplexed-runs still holds a whopping 447T of data however.

**Comment by vwirta** [comment]
@barrystokman is the demultiplexed-runs folder of 447 TB the spring-compressed files, or raw fastq?

**Comment by barrystokman** [comment]
83 TB of spring, 363 TB of fastq

**Comment by barrystokman** [comment]
Only documentation left to do, will close this when finished
