### ISSUE TITLE
Deleting a case LoqusDB should also remove the corresponding loqusDB id in StatusDB

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1311]
## Description

When deleting a case in loqusDB the corresponding entry in StatusDB is not removed automatically and you have to do it manually from cg-statusdb GUI.

## Suggested solution

Update the statusDB database from cg when deleting a case via cg

## This can be closed when
When deleting a case in loqusDB via cg also removes the loqusDB ID entry in the samples table

**Comment by Mropat** [comment]
This can be fixed in 30 minutes. @henrikstranneheim does this need solving within current cg version?

**Comment by henrikstranneheim** [comment]
Yes, since this is a bug that leaves the system in a false state, which is hard to understand afterwards and needs manual intervention to correct

**Comment by fevac** [comment]
Do you think this could be a good second issue for me? or is LoqusDB too hard to understand for someone who just arrived and the gain would be small?

**Comment by henrikstranneheim** [comment]
@fevac and @ivadym Looks like Vadym is fixing it here: https://github.com/Clinical-Genomics/cg/pull/1567

**Comment by ivadym** [comment]
Not quite, I'm just refactoring it. Since @fevac already spent some time looking into how to fix it, I'd leave it to her

**Comment by henrikstranneheim** [comment]
Solved here: https://github.com/Clinical-Genomics/cg/pull/1568
