### ISSUE TITLE
Feat(Datamanagement): Remove HK bundle according to rules

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1321]
- [ ] Protect variant files and logs for all case bundles, always keep indefinitely
  - [ ] Create whitelisted tag file map for each pipeline
- [ ] Remove all other files than whitelisted older than 365 days for latest case bundle
~Create specific systemd command to wipe trimmed fastqs derived from Balsamic in sample bundles after 30 days~
- [x] Create specific systemd command to wipe fastqs in Balsamic analysis bundles after 45 days
- [ ] Create specific systemd command to wipe all files that are not whitelisted in all versions of case bundles, except the latest case bundle version, i.e. do not delete anything in the latest case bundle

**Comment by patrikgrenfeldt** [comment]
> Create specific systemd command to wipe fastqs in Balsamic analysis bundles after 45 days
@Mropat @henrikstranneheim 
- Should we delete only from analyses marked as "Delivered"?
- If we only have the criteria older than 45 days then we will have to process more and more analyses each time?

**Comment by Mropat** [comment]
* Perhaps @moahaegglund could help with identifying when the trimmed fastq is safe to delete? How does the timeline of delivery usually look in production? 
 * The command runs relatively quickly in background even if it processed increasing amount of cases. But yes the number of cases processed if increasing the more analyses have been run. However it will skip case when it finds no files in housekeeper to delete. This could be mitigated if we create "Bundle file trimmed fastq cleaned " timestamp field in the database on analysis level. Then we know if this particular cleaning was done on the case, and construct a query that doesnt return the analysis again. I dont think this is a good idea: the amout of time developing extra functionality to accomodate this does not outweigh the gain, especially if the gain concerns seconds per day of runtime for a script running sql queries in the background.

**Comment by moahaegglund** [comment]
> * Perhaps @moahaegglund could help with identifying when the trimmed fastq is safe to delete? How does the timeline of delivery usually look in production?

Yes, I brought this up at the balsamic workshop. I don't see any reason to save those fastq files in HK, they are never delivered to customer. It's a better traceability to have a log file that specifies what raw data was utilised in the analysis, this will be created. Vadym, Kalle N and Keyvan will go through the storing to HK to see which files should be stored and not for balsamic.

**Comment by henrikstranneheim** [comment]
## MIP Tags

- vcf-snv-clinical
- vcf-snv-research
- vcf-str
- snv-gbcf, snv-bcf
- mip-config
- mip-config
- mip-analyse, reference-info
- sample-info
- qc-metrics
- smn-calling
- sv-bcf
- vcf-sv-clinical
- vcf-sv-research
- exe-ver
- vcf2cytosure

**Comment by talnor** [comment]
# MicroSALT Tags to keep indefinitely
- microsalt-log
- config
- qc-report, visualization
- typing-report, visualization
- typing-report, qc-metrics
- microsalt-config
- assembly

# Mutant Tags to keep indefinitely
- fohm-delivery, pangolin-typing, csv, visualization
- fohm-delivery, instrument-properties
- fohm-delivery, pangolin-typing-fohm, csv
- vcf, vcf-report, fohm-delivery
- mutant-log
- metrics
- config
- mutant-config
- software-versions
- fohm-delivery, komplettering, visualization
- fohm-delivery, pangolin-typing, csv, visualization
- ks-delivery, ks-results, typing-report, visualization, csv
- ks-delivery, ks-aux-results, typing-report, visualization, csv
- ks-delivery, multiqc-html
- gisaid-log
- gisaid-csv

**Comment by patrikgrenfeldt** [comment]
> Vadym, Kalle N and Keyvan will go through the storing to HK to see which files should be stored and not for balsamic.

@ivadym @karlnyr and @keyvanelhami could you supply me with the balsamic tags to permanently store in Housekeeper?
