### ISSUE TITLE
Pools should get received_at and delivered_at filled in

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#133]
As a clinical-genomics facility manager I want the received_at and delivered_at for pools to be automatically filled in, so that I am able to invoice pools so that we get money for our pool services.

When looking in https://clinical-api.scilifelab.se/admin/pool/?sort=4&desc=1 there should be some dates in received_at and delivered_at

These dates comes from LIMS reception-control step and delivery step and should happen via cg transfer just like with samples

Should be run in the same script that ran the transfer sample information: new script: like for example transfer-lims-delivered

- [ ] inform Maya

**Comment by barrystokman** [comment]
cg transfer pools

**Comment by ingkebil** [comment]
https://github.com/Clinical-Genomics/servers/blob/master/crontab/transfer-lims-prepared.sh

**Comment by barrystokman** [comment]
```
# check for  pools that have been delivered [every 4th hour]
35 */4 * * * $CRONIC ${HISEQ_HOME}/servers/crontab/transfer-lims-pools-delivered.sh >> ${LOG_BASE}/cg.transfer-pools-delivered.log 2> >(tee -a ${LOG_BASE}/cg.transfer-pools- delivered.log >&2)
```

again for received
