### ISSUE TITLE
Unnecessary time might be spent on curating MIP analyses

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#1331]
## Description

Right now production spend a lot of time to manually inspect every MIP analysis uploaded to scout before delivering the case to the customer.

## Suggested solution

Automate the delivery of MIP analyses to customers. But before that can happen we should spend a few weeks with logging every time a ticket assigned as "complete" is not delivered to the customer.

The log is kept here in this issue by writing a reply below. The following template can be used (and possibly add additional information if you feel it is needed):
`Case <petname> had status completed in trailblazer and got uploaded to scout. This analysis was not delivered to customer because of <reason>.`

## This can be closed when

We close this ticket when year 2022 has started. At closing off this ticket we also have a meeting and discuss the log we have generated.

**Comment by henrikstranneheim** [comment]
@henningonsbring Since the project https://github.com/Clinical-Genomics/project-planning/issues/196 is done can we close this one? It is not really a suggestion yet to make any new features in cg nor MIP. We should open new issues when we know what to build

**Comment by henningonsbring** [comment]
Closing, we are not spending unnecessary time anymore on curating MIP analyses and 2022 has started.
