### ISSUE TITLE
Standard procedures do not work when analysing already sequenced data and tickets can be difficult to find for delivery of analysis

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#1336]
## Description

Sometimes the customer places an order where they want CG to perform an analysis on already sequenced data. This situation can be difficult for production. Here is an example how production work and why it can be difficult:

1. Production monitor the completed analyses in trailblazer and find modelfly that is ready to be delivered to the customer.
<img width="1302" alt="1_issue" src="https://user-images.githubusercontent.com/66672810/144572629-32e619d3-ee09-4e31-b946-549b277e52b4.png">

2. Standard procedure is clicking into modelfly and then find a link in the column "Ticket number" which leads to the ticket in support system. Finding the ticket in support system is crucial, since that is where the scout link to the analysis should be given to the customer.
<img width="1301" alt="2_issue" src="https://user-images.githubusercontent.com/66672810/144572707-111baf25-0df3-4b7a-b635-2dca6fbe6fb3.png">

3. Remember, modelfly is a MIP-case. However, the link to ticket 128900 leads to a balsamic ticket: https://clinical-scilifelab.supportsystem.com/scp/tickets.php?number=128900

4. Now the production staff might go to modelfly in statusdb and click the sample to find the ticket. Unfortunately sample ACC8954A2 got the balsamic ticket 128900 displayed: https://cg-statusdb.scilifelab.se/admin/sample/?search=ACC8954A2

5. Still the production staff have no idea where to deliver the analysis. Sometimes the customer ask for files uploaded to caesar, then production will run the command: `cg deliver analysis -d <delivery-type> -c modelfly`

Unfortunately this command will place the analysis files in `/home/proj/production/customers/cust127/inbox/128900/` (i.e. a folder named as the balsamic ticket). This will be confusing for production since they still do not know which tickets they should deliver the analysis to. It will also be confusing for the customer which will get the analysis delivered to caesar in a folder that is not named as the ticket from the order (unless production manually change this).

6. Now production need to do creative detective work to track down the ticket they should deliver the files to. The best remaning option is to perform the following steps:
a) Search for "modelfly" in statusdb
b) Find that the name given to the case by the customer is "GMSB-ST023MIP"
c) Search for a ticket on supportsystem where "ST023MIP" is mentioned (note that searching for "GMSB-ST023MIP" wont work since supportsystem will give you all tickets where "GMSB" is mentioned and all tickets where "ST023MIP" is mentioned. Searching for GMSB will give **A LOT** of hits).

By now production recognise these problematic tickets and jump to step 6 directly. What is annoying here is that for this situation our standard way of working will not be possible. Also step 6 will only work if the customer named the sample something unique. If they name it for example "GMSB-001", or something else generic that is mentioned many times on support system, then the ticket will be **very difficult** to find since searching for customer case name wont work.

## Suggested solution

If ticket would be connected to case and re-runs would get a new petname assigned. Doing this would also make it much easier to track re-runs instead of the complicated systems we discussed before. There could even be a flag in statusdb like "analysis of already sequenced data".

Samples can be connected to an order-ID which could be useful for the lab and would allow us to trace back when and how the initial order for the sequencing of the sample was done. The order-ID should however not be used in the bioinformatic analyses as input.

We will probably need to keep samples associated with tickets for the lab (?)

## Solution suggested by @Vince-janv:
- [x] Add a tickets field to cases, that keep track of all tickets where the case has been ordered. (Done in #1534)
- [ ] Create utility methods for identifying re-runs. Add re-run ticket to cases that are ordered again. 
- [ ] Have a refinement session with @elevu and/or @moedarrah regarding changes to the /analyses/<int:analysis_id> page in cigrid.
- [ ] (Optional) Small changes might need to be made to trailblazer to allow for the Cigrid changes.
## This can be closed when

Same commands as used when dealing with analyses of newly sequenced data should work as when dealing with analyses of already sequenced data. Also which ticket to deliver what analysis into should be easy to find.

**Comment by henningonsbring** [comment]
@Vince-janv you are working on changing the database? That would fix this right? If this issue is redundant with any issue/project you might have created feel free to close this one.

**Comment by Vince-janv** [comment]
Yes, however I found a PR by Patrik which attempted the same thing. It was never merged though after some discussion with @Mropat and @henrikstranneheim. I will try to convince them though 😉

**Comment by henningonsbring** [comment]
I remember discussing the PR from PG with various persons at CG and I was sceptic to his approach and I predicted that it would case more confusion and buggs than actual help. Potentially Patriks approach could be a stepping stone before ultimately fixing the problem since if I remember correctly both sample and case had ticket connected to them. But I do not believe in this solution.

**Comment by henrikstranneheim** [comment]
@Vince-janv How much of this was solved by: https://github.com/Clinical-Genomics/cg/pull/1534. Would be great with a bullet list of what was resolved and what remains to be done.

**Comment by Vince-janv** [comment]
@henrikstranneheim I'd say the majority was solved by it. Hopefully it's just the easy part left. I updated the description with a bullet list 👍

**Comment by Vince-janv** [comment]
Closing as part of the problem has been solved. Remaning issues can be addressed in an other issue focusing on facilitating re-runs
