### ISSUE TITLE
External cases incorrectly started by start-available commands.

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1346]
## Description

After the merge of #1309, external cases that do not have an analysis in statusdb have been started or attempted to be started by the start-available functions, resulting in a spam of Error mails and at least one case starting its analysis.

This has affected old external cases where analyses were not stored, and recent cases where data has not been transferred to hasta and added to housekeeper yet.

## Suggested solution

- All affected external cases were set to "hold".
- In the future, when a case containing external data is created it should automatically be set to hold since after #1335 has been merged, they will be set to "analyze" when the data is on hasta and sample bundles have been created.

## This can be closed when

- [ ] A PR setting the default action of new external cases to "hold" has been merged.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
According to @patrikgrenfeldt a large change to the relevant code will be merged next week, so I'll wait until then to start working on the PR.

**Comment by patrikgrenfeldt** [comment]
@Vince-janv I looked around for places where we could alter the behavior of the system and implemented a small change somewhere else than what I suggested to you. I'm not convinced this is the best solution though, please have a look a PR #1347 and tell me what you think?
