### ISSUE TITLE
Quality issues

### ISSUE THREAD

**Issue by AleksandraKrstic** [Clinical-Genomics/cg#1357]
![image](https://user-images.githubusercontent.com/82517572/147931789-447d14ee-c7ec-43ac-9a0a-2f693e645a2e.png)
Hi,
When we analyse leukemia followup samples with Myeloid Twist panel for variants bellow 5% VAF in Scout we sometimes suspect that they are artefacts (background). It would help us if it would be possible that we get to see all samples from the same run on a specific position like in the image I attached (that is how they do it in Uppsala). It would be great to be able to click from Scout and get such a view in IGV. If we need to load .bam and .bam.bai manually, where do we find these files from the same run? In Scout or?

Thank you for your help!

**Comment by northwestwitch** [comment]
Transferring this suggestion here since cg is creating the config files for scout. The suggested feature could be in theory implemented by adding to the case config files a list of other files that were runned together ?

**Comment by ChrOertlin** [comment]
@henrikstranneheim, @northwestwitch has this been addressed by any releases at some point or is this still relevant?

**Comment by northwestwitch** [comment]
> @henrikstranneheim, @northwestwitch has this been addressed by any releases at some point or is this still relevant?

No, it has not been addressed so far. I don't know if it's still relevant

**Comment by AleksandraKrstic** [comment]
Hi,
I didn’t submit this issue and I don’t know what it was about. Maybe Lucia knows

Aleksandra Krstic, PhD
Sjukhusgenetiker
Klinisk Genetik, L5:03
Karolinska Universitetssjukhus, Solna
+46 760782721

Från: ChristianOertlin ***@***.***>
Skickat: den 13 juni 2024 16:24
Till: Clinical-Genomics/cg ***@***.***>
Kopia: Aleksandra Krstic ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/cg] Quality issues (Issue #1357)


@henrikstranneheim<https://github.com/henrikstranneheim>, @northwestwitch<https://github.com/northwestwitch> has this been addressed by any releases at some point or is this still relevant?

**Comment by northwestwitch** [comment]
> Hi, I didn’t submit this issue and I don’t know what it was about. Maybe Lucia knows

Hi! It has been so long that I think your forgot (About 2 years ago in Scout). But I guess this means that it's no longer relevant and perhaps we can close it?

**Comment by ChrOertlin** [comment]
Ok then let's close it. In case quality issues pop up in the future there will likely be another report under the newer software version and it will help us with tracing it then.

Or we can re-open this at that point.

**Comment by AleksandraKrstic** [comment]
In that case, yes. Thank you

Aleksandra Krstic, PhD
Sjukhusgenetiker
Klinisk Genetik, L5:03
Karolinska Universitetssjukhus, Solna
+46 760782721

Från: Chiara Rasi ***@***.***>
Skickat: den 14 juni 2024 09:28
Till: Clinical-Genomics/cg ***@***.***>
Kopia: Aleksandra Krstic ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/cg] Quality issues (Issue #1357)


Hi, I didn’t submit this issue and I don’t know what it was about. Maybe Lucia knows

Hi! It has been so long that I think your forgot (About 2 years ago in Scout). But I guess this means that it's no longer relevant and perhaps we can close it?
