### ISSUE TITLE
New category in statusdb "Sample returned to customer"

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/cg#1387]
## Description
There is a need of a search function to find out if a sample is returned to the customer. Today we only have it on paper in a binder.

## Suggested solution
We need a new category/field in statusdb in "Sample" called "Sample returned to customer". It should be in the form of a checkbox that should be searchable through filtering.

## This can be closed when
The new category is implemented.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Mropat** [comment]
@annagellerbring @henrikstranneheim 
This requires help prioritizing within this quarter or should be instead added to feature wishlist for new orderportal

**Comment by annagellerbring** [comment]
@annaengstrom what do you say?

**Comment by annaengstrom** [comment]
We get the request for returning samples on a regular basis and it would be useful to have this digitally, also to be able to have a clearer picture of samples that already have been returned. I agree with the labels Gain M and Urgency M.

**Comment by henrikstranneheim** [comment]
Feels like this should be recorded in LIMS and not in StatusDB. @RasmusBurge-CG @Karl-Svard what do you think?

Is there a function to record this on sample level in LIMS or similar?

**Comment by henrikstranneheim** [comment]
Do you have any input @saschaconradt @MarcelaGa? How do you record this today?

**Comment by MarcelaGa** [comment]
Hi @henrikstranneheim, today we don't record returning samples in any system or whatsoever. We only have as a proof of the sample was returned a form (returning sample form) signed by the customer and the person responsible for the return. It is printed and archived in the fireproof cabinet. I agree with Anna, it would be great to have a better system to track the status of each sample.

**Comment by saschaconradt** [comment]
> Hi @henrikstranneheim, today we don't record returning samples in any system or whatsoever. We only have as a proof of the sample was returned a form (returning sample form) signed by the customer and the person responsible for the return. It is printed and archived in the fireproof cabinet. I agree with Anna, it would be great to have a better system to track the status of each sample.

I agree too.

**Comment by annaengstrom** [comment]
> Feels like this should be recorded in LIMS and not in StatusDB. @RasmusBurge-CG @Karl-Svard what do you think?
> 
> Is there a function to record this on sample level in LIMS or similar?

I think it would be difficult to print to the LIMS database since almost always we do this after the sample "case" has been closed in LIMS. It is done on a sample level and I think statusDB would be great for this. Is there a reason for not having it in statusDB?

**Comment by henrikstranneheim** [comment]
> I think it would be difficult to print to the LIMS database since almost always we do this after the sample "case" has been closed in LIMS. It is done on a sample level and I think statusDB would be great for this. Is there a reason for not having it in statusDB?

Yes, it is inherently a LIMS feature to keep track of how much sample is left or if it has been returned. StausDB does not use this information in any way and therefore it is not best practice to add this to StatusDB. It would just clutter the database and not make any sense. If a sample has been returned I think it should be recorded in LIMS on the sample level or wherever appropriate. I do not know if LIMS already has this feature (it should be able to exit samples from the system) or if it is something we can develop? What do say @RasmusBurge-CG @Karl-Svard

**Comment by RasmusBurge-CG** [comment]
Testing to solve this by a new wf. The new wf on stage is called "Return Samples". The user will set the date and run an EPP that stores that information on the submitted sample level. Users are then able to see this information when searching on the LIMS-ID and in "PROJECTS & SAMPLES". 
<img width="1113" alt="Screenshot 2022-09-26 at 11 27 03" src="https://user-images.githubusercontent.com/80392398/192242325-6592414b-17f4-4625-8d7a-2f731f10f0b0.png">

<img width="875" alt="Screenshot 2022-09-26 at 11 20 56" src="https://user-images.githubusercontent.com/80392398/192242346-82a1d708-3b1e-4c72-bef6-f6626f5365ff.png">



https://github.com/Clinical-Genomics/cg_lims/issues/321

**Comment by henrikstranneheim** [comment]
Suggestion: Add all samples from the paper to LIMS records for all previously returned samples

**Comment by saschaconradt** [comment]
Sounds good. I can take care of it as soon the new sample returning workflow is in production. Let me know @RasmusBurge-CG

**Comment by Karl-Svard** [comment]
I will close this issue and move the conversation over to the cg_lims repository as that seems like a better fit. See issue https://github.com/Clinical-Genomics/cg_lims/issues/321

**Comment by saschaconradt** [comment]
> Suggestion: Add all samples from the paper to LIMS records for all previously returned samples

I processed all DNA-samples which we returned during 2022 in "LIMS Return Samples-workflow" and uploaded the corresponding returning samples documents.
