### ISSUE TITLE
Add gender information to Balsamic from status DB

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/cg#1395]
## Description

For copy-number calls in BALSAMIC, having correct gender information is key. 
We are currently using other internal tools to estimate the gender information based on coverage. 
Sometimes the tools won't be able to calculate the correct gender and returns the output as "?" 
However, we have this information in status about gender. 

## Suggested solution

Add gender information to Balsamic from status DB via cg when starting analysis

**Comment by patrikgrenfeldt** [comment]
@ashwini06 please make a PR to cg about it, if you know where in the Balsamic config (e.g. what key) to add it. It should be kind of straight forward. The gender information in statusdb is located in the "sex" property of samples

**Comment by ashwini06** [comment]
> @ashwini06 please make a PR to cg about it, if you know where in the Balsamic config (e.g. what key) to add it. It should be kind of straight forward. The gender information in statusdb is located in the "sex" property of samples

@patrikgrenfeldt Thanks! But for BALSAMIC cases, gender information is not always provided by the customer. Most cases it is shown as 'unknown', isn't it also while placing orders from the customer, this field should be asked as mandatory from the customer?

https://cg-statusdb.scilifelab.se/admin/sample/?search=ACC7363A2

**Comment by patrikgrenfeldt** [comment]
The gender information is mandatory, it's the customer that actively chooses "unknown" as I understand it. We could prohibit the value "unknown" for Balsamic orders, it that what you want @ashwini06? Otherwise we could inform the customers that we would like them to choose the correct gender for the samples

**Comment by vwirta** [comment]
If we need gender information for CNA analysis in Balsamic, then we should have the field set to mandatory. I have hard time to see a situation where gender information is not available for a cancer case. 
(for rare diseases the situation is different with unborn being analyses)

Do we know why cancer customers do not set gender information?

**Comment by patrikgrenfeldt** [comment]
This is implemented in https://github.com/Clinical-Genomics/cgweb/pull/419
