### ISSUE TITLE
Wrong QOS when starting BALSAMIC

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#1396]
## Description

Production reports that the QOS is wrong when BALSAMIC starts

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when
- [ ] Balsamic starts with a qos set according to the balsamic case

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Mropat** [comment]
This was opened in cg previously, but since the problem is not in cg it was transferred to Balsamic here https://github.com/Clinical-Genomics/BALSAMIC/issues/856

Does this issue refer to a different phenomenon?

**Comment by patrikgrenfeldt** [comment]
> This was opened in cg previously, but since the problem is not in cg it was transferred to Balsamic here [Clinical-Genomics/BALSAMIC#856](https://github.com/Clinical-Genomics/BALSAMIC/issues/856)
> 
> Does this issue refer to a different phenomenon?

No, we discussed this on the cancer meeting today and it was suggested that the problem was in cg but some testing shows cg seems to handle it ok, I couldn't find the issue put the test result in so I created an issue.

Some tests:
```
cg set family fairrhino -p standard && cg workflow balsamic start-available -d
...
INFO Running command /.../S_BALSAMIC/bin/balsamic run analysis --account development  --qos normal ...
...
cg set family fairrhino -p express && cg workflow balsamic start-available -d
...
 INFO Running command /.../S_BALSAMIC/bin/balsamic run analysis --account development --qos high
```
➡️ The priority on the case in cg seems to propagate to the input of Balsamic
