### ISSUE TITLE
Linking and concatenation of fastq files for BALSAMIC

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#1398]
## Description

Linking and concatenation of fastq files for BALSAMIC are done by cg. Sometimes I want to analyse a case with a subset of the fastq files that are available in Housekeeper for a sample. In order to do this today I do linking and concatenation manually. I would like to be able to link the fastq files with cg, manually remove fastq files if needed, and then start the analysis.

## Suggested solution

Split linking and concatenation? Move concatenation to BALSAMIC?

**Comment by moahaegglund** [comment]
In a way connected to https://github.com/Clinical-Genomics/BALSAMIC/issues/862

**Comment by Mropat** [comment]
I agree with this suggestion. We concatenate files for microsalt and mutant fastq in cg, which ideally should be handled by the pipelines also.

**Comment by ivadym** [comment]
Closing @Clinical-Genomics/cancer!

This has been implemented as part of release v13:
 - Concatenation on Balsamic side:
   - CG: https://github.com/Clinical-Genomics/cg/issues/2447
   - Balsamic: https://github.com/Clinical-Genomics/BALSAMIC/pull/1069
 - Analysis can be started with the available fastq in the analysis/fastq directory (and therefore available sample fastqs in HK)
   - CG: https://github.com/Clinical-Genomics/cg/issues/2447
   - Balsamic: https://github.com/Clinical-Genomics/BALSAMIC/issues/1077
