### ISSUE TITLE
New category in statusdb "Lab contact"

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/cg#1399]
## Description

For sample, lab or prep related issues the lab needs to be able to contact someone from the customer who is involved and updated in such issues. The primary contact is usually not involved in sample submission. We often have an informal lab contact at the customer site but it needs to be documented for everyone to find.

## Suggested solution

We need a new category/field in statusdb in "Customer" called "Lab contact". It should be formatted in the same way as "Primary contact", which means as a drop down list of registered "Users". 

## This can be closed when

The new category is implemented.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Mropat** [comment]
This is a feature request already noted and taken into account in new orderportal design.
@annagellerbring @moahaegglund @henrikstranneheim I need input on deciding whether implementing this feature is urgent and should be done in this version of orderportal

**Comment by annagellerbring** [comment]
> This is a feature request already noted and taken into account in new orderportal design.
> @annagellerbring @moahaegglund @henrikstranneheim I need input on deciding whether implementing this feature is urgent and should be done in this version of orderportal

It's not super urgent so could be implemented in the new orderportal

**Comment by Mropat** [comment]
Closing, will be addressed in new orderportal

**Comment by annagellerbring** [comment]
I'm opening this issue again since it's still needed and not solved in the new orderportal.

**Comment by islean** [comment]
Testing went well with the column added as a drop down option from the User table:

<img width="262" alt="image" src="https://github.com/Clinical-Genomics/cg/assets/40887124/f099a16d-2952-40a9-bcd5-3a8e8106c9fc">
<img width="307" alt="image" src="https://github.com/Clinical-Genomics/cg/assets/40887124/7ed2c25f-c326-4cb1-8862-abff113116bd">

**Comment by annagellerbring** [comment]
Great @islean, thanks!

**Comment by islean** [comment]
Would have been great but Database changes in production seems to be broken at the moment, so it has not been added yet @annagellerbring

**Comment by henrikstranneheim** [comment]
Done
