### ISSUE TITLE
Many old case folders under  /home/proj/production/cancer/cases

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#1405]
## Description

There is a lot of old case folders under `/home/proj/production/cancer/cases`, 803 folders from 2019 and 2020. Many are owned by individual users. There are both empty folders and folders containing all the data. `firmshiner`, is a folder owned be hiseq.clinical, from october 2019, the case is set to `hold` in statusDB and it's not stored in HK.
How can we remove the old case folders that aren't removed by the cronjob? Should/can we store them in HK before removing?

**Comment by henrikstranneheim** [comment]
@moahaegglund Nice find! I have added it to the data storage management project. We need to understand which cases have been stored in Housekeeper and which have not.

**Comment by Mropat** [comment]
This issue s not related to cg software, but is an IT issue related to data management. It is not possible to transfer this, so closing and will reopen in a provate repository
