### ISSUE TITLE
Tracking MIP runs started by melter in Trailblazer

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#1416]
Melter (a tool for starting reruns automatically) will start mip analyses on hasta. Ideally these melter-reruns are monitored in trailblazer together with all the other mip analyses. However, in the list with analyses on trailblazer it should be easy to identify which analyses are started by melter without clicking on the case.

HS suggested that we add a new field in the analysis table called something like "Initiated by", then this column can be added to trailblazer.

What problems could arise from introducing a new field in the analysis table and a new column in trailblazer? Are there any other solution that is better?

This issue can be closed when we have agreed on the optimal way to monitor the MIP runs started by melter.

**Comment by Mropat** [comment]
Trailblazer development is frozen and this issue can be addressed in new orderportal. 
For now a workaround can be made by having melter utilize trailblazer REST api to add a comment in cigrid to ongoing case about why the cas ehad started
