### ISSUE TITLE
adding of umi analysis type for BALSAMIC cases

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/cg#1419]
## Description

Currently, for all panel cases UMI analysis is being run by BALSAMIC as a default. This involves unnecessary computational resources

### Order Form / UI

- [ ] Should support new analysis type: `balsamic-umi` for order form 1508 / UI and supported in the back-end. (Can be done now). If we do this we also need to update the automation in cg to handle this. https://github.com/Clinical-Genomics/cgweb/issues/371

### Balsamic

- [ ] Fix `--umiworkflow / --no-umiworkflow` flag to function in Balsamic

We should do this Cg changes after the next Balsamic major release scheduled before Easter.

### Cg

- [ ] Default should be `--no-umiworkflow` when ordering analysis type: `balsamic`
- [ ] Cg should use: `--umiworkflow` when ordering analysis type: `balsamic-umi`. this means that both the umi-workflow and the ordinary balsamic workflow will run.
- [ ] Update storing in Housekeeper accordingly
- [ ] Update cg delivery accordingly
- [ ] Update scout upload accordingly

**Comment by Mropat** [comment]
@henrikstranneheim needs help prioritizing

**Comment by moahaegglund** [comment]
@henrikstranneheim we need to prioritise this in order to be able to make delivery automatic in addition to avoid unnecessary computational resources as Ashwini mention.

**Comment by henrikstranneheim** [comment]
@moahaegglund I added it to next weeks refinement session

**Comment by moahaegglund** [comment]
> Action:
> 
> * We need to ask the customers if they really want only UMI or both UMI and no-UMI balsamic workflow (MHA)
> 
> Changes needed if only UMI requested: In OF: add DataAnalysis: BALSAMIC-UMI (Effort M) In cg: handle new BALSAMIC-UMI workflow by supplying the `--umiworkflow / --no-umiworkflow` (Effort M) In Balsamic: Enable only UMI workflow and not the regular balsamic workflow (Effort: L)

We have discussed this on todays production management meeting, customers ordering UMI are only interested in UMI. We should have a workflow with only UMI, if interested in both analyses customer should make two separate orders,  one for balsamic and one for balsamic-umi (one with rerun).

**Comment by moahaegglund** [comment]
@henrikstranneheim would be great to bring this up in refinement on wednesday!

We now know that BALSAMIC and BALSAMIC-UMI will be completely separated. We discussed this on the cancer meeting today, it is a large effort to the BALSAMIC part of this but it would be great to have the other parts in place as soon as possible. It's causing confusion for customers and prod bioinfo right now. 

Things to consider:
* add balsamic-umi to the  orderform
* start regular balsamic in the meantime (or maybe supply --umiworkflow / --no-umiworkflow?)
* add a tag for balsamic-umi to delivery (`cg deliver analysis -a balsamic-umi`)
* change files uploaded to Scout if balsamic-umi is ordered

**Comment by henrikstranneheim** [comment]
@moahaegglund Added to refinement agenda 30/3

**Comment by ivadym** [comment]
Closing as this has already been done in [CG](https://github.com/Clinical-Genomics/cg/pull/1493) & [BALSAMIC](https://github.com/Clinical-Genomics/BALSAMIC/pull/932)
