### ISSUE TITLE
Customer mark RNA samples as tumour in orderform but that info is not available in statusDB

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#1431]
## Description

See ticket [407874](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=46409) for example of an orderform where customer has marked the samples as from tumour, in statusDB these samples are not marked as from tumour. We need this information to be transferred to statusDB.

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt Resolved in here https://github.com/Clinical-Genomics/cgweb/pull/363 right?

**Comment by patrikgrenfeldt** [comment]
Yes @henrikstranneheim, this issue was resolved by https://github.com/Clinical-Genomics/cgweb/pull/363
