### ISSUE TITLE
capture kit process UDF from LIMS is automatically used when starting MIP analysis of WES/TGA samples

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#144]
As a production team member I want the capture kit to be fetched from the correct step in LIMS so that the automation works and I can take a coffee instead of changing things manually.

Problem: 
cg analysis (I think) fetches the capture kit from lims when building the pedigree for MIP and it now get's it from the depricated workflow for sure select. There is a new workflow from where the information should be fetched instead. Also, the capture kit names are different and they need a translation similar to what is being done for capture kits today. Solution today is to manually enter the bed-file name of the capture kit in status db.

Expected outcome / suggested solution:
The expected outcome is that a case with TGA samples prepped using the new TWIST v1 protocol in LIMS can be started automatically with cg analysis -fT

~~There is a development workflow in LIMS where all "odd" sample should be taken through to record lab events. We need to add the capture kit UDF and transfer that information to status db.~~

~~- [ ] Add free text UDF ´Capture Kit` to the CG002 Library Prep step in the CG002 Library Prep (Dev) protocol.~~

Question: When is the information transfered from the regular CG003 SureSelect XT work flow??? Should be the same for the DEV wf

**Comment by barrystokman** [comment]
changes needed in LIMS, cg

**Comment by emiliaol** [comment]
New info:

As a production team member I want the capture kit to be fetched from the correct step in LIMS so that the automation works and I can take a coffee instead of changing things manually.

Problem: 
cg analysis (I think) fetches the capture kit from lims when building the pedigree for MIP and it now get's it from the depricated workflow for sure select. There is a new workflow from where the information should be fetched instead. Also, the capture kit names are different and they need a translation similar to what is being done for capture kits today. Solution today is to manually enter the bed-file name of the capture kit in status db.

Expected outcome / suggested solution:
The expected outcome is that a case with TGA samples prepped using the new TWIST v1 protocol in LIMS can be started automatically with cg analysis -f <familyID>

**Comment by emiliaol** [comment]
Creating a new issue and closing this one that's not current yet
