### ISSUE TITLE
Feature request: Add comment to sample

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#1440]
## Description

Currently production is only able to SET a comment from the previous one. The request is to enable production to ADD comments to multiple sample without replacing the old one. Similar to what exists in the gui

## Suggested solution

Either change how values are set for comments key or add another cli call to add a comment to a sample

## This can be closed when

You can add a comment to a sample through CLI

## Blocked by

*NA*

**Comment by henrikstranneheim** [comment]
Added to refinement tomorrow

**Comment by henrikstranneheim** [comment]
- Add new comment to existing comment (sorted on newest on top)
- Do not repeat the previous comments twice

### Before
```
"first comment"
```

### After
```
"second comment"
"first comment"
```

**Comment by thelander** [comment]
Hi @karlnyr, this feature was just deployed to prod 😊
