### ISSUE TITLE
Automated store for previously failed Balsamic cases

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#1451]
## Description

If a case has the status `FAILED` in trailblazer production intervenes. If the case is deemed to be finished  production sets the case to completed in Trailblazer using the `Make complete` button. Production expects that the storing of analysis files is done, and that the case is ready to be uploaded to its services. However Balsamic requires a `analysis_finished` file for it to be stored. This can be solved today by doing `touch analysis_finished && cg workflow balsamic store-available`, but it would be better if making the analysis finished actually made the case ready for storage and upload.

## Suggested solution

Implement the same system as exists for the MIP-pipeline

## This can be closed when

Analyses set to completed in trailblazer are automatically stored by `cg workflow balsamic store-available`

## Blocked by

*NA*

**Comment by henrikstranneheim** [comment]
@karlnyr @Mropat @ashwini06  Added to next weeks refinement

**Comment by Mropat** [comment]
Awesome, store balsamic worked this way since before Trailblazer integration. Had no idea this was still happening

**Comment by henrikstranneheim** [comment]
Decided on the improvements meeting:

- We will ignore the `analysis_finished` flag coming from Balsamic in cg and try to store the analysis from Balsamic if it shows as completed in SLURM/Trailblazer
