### ISSUE TITLE
Threshold for fastq cases

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1460]
## Description

The `cases_to_analyze` function has a boolean parameter called threshold that if true, prevents it from returning a case where one or more of the samples are not sequenced or have not gotten enough reads (based on the apptag).

The RML cases, for which the automatic fastq delivery was intended, are supposed to be delivered regardless of failing samples within the pool. 

However, cust144 will start to send TGA (PANKT) samples for fastq-delivery. For these, we do not want to start the transfer of fastq-files unless all samples in the case have been sequenced.

#### Easy solution:
Change the `Target Reads` or `Percent Reads Guaranteed` for the RML samples to 0. This allows for the threshold parameter to be set to true but still including all RML samples. However someone with better knowledge of the apptags and what the customer expects needs to be consulted.

#### Harder solution:
Make the threshold parameter a boolean field for the apptags instead of a parameter within the workflows. This makes more sense since samples with differing apptags can be passed trough the same pipeline.

#### Easier solution:
Add a filtering step to the `cg workflow fastq store-available` command which removes non-RML cases where samples have failed sequencing or have not been sequenced yet.

## This can be closed when

The automatic delivery of fastq files works independently of apptags.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
Decision:
- Add a condition for non RML cases that all samples for a case must have passed the QC-check before creating an analysis row in the analysis table.
