### ISSUE TITLE
NIPT orders get wrong priority on invoices

### ISSUE THREAD

**Issue by vwirta** [Clinical-Genomics/cg#1474]
## Description

Pools for NIPT get the wrong priority on invoices.
Unclear where the error occurs. 

Using the pool as example: **2204898_NIPT**

In SuSy the order seems to have correct priority: **'priority'**
In statusDb the priority is correctly: **'priority'** (search for family maturecollie)
In LiMS the priority is correctly: **'priority'**
In Cigrid/TB the status is shown as **'priority'**
In statusdb the invoice shows incorrectly **'research'** priority. See invoice specification 852

## Suggested solution

Check the code for generating the invoice specification. Is it always setting priority 'research' for pools?

## This can be closed when

Invoice specification correctly reflects the priority set by customer

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
Found the problem:
https://github.com/Clinical-Genomics/cg/blob/master/cg/meta/invoice.py#L149
For pools the prio is hard coded to `research`. This could easily be removed, so that it matches the case prio.
However this means that the price would be ~40% higher for the NIPT-samples in question. Is this correct @vwirta?

**Comment by vwirta** [comment]
> However this means that the price would be ~40% higher for the NIPT-samples in question. Is this correct @vwirta?

It is correct... in fact, I already today manually change to the higher cost ;)

**Comment by Vince-janv** [comment]
This turned out to be quite a bit more complicated to fix than expected. The invoicing part of cg is quite cryptical and it is probably worthwhile to re-write most of it. This however would need to be prioritised.

**Comment by vwirta** [comment]
thanks for looking into this @Vince-janv 
Could we, as an interim solution, hardcode NIPT always to `standard`?

**Comment by ChrOertlin** [comment]
Hi,

@vwirta , @Vince-janv I am looking into the issue. 

 Is it only cust032 - KS / Klinisk genetik / NIPT that orders NIPT samples?

If that is the case the following could be a fix (if I understand the code correctly).
`
if record.customer_id == "cust032":
            priority = record.priority_human
elif self.record_type == "Pool" or record.priority_human == "clinical trials":
            priority = "research"
else:
            priority = record.priority_human
`
Less than ideal, but it could maybe safe some manual steps until there is a decision on a re-write.

**Comment by vwirta** [comment]
Correct, cust032 is the only one who orders NIPT.

**Comment by henrikstranneheim** [comment]
@ChrOertlin Done?

**Comment by ChrOertlin** [comment]
The PR related to this was merged. As of now no complains about bugs etc. So I think we can close this. Or have there been any issues @vwirta ?
