### ISSUE TITLE
Snapshot production SV VCFs with SVDB for use in MIP.

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#149]
See also MIP issue #523.

We imagine a script for monthly running, where all available SV VCFs (eventually limited for one affected individual per family, but don't let that check become a hurdle if inconvenient) would be added such as:

svdb --build --vcf sample1.vcf sample2.vcf sample3.vcf

See https://github.com/J35P312/SVDB.

**Comment by henrikstranneheim** [comment]
This has now been replaced by production loading into Loqusdb_rd. It is live in production but awaits a final check of:
- Scout compatibility with loqusdb version 2.0 databases
- WES filter in cg to not add any WES samples to new instance of loqusdb_rd to make into a clean WGS database
- Reloading of all rare disease wgs cases into new loqusdb_rd
 to make it through to the customers.

Test specification and testing on stage for loqusdb and Scout compatibility, as well as cg wes filter scheduled next week.

@emiliaol I think this issue can be closed

**Comment by emiliaol** [comment]
I'll close this then. Feel free to reopen if relevant
