### ISSUE TITLE
Fix(bug) - Refactor path extraction from long-term-storage query

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#1516]
## Description

Backup flow cells is incorrectly fetching directories due to a split which can be inappropriately retrieve an incorrect path.

## Suggested solution

replace the splitting with a regexp:

`\/home\/hiseq\.clinical\/ENCRYPT\/.+?\s`

## This can be closed when

All flow cells can be retrieved correctly

**Comment by henrikstranneheim** [comment]
@karlnyr Is this done?

**Comment by karlnyr** [comment]
yep!
