### ISSUE TITLE
Housekeeper interface in cg should change to CLI instead of python interface

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#152]
As a developer of CG I don't want to have to keep track of the actual code in HK when using it in CG so that I can safely just code away and not risk things breaking.

Problem description:
Housekeeper API should run over the CLI instead of over the python interface. This avoids having to know about the internal workings of HK.

Prerequisites:
The HK-CLI interface should have:
- add/remove a bundle
- add/remove a version
- add/remove a file
- include a bundle

Suggested solution:
Replace the housekeeper-app in cg/app/hk.py with call to the HK-CLI interface instead.
Refactor the HK calls in the CLI code of CG to use the HK-CLI calls instead.

DoD: major

How to demo:

Questions:

**Comment by emiliaol** [comment]
@ingkebil @patrikgrenfeldt Still something we need to do? If so please add to the backlog

**Comment by henrikstranneheim** [comment]
Will bbe handled in https://github.com/Clinical-Genomics/cg/issues/233. Closing
