### ISSUE TITLE
Automatically clear family dir before analysis start

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#153]
A bioITer now needs to remove the famliy directory manually before restarting an analysis. The removal is necessary due to how result files are saved into HK. After successful analysis, the result files are saved into a bundle and the bundle is included into HK. Including means that the files of a bundle are now hardlinked into the HK structure.
When an analysis is started with the family directory still in place, the result files will be overwritten. Because those result files are also hardlinked as a bundle into the HK structure, those included bundle files are now being overwritten too!

There are two solutions:
- automatically remove the family folder on start (advantage: simple. Disadvatage: might regret starting an analysis)
- or instead of having one directory for the analysis of a family (e.g. `/mnt/hds/proj/bioinfo/families/cuddlyoryx`) consider the families folder a scratch. Meaning that each start of analysis, would be done in a directory with a randomly generated name, e.g. `/mnt/hds/proj/bioinfo/families/cuddlyoryx/GAtjaAL/`. (advantage: all analyses are kept until they are automatically cleaned up. Disadvantage: more implementation time and slightly less clear what last analysis might be)

DoD:
- minor

**Comment by Mropat** [comment]
@ingkebil  @henrikstranneheim  Do we still want this?

**Comment by henrikstranneheim** [comment]
Yes, but only for reruns i.e. a "rerun" the trigger should be that Action is set to "rerun" in StatusDB

**Comment by hassanfa** [comment]
Piggy backing on this: It is a similar situation for BALSAMIC.

**Comment by Mropat** [comment]
Stale issue. Will not be completed within current planning schedule
