### ISSUE TITLE
Cases with no data_delivery in statusdb

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1546]
## Description

Currently, old cases which have no data_delivery cause a python error when running the upload command. This is because it checks the field for the substring "scout" and fails if it is None.

## Suggested solution

Set a delivery_type for all cases missing it.

The delivery types should be set as follows, based on the data_analysis field:
mip-dna: scout
balsamic: scout
fastq: fastq
microsalt: fastq_qc
fluffy: statina
mip-rna: analysis (only 2 cust000 cases)
"" (empty string): fastq

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
@moahaegglund @henrikstranneheim Do you approve of the solution or would you like to change the mapping for some pipeline?

**Comment by henrikstranneheim** [comment]
@Vince-janv I think it looks good!

**Comment by Vince-janv** [comment]
Now fixed
