### ISSUE TITLE
RNAFUSION: implementation in production

### ISSUE THREAD

**Issue by rannick** [Clinical-Genomics/cg#1560]
## Description

Implementing rnafusion in production

## This can be closed when

- [x] start, start-available, config-case, run, store, store-available are implemented in cg (https://github.com/Clinical-Genomics/cg/pull/1541) -- running on the logging node (no tower implementation)
- [x] scout upload
  - [x] https://github.com/Clinical-Genomics/scout/pull/3747#issuecomment-1406548473
  - [x] https://github.com/Clinical-Genomics/hermes/pull/70
  - [x] https://github.com/Clinical-Genomics/cg/pull/1693
- [x] delivery report
  - [x] https://github.com/Clinical-Genomics/cg/issues/1720
- [x] implementation using tower CLI -> not mature yet because of issues due to java memory allocation (https://github.com/Clinical-Genomics/IT-issues/issues/582)
- [x] Trailblazer support
  - [x] https://github.com/Clinical-Genomics/cg/issues/1672
- [x] systemd scripts for automatic start and store
  - [x] https://github.com/Clinical-Genomics/servers/issues/971
- [x] Atlas documentation

## Blocked by

- [x] implementation using tower CLI -> not mature yet because of issues due to java memory allocation (https://github.com/Clinical-Genomics/IT-issues/issues/582) -- see above

**Comment by fevac** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RNAfusion](https://trello.com/c/L5k8OeSX/1-rnafusion)
