### ISSUE TITLE
Misleading data_delivery field for sars-cov2 and microbial cases

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1569]
### Sars-cov2
sarscov2 cases all have data_delivery FASTQ while we are actually expected to use the `sarscov2` flag when delivering the case. This then includes result files as well as fastq-files. This differs from the logic used for all other pipelines where ANALYSIS_FILES or just ANALYSIS is used to signal that files from the subsequent analysis should be delivered.

### Microsalt
Reversely, many micro cases are ordered with FASTQ_QC_ANALYSIS while we only delivery fastq files to caesar. 

## Suggested solution

Change the data_delivery option for sarscov2 from FASTQ to FASTQ-ANALYSIS

Urge customer to order cases correctly for microsalt.

## This can be closed when

The logic used for the rest of the pipelines is applicable to sars-cov2 as well.

Micro customers select the correct delivery-type.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
- Add FAST-ANALYIS to order portal
- Refactor sars-cov2 delivery CLI

**Comment by ChrOertlin** [comment]
Closing, partly duplicated by: #3339
