### ISSUE TITLE
Add new dragen node partition to SLURM API

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1571]
## Description

When IT adds the new dragen node to SLURM cg need to be able to use the new partition.

## Suggested solution

in: cg/apps/slurm/sbatch.py modify: DRAGEN_SBATCH_HEADER_TEMPLATE to have a input list of both the named dragen partitions: cg-dragen, cg-dragen2 (TBD by IT)

From SLURM docs.
"-p, --partition=<partition_names>
    Request a specific partition for the resource allocation. If not specified, the default behavior is to allow the slurm controller to select the default partition as designated by the system administrator. If the job can use more than one partition, specify their names in a comma separate list and the one offering earliest initiation will be used with no regard given to the partition name ordering (although higher priority partitions will be considered first). When the job is initiated, the name of the partition used will be placed first in the job record partition string. "

## This can be closed when

- [ ] Cg can use both dragen partitions

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by GustavLagneborgScilifelab** [comment]
Kommer CG-dragen2 läggas till som en egen partition i vår Nodelist när vi man kör `sinfo` i Hasta, eller kommer den läggas till på den nuvarande dragen partitionen?

**Comment by henrikstranneheim** [comment]
My guess would be a separate partition as it is a separate machine

**Comment by GustavLagneborgScilifelab** [comment]
If the the new DRAGEN2 will be added as core in the already existing DRAGEN partition as shown in the image below I don't think we have to do much with the config as the SLURM should intelligently assign jobs to one of the DRAGEN

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/107848458/191915329-71100f05-30a5-4331-8f88-624fc3990522.png">

If this is not the case we might have to create a new template for DRAGEN2 or class that assigns the relevant template variables.

Can we ask ScilifeLab IT if the new dragen will be a core in the existing dragen partition or if it will be a new partition?

**Comment by henrikstranneheim** [comment]
cg-dragen2 was added to the current `dragen`partiition. Hence, I think no code in cg needs to change.

```
θ67° [henrik.stranneheim@hasta:~] [base] 3s $ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
DEBUG        up   infinite      0    n/a
dragen       up 14-00:00:0      2   idle cg-dragen,cg-dragen2
core*        up 14-00:00:0      6    mix compute-0-[2,5,15,24-25],gpu-compute-0-1
core*        up 14-00:00:0     20  alloc compute-0-[3-4,6-14,16-23],gpu-compute-0-0
WHEEL        up   infinite      6    mix compute-0-[2,5,15,24-25],gpu-compute-0-1
WHEEL        up   infinite     20  alloc compute-0-[3-4,6-14,16-23],gpu-compute-0-0
WHEEL        up   infinite      4   idle cg-dragen,cg-dragen2,hasta,hasta-login
```
