### ISSUE TITLE
Microbial results folder is never cleaned

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1572]
## Description

There is no `cg workflow microsalt clean` function and hence the microsalt results folder does not seem to have been cleaned in a while. It is currently occupying 75 TB.

## Suggested solution

Add a function similar to the other pipelines to clean the folder of old cases. Then add this function to the cleaning crontab job.

## This can be closed when

- [ ] The function `cg workflow microsalt clean` has been created.
- [ ] The function is added to the crontab

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by vwirta** [comment]
Good catch!
