### ISSUE TITLE
Delivery fails when gene panel attribute is empty for a case.

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/cg#1583]
## Description

With recent changes, when the attribute 'gene panel' is empty for a case in MIP-DNA, with delivery type ANALYSIS_FILES such as for MAF controls, it causes the delivery step of that case to fail.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/57712924/193270690-a7675489-9a5e-41f7-80c3-8c10419548ae.png">

## Suggested solution

A suggestion would be to automatically set the gene panel of a case to OMIM if empty at the start of the analysis.

## This can be closed when

This can be closed when the delivery of cases without a set gene panel succeeds.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@peterpru could you estimate the gain and urgency?
