### ISSUE TITLE
Remove dependency to cyvcf2 when fixed in locusdb

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#159]
When issue https://github.com/moonso/loqusdb/issues/43 is fixed we can remove the dependency to cyvcf2

**Comment by patrikgrenfeldt** [comment]
Ensure that dependency removed in #341 and then close this issue

**Comment by emiliaol** [comment]
@patrikgrenfeldt ready to close?

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt @moonso Done?

**Comment by henrikstranneheim** [comment]
I cannot find it in the requirements or pipfile - closing
