### ISSUE TITLE
No help message in cg set sample 

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1598]
## Description

Non-standard help message (click style) is printed when running `cg set sample --help`. Additionally the following message is raised 
`Can't find sample None` and the execution is aborted. 

<img width="832" alt="image" src="https://user-images.githubusercontent.com/29628428/194902968-632651e3-ec42-441d-a0b5-ab58b9455466.png">

## Suggested solution

It can probably be fixed by making the `sample_id` argument mandatory, making it as an option (instead of argument) or exiting after printing so the execution is stopped.

## This can be closed when

The proper click help message is displayed

**Comment by Karl-Svard** [comment]
Sounds like a good first project for @mathiasbio!

**Comment by henrikstranneheim** [comment]
@mathiasbio Great work fixing this - closing.
