### ISSUE TITLE
Deliver nextclade output as part of MUTANT deliverables

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/cg#1602]
## Description

Today MUTANT does produce a nextclade output file, but this is not delivered together with the other output from gms-artic/MUTANT. 

## Suggested solution

Add the output file in the delivery to caesar

## This can be closed when

Nextclade delivery is part of production

## Blocked by
Nextclade as part of gms-artic is due for an update, and the output from this might be parsed differently going forward. Don't think this should affect the delivery, but would be good to keep an eye on.

genomic-medicine-sweden/gms-artic#68
Clinical-Genomics/MUTANT#161

**Comment by karlnyr** [comment]
Data is generated for the cases under:

```Command
/home/proj/{ENVIRONMENT}/mutant/cases/maturejay/results/ncovIllumina_sequenceAnalysis_nextclade/
```

However, they are all in `.tsv` format. I have checked with @sofstam and she agreed that primarily we are aiming to simply concatenate all of these files - only using one header - and send that as a file to the customer instead.

I think this requires some work in `MUTANT` - as I believe the concatenation should be part of the pipeline and the delivery part of `cg`

**Comment by talnor** [comment]
Output is delivered by cg based on the ks-delivery tag. Added in Hermes PR https://github.com/Clinical-Genomics/hermes/pull/84.
