### ISSUE TITLE
Old cases was re-run on wrong pipeline

### ISSUE THREAD

**Issue by GustavLagneborgScilifelab** [Clinical-Genomics/cg#1607]
## Description

When cust093 ordered a balsamic re-run in [Ticket #526214](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=52284) for old cases, it got analyzed with MIP. This is because, previously, CG just changed the pipeline instead of creating new cases.

## Suggested solution

Add a check in the orderportal that checks if the old case has the same pipeline as the order has. If not we should add some smart logic to make a new case of it. Or ask the customer to create a new family but with the same link to the sample

## This can be closed when

- [ ] when a check has been added to the orderportal

**Comment by henrikstranneheim** [comment]
@GustavLagneborgScilifelab @Vince-janv We had this up on refinement, did we decide to close this and not add any extra checks since this is a rare occasion and it will be cleaned and handled manually every time which will also make it happen even less frequently

**Comment by Vince-janv** [comment]
@henrikstranneheim I just merged a PR preventing this from happening again! Was about to close this just now 😅 

Solved in https://github.com/Clinical-Genomics/cg/pull/1639
