### ISSUE TITLE
Single sample microsalt cases are never cleaned

### ISSUE THREAD

**Issue by GustavLagneborgScilifelab** [Clinical-Genomics/cg#1608]
## Description
When a single sample microsalt case is run, no analysis object is created. Hence, the run directories for single sample cases in microsalt are never cleaned. 

The cleaning function fetches the path to delete through the lims project id e.g. ACC1234 and not ACC1234A1. 

The fact that single sample microsalt cases doesn't have a analysis object might cause other problems that I have not thought of

## Suggested solution
- write a separate cleaning function that loops through the directory and checks the single sample case and their date stamp to see if it can be deleted. This function can be invoked when the "regular" cleaning function for microsalt is invoked. It will use the same before date as the microsalt_past_run_dirs uses. 

OR

- Change the logic for single sample cases so it creates a new family etc. This might be to much work since microsalt is to be replaced.

## This can be closed when
- [ ] single sample cases is captured by the cleaning function
or
- [ ] An analysis object is created for single sample cases and captured by the cleaning function

**Comment by henrikstranneheim** [comment]
@GustavLagneborgScilifelab @moahaegglund All analyses should be on the case level to standardize the system and the logic controlling it. Are the single analysis runs on sample level a legacy thing or can it still happen?

**Comment by moahaegglund** [comment]
> @GustavLagneborgScilifelab @moahaegglund All analyses should be on the case level to standardize the system and the logic controlling it. Are the single analysis runs on sample level a legacy thing or can it still happen?

This still happens, it's mostly when we have to change the reference for a sample, instead of rerunning the whole case we just rerun one sample to save time. All samples in the case is included in the resulting QC and typing report, and this is delivered to the customer. This also means that for the cases where this happens it's not the final version of the analysis, that is delivered to the customer, that is saved in Housekeeper.

**Comment by GustavLagneborgScilifelab** [comment]
I tested running a single sample analysis for case `richowl`. This created a new run directory : `ACC10667A22_2022.10.31_16.48.45/` but no new analysis object in statusDB, as expected.

The single sample directories can easily be cleaned by altering the get_case_path in micrsalt from:

```
return [
            Path(path)
            for path in glob.glob(f"{self.root_dir}/results/{lims_project}_*", recursive=True)
        ]
```
to (removing an underscore):
```
return [
            Path(path)
            for path in glob.glob(f"{self.root_dir}/results/{lims_project}*", recursive=True)
        ]
```

However, then a single sample run directory might be deleted earlier than 21 days since it looks at the case analysis object and not when the single sample analysis was run. 

@moahaegglund @henrikstranneheim - Is it acceptable or should we create a better fix, e.g. making sure that single sample analysis gets there own analysis object etc?

**Comment by henrikstranneheim** [comment]
@moahaegglund Would it be possible to create a new single sample case with the sample in need of a rerun? Then all the logic which expects analysis to be performed on case level will work

**Comment by GustavLagneborgScilifelab** [comment]
I think one of the issues is that a single sample case can not start automatically cause it crashes. But I think customers cant order a single sample case, so maybe single sample cases are only started manually. I will explore the code more today to see if there is an easy way to make single sample cases their own family when a re-run is requested

**Comment by moahaegglund** [comment]
Good that you can look into this Gustav. `livemayfly` is an example of a case that customer has ordered that only contains one sample. As you say I see in the log that it was problematic to start this case. We have nothing saved from this analysis, not in HK or under analysis in statusDB.

I get the logic of creating a new case and have all analyses on case level. But the drawback with this approach is that it's extra work to create a new case and it will not result in one final version of the reports that contains all samples, might be a drawback for some customers. One alternative is to rerun the entire case with all samples.

**Comment by GustavLagneborgScilifelab** [comment]
I agree with @moahaegglund, microsalt analyses are fairly quick, so maybe it is easier to rerun the entire case. But I will look into the code and come back to you guys

**Comment by henrikstranneheim** [comment]
Sounds good

**Comment by GustavLagneborgScilifelab** [comment]
I have looked into it and talked to the others in prodbio, and firstly, when one sample has to be re-run, e.g. because a reference was changed, all of us just re-run the entire case. Therefore, I believe the most optimal solution would be to fix it so that a single sample case can start automatically and then make the sample-id parameter for the microsalt start command obsolete. This will make all analyses run at a case level and also get an analysis to object in StatusDB.

**Comment by henrikstranneheim** [comment]
@GustavLagneborgScilifelab Could you link the upcoming Atlas PR here when it is ready?

**Comment by GustavLagneborgScilifelab** [comment]
A relatively easy fix to this would be to additionally retrieve a list of single sample paths related to a case and then check if those files are younger than 21 days. If so, skip this case. and go to the next one. This would allow the cleaning function to only clean run dirs when all paths (case and single sample) are 21 days old. 

The only downside to this is that would introduce a new constant to maintain = 21 days.

What do you say? @moahaegglund @henrikstranneheim

**Comment by henrikstranneheim** [comment]
@GustavLagneborgScilifelab Sounds like a good solution, which is not adding a lot of complexity. 👍

**Comment by GustavLagneborgScilifelab** [comment]
Atlas documentation updated on how to handle single sample cases: https://github.com/Clinical-Genomics/atlas/pull/1280

**Comment by GustavLagneborgScilifelab** [comment]
PR merged and installed in production: https://github.com/Clinical-Genomics/cg/pull/1642

Closing issue
