### ISSUE TITLE
cannot add gene panel 'CH' when using 'cg set family'

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/cg#1609]
## Description

The most recently added gene panel cannot be added when using `cg set family -g 'CH'`, and it fails with the error: `unknown gene panel: CH`. This panel was added in PR https://github.com/Clinical-Genomics/cg/pull/1587. Example screenshot below in cg-stage on hasta:

![image](https://user-images.githubusercontent.com/57712924/198232865-0e3f5f78-e760-490e-a638-b49f81111814.png)

As extra information, for the cases that use the gene panel master list, here it is successfully added along with the other 20+ panels, and also functions as normal in scout. Below an example of a mip case starting and having CH included.

<img width="819" alt="image" src="https://user-images.githubusercontent.com/57712924/198233784-43771c35-2d62-4f09-a0bd-356b2db01615.png">

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

When cg set family can add panel CH.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
Did you add it to StatusDB?

<img width="1337" alt="Screenshot 2022-10-27 at 11 58 19" src="https://user-images.githubusercontent.com/584738/198254655-76f09906-a1f5-4c95-9ffc-84346b5bd375.png">

<img width="1337" alt="Screenshot 2022-10-27 at 11 53 21" src="https://user-images.githubusercontent.com/584738/198253515-4cf27e4f-fa4c-4bc8-b0c3-38371c8179ab.png">


Code seems to look there:
```
   if panels:
        for panel_id in panels:
            panel_obj: models.Panel = status_db.panel(panel_id)
            if panel_obj is None:
                LOG.error(f"unknown gene panel: {panel_id}")
                raise click.Abort
```

and

```
    def panel(self, abbrev):
        """Find a panel by abbreviation."""
        return self.Panel.query.filter_by(abbrev=abbrev).first()
```

The other code communiicates with Scout and the panel exists there already - therefore it works

**Comment by moahaegglund** [comment]
Added panel CH to statusDB:
<img width="1186" alt="Screenshot 2022-11-09 at 07 36 34" src="https://user-images.githubusercontent.com/19236050/200757234-ff2b44ec-d298-4a46-b1ad-ba28dcc3f794.png">
Possible to change to panel CH now:
<img width="543" alt="Screenshot 2022-11-09 at 07 40 54" src="https://user-images.githubusercontent.com/19236050/200757816-22655b2e-5ef8-4c1a-8fa8-d67e60192d9b.png">
