### ISSUE TITLE
MIP-RNA multiQC delivered to Scout

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/cg#1610]
## Description

When customers order the MIP-RNA analysis with scout delivery, it would be good to also include the RNA MultiQC in scout.
After talking to @dnil and @northwestwitch we came to the conclusion that we need cg export rna qc to scout config. From there they can then take over and make sure it's available on the frontend.

## Suggested solution

- cg exports the rna qc to scout config

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by pbiology** [comment]
I don't have any good insight in what is good or not here. Perhaps we can get @henrikstranneheim or @karlnyr in on this?

**Comment by karlnyr** [comment]
I think this should be a quite quick fix. Would need to be validated of course :) I can get something started asap.

**Comment by karlnyr** [comment]
Implementation in CG: https://github.com/Clinical-Genomics/cg/pull/1618

Waiting for @northwestwitch and @dnil to decide on final syntax to be used for the new report upload function.
