### ISSUE TITLE
Unify cg set sample labels to be able to update StatusDB and LIMS simultaneously when labels have different names

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1616]
## Description

Currently when using `cg set sample` some labels are only changed either in StatusDB or LIMS but not in both. This occurs when the label has different names even if they correspond to the same feature. 

For example:
`cg set sample -kv is_tumour false ACCXXXXX` would only change the values in StatusDB and 
`cg set sample -kv tumour no ACCXXXXX` would only change the values in LIMS.

It would be nice to unify these labels and sync them so corresponding fields can be simultaneously updated in both LIMS and statusdb if desired. 

Note: downsamples are not on registered on LIMS, so let's make sure this is still functional to change only values in either StatusDB or LIMS (and not both).

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
Added to refinement 19-06-2024

**Comment by mathiasbio** [comment]
I was working on this a million years ago but somehow it completely faded from view! Sorry!
