### ISSUE TITLE
SOI: pilars of separation

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#162]
# Pillars of separation

## The problems

Bioit and IT are very similar or have at least a very overlapping scope. Their interface is at this moment not well defined leading to ill communication, too much communication, assumptions about ones responsibilities, and assumptions on how tools interacting on the border of bioit nad IT are supposed to communicate.

## How to deal with two very similar pillars

The solution is to more clearly define the interface between Bioit (Balsamic, MIP, microsalt, ... pipelines) and IT (TTN).

## Interface of a pipeline (requirement)

- fastq files names: end with `_{1,2}.fastq.gz`
- all other information should be provided by configuration files

## Development (suggestion)

Relating to the development of a pipeline.

Requirements:
- have small test data (should cover unit and integration test). Unit test tests each component by itself. The integration test tests the interaction of those components.
- --dry-run

### Bioinformatics side

The Acceptence Testing Environment is usually referred to as A. To avoid confusion in referring to this environment, we will opt for the Swedish phonetic spelling: EJ.

The EJ is a copy of the production environment, including copies of the production databses. Those databases will have additional information related to our standard set of test samples.

How to deal with multiple people wanting to run their pipeline in EJ? FIFO + reset? Multiple EJ envs?

Requirements:
- standard set of validation samples provided by CG (production samples) and the hospitals
  - should we add GIAB data and/or dreamchallenge data?
  - in house sequence test data (cancer specific)
  - in house synthetic data (test precision and recall: F1 score)

Validation:
- assess the success of the pipeline on predefined values [expand].

### Production side

Validation:
- anchored on certain sample ids. Testing the successful automatic start and finish of the pipeline.

Verification:
- health check the input files.

## Installation to production

Installation is performed by TTN (responsible).

Requirements:
- one deployment responsible. Alternatively: multiple deployment responsibles with deployment log.
- deployment needs to be announced on morning standup (transparency)
- code to be deployed needs to follow "definition of done" (in short: production ready, unit tests, tested on stage, documented, communicated with the parties affected)
- deployment needs to follow the deployment procedure (which for example includes taking steps for a rollback)
- each release needs a semantic version or commit hash

## Running production

The maintenance of health of production is performed by TTN (responsible).
This would also mean that decisions related to the infrastructure can be made independently of the tools using the infrastructure, e.g. versions of python, virtual envs, how installation is performed.

**Comment by emiliaol** [comment]
@ingkebil Still something you want to do?

**Comment by ingkebil** [comment]
Nope
