### ISSUE TITLE
Requests for update of 1508 ordeform

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1631]
## Description

- provvolymer i excel avrundas till en decimal men OP tillåter endast heltal
- nya panelar behöver läggas till i excel-arket. ([#632752](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=51739)) + new one added by Chiara and Daniel
- add no-delivery option for placing control samples (is this needed?)

## Suggested solution

Update orderform once enough requests have been submitted

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by AnnaZetterlund** [comment]
Wish from customer to have Fibroblast as source

**Comment by AnnaZetterlund** [comment]
METLIFR010, METLIFR020, METPCFR010, METPCFR020 archived

**Comment by henrikstranneheim** [comment]
@Vince-janv Done?

**Comment by Vince-janv** [comment]
yes, updated yesterday
