### ISSUE TITLE
Positive controls in Balsamic are attempted for Caesar delivery and fail

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1633]
## Description

Positive controls in Balsamic are automatically being delivered to caesar and failing (e.g. `merrycoral` and `manyganet`). It is logical that they are being delivered as they have `analysis`  as delivery type. We should consider how to deal with this in the future. 

## Suggested solution

Potential solutions could be:
- Change delivery type (personally I prefer this option)
- Make an exception  
- Others -> to brainstorm

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
### Decision:
- Add new delivery type `no-delivery` to orderportal
- Update instructions for lab-personnel placing orders to use new type

**Comment by Vince-janv** [comment]
Solved in #1639
