### ISSUE TITLE
Suggestion: Check for customer quota in caesar and inform customer when it reaches certain limit

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1636]
## Description

Caesar deliveries often fail when the customer quota has been exceeded. In those cases we need to contact customers and ask them to delete data, wait and follow up on their response and manually restart the deliveries. It would be nice if the quota could be checked automatically and customers informed that they need to delete old data.

This could be done in several ways. An idea:
1. Set a check_quota function that gets the available and the percentage of capacity (4th and 5th columns on `df -h`) for a given customer.
2. Set a function inform_customer that informs customers and ask to delete data in the appropriate ticket

This could be run prior attempting automatic delivery.
Alternatively, this could be run once every week for all customers to avoid spamming. 
Another alternative would be to run the removal of files more frequently to avoid informing customer every time. 

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
We will move clinical-delivery to a new VM on the NetApp solution and there we can expand the storage to 50 TB (from 20 TB today). Furthermore, it is much easier to expand the storage further as a VM as we do not have to purchase any hardware. See https://github.com/Clinical-Genomics/IT-issues/issues/634. I think we should focus our efforts on getting the new solution in place so closing this for now. Let´s reopen if needed
