### ISSUE TITLE
RNAfusion: Remove unexpected parameters

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1669]
## Description

Remove unexpected parameters: `--cluster-options: --qos=low` and `--genomes:` (warning raised on the on the *.stdout.log file)

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@fevac Done?

**Comment by fevac** [comment]
not needed anymore. Closing
