### ISSUE TITLE
Add Upload date in Delivery report instead of Svarsdatum

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/cg#168]
Contact person: ES

As a customer using Scout I want the delivery report to contain relevant dates so that I can trace what has happened when with my samples.

Problem description:
"Svarsdatum" is set in LIMS manually after the upload in Scout has happened, therefore it's impossible to get that into the delivery report at upload. Instead use the upload to Scout date in the report. We also miss the Analysis (ie version of 1383 used for the analysis) because we fill that in in the delivery step after upload has happened.

Suggested solution:
* Add the Svarsdatum based on the upload date.
* Not sure what to do about the Analysis method...

How to demo:
ssh rasta
up
cg upload delivery-report -p custXXX Family_id_of_new_case_not_delivered_in_lims
the printed report should include the Svarsdatum and Analysis method.

Questions

**Comment by emiliaol** [comment]
@patrikgrenfeldt How obsolete is this after the swedac US are done?

**Comment by patrikgrenfeldt** [comment]
will be solved by #168
