### ISSUE TITLE
New panel to the DSD combo

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/cg#1689]
Hi 
For Klin Genet I've created a new panel "DSD syndromic" (DSD-S) that should be added to the clinical master list

Thank for your help,

Michela

**Comment by dnil** [comment]
Had another discussion with @4WGH about this and we are in agreement that was is desired is to add the `DSD-S` panel to the DSD combo. That seems like a straightforward request - I can make a PR.

**Comment by 4WGH** [comment]
how is it going with this issue?

Still not fixed but i can not find it in Github



________________________________
Från: Daniel Nilsson ***@***.***>
Skickat: den 23 februari 2023 20:45
Till: Clinical-Genomics/cg ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/cg] new panel to the clinical master list (Issue #1689)


Had another discussion with @4WGH<https://github.com/4WGH> about this and we are in agreement that was is desired is to add the DSD-S panel to the DSD combo. That seems like a straightforward request - I can make a PR.

**Comment by dnil** [comment]
Hi, there is also an app for your phone if you often find yourself interacting with GitHub when you don't have a full size web browser handy. A suggested fix is in GitHub, right above this message if you click the link in the email which I guess you are reading now.

It has been reviewed and approved for testing in the stage env, so at some point I, or someone else, will have to fake a case with that panel and test it. Is it urgent? The issue was a few months old so.. 😅

**Comment by 4WGH** [comment]
I did look for #1689 and can not see it.

I've had a DSD case In scout today (not present on Friday) and I can not the see DSD-syndormic


thank fot you help 🙂 Daniel



________________________________
Från: Daniel Nilsson ***@***.***>
Skickat: den 6 mars 2023 16:47
Till: Clinical-Genomics/cg ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/cg] New panel to the DSD combo (Issue #1689)


Hi, there is also an app for your phone if you often find yourself interacting with GitHub when you don't have a full size web browser handy. A suggested fix is in GitHub, right above this message if you click the link in the email which I guess you are reading now.

It has been reviewed and approved for testing in the stage env, so at some point I, or someone else, will have to fake a case with that panel and test it. Is it urgent? The issue was a few months old so.. 😅
