### ISSUE TITLE
Problems with fastq when starting and storing fastqs in stage environment

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1691]
## Description

When starting a case in the stage environment (e.g. for validations) all FASTQ files must be available (ie decompressed) and stored in housekeeper stage. However in stage the housekeeper root dir is modified and there are no files where the paths in the bundles point to.

## Suggested solution

- Somehow link the stage paths to the prod files (scary?)
- Temporarily copy the prod files to stage (when needed) and having them cleaned regularly.

## This can be closed when

Bioinformaticians and developers can intuitively navigate housekeeper and the cg CLI without need for a production member to interfere.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
Current solution is the following:
- run` cg decompress case <case_id>` in prod
- Wait for jobs to complete
-  run` cg store case <case_id>` in prod
- Copy the housekeeper prod database to stage using `systemctl --user start sql-prod-to-stage@housekeeper.service`

Decision is to not touch the logic and instead add more cases to the validation cases which are not compressed.

**Comment by henrikstranneheim** [comment]
Closing this as the current procedure described by Vincent above is the way to go right now and we will not work on other solutions to improve this within this quarter
