### ISSUE TITLE
Setup compatability with new Sequencing machine: NovaSeq Dx

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#1697]
## Description

A new sequencing machine is going to be installed. We need to make sure that our automations can handle the data it produces. The new sequencing machine will be directly connected to a Dragen server which means that it will generate fastq data instantly, thus there is no need to demultiplex but I assume we want to keep the bcl data anyways?

## Suggested solution

- Add the new server as a Nas? For removal from the server we need automations for it
- Will we encounter issues when transferring already demultiplexed data from this server to hasta?

## This can be closed when

- Data movement and usage is smooth from the new sequencing machine

**Comment by pbiology** [comment]
Part of Clinical-Genomics/project-planning#436
