### ISSUE TITLE
Microsalt case incorrectly set as failed in Trailblazer

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#1701]
## Description

Case `freshskunk` is incorrectly set to failed in Trailblazer do to failure in sample `ACC11075A27`, which is a `NTC-entba-2` with 76 reads. Due to low number of reads the assembly could not be created and the spades assembler raises an error which makes the case fail:

```
== Error ==  system call for: "['/home/proj/production/bin/miniconda3/envs/P_microSALT/bin/spades-core', '/home/proj/production/microbial/results/ACC11075_2023.1.12_12.46.12/ACC11075A27/assembly/K21/configs/config.info', '/home/proj/production/microbial/results/ACC11075_2023.1.12_12.46.12/ACC11075A27/assembly/K21/configs/careful_mode.info']" finished abnormally, err code: -6
ERROR! File not found (contigs): /home/proj/production/microbial/results//ACC11075_2023.1.12_12.46.12/ACC11075A27/assembly/ACC11075A27_contigs.fasta
```

## Suggested solution

A fix is needed to prevent incorrectly setting NTC samples as failed due to insufficient number of reads. 
Needs refinement.

## This can be closed when

Microsalt no longer fails NTC samples due to insufficient number of reads on NTC samples.

**Comment by henrikstranneheim** [comment]
@gustavlagneborg Will this PR  https://github.com/Clinical-Genomics/cg/pull/1655 affect this issue?

**Comment by gustavlagneborg** [comment]
Unfortunately not, my PR will only run QC on cases that are completed. The only affect is that these cases wont be qc checked for

**Comment by seallard** [comment]
@beatrizsavinhas is this still an issue?

**Comment by beatrizsavinhas** [comment]
I don't recall it happening again so maybe not!

**Comment by seallard** [comment]
Great! I'll close it for now then and we can open it again if it re-occurs
