### ISSUE TITLE
Delivery reports from mip-dna not included in the automatic delivery of analysis files to caesar

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#1702]
## Description

We have a request from a customer to deliver the delivery report from mip-dna to caesar. The file is listed as a file to deliver but it is not included in the delivery today as it has not been created when the files are linked to the customer folder.
This does not seem to be the case for cases analysed with balsamic.

## Suggested solution

Create delivery report before upload to caesar is initiated. 

## This can be closed when

Delivery reports is included in the automatic delivery to caesar.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ivadym** [comment]
It seems that the automatic clinical delivery upload has been added before the delivery report generation for MIP, I will take care of this @moahaegglund

**Comment by moahaegglund** [comment]
> It seems that the automatic clinical delivery upload has been added before the delivery report generation for MIP, I will take care of this @moahaegglund

Thanks @ivadym!
