### ISSUE TITLE
Flowcell H7537DSXY stuck on retrieved, even though it finished demultiplexing

### ISSUE THREAD

**Issue by gustavlagneborg** [Clinical-Genomics/cg#1715]
## Description

Novaseq flowcell H7537DSXY was stuck on retrieved 2023-01-24. Even though it finished demultiplexing, the status of the flowcell was not changed to ondisk. I manually changed it to on disk and then the corresponding cases could start

Hiseqx flowcell HK3KHALXX seems to have the same issue. I finished demultiplexing 24 of January but it is still stuck on retrieve in statusDB

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@gustavlagneborg Any idea on what went wrong?

**Comment by gustavlagneborg** [comment]
Not yet, I'm investigating the issue right now

**Comment by gustavlagneborg** [comment]
Hiseqx flowcell HK3KHALXX seems to have the same issue. I finished demultiplexing 24 of January but it is still stuck on retrieve in statusDB

**Comment by gustavlagneborg** [comment]
Is it in the `_add_flow_cell_to_status_db` function that a flowcell should change from retrieve to ondisk? @henrikstranneheim

**Comment by henrikstranneheim** [comment]
Resolved
