### ISSUE TITLE
Start automatic decompression when running cg deliver -d fastq

### ISSUE THREAD

**Issue by gustavlagneborg** [Clinical-Genomics/cg#1719]
## Description
When running `cg deliver` with fastq as delivery type it will only link existing fastq files in the housekeeper bundle file. So, if the sample has been compressed it will just skip it and link 0 files for that bundle.

## Suggested solution

GL: When running `cg deliver` it should be checked if the sample is compressed or not and if so run `cg decompress` and then link the sample. Perhaps this might be difficult since the delivery command have to wait for decompress to be finished

VJ: The delivery command should more clearly notify non-existant fastq files are attempted to be delivered, and suggest decompression first.
## This can be closed when

- [ ] Decompression intelligently starts when running `cg deliver`
- [ ] A way to queue the delivery command until all decompressions is done 

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by diitaz93** [comment]
Solved using VJ solution in #1765
