### ISSUE TITLE
RNAfusion: Add delivery report

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1720]
## Description

Add delivery report into RNAfusion and upload it to Scout.

It requires deciding and adding the metrics to deliver.

## Suggested solution

For metrics to deliver:
- Create: `cg/models/rnafusion/rnafusion_metrics_deliverables.py` and `cg/models/rnafusion/rnafusion_analysis.py`

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ivadym** [comment]
@rannick: I will include in the future annotated VCF file for Scout the following values:
- Gene fusion
- Found in DB
- arriba
- fusioncatcher
- pizzly
- squid
- starfusion
- Tools hits
- score
- junction reads
- spanning fragments
- ffpm
- exon number
- transcript ID
- transcript version

Tagging @AleksandraKrstic for metrics discussion and including a balsamic accredited delivery report for reference:

<details><summary>Delivery report</summary>

![Clinical-Genomics-Report-F0052619](https://user-images.githubusercontent.com/26309194/231809430-b9982b02-d465-4875-ba9a-169ce86086d0.png)

</details>

**Comment by vwirta** [comment]
Additional fields to RNA delivery report:
- % mapped reads
- RIN value

**Comment by AleksandraKrstic** [comment]
Information that we would like to have additionally in the delivery report are:
RNA quality: RIN value and RNA amount used for library prep.
What library prep method was used
Which sequencing application and instrument
Number of total mapped reads and % in relation to total reads
Number of mapped junction reads and % in relation to total mapped reads
Inner distance between the ends of the two reads: Passed (mean > 100 bp)/Low
The gene body coverage %
Bioinformatic pipelines used for analysis: QC, alignment, fusion calling, gene expression

Information that we would like to have in the Fusion report are:

  *   Gene fusion
  *   Found in DB
  *   arriba
  *   fusioncatcher
  *   pizzly
  *   squid
  *   starfusion
  *   Tools hits
  *   score
  *   junction reads
  *   spanning fragments
  *   ffpm
  *   breakpoints coordinates with exon number
  *   Frame status
  *   transcript IDs
  *   transcript version

Hope I didn’t forget anything
Thanks for your help!

Aleksandra Krstic, PhD
Sjukhusgenetiker
Klinisk Genetik, L5:03
Karolinska Universitetssjukhus, Solna
+46 760782721

Från: Vadym ***@***.***>
Skickat: den 13 april 2023 17:35
Till: Clinical-Genomics/cg ***@***.***>
Kopia: Aleksandra Krstic ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/cg] RNAfusion: Add delivery report (Issue #1720)


@rannick<https://github.com/rannick>: I will include in the future annotated VCF file for Scout the following values:

  *   Gene fusion
  *   Found in DB
  *   arriba
  *   fusioncatcher
  *   pizzly
  *   squid
  *   starfusion
  *   Tools hits
  *   score
  *   junction reads
  *   spanning fragments
  *   ffpm
  *   exon number
  *   transcript ID
  *   transcript version

Tagging @AleksandraKrstic<https://github.com/AleksandraKrstic> for metrics discussion and including a balsamic accredited delivery report for reference:
Delivery report

[Clinical-Genomics-Report-F0052619]<https://user-images.githubusercontent.com/26309194/231809430-b9982b02-d465-4875-ba9a-169ce86086d0.png>

**Comment by henrikstranneheim** [comment]
I wonder if we have the RIN value stored? @Karl-Svard @Vince-janv

**Comment by fevac** [comment]
I talked to @Karl-Svard and could parse LIMS to get it. We would need to add some new functions

**Comment by Vince-janv** [comment]
I found it in Arnold as well if we want to start talking to the Terminator 🤖

**Comment by fevac** [comment]
@ivadym and I are going to make a draft delivery report with these suggestions. Let's discuss it in the next refinement meeting and take a decision.

**Comment by henrikstranneheim** [comment]
Always get info from the original source - in this case LIMS. Otherwise you create an unnecessary dependency which adds complexity

**Comment by Vince-janv** [comment]
But were things like this not the intended use of Arnold?

**Comment by henrikstranneheim** [comment]
Unless of course Arnold is supposed to be the entry point to LIMS data. I have a vague memory of discussing this with Maria and Maya

**Comment by fevac** [comment]
draft delivery report to be discussed on Wednesday: https://docs.google.com/spreadsheets/d/1A1O2Y0dWOlj3x4hVvgoK2XU96Xf4COUV5mgsFN7sfRM/edit#gid=0

**Comment by fevac** [comment]
As we talked, we will add a first delivery report version that will need to be updated in the future once we have figure out how to provide information at the analysis level for descriptions and limitations (bigger project that might require statusdb changes). In this first version, this information will be at the apptag level.

Things to do:
- Get RIN and input concentration values from LIMS: @Karl-Svard 
- Get metrics file: @fevac (probably next week)
- Create delivery report: @ivadym 

please @Karl-Svard and @ivadym keep each other updated
