### ISSUE TITLE
RNAfusion: order portal support

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1721]
## Description

Add RNAfusion as a new analysis type in the order portal

### Draft plan

- [ ] Back end: cg, cgweb
- [ ] Front end: orderportal
- [ ] Update documentation if the orderportal if needed

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by fevac** [comment]
@Vince-janv could you help me understanding what changes are required in order to get this done and to know how difficult/time consuming this would be?

**Comment by henrikstranneheim** [comment]
@elevu and @Vince-janv What is the status of this in the new order portal?

**Comment by elevu** [comment]
A pull request is ready in the frontend as soon as the backend is ready. https://github.com/Clinical-Genomics/clinical-genomics-ui/pull/287

The info needs to be added to contentful, I can do it tomorrow

**Comment by henrikstranneheim** [comment]
@elevu Great thx!

@Vince-janv and @islean Do you think Isak can start working on this next week?
