### ISSUE TITLE
Improve Balsamic analysis API and workflow methods

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#1724]
## Description

Balsamic workflow and analysis methods need a refactoring. Currently, small changes to the workflow require uncorrelated code changes, and it is often difficult to follow the flow of data, both for the code writer and reviewers, as there are weird custom types being passed from method to method, e.g. the `sample_data` dictionary. In minor scale, this is also affecting the rest of the pipelines making use of the analysis API.

## Suggested solution

- [ ] Update the CLI (`cg/cli/workflow/balsamic/*`)
  - [ ] Review docstings ensuring clarity and relevance
  - [ ] Add missing typehints (methods & variables)
  - [ ] Review LOG messages and exceptions
  - [ ] Move shared click options to constants
  - [ ] Fix broken declarations by defining `config_case`, `report_deliver`, etc. in the parent Analysis API
  - [ ] Replace the `context.invoke()` with calls to analysis API methods

> - [ ] Updated `cg/meta/workflow/balsamic_*.py`
> - [ ] Updated `cg/models/balsamic`
> - [ ] Updated `tests/cli/workflow/balsamic`
> - [ ] Updated `tests/meta/workflow/test_balsamic.py`
> - [ ] Updated `tests/models/balsamic`

## This can be closed when
- [ ] Make use of Data Classes to manage the data flow.
- [ ] Validate the data through Pydantic models (remove the `get_verified_` methods).
- [ ] Fix broken declarations (`analysis_api.config_case` for example).
- [ ] Clean unused methods (`build_sample_id_map_string`, etc.)
- [ ] Add new constants and remove all hardcoded variables that are widely used through the API.
- [ ] Add typhints, improve docstrings, and update variable names to enhance readability.
- [ ] Add pytest for the missing methods.

**Comment by henrikstranneheim** [comment]
Love it 🎉🤩

**Comment by ivadym** [comment]
Not relevant anymore since https://github.com/Clinical-Genomics/project-planning/issues/547
