### ISSUE TITLE
Clean case folders for MIP-RNA cases

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1727]
## Description
Currently the `cg clean mip-past-run-dirs` only fetches and removes MIP-DNA cases. This results in MIP-RNA cases not being cleaned (currently a total of 1236 folders under /home/proj/production/rare-disease/cases). 

## Suggested solution

- Rename the function mip-past-run-dirs to mip-dna-past-run-dirs
- Create a new function mip-rna-past-run-dirs that cleans MIP-RNA case folders

## This can be closed when

- [ ] The cleaning of MIP-RNA case folders are regularly cleaned like all other pipelines

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
Current state:
```
du -sch /home/proj/production/rare-disease/
286T	/home/proj/production/rare-disease/
``´
Since we are quickly running out of storage space I manually did:

```
6d [hiseq.clinical@hasta:~] [P_base] $ find /home/proj/production/rare-disease/cases/*/analysis/ -mtime +120 -type f -delete -print
θ61° 6d [hiseq.clinical@hasta:~] [P_base] 1h32m32s $ du -sch /home/proj/production/rare-disease/
146T	/home/proj/production/rare-disease/
```
