### ISSUE TITLE
Make mip agnostic to "Min Sequencing Depth" for Rxxx apptags

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#1728]
## Description

There was an error where mip-dna case failed to start due to `sample -> expected_coverage: Field may not be null`. This happened because the apptag used for this sample (https://cg-statusdb.scilifelab.se/admin/application/?search=WGSDPFR400) didn't have a value set for "Min Sequencing Depth". However, the criteria for these Rxxx tags is only that 75 % of reads should be guaranteed and coverage is not relevant. To fix the issue, the value for "Min Sequencing Depth" was added in statusDB and the case had to be restarted mannually.

In order to prevent future cases not running due to this issue, we should make mip agnostic to "Min Sequencing Depth" for Rxxx apptags.

## Suggested solution

- Make the code agnostic to a NULL value for "Min Sequencing Depth" for Rxxx apptags.
- Needs further refinement.

## This can be closed when

- Cases with Rxxx apptags without a value set for "Min Sequencing Depth" can start without problems.

## Blocked by

As far as I know, there is nothing blocking this issue from being fixed.

**Comment by henrikstranneheim** [comment]
Easy workaround is just to add `0` to the `Min Sequencing Depth` field in status db.

We should also let the field default to 0 if no value is supplied when creating the application tag by cg
