### ISSUE TITLE
Slow CLI commands

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#1732]
## Description
Our different CLIs can take more than 20 seconds to execute on Hasta. This is an issue because it makes working with the tools we build annoying and inefficient.

### Why is it slow? 
Based on profiling, it is due to slow loads from the networked storage (GPFS) on Hasta for all packages used in our projects. The packages are loaded at runtime from GPFS, which involves transferring them over a network which introduces a delay.

Measuring with `multitime -n 10 cg --help`

Local results
```
===> multitime results
1: cg --help
            Mean        Std.Dev.    Min         Median      Max
real        1.540       0.011       1.526       1.538       1.566       
user        1.911       0.009       1.902       1.909       1.935       
sys         0.316       0.004       0.309       0.316       0.322 
```

Hasta stage environment results
```
===> multitime results
1: /home/proj/stage/bin/miniconda3/envs/S_main/bin/cg --help
            Mean        Std.Dev.    Min         Median      Max
real        24.073      2.771       21.588      23.177      30.946      
user        3.026       0.214       2.636       3.037       3.325       
sys         2.695       0.089       2.568       2.710       2.823 
```

Running various profilers and simply interrupting the CLI indicates that a lot of time is spent on importing different dependencies.

## Suggested solutions
- Do not install the tools on the networked storage
- Setup a ramdisk and install the tools there
- Create a local partition and install the tools there
- Package CLI with dependencies in a container or in some other way (loading many separate small files is much slower compared to one larger unit on a GPFS)

## This can be closed when
The execution time for various commands is reasonable/proportional to what the command actually does. Getting information about the commands should be instantaneous.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
Here is a flame graph of ```cg --help``` generated using py-spy in the Hasta stage environment with

```
cg --help & echo $! > pid
py-spy record -o profile.svg --pid $(<pid)
```

![profile](https://user-images.githubusercontent.com/33596072/216632885-0afbdbda-ccff-49e8-9677-809ab93a819c.svg)

**Comment by seallard** [comment]
From the flame graph above we can see that some specific function calls are present in a large percentage of the sampled stack traces.

| Function call      | File name | % of sampled stack traces |
| ----------- | ----------- | ----------- |
| import pandas      |  fluffy.py     | 30 %
| import requests_cache    | lims/api.py        | 11 %
| import alchy   | stats.py       | 5 %
| import requests   | tb/api.py       | 4 %
| import jwt  | tb/api.py        | 4 %
| import yaml  | yaml.py       | 2 %

**Comment by seallard** [comment]
Reproducing the Hasta stage environment (CentOS Linux release 7.9.2009, conda 4.12, python 3.7.1) and installing cg with:
```
conda run --live-stream --name  cg_test pip install -U "git+https://github.com/Clinical-Genomics/cg@master"  --force-reinstall --no-deps
conda run --live-stream --name cg_test pip install -U "git+https://github.com/Clinical-Genomics/cg@master"
```

Seems to be some specific issue with the Hasta environment.

```
===> multitime results
1: cg --help
            Mean        Std.Dev.    Min         Median      Max
real        1.832       0.121       1.745       1.791       2.184       
user        1.656       0.026       1.600       1.657       1.702       
sys         0.137       0.012       0.117       0.140       0.154 
```

**Comment by seallard** [comment]
```
[sebastian.allard@hasta:~/cg] [S_main] master ± python -m cProfile cg/cli/base.py | sort -rn -k 2 | head -n 20

     1510   11.766    0.008   11.766    0.008 {method 'read' of '_io.FileIO' objects}
  128/127    2.879    0.022    2.898    0.023 {built-in method _imp.create_dynamic}
     1510    2.395    0.002   14.160    0.009 <frozen importlib._bootstrap_external>:914(get_data)
     8243    2.063    0.000    2.063    0.000 {built-in method posix.stat}
     1510    0.355    0.000    0.355    0.000 {built-in method marshal.loads}
3845/3761    0.245    0.000    1.141    0.000 {built-in method builtins.__build_class__}
   128/76    0.074    0.001    1.601    0.021 {built-in method _imp.exec_dynamic}
      486    0.061    0.000    0.061    0.000 {built-in method posix.listdir}
      595    0.056    0.000    0.056    0.000 {built-in method builtins.compile}
33513/593    0.051    0.000    0.111    0.000 copy.py:132(deepcopy)
     1185    0.050    0.000    0.058    0.000 sre_compile.py:276(_optimize_charset)
 1544/316    0.047    0.000    0.131    0.000 sre_parse.py:475(_parse)
     2685    0.044    0.000    2.059    0.001 <frozen importlib._bootstrap_external>:1356(find_spec)
       18    0.043    0.002    0.043    0.002 {method 'read' of '_io.BufferedReader' objects}
     1455    0.039    0.000    0.040    0.000 {method 'sub' of 're.Pattern' objects}
39066/37884    0.038    0.000    0.185    0.000 {built-in method builtins.hasattr}
   2122/1    0.037    0.000   22.015   22.015 {built-in method builtins.exec}
        1    0.037    0.037    0.037    0.037 grid_file.py:412(GridOut)
   140591    0.035    0.000    0.042    0.000 {built-in method builtins.isinstance}
    51472    0.033    0.000    0.034    0.000 {built-in method builtins.getattr}

```

**Comment by seallard** [comment]
The slow imports might be due to the type of file system used by Hasta (GPFS).

**Comment by seallard** [comment]
Copying an environment from GPFS to the local file system

```
 cp -R /home/proj/stage/bin/miniconda3/envs/test_imports_env/*  /var/tmp/test_env_local/
 conda activate /var/tmp/test_env_local/
```

The import is significantly faster:
```
time python -X importtime -c 'import pandas'

real	0m1.786s
user	0m3.329s
sys	0m2.353s
```

```

**Comment by seallard** [comment]
Some possible solutions suggested by GPT:

### Caching libraries on local storage:
If users frequently use the same set of libraries, you can cache those libraries on the local storage of each node. This can help to reduce the time taken to load libraries from the GPFS. To do this, you can create a local directory on each node (e.g., /local/python_libs/) and copy the necessary libraries into it. Make sure to update the PYTHONPATH environment variable accordingly.

### Use a containerization solution:
Containerization tools like Docker or Singularity can help package the tool and its dependencies into a single, portable unit. Users can run the containerized version of the tool, which already includes the required libraries, reducing the need to access the GPFS repeatedly.

### Use a Python virtual environment:
Create a Python virtual environment on the local storage of each node and install the required libraries there. This way, users can activate the virtual environment to use the CLI tool, which can help to reduce the loading time. However, this solution might not be ideal if you have a large number of users and nodes, as it would require maintaining separate environments for each user and node.

### Optimize GPFS performance:
You can also investigate the GPFS performance and try to optimize it by tuning GPFS parameters or adjusting the configuration. For example, you can enable data prefetching or adjust the buffer pool size to improve I/O performance. However, this might require in-depth knowledge of GPFS and might not guarantee a significant improvement in loading times.

### Deploy the tool to local storage:
As you mentioned, the simplest solution might be to deploy the CLI tool to local storage on each node. However, this approach might not be ideal if the tool needs frequent updates or if there are many nodes to manage.

Each of these solutions has its pros and cons, and the best option would depend on your specific use case and constraints. It might be worthwhile to explore a combination of these solutions to achieve optimal performance.

**Comment by seallard** [comment]
## Test caching libraries on local storage

### Creating a local cache and updating the Python path
```
mkdir /var/tmp/python_cache

us
conda activate S_main
cp -R /home/proj/stage/bin/miniconda3/envs/S_main/lib/* /var/tmp/python_cache
 
PYTHONPATH="/var/tmp/python_cache/lib/python3.7:/var/tmp/python_cache/python3.7/site-packages:/var/tmp/python_cache/python3.7/lib-dynload:${PYTHONPATH}"

# For some reason, these need to be removed from the cache
rm -R /var/tmp/python_cache/site-packages/cg
rm /var/tmp/python_cache/site-packages/dataclasses.py
```

A copy of the Python dependencies in the S_main conda environment has been created on the local storage of the node. The Python path has been updated to search for libraries in the cache first, before accessing the GPFS and looking for them there (which seems to be slooooow).

### Validating the fix
Measuring before applying the fix:
```
[sebastian.allard@hasta:~] [S_base] $ time cg --help

real	0m29.931s
user	0m4.298s
sys	0m3.440s
```

Measuring after applying the fix in the stage environment:
```
[sebastian.allard@hasta:~] [S_main] 11s $ time cg --help
real	0m8.763s
user	0m3.397s
sys	0m2.472s
```

Which is a bit faster but still pretty slow.


### Suggested solution and remaining questions
A simple solution would be to just add an rsync line to our deployment script, ensuring the Python cache is updated with the latest dependencies. I'm not entirely sure how this solution works with all of the nodes, whether it has to be applied individually or if all nodes can access the same `/var/tmp/python_cache`. Maybe there is a more suitable location for the cache outside the GPFS or maybe we should create a separate partition for it somehow. Or maybe there is a better solution!

**Comment by seallard** [comment]
Before fix:
```
multitime -n 10 /home/proj/stage/bin/miniconda3/envs/S_main/bin/cg --help
===> multitime results
1: /home/proj/stage/bin/miniconda3/envs/S_main/bin/cg --help
            Mean                      Std.Dev.    Min         Median      Max
real      7.468+/-4.7280      4.718       5.528       5.919       21.596      
user     3.389+/-0.2114      0.211       3.073       3.385       3.928       
sys       2.975+/-0.1153      0.115       2.758       2.978       3.243 
```


After fix (updating python path with local cache):
```
multitime -n 10 /home/proj/stage/bin/miniconda3/envs/S_main/bin/cg --help
===> multitime results 
1: /home/proj/stage/bin/miniconda3/envs/S_main/bin/cg --help
                    Mean                Std.Dev.    Min         Median      Max
real        2.136+/-0.8451      0.843       1.412       1.699        3.976       
user       3.040+/-0.1641      0.164       2.865      3.001        3.377       
sys         2.540+/-0.0801     0.080       2.450      2.523       2.723 
```

**Comment by seallard** [comment]
The fix consisting of a local cache with python packages is not viable in the long term since it may cause issues with stale packages, version mismatches and corrupted packages.

**Comment by seallard** [comment]
Wrapping the cg cli in a container seems to provide a 3x speedup https://github.com/Clinical-Genomics/cg/pull/2610

**Comment by diitaz93** [comment]
## Closing as not planned to work on it
