### ISSUE TITLE
Add file tags to protect in Housekeeper for Balsamic analysis

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1739]
## Description
We need to decide which Balsamic files are needed to keep in Housekeeper for longer than 1 year. The other files will be deleted.

*Describe the problem/suggestion*

## Suggested solution
- Add housekeeper tags to protect for Balsamic in `cg/constants/housekeeper_tags.py`:
```
WORKFLOW_PROTECTED_TAGS = {
    str(Pipeline.BALSAMIC): [],

```
Unprotected files will be removed by systemD via: `config/hasta.scilifelab.se/systemd/cg-clean-hk-case-bundle-files.service`

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@Clinical-Genomics/balsamic It would be great to sit down and define the list of tags next week

**Comment by ivadym** [comment]
Has been addressed here: https://github.com/Clinical-Genomics/cg/pull/1769
