### ISSUE TITLE
Clean all Balsamic pipeline analysis case folders

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1740]
## Description
Currently `cg clean balsamic-past-run-dirs` only fetches and removes pipeline = balsamic, case folders This results in Balsamic-umi, balsamic-pon, balsamic-qc cases not being cleaned (currently a total of 776 folders under  /home/proj/production/cancer/cases/).

*Describe the problem/suggestion*

## Suggested solution

- Write new CLI functions to also clean the other balsamic run dirs and add automated removal using systemD

## This can be closed when

- All Balsamic pipelines are regularly cleaned

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
I manually did:
```
 find /home/proj/production/cancer/cases/*/analysis/ -mtime +120 -type f -delete
90T	/home/proj/production/cancer
```

**Comment by seallard** [comment]
Is there a reason why it is desirable to have a separate command for cleaning up the different directories related to balsamic?In my mind, it seems more intuitive to have a single clean up command for each pipeline which handles all of the related directories and files. So in this case, is it OK to just update the ```cg clean balsamic-past-run-dirs``` command? @henrikstranneheim

**Comment by henrikstranneheim** [comment]
Yes, that sounds fine. I think @diitaz93 did it the other way around and added a parallel command. That way is more transparent and atomic, although  requires a bit mire work to create the systemD command and API:s. I think it would be good to do it in the same way (whichever route we take)

**Comment by seallard** [comment]
I decided to stick to one command per pipeline for now to be consistent. I think it is more clear that way
