### ISSUE TITLE
Clean fohm upload folder

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1759]
## Description

The folder where the fohm uploads are being aggregated is never cleaned and contains all the FASTQs and assemblies from each upload. It currently contains 12 T of data

## Suggested solution

1) These should be cleaned up after the upload is completed
2) A regular cleaning job is run to clean up the folder

## This can be closed when

- [ ] The fohm upload folder is cleaned automatically

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
Would it be a good idea to update the mutant_past_run_dirs to clean these directories as well? Or should a new cg command be added for it? Or maybe the files should be deleted immediately after the sftp transfer @Vince-janv

**Comment by Vince-janv** [comment]
To me the last solution (delete immediately after the sftp transfer) sounds the cleanest, however I'm not very familiar with the code. I like all of your suggestions, so I think you're opinion is as good as mine! 👍

**Comment by seallard** [comment]
Completed https://github.com/Clinical-Genomics/cg/pull/1763
