### ISSUE TITLE
Verify capture kits set through the CLI

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#177]
As a bioiter, I want to be able to change the capture kit of a sample on the command line. The input needs to be validated.

**Problem: **
Now the command `cg set sample --capture-kit` can take any input. The input should be validated against the possible capture kit options. Those options can be found here: https://github.com/Clinical-Genomics/cg/blob/ffb6db6acdbbc2707c4a7b62d6daa9b1fc638216/cg/meta/analysis.py

**Suggested solution:**
- Change capture kits being hardcoded to a table in statusdb.
- Capture kits are not hardcoded in `cg/constants.py`

**Questions: **
Q: How can we apply the same validation to the input of clinical-api?

**What needs to be done on the planning meeting:**
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by ingkebil** [comment]
OK, then this US doesn't apply and we can remove it. what do you say?

**Comment by emiliaol** [comment]
I say we can remove it unless you have a good way of just giving a warning if you don't supply a regularly used capture kit?

**Comment by ingkebil** [comment]
That's possible. I've added that to the suggested solution.

**Comment by emiliaol** [comment]
@patrikgrenfeldt Might be sort of implemented already, care to update or close?
