### ISSUE TITLE
improve --note option with cg set sample

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#178]
In `cg set sample`
- rename the `--note` to `--add-comment` to reflect the structure of statusdb and the action that is happening.
- print out the comments after adding the note

Questions: 
None so far.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by emiliaol** [comment]
Done here right? https://github.com/Clinical-Genomics/cg/pull/182

**Comment by patrikgrenfeldt** [comment]
resolved by #182
