### ISSUE TITLE
Create interim solution for updating LIMS data from orders

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1785]
## Description
The workflow of a major customer relies on sending emails after placing orders, do update some values. Currently sample volume but in the future well-position as well. This is not reliable and requires manual work from both sides.

## Suggested solution
Create and interim solution were samples can have these two fields modified trough the orderportal.

## This can be closed when

The communication of these changes are handled less manually, and trough the orderportal.
Functionality needed:
- Changes to the Orderportal UI
- At least two new endpoints in cg
- Functions in cg to update the correct fields in LIMS

**Comment by ChrOertlin** [comment]
Added to refineent 19-06-2024

**Comment by Vince-janv** [comment]
No longer relevant
