### ISSUE TITLE
Possible issue with the assignment of ondisk status for flowcells

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg#1799]
## Description

There could be a current bug where flowcells have issues assigning and de-assigning the status `ondisk` in statusdb. There have been several instances in production where analyses couldn't start as a flowcell was set to ondisk but in actuality already had been removed from hasta. In the same vein, some recently demuxed old flow cells haven't been set to ondisk after all the required post-demux steps had been performed. Newly sequenced flow cells are, however, unaffected by this.

FCs I have encountered so far where ondisk hadn't been set:
HVMVHDSXX, novaseq
HY2N7DSXX, novaseq
HY22FDSXX, novaseq
HVMVHDSXX, novaseq
HYG7YDSXX, novaseq
H3YKMDSXY, novaseq

FCs that were incorrectly set to ondisk:
HHKVCALXX, hiseqx
HHH5TDSX2, novaseq

I'll update these lists if any new ones are identified.

## Suggested solution

Investigate the ability of to set `ondisk` in current cg based automation. 

## This can be closed when

A fix or explanation has been found, and flow cells are able to be processed as normal again.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by beatrizsavinhas** [comment]
After manually generating the SampleSheet for flow cell **HLCKNCCXY** and starting demultiplexing according to [Demultiplexing HiSeqX](https://atlas.scilifelab.se/production/data_analysis/supporting_procedures/demultiplexing_in_production/demultiplexing_hiseqx/#demultiplexing-and-fastq-generation), this same issue was observed and the status remained as `retrieved` for this flow cell in statusdb.
I noticed that the project based stats files created by the automation in the demultiplexing directory were empty. After manually re-generating all the stats files and making sure they were added to cgstats, I manually set the flow cell status to `on disk ` in statusdb.

**Comment by Vince-janv** [comment]
@Karl-Svard Has this occurred lately or was it solved in the series of patches las autumn?

**Comment by Karl-Svard** [comment]
I have seen it once or twice in the last few months. But it's hard to know if this is because of an existing bug or simply remnants of one that was fixed last year

**Comment by Vince-janv** [comment]
The status is set to ondisk during the post-processing of a sequencing run. If it is still retrieved then the post-processing must have failed. Could you post here next time this happens?

**Comment by Vince-janv** [comment]
@Karl-Svard Will close this for now. If this happens again, can you leave the crime scene untouched and ping the sentinel?
