### ISSUE TITLE
Add reception control things

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/cg#18]
Order:

- [x] add expected reads to "Reads missing (M)" UDF (as millions of reads)
- [x] update WGSPCFC030 => WGTPCFC030 (for 3-4 members in a family)

cgweb:

- [ ] report duplicate sample names when creating order (specially from orderform)

**Comment by ingkebil** [comment]
@patrikgrenfeldt do you know if this is still needed?

**Comment by patrikgrenfeldt** [comment]
shpould be solved by https://github.com/Clinical-Genomics/cgweb/pull/47

**Comment by patrikgrenfeldt** [comment]
Could you please close it?

BR
P

2018-05-15 15:48 GMT+02:00 Kenny Billiau <notifications@github.com>:
