### ISSUE TITLE
Refactor structure of handlers

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#1802]
## Description
We have one handler for each CRUD action. Separating them into model specific handlers could make the code more modular and easier to maintain.

## Suggested solution
Implement base handlers for CRUD and separate ones for each model.

handlers/
    ├── base.py
    ├── base_find_handler.py
    ├── base_create_handler.py    
    ├── base_update_handler.py
    ├── base_delete_handler.py
    ├── case/
     │   ├── case_find_handler.py
     │   ├── case_update_handler.py
     │   └── case_delete_handler.py
     │   └── case_create_handler.py

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
Sounds great 💯

**Comment by seallard** [comment]
Seems more like a guideline/design thing, does not belong in an issue
