### ISSUE TITLE
_add_missing_reads function not working

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#1817]
## Description
The [_add_missing_reads function](https://github.com/Clinical-Genomics/cg/blob/f64c28a39d5c73811e3e5aa4bd02d4d72f80b0d4/cg/meta/orders/submitter.py#L47-L52) does not seem to be working. It is used when submitting some orders, but the field does not seem to be set in LIMS. Instead [LIMS queries cg](https://github.com/Clinical-Genomics/cg_lims/blame/master/cg_lims/EPPs/udf/set/set_samples_reads_missing.py) in the reception control steps and sets the field.

## Suggested solution
- [x] Remove the function from cg,https://github.com/Clinical-Genomics/cg/pull/3444
- [ ] Fix the function in cg, and remove it from cg-lims

## This can be closed when
The faulty function is removed from cg or fixed

**Comment by diitaz93** [comment]
## Technical refinement
Delete this function in cg and its usages

**Comment by henrikstranneheim** [comment]
Remove function in cg: https://github.com/Clinical-Genomics/cg/pull/3444

**Comment by ChrOertlin** [comment]
addressed in #3574
