### ISSUE TITLE
Decrease the notification fatigue of systemD services failing in slack

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/cg#1830]
## Description

Right now there is a bit of notification fatigue going on in the systemd slack logs channels. It feel like failures could get lost due to the shear amount of messages per day in there. It feels tricky to now add new services, and feel safe in that someone would spot a failure.

## Suggested solution

There are two things that would help.
One would be to collect data on which services keep failing loudly and try to patch these. A good example is all the atlas-doc services failing.

Another help could be to improve the slack-notification services to include pings to set usergroups on slack. As one now can make usergroups (say for instance with all of prod-bioinfo members), one could include a @prodbioinfo group for that channel and make sure that a slack notification is sent out to them when selected services fail. This would help certain things to cut through the noise.

## This can be closed when

**Comment by ChrOertlin** [comment]
This does not seem to be related to CG, but rather the Slack / systemd services in servers. Closing
