### ISSUE TITLE
Remove two obsolete panels from the DSD order bundle

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#1831]
## Description

Two of the panels on the DSD-bundle have become obsolete, and are "deleted" by the responsible clinician in Scout. However, new cases are still ordered with the panel.

![Screenshot 2023-03-22 at 10 20 13](https://user-images.githubusercontent.com/758570/226857719-94328eb5-f049-483c-a298-efee56f7e5bb.png)

## Suggested solution

Remove the two panels SEXDET, SEXDIF from the DSD bundle.

## This can be closed when

Remove the two panels SEXDET, SEXDIF from the DSD bundle.

**Comment by henrikstranneheim** [comment]
@beatrizsavinhas Do you have time to take a look?

**Comment by beatrizsavinhas** [comment]
The obsolete panels have now been removed from the DSD panel bundle!
