### ISSUE TITLE
Add multiqc report to scout config

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#185]
As a Scout user, I want to be able to see the multiqc report in Scout, so that I know if I can trust the data.

Problem: 
The multiQC report is not presented to Scout

Suggested solution:
1. Find out where the report is produced by MIP: <case-id>_qc_sample_info.yaml. Needs to be parsed in TB.
1. store in housekeeper with tag `multiqc-report` based on key: 
```multiqc:
    <case-id>_html: <path>``` 
Add to `cg store`
2. Add it to the scout load config from housekeeper using the field `multiqc: <path to report>`.
Add to `cg upload scout`
3. verify

Expected outcome/DoD (minor):
`cg upload scout --dry <case>` output should contain the `mulitqc: <path to report>`

How to demo:
`cg upload scout --dry <case>`

**Comment by emiliaol** [comment]
@henrikstranneheim Is this something we have in v6 or do we need ot wait for v7?

**Comment by henrikstranneheim** [comment]
Sample multiqc reports have been in MIP since ages ago. Additional support for one report per case is MIPv7 😄.  
See https://github.com/Clinical-Genomics/MIP/issues/515

**Comment by emiliaol** [comment]
Ah right, so we need to store this in HK and upload to Scout then?

**Comment by henrikstranneheim** [comment]
Spot on!!

**Comment by henrikstranneheim** [comment]
@ingkebil @barrystokman @emiliaol @patrikgrenfeldt Do not forget this for MIP 7.1. This is also the file that Vogue needs for trending.

**Comment by ingkebil** [comment]
Alright. We have the entry point from MIP, but what's the entry point for scout? Can someone let us know where to place what for scout? @moonso @henrikstranneheim ?

**Comment by ingkebil** [comment]
As this doesn't seem critical to get MIP7 in production, we can work on this after the validation.

**Comment by henrikstranneheim** [comment]
It is critical for Vogue, good for production, bionfo and other Scout users. It should be quite easy to add to the branch and maybe most importantly it has been due for a year.

**Comment by moonso** [comment]
@ingkebil in the scout load config for a case:

```
...
multiqc: path/to/report
```

**Comment by henrikstranneheim** [comment]
Will be fixed here: https://github.com/Clinical-Genomics/cg/pull/533

**Comment by henrikstranneheim** [comment]
Done in #542
