### ISSUE TITLE
Add Balsamic validation cases  

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1855]
## Description

Add validation cases for Balsamic WES:
- livedeer (TO, WES)
- Add (TN, WES)

## Suggested solution

- Add cases to: `cg/constants/compression.py`

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@ivadym @fevac Is this done or planned?

**Comment by fevac** [comment]
No, I can do it this week
