### ISSUE TITLE
Upload research variants to Scout for Balsamic UMI

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#1880]
## Description

It has been reported that a reduced number of variants are currently being uploaded to Scout for Balsamic UMI due to clinical filtering being too restrictive.

## Suggested solution
- Upload research and clinical variants
- Upload only research variants
- Improve clinical filtering for UMIs (Balsamic issue)

## This can be closed when
- [ ] A comparison of the number of variants has been made between the clinical and research files
- [ ] Research variants are uploaded to Scout

**Comment by vwirta** [comment]
Where was this reported? I would like to read more about this.
