### ISSUE TITLE
Duplicate endpoints

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#1886]
## Description
There currently are two duplicate endpoints: /families and /cases. These represent the same resource, but the logic in the endpoints differ. We should rename/remove them so there is a single endpoint representing the cases resource.

**Comment by elevu** [comment]
/families is currently used in 
cigrid-ui
clinical-genomics-ui
cgweb

/cases is not used anywhere that I know. 

The cg flask app hosted on https://cg-statusdb.scilifelab.se/admin/ might also use these endpoints.

**Comment by islean** [comment]
Discussed a bit with @elevu over slack. Suggested actions to ensure stability in the frontend are:
1. deploy change in backend causing /cases and /families to both invoke the /families logic.
2. deploy changes in the frontend to reroute usage to /cases
3. deploy change in backend removing /families as an endpoint.

**Comment by islean** [comment]
Reopening since more actions are needed

**Comment by islean** [comment]
Duplicated endpoints are now removed.
