### ISSUE TITLE
families endpoint always filters on hard coded pipeline

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#1889]
## Description

In the API the /families endpoint always filters cases bases on the MIP DNA pipeline when the analysis filter is requested.

```python
def _get_cases(
    status: str, enquiry: Optional[str], action: Optional[str], customers: Optional[List[Customer]]
) -> List[Family]:
    """Get cases based on the provided filters."""
    if status == "analysis":
        return db.cases_to_analyze(pipeline=Pipeline.MIP_DNA)
```

## Suggested solution
Should accept parameter specifying which pipeline.

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
Resolved in https://github.com/Clinical-Genomics/cg/pull/2096, closing
