### ISSUE TITLE
Transfer microbial QC analysis data to Trending db

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#189]
This issue is related to the Trending goal.

Problem: 
Some of the high priority goals in the trending project is to plot information from the microbial QC analysis. This information is currently not stored in status-db, but in some other database. 

Steps to reproduce
  1. update the microbial table int hte database with new columns
  2. update the microbial model in cg
  3. write new script (ore something) to load the qc data from the pipeline inte status-db. - should be part of the cg code?
  4. update the "api" to contain the new microbial information

Expected outcome / suggested solution:

What needs to be done on the planning meeting:
- Estimate storypoints

**Comment by emiliaol** [comment]
Should we not store this in Trending db?

**Comment by mayabrandi** [comment]
I think when this was written, It was still not decided that the trending database also should contain lims data that is already stored in cg. That is why we wrote cg here.
