### ISSUE TITLE
Rename samples in VCF/BCF/Tabix

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/cg#19]
Quite easy with bcftools

http://samtools.github.io/bcftools/bcftools-man.html#reheader

1. create file with `sample_id sample_name\n`
1. `bcftools reheader --samples /path/to/samples.txt --output /path/to/new_file.vcf`

**Comment by robinandeer** [comment]
...and here is the command for BAM files: https://github.com/IARCbioinfo/BAM-tricks#change-sample-name

**Comment by robinandeer** [comment]
...and here is the command for BAM files: https://github.com/IARCbioinfo/BAM-tricks#change-sample-name

**Comment by robinandeer** [comment]
@ingkebil: did you see this since you are updating the delivery scripts?

**Comment by emiliaol** [comment]
Maybe time to actually do this as part of the delivery...

**Comment by moonso** [comment]
Is this still an issue @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
yes

**Comment by Mropat** [comment]
Will not be addressed within current planning cycle
