### ISSUE TITLE
Missing fastq files for a case

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/cg#2]
Can you look into this @ingkebil? How can we check this before starting the analyses?

Missing dir: `/mnt/hds/proj/bioinfo/MIP_ANALYSIS/customers/cust003/15002/wgs/SVE2622A11/fastq`
Case: `cust003-15002 `

**Comment by Dilea** [comment]
This is a case when not all samples are sequenced yet and we will have these regularly, I think.

**Comment by ingkebil** [comment]
https://github.com/Clinical-Genomics/deliver/blob/master/deliver/cli.py#L98

Checks cgstats and on disk and throws errors when files are missing that should be there

**Comment by robinandeer** [comment]
Is there a Python API exposed for this? Best of all to return True/False if all *expected* fastq-files are linked?

**Comment by ingkebil** [comment]
There are two situations:
1/ list the expected fastq files on disk for a sample?
2/ are the expected links present in MIP_ANALYSIS?

The first is partly there, but only in the CLI, so I'll fix that into an API call that returns true/false. I'll fix that this week.
Second is not trivial and requires some rewriting and I am not going to implement unless really needed.

**Comment by robinandeer** [comment]
yeah if we go with linking before every start it's not necessary!

**Comment by ingkebil** [comment]
Yes, but that one doesn't give you a notification on fail :) The command only logs an error on missing fastq files.
