### ISSUE TITLE
Migrate StrEnum class from cgmodels to cg

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2000]
## Description

Taking a step towards deprecating cgmodels, the class `StrEnum` currently implemented in [cgmodels](https://github.com/Clinical-Genomics/cgmodels/blob/main/cgmodels/cg/constants.py) can be implemented inside cg. 

## Suggested solution
SD: Copy the code from the class and paste it into `cg/constants/constants.py`. Then update all the usages.

## This can be closed when

Cg calls the class `StrEnum` internally and not from cgmodels.

## Blocked by

Nothing

**Note:** The class should not be deleted from cgmodels yet, unless we are extremely sure that other repositories don't use it.

**Comment by KaitoMizukami** [comment]
I would like to do this task, can you please assign this task to me ?

**Comment by islean** [comment]
Class was already present in cg.utils.enums but usage did not seem to have been rerouted to it. Also refactored an enum from cg.constants.constants to cg.constants.sequencing to get rid of a dependency cg.constants.constants -> cg.constants.sequencing.

**Comment by diitaz93** [comment]
> Class was already present in cg.utils.enums but usage did not seem to have been rerouted to it. Also refactored an enum from cg.constants.constants to cg.constants.sequencing to get rid of a dependency cg.constants.constants -> cg.constants.sequencing.

Nice! Can you link the PR where you did this?

**Comment by islean** [comment]
The PR is linked now!
