### ISSUE TITLE
Add sequenced data type per customer to StatusDB

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#2010]
## Description

We need to distinguish between: `clinical` and `research`  data because:

- We need to know what kind of data we are handling
- How long we should store the "raw" data differs: 10 vs 2 years.
- Where we can send the data for archiving differs.
- To whom we can share the data differs.

## Suggested solution

- Add a new field in the `customers` table in StatusDB with to allowed entries: `clinical` and `research`

## This can be closed when

- When we can distinguish between clinical and research data

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
Decision:
- Add to customer table
- Field is a string
- Allowed entries: `clinical`, `research`
- Field name needs to be decided. Here are some suggestions:
  - `data_management_level`
  - `data_management_type`

**Comment by Vince-janv** [comment]
### Suggestion:
Add a boolean column called `is_clinical_customer` to avoid clunky column name
@Clinical-Genomics/infrastructure any objections?

**Comment by islean** [comment]
Sounds good to me!

**Comment by henrikstranneheim** [comment]
Will that be instead of "data_handling_protocol"?

**Comment by Vince-janv** [comment]
> Will that be instead of "data_handling_protocol"?

Me and @islean felt that `data_handling_protocol` was a bit hard to understand

**Comment by henrikstranneheim** [comment]
Only thing with "is_clinical_customer" is that it doesn't convey any meaning about what being clinical means cmp to data_handling_protocol. But I think both are ok.

**Comment by islean** [comment]
Closing this since we both have the column `is_clinical` and also `data_archive_location` at this point.
