### ISSUE TITLE
Add where to archive data in StatusDB

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#2011]
## Description

We need to deliver and archive data for different customers at different locations.

For instance K customers should get data to Ks' Ceph storage while KI customers should use PDC.

## Suggested solution

- Add a new field `archive_at` to the `customer` table in StatusDB for where to archive data. 

## This can be closed when

When it is explicit where to archive data for each customer

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
`raw_data_archive_location`

**Comment by Vince-janv** [comment]
`data_archive_location`

**Comment by seallard** [comment]
`offsite_archive_location`

**Comment by diitaz93** [comment]
> `raw_data_archive_location` Not sure what it will point to, is it an url, directory path or just a name? Maybe we can clarify "location" accordingly

I understand it will be a string with a name, like "karolinska_server", something like that

**Comment by diitaz93** [comment]
`external_storage_location`

**Comment by henrikstranneheim** [comment]
Decision:
- Add to customer table
- Field will be a string
- Allowed entries TBD
- We will arrange a vote to determine the field name, based on suggestions in this issue

**Comment by Vince-janv** [comment]
Vote in Trocadero slack channel landed on `data_archive_location`

**Comment by henrikstranneheim** [comment]
Done
