### ISSUE TITLE
MIP-RNA: delivery report

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#2029]
## Description

We have gotten a request by a customer to add a delivery report for mip-rna.

## Suggested solution

Come to the conclusion about the format of the delivery report - including cases to which the rna report has been uploaded to.

## This can be closed when

A delivery report can be generated and uploaded to Scout.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by karlnyr** [comment]
Customer request done in #633285

**Comment by karlnyr** [comment]
I believe this would need the ability to upload multiple delivery reports to scout - at least an rna-delivery-report - right @dnil @northwestwitch ?

We could perhaps use the same kind of information about the sample that is going to be used for the rnafusion one defined in:
https://github.com/Clinical-Genomics/cg/issues/1720

**Comment by dnil** [comment]
In principle you can already load multiple delivery reports, but I guess it will 1) look just like reruns and 2) the user will have to open them to figure which is RNA. A new report type is not hard to add. Standard is an html report, that can be rendered to pdf within Scout on user request, but can be native pdf or yaml/txt as well. We'd need a name that can be used when loading from case config file and from command line, along the lines of 
```
 scout load report --help
2023-05-11 16:02:48 macbook-pro-3.gaia.sll.se scout.commands.base[92762] INFO Running scout version 4.67
2023-05-11 16:02:48 macbook-pro-3.gaia.sll.se scout.commands.base[92762] DEBUG Debug logging enabled.
2023-05-11 16:02:48 macbook-pro-3.gaia.sll.se scout.adapter.client[92762] INFO Connected to MongoDB 6.0.1
2023-05-11 16:02:48 macbook-pro-3.gaia.sll.se scout.adapter.mongo.base[92762] DEBUG Database name: scout
2023-05-11 16:02:48 macbook-pro-3.gaia.sll.se scout.server.app[92762] INFO Enable Phenopacket API
Usage: scout load report [OPTIONS] CASE_ID REPORT_PATH

  Load a report document for a case.

Options:
  -t, --report-type [delivery|cnv|cov_qc|exe_ver|multiqc|multiqc_rna|gene_fusion|gene_fusion_research|reference_info|RNAfusion_inspector|RNAfusion_inspector_research|RNAfusion_report|RNAfusion_report_research]
                                  Type of report  [required]
  --help                          Show this message and exit.
```
so `rna_delivery` perhaps?

**Comment by ivadym** [comment]
I would say that generating the delivery report is relatively straightforward since we already have most of the necessary features in place to extract the required data.

However, to proceed with this, we'll need:
- A deliverables file that contains the metrics to be included in the report.
- A template specifying the fields and their respective data sources. We can refer to the approach we used for RNAfusion [here](https://docs.google.com/spreadsheets/d/1A1O2Y0dWOlj3x4hVvgoK2XU96Xf4COUV5mgsFN7sfRM/edit#gid=1963444008) as a reference.
- `rna_delivery` option in Scout.

Once we have this in place, I'm more than willing to take over the report generation 👍

**Comment by karlnyr** [comment]
This is being requested again by customers, any chance that we can push the generation of this report? @ivadym

**Comment by ivadym** [comment]
Could you or someone please go through the template, fill in the missing fields, and review it? We need to identify what should be included in it:
https://docs.google.com/spreadsheets/d/1Seka2Dror-UHemixCvWCSuF0-POxxYXnpJD6PadMf6g/edit#gid=0

**Comment by karlnyr** [comment]
@jemten can you add all the QC parameters that we fail mip-rna on into the. We have some in row 30, are those all of them?

**Comment by ivadym** [comment]
I've also included the RIN and input amount metrics, as they were requested by teresita: https://github.com/Clinical-Genomics/MTP-RNAFUSION/issues/40#issuecomment-1812740962

**Comment by jemten** [comment]
I've added some other metrics that mip uses to fail/flag a run. Currently those are note written to the deliverables file, but we can update that if you think that they are still useful.

**Comment by karlnyr** [comment]
I don't know if I need them in the deliverables file, but I think it is nice to include the thresholds that we use in our analysis in the delivery report as well.

**Comment by fevac** [comment]
In the case of including thresholds I would add a sentence like:
An analysis is considered to have good/passing quality when: LIST THRESHOLDS (but better said)

So then, even when we deliver analyses failing QC it will still bel "somewhat" clear that they didn't pass those thresholds

**Comment by karlnyr** [comment]
With tomte being a goal, this is closed
