### ISSUE TITLE
Remove old way of dealing with tickets in the rsync step

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2033]
### Description
In [this function](https://github.com/Clinical-Genomics/cg/blob/a4cc6e176b679e62d534dac168aab2ae114a0396/cg/meta/rsync/rsync_api.py#L104C10-L109) customer should not be fetched from the first case returned but rather be an argument in the function.

The current code caused issues when a case was changed from one customer to another but the ticket remained the same. 

Case to test on: `newhound`

**Comment by islean** [comment]
Deployed to stage and production.
