### ISSUE TITLE
Remove flow cell mode

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2038]
## Description

The term flow cell mode, referring to whether the flow cell is SP, S2, S4, or 2500 is:
1. Confusing, as it brings more complexity to the demultiplexing.
2. Outdated, as SP and 2500 correspond to old flow cells (Miseq, Nextseq) for which cg does not do demultiplexing anymore.
3. Incomplete, as there may be other types, such as S1 (and apparently many more).
4. Unnecessary, as the main information for the demultiplex can be extracted from the sequencer type (already implemented).
5. Currently unused, as the endpoint is the `SampleSheet` class that does not use this attribute for anything.

## Suggested solution
SD:
1. Remove the property `flow_cell_mode` in run parameters and its usage until the endpoint.
2. Remove constants related to this property.
3. Remove tests that involve the property.
4. Remove fixture files exclusively for testing this attribute or rename fixtures if they are used for some other tests.

## This can be closed when

There is no trace of `flow_cell_mode` in cg.

## Blocked by

Preferably wait until #2036 is merged

**Comment by diitaz93** [comment]
@karlnyr what do you think about this?

**Comment by karlnyr** [comment]
I think it is a good angle - but I guess you would have to replace all logics which makes use of `flow_cell_mode` today - can you make a suggestion here as well for that?

**Comment by diitaz93** [comment]
> I think it is a good angle - but I guess you would have to replace all logics which makes use of `flow_cell_mode` today - can you make a suggestion here as well for that?

Yes, the term is basically not used so replacing it is not hard. I will start developing this idea next week and keep you posted
