### ISSUE TITLE
Edit the tumour property when rerunning samples

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/cg#2058]
A user asked if it is possible to make the tumour property editable when adding existing samples to orders.

**Comment by henrikstranneheim** [comment]
- Allow Balsamic orders to have only `normal` samples and no tumors
- Modify Cg to check for only normal samples cases and apply `force-normal` CLI flag
- No need to sync FE and BE
- Question: @karlnyr Should we allow multiple samples or only cases with one normal?

**Comment by Vince-janv** [comment]
Issue for cg fix created here: #2186

**Comment by Vince-janv** [comment]
### Decision
- Balsamic order no longer need to include a tumor sample to be placed
- Only one normal sample per case allowed

**Comment by Vince-janv** [comment]
All actions completed
