### ISSUE TITLE
Implement Coding Standards for Consistent Code Quality and Development Practices

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2086]
### Description
Currently, our project lacks a formalized coding standard, leading to inconsistencies across our codebase. This lack of uniformity creates extra work during code reviews, induces uncertainty during development, and leads to diverse standards and design solutions within our codebases.

### Proposed Solution
A coding standard document should be created, which should be accessible and easy to update as our project evolves. This document can be stored in our internal documentation system or within each repository in a contributing.md file.

The documents/guides should address:

- Code formatting rules (e.g., type hints, named parameters)
- Documentation practices (e.g., docstring formatting and usage)
- Additionally, we should consider creating a separate document for design decisions, to keep track of design rationales and to ensure consistency in our approach to solving problems such as

    - Database access and session management guidelines
    - Database vs domain models
    - Json serialization

### Acceptance Criteria

This issue can be marked as resolved when:

- A coding standard document/template is created, and it can be updated as our standards evolve.
- A design decisions document/template is established, allowing us to record our design choices and their rationales over time.

This proposed action will make our development process more effective, reduce ambiguities during code reviews, and maintain code consistency and quality.

**Comment by ChrOertlin** [comment]
Document is created and coding guidelines are being updated. https://atlas.scilifelab.se/infrastructure/development/coding_guidelines/
