### ISSUE TITLE
`tests/conftest.py` is getting too crowded

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2095]
## Description

`tests/conftest.py` has too many fixtures that **need** to be there because they are accessed by tests in different locations. The file has some comments with hashtags that try to divide it into sections but is not getting the readability easier.

## Suggested solution

SD: Group the tests by functionality or application (e.g. demultiplex, timestamps, HK) into scripts accessible by `tests/conftest.py` in the following way:
```shell
tests/
├── conftest.py
├── fixtures/
│   ├── __init__.py
│   ├── hk.py
│   └── demultiplex.py
```

The file `tests/conftest.py` should look like this:
```python
pytest_plugins = [
    "fixtures.hk",
    "fixtures.demultiplex",
]
```

## This can be closed when

The file `tests/conftest.py` has been divided into different files in `tests/fixtures/<fixture_topic>.py`.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by islean** [comment]
I think this also addresses issue #2056 since with this structuring it is easier to put the fixtures in the lowest possible level without needing direct imports.

**Comment by seallard** [comment]
I think it would be nice to group related fixtures in separate conftest files in the root, nice initiative 👍 

Is this really how pytest-plugins is supposed to be used? It looks a bit weird. Could we not just create multiple conftest files in the root with different names like `conftest_housekeeper.py`?

**Comment by diitaz93** [comment]
> I think it would be nice to group related fixtures in separate conftest files in the root, nice initiative 👍
> 
> Is this really how pytest-plugins is supposed to be used? It looks a bit weird. Could we not just create multiple conftest files in the root with different names like `conftest_housekeeper.py`?
> 
> https://stackoverflow.com/questions/27064004/splitting-a-conftest-py-file-into-several-smaller-conftest-like-parts

It says it's deprecated in a non-top-level contest. I think I would give it a try in the near future to see if it works. But open to other suggestions too

**Comment by diitaz93** [comment]
Some progress done in #2230

**Comment by seallard** [comment]
> Some progress done in #2230

I think I'm doing the opposite of what we want according to this issue, moving more fixtures into the root one. But it might be easier to extract them to separate files later once we have removed all the direct imports

**Comment by diitaz93** [comment]
> > Some progress done in #2230
> 
> I think I'm doing the opposite of what we want according to this issue, moving more fixtures into the root one. But it might be easier to extract them to separate files later once we have removed all the direct imports

The first step is moving all the fixtures to contest 🙂
