### ISSUE TITLE
Sync cg with database structure

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2098]
## Description

When using auto generate and letting alembic sync the database with the python models in the genotype-api repo, many discrepancies were discovered, in particular with regards to indices. This proposes a potential risk to performance as the upgrade script would have dropped many indices if no manual action was taken. A smaller risk would be functionality dropping if there are larger discrepancies than just indices missing. Syncing for genotype-api was done upon discovery.

A similar syncing should be performed in cg.

## Suggested solution

Compare the Python models with the actual database structure and sync the two by deciding which version should be kept for any discrepancy found.

## This can be closed when

Python models agree with the database.

**Comment by islean** [comment]
This is the auto-generated upgrade script:

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("analysis", "family_id", existing_type=mysql.INTEGER(), nullable=True)
    op.alter_column(
        "application",
        "prep_category",
        existing_type=mysql.ENUM("cov", "mic", "rml", "tgs", "wes", "wgs", "wts"),
        nullable=False,
    )
    op.alter_column(
        "application", "min_sequencing_depth", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "family",
        "priority",
        existing_type=mysql.ENUM("research", "standard", "priority", "express", "clinical_trials"),
        nullable=False,
    )
    op.alter_column("invoice", "customer_id", existing_type=mysql.INTEGER(), nullable=False)
    op.alter_column("invoice", "comment", existing_type=mysql.TEXT(), nullable=True)
    op.drop_index("customer_invoice_pk", table_name="invoice")
    op.create_foreign_key(None, "invoice", "customer", ["customer_id"], ["id"])
    op.create_foreign_key(None, "pool", "invoice", ["invoice_id"], ["id"])
    op.alter_column(
        "sample",
        "priority",
        existing_type=mysql.ENUM("research", "standard", "priority", "express", "clinical_trials"),
        nullable=False,
    )
    op.create_foreign_key(None, "sample", "invoice", ["invoice_id"], ["id"])
    op.drop_column("sample", "beaconized_at")
    op.alter_column(
        "sample_lane_sequencing_metrics",
        "flow_cell_name",
        existing_type=mysql.VARCHAR(charset="latin1", collation="latin1_swedish_ci", length=32),
        nullable=False,
    )
    op.alter_column(
        "sample_lane_sequencing_metrics",
        "sample_internal_id",
        existing_type=mysql.VARCHAR(charset="latin1", collation="latin1_swedish_ci", length=32),
        nullable=False,
    )
    # ### end Alembic commands ###

**Comment by islean** [comment]
I am basing this comment on the following it seeming like changing a column nullable -> not nullable requires all data to be not null beforehand. With that in mind, I suggest the following:

1. We add the column "beaconized_at" to the python model for "sample", since there seems to be data kept in that column. Regardless of whether this data is actually used in cg or not, not having it could cause us to mistakenly remove it with an alembic auto-revision such as this.
2. All changes to set nullable=true should be replaced by actually adding the not nullable constraint to the python model since I would guess that there is a reason for having said constraint in the database. I.e. having an analysis tied to a family/case. This would include:
- analysis.family_id
- invoice.comment
4. We add the constraint of not nullable to the database in instances where no entries are null either way. This would include:
- application.prep_category
- family.priority
- invoice.customer_id
- sample.priority
- sample_lane_sequencing_metrics.sample_internal_id
5. We remove the not nullable contraint from the python models where the db actually have a number of entries with the value set to null. This would include:
- application.min_sequencing_depth
- sample_lane_sequencing_metrics.flow_cell_name
6. Renaming of indices are not really that important, maybe keep as they are in the database, i.e. rename the python indices to match?
7. Add the index customer_invoice_pk to the python model for "invoice".

**Comment by seallard** [comment]
I guess the marking of a field as a nullable will also require us to revisit the parts of the application using that field and ensure that it actually is handled correctly.

**Comment by islean** [comment]
Good point, I can add fixing null handling in step 5.

**Comment by islean** [comment]
@seallard @ChrOertlin 
Seems as if there are 1476 entries in sample_lane_sequencing_metrics which are not tied to any flow cell. Sebastian suggested that this would be good to look into.

**Comment by islean** [comment]
> @seallard @ChrOertlin Seems as if there are 1476 entries in sample_lane_sequencing_metrics which are not tied to any flow cell. Sebastian suggested that this would be good to look into.

Seems to be due to 31 flow cells being present in cg-stage but not cgstats-stage. You should find them with this script:

SELECT * 
FROM `cg-stage`.flowcell f 
WHERE NOT EXISTS 
(SELECT 1 FROM `cgstats-stage`.flowcell f2 WHERE f.name=f2.flowcellname);

**Comment by henrikstranneheim** [comment]
@islean beaconized_at is deprecated and should be removed from the database. The functionality has been moved to Scout

**Comment by islean** [comment]
@henrikstranneheim Oh okay! So we should drop the column and the data stored there?

**Comment by henrikstranneheim** [comment]
Yes

**Comment by seallard** [comment]
https://github.com/Clinical-Genomics/cg/issues/2154

**Comment by seallard** [comment]
Have we understod why or how the database schema got out of sync with the models yet? I would assume that it is due to manual edits of the database schema or editing the database models without creating a revision.

**Comment by ChrOertlin** [comment]
As I mentioned in the meeting, I just copied whatever from cgstats-stage to CG at some point to check if it would work and how everything would look in the table using a direct SQL command.

If that voids any assumptions that are checked using the python way, then we would have the answer. 

1. Delete entries in cg-stage SampleLaneSequencingMetrics
2. Create an alembic revision that populates cg-stage SampleLaneSequencingMetrics from CGstats
3. See if the issue persists

All this could really just due to me copying some stuff without data curation etc.

**Comment by seallard** [comment]
> As I mentioned in the meeting, I just copied whatever from cgstats-stage to CG at some point to check if it would work and how everything would look in the table using a direct SQL command.
> 
> If that voids any assumptions that are checked using the python way, then we would have the answer.
> 
> 1. Delete entries in cg-stage SampleLaneSequencingMetrics
> 2. Create an alembic revision that populates cg-stage SampleLaneSequencingMetrics from CGstats
> 3. See if the issue persists
> 
> All this could really just due to me copying some stuff without data curation etc.

Maybe for the `SampleLaneSequencingMetrics`, not sure why though. I would be really surprised if affected constraints in the other tables.

**Comment by islean** [comment]
@seallard I would guess that not all changes have been done through alembic scripts. Regarding other repos, that is quite possible. Vincent and I synced genotype not too long ago, though.

**Comment by islean** [comment]
Solved by the linked PR #2462.
