### ISSUE TITLE
Alembic revisions out of sync

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2113]
## Description
Now and then our alembic revisions get out of sync, I've only noticed it for our staging environment in cg so far.
When checking the latest applied revision with `alembic revision`, it lists the latest revision - but it does not match the entry in the `alembic_version` table in the cg-stage database.

## Suggested solution
Not sure since I have not been able to reproduce the error 😞
The temporary fix is to just manually edit the latest applied revision in the `alembic_version` table to the correct one.
Understand how the `version_num` value is set in the `alembic_version` table.

## This can be closed when
The migrations no longer get out of sync for the staging environment.

**Comment by seallard** [comment]
That sounds like a nice way to try and reproduce the issue!

**Comment by seallard** [comment]
The issue is due to the set of available revision scripts differing between the branch and what the database points to.

**Comment by Vince-janv** [comment]
### Suggested fix (pseudo code because my bash is crap):
```bash
if CURRENT_ALEMBIC_VERSION_IN_PROD not in alembic history:
    git checkout master
    git fetch
    git pull
continue with the rest of the alembic part
```

**Comment by seallard** [comment]
> 

Nice!
Maybe we could do this step no matter what and skip the logic for checking if the version is in the alembic history?

**Comment by Vince-janv** [comment]
> > 
> Nice! Maybe we could do this step no matter what and skip the logic for checking if the version is in the alembic history?

We could then end up in the situation where the stage is in the version `xxx` while the head in master (ie latest script) is `yyy` and the downgrade would then crash.

**Comment by islean** [comment]
Addressed by a change in the deployment script. Documented in https://github.com/Clinical-Genomics/servers/pull/1073.
