### ISSUE TITLE
MIP-RNA uploads cannot be re-done with --restart flags in cg upload

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#2116]
## Description

Previosuly failed uploads to scout for mip-RNA cases cannot be forced to restart with the --restart flag, it is somehow not recognised.

cg upload --restart -f safefilly
Case safefilly exists in Status DB
The analysis has been already uploaded: 2023-06-07

Context: the RNA case was done, so I tried to upload it. However, at the time the DNA case it should be uploaded to was not yet finished due to pipeline errors. So for the RNA case it seems an upload date was set, without an upload actually happening.

Is this intended @karlnyr 

## This can be closed when

Uploads can be restarted

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by islean** [comment]
Seems as if "--restart" is intended for instances where the analysis object has: 
- upload_started_at filled in (but not completed within 24 hours)
- and not uploaded_at filled in.
I interpret this as "restart" is only implemented for failed uploads. Is there an inherent risk to extending --restart to work for completed analyses also? I guess we could potentially overwrite data that is already processed by the customer?

If there is a risk with extending --restart to work for the analyses with uploaded_at filled in - should the goal be to add checks to ensure that the uploaded analyses are correctly configured?

**Comment by islean** [comment]
Consultation with @karlnyr yielded the following:

Probably for the better to allow users to force a reupload even when "uploaded_at" is filled in.
Add additional check for MIP-RNA uploads; related DNA case must have an "uploaded_at" themselves to ensure that they are present in scout as well.
