### ISSUE TITLE
cg transfer lims microbial data to status db

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#214]
Contact person: DB

As VW, I want the system to transfer dates from LIMS to status-db, so that Invoicing can performed on them

**Problem description:**
Invoicing of microbial samples should be handled the same way for microbial samples as for human samples. To be able to do that we need some information to be filled into status db in the "Microbial Sample" table. Most of this info comes from completed steps in LIMS.

Steps to reproduce:
1. Go to lims
2. Find a microbial sample that has been received earlier than today
3. Look at that sample in clinical-api

Expected outcome:
Sample has that received date

Actual outcome:
Empty received date

Suggested solution:
Implement something like the "cg transfer lims" function for microbial samples and run it as a cronjob. The data we need to fetch is:
* Received At
* Prepared At
* Sequenced At
* Delivered At

DoD:
- demo
  - Show that we have a sample in LIMS that has been delivered but not updated to statusdb
  - Run the `cg transfer microbials`
  - Show that dates have been updated.

**Comment by patrikgrenfeldt** [comment]
Vad betyder det att jag är assignad på den här user-storyn?
/Patrik

Den tis 9 okt. 2018 10:00emiliaol <notifications@github.com> skrev:

**Comment by emiliaol** [comment]
Sorry, såg inte att du hade skrivit. Bara att du tittar på den lite extra inför refinement.

**Comment by barrystokman** [comment]
Options:

```cg transfer microbials --status received```
```cg transfer microbials --status prepared```
```cg transfer microbials --status sequence-start```
```cg transfer microbials --status sequenced```
```cg transfer microbials --status delivered```
