### ISSUE TITLE
Data discrepancies between cgstats and status db

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2149]
## Description

For the CGstats-to-CG data migration we are investigating the data present in both data bases.
Currently there are discrepancies in the number of flow cells as well as samples that are present in both data bases.

To be able to migrate data we need to sync up these data bases first to fulfil foreign key constraints between data base tables.

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by islean** [comment]
Leaving one script here that I think should fetch flow cells from cg-stage which are not present in cgstats-stage. Gives 30 matches right now:

SELECT *
FROM cg-stage.flowcell f
WHERE NOT EXISTS
(SELECT 1 FROM cgstats-stage.flowcell f2 WHERE f.name=f2.flowcellname);

**Comment by ChrOertlin** [comment]
| Entity | CG | CGstats | Query|
| ------ | ------ |------| -----|
| Flow cells | 2,288 |2,627| 1 |
| Samples | 122,061 |171,812| 2 |

```
# Query 1  
# Get the number of flow cells in CG and CGstats  
SELECT  
    flow_cell_count_cg,  
    flow_cell_count_cgstats  
FROM  
    (SELECTCOUNT(DISTINCT name) AS flow_cell_count_cg  
    FROM   
cg.flowcell) AS subquery_cg,  
    (SELECT   
COUNT( DISTINCT flowcellname) AS flow_cell_count_cgstats  
    FROM   
cgstats.flowcell) AS subquery_cgstats;  
  
# Query 2  
# Get the number of samples in CG and CGstats  
SELECT  
    sample_count_cg,  
    sample_count_cgstats  
FROM  
    (SELECT        COUNT(DISTINCT id) AS sample_count_cg  
    FROM  
        cg.sample) AS subquery_cg,  
    (SELECT  
        COUNT(DISTINCT sample_id) AS sample_count_cgstats  
    FROM  
        cgstats.sample) AS subquery_cgstats;  
  ```

**Comment by seallard** [comment]
## Flow cells difference
![image](https://github.com/Clinical-Genomics/cg/assets/33596072/13416773-927f-4363-9f10-62a65d510a02)

**Comment by vwirta** [comment]
> 

I quickly searched our Google Drive, and at least some of these are really old samples from 2014.
At that time we did not have proper databases, and simply had a lot of stuff in spreadsheets on drive

For example, K37063-T-panel_index13 was in an sequencing run in Feb 2014: https://docs.google.com/spreadsheets/d/1BeS7WqvoXBeQHQgMK5cYqScFbO0f9b1_5pYsEGBINYY/edit#gid=34

**Comment by ChrOertlin** [comment]
@vwirta is there a consensus on what we want to do with those samples? Migrate them over or leave them be?

**Comment by vwirta** [comment]
> @vwirta is there a consensus on what we want to do with those samples? Migrate them over or leave them be?

I don't think we have ever discussed what to really do with those samples :)
These are probably samples for which data is on tape in our safe. 
Can we somehow see what are the most recent samples among these?

**Comment by ChrOertlin** [comment]
Numbers on samples that are Unique per quarter
Seems like most of the unqiue samples in CGstat are prior 2018. Although there are still samples added to CGstats that are not found in CG after 2018 (when statusDB got launched I guess). 

![image](https://github.com/Clinical-Genomics/cg/assets/8860786/a4624f51-de32-4042-945c-02cab8f54de5)

![image](https://github.com/Clinical-Genomics/cg/assets/8860786/d8c15fd3-3ccd-452d-8562-814dc7e1b5f7)


```
# DataQuery Plot1
# summarise data per quarter
SELECT
  CONCAT(YEAR(cgstats.sample.time), '-', QUARTER(cgstats.sample.time)) AS quarter,
  COUNT(*) AS count_per_quarter
FROM
    cgstats.sample
LEFT JOIN
    cg.sample
    ON cgstats.sample.limsid = cg.sample.internal_id
WHERE
    cg.sample.name IS NULL
GROUP BY
  quarter
ORDER BY
  quarter;

# Dataquery plot2
SELECT
  CONCAT(YEAR(cg.sample.ordered_at), '-', QUARTER(cg.sample.ordered_at)) AS quarter,
  COUNT(*) AS count_per_quarter
FROM
    cg.sample
LEFT JOIN
    cgstats.sample
    ON cgstats.sample.limsid = cg.sample.internal_id
WHERE
    cgstats.sample.limsid IS NULL
GROUP BY
  quarter
ORDER BY
  quarter;

```

**Comment by ChrOertlin** [comment]
> > @vwirta is there a consensus on what we want to do with those samples? Migrate them over or leave them be?
> 
> I don't think we have ever discussed what to really do with those samples :) These are probably samples for which data is on tape in our safe. Can we somehow see what are the most recent samples among these?

With "most recent among these" you are referring to the most recent samples in the google docs that you linked?

**Comment by henrikstranneheim** [comment]
I don't think we should spend too much time on trying to save data more than 5 years old. If needed one could in the future investigate particular samples if needed by production. We will keep a copy of cgstats db for future needs.

**Comment by ChrOertlin** [comment]
# Flow cells considering data from 2018-01-01 onward
It looks like there are only three flow cells in CG that are not in CGstats considering data from 2018 onward (sequenced_at date in CG)
![image](https://github.com/Clinical-Genomics/cg/assets/8860786/b8a1f4d4-8305-4961-915d-509fc6b9fc7d)

The flow cells are not recently sequenced - there is even a missing date
![image](https://github.com/Clinical-Genomics/cg/assets/8860786/0c6ac1fb-23f2-430c-b21a-542ba4f3c41f)

```SQL
#### Queries considering only data from 2018 or later

# Get the number of flow cells in CG and CGstats
SELECT
    subquery_cg.flow_cell_count_cg,
    subquery_cgstats.flow_cell_count_cgstats,
    combined_flowcells.total_flow_cells_both,
    subquery_cg_not_in_cgstats.flow_cell_count_cg_not_in_cgstats,
    subquery_cgstats_not_in_cg.flow_cell_count_cgstats_not_in_cg
FROM
    # Subquery all CG
    (SELECT COUNT(DISTINCT name) AS flow_cell_count_cg
    FROM
        cg.flowcell
    WHERE
        cg.flowcell.sequenced_at >= '2018-01-01') AS subquery_cg,
    # Subquery all CGstats
    (SELECT COUNT(DISTINCT flowcellname) AS flow_cell_count_cgstats
    FROM
        cgstats.flowcell
    WHERE
        cgstats.flowcell.time > '2018-01-01') AS subquery_cgstats,
    # Subquery combined
    (SELECT COUNT(*) AS total_flow_cells_both
    FROM
        (SELECT name AS flow_cell_name_cg
        FROM
            cg.flowcell
        WHERE
            cg.flowcell.sequenced_at >= '2018-01-01'
        UNION
        SELECT flowcellname AS flow_cell_name_cgstats
        FROM
            cgstats.flowcell
        WHERE
            cgstats.flowcell.time > '2018-01-01') AS combined_flowcells) AS combined_flowcells,
    # Subquery exist in CG but not CGstats
    (SELECT COUNT(*) AS flow_cell_count_cg_not_in_cgstats
    FROM
        cg.flowcell
    WHERE
        cg.flowcell.sequenced_at >= '2018-01-01'
        AND cg.flowcell.name NOT IN (SELECT flowcellname FROM cgstats.flowcell)) AS subquery_cg_not_in_cgstats,
    # Subquery exists in CGstats but not CG
    (SELECT COUNT(*) AS flow_cell_count_cgstats_not_in_cg
    FROM
        cgstats.flowcell
    WHERE
        cgstats.flowcell.time > '2018-01-01'
        AND cgstats.flowcell.flowcellname NOT IN (SELECT name FROM cg.flowcell)) AS subquery_cgstats_not_in_cg;


# Get the flow cells in CG not in CGstats
SELECT *
    FROM
        cg.flowcell
    WHERE
        cg.flowcell.sequenced_at >= '2018-01-01'
        AND cg.flowcell.name NOT IN (SELECT flowcellname FROM cgstats.flowcell);
```

**Comment by ChrOertlin** [comment]
# Sample discrepancy breakdown post 2018

Thanks to a nice insight from @Vince-janv we could identify a big chunk of the 30k samples that are in CGstats but not in CG - 6505 of those belong to sequencing pools (i.e. the project number in cgstats matches a ticket in the statusdb pool table).
Almost all project (except 7) are pools for those samples.

![image](https://github.com/Clinical-Genomics/cg/assets/8860786/f2e45d4c-44b7-4393-bc99-ab14a12060dd)

The other 7 projects are listed here:
![image](https://github.com/Clinical-Genomics/cg/assets/8860786/e9885025-5e30-4471-a3c0-10cbc9f55599)

``SQL
SELECT
    subquery_cgstats_not_in_cg_samples_count.samples_in_cgstats_not_in_cg_count,
    subquery_cgstats_not_in_cg_ticket_count.samples_in_cgstats_not_in_cg_ticket_count,
    subquery_cgstats_not_in_cg_pool_count.samples_in_cgstats_not_in_cg_count_pools_count

    # Subquery number of tickets that the samples belong to
    FROM
       (SELECT COUNT(DISTINCT(projectname)) AS samples_in_cgstats_not_in_cg_ticket_count
        FROM
            cgstats.sample
        JOIN cgstats.project on cgstats.project.project_id = cgstats.sample.project_id
        LEFT JOIN cg.pool on cgstats.project.projectname = cg.pool.ticket
        WHERE
            cgstats.sample.time >= '2018-01-01'
            AND cgstats.sample.limsid NOT IN (SELECT internal_id FROM cg.sample) AND cgstats.sample.limsid LIKE '%ACC%') AS subquery_cgstats_not_in_cg_ticket_count,
    # Subquery number of samples that are not in CG but in CGstats with ACC lims id
    (SELECT COUNT(DISTINCT(limsid)) AS samples_in_cgstats_not_in_cg_count
        FROM
            cgstats.sample
        JOIN cgstats.project on cgstats.project.project_id = cgstats.sample.project_id
        LEFT JOIN cg.pool on cgstats.project.projectname = cg.pool.ticket
        WHERE
            cgstats.sample.time >= '2018-01-01'
            AND cgstats.sample.limsid NOT IN (SELECT internal_id FROM cg.sample) AND cgstats.sample.limsid LIKE '%ACC%') AS subquery_cgstats_not_in_cg_samples_count,
    # subquery how many of those tickets belong to pools
    (SELECT COUNT(DISTINCT(ticket)) AS samples_in_cgstats_not_in_cg_count_pools_count
        FROM
            cgstats.sample
        JOIN cgstats.project on cgstats.project.project_id = cgstats.sample.project_id
        LEFT JOIN cg.pool on cgstats.project.projectname = cg.pool.ticket
        WHERE
            cgstats.sample.time >= '2018-01-01'
            AND cgstats.sample.limsid NOT IN (SELECT internal_id FROM cg.sample) AND cgstats.sample.limsid LIKE '%ACC%') AS subquery_cgstats_not_in_cg_pool_count;


# Get the projectname that are not in the cg pools ticket column
SELECT DISTINCT (projectname)
        FROM
            cgstats.sample
        JOIN cgstats.project on cgstats.project.project_id = cgstats.sample.project_id
        LEFT JOIN cg.pool on cgstats.project.projectname = cg.pool.ticket
        WHERE
            cgstats.sample.time >= '2018-01-01'
            AND cgstats.sample.limsid NOT IN (SELECT internal_id FROM cg.sample) AND cgstats.sample.limsid LIKE '%ACC%' AND cg.pool.ticket IS NULL;

```

**Comment by ChrOertlin** [comment]
# What are the other samples in CGstats that do not belong to pools in CG POST 2018?

The samples that are in CGstats but not in CG and do not belong into pools have often weird project names as well as samples that do not show up in lims. 

They also contain samples that show up in lims - seems they are related to ALASCCA (clinical trial)

![image](https://github.com/Clinical-Genomics/cg/assets/8860786/1f546547-c12a-402b-b515-56353bdd0ac9)
``SQL 
SELECT
    subquery_samples_in_cgstats_not_cg_count.samples_in_cgstats_not_in_cg,
    subquery_samples_in_pool_count.samples_in_cgstats_in_cg_pool_count,
    subquery_samples_not_in_pool_count.samples_in_cgstats_not_in_pool
FROM
    (SELECT count(DISTINCT(limsid)) AS samples_in_cgstats_in_cg_pool_count
        FROM
            cgstats.sample
        JOIN cgstats.project on cgstats.project.project_id = cgstats.sample.project_id
        LEFT JOIN cg.pool on cgstats.project.projectname = cg.pool.ticket
        WHERE
            cgstats.sample.time >= '2018-01-01'
            AND cgstats.sample.limsid NOT IN (SELECT internal_id FROM cg.sample) AND cg.pool.ticket is not NULL) AS subquery_samples_in_pool_count,
    (SELECT count(DISTINCT(limsid)) AS samples_in_cgstats_not_in_cg
        FROM
            cgstats.sample
        JOIN cgstats.project on cgstats.project.project_id = cgstats.sample.project_id
        WHERE
            cgstats.sample.time >= '2018-01-01'
            AND cgstats.sample.limsid NOT IN (SELECT internal_id FROM cg.sample)) AS subquery_samples_in_cgstats_not_cg_count,
    (
        SELECT COUNT(DISTINCT limsid) AS samples_in_cgstats_not_in_pool
        FROM cgstats.sample
        JOIN cgstats.project ON cgstats.project.project_id = cgstats.sample.project_id
        LEFT JOIN cg.pool ON cgstats.project.projectname = cg.pool.ticket
        WHERE
            cgstats.sample.time >= '2018-01-01' AND
            cgstats.sample.limsid NOT IN (SELECT internal_id FROM cg.sample)
            AND cg.pool.ticket IS NULL
    ) AS subquery_samples_not_in_pool_count;
```

![image](https://github.com/Clinical-Genomics/cg/assets/8860786/d266f3d6-b126-4ee3-9167-5e62b7fd4e97)

```SQL
SELECT *
        FROM
            cgstats.sample
        JOIN cgstats.project on cgstats.project.project_id = cgstats.sample.project_id
        LEFT JOIN cg.pool on cgstats.project.projectname = cg.pool.ticket
        WHERE
            cgstats.sample.time >= '2018-01-01'
            AND cgstats.sa
```

**Comment by vwirta** [comment]
@ChrOertlin 
regarding the second screenshot... I think these are samples that another unit called CTMR sequenced with us at some point. I found some of these samples in here: https://docs.google.com/spreadsheets/d/1YVx-YRhVDf4be1KHym--Lh5OoUO84Iew0Cmsyg5n2eI/edit#gid=623572085

We do not need to keep track of this data.

**Comment by ChrOertlin** [comment]
After the meeting it was decided to move only the data that are common between cgstats and cg dependent on lims ids (i.e. sample internal ids).
