### ISSUE TITLE
Non nullable field is null in database for SampleLaneSequencingMetris

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2154]
## Description
The `flow_cell_name` column in the `SampleLaneSequencingMetrics` table contains NULL for 1984 entries in the stage environment after we populated it with data from cgstats. This should not be possible since we have marked the field as non-nullable in the model. For some reason, the constraint is not reflected in the database schema.

```sql
SHOW FULL COLUMNS FROM `sample_lane_sequencing_metrics`;
```
Reveals that the column actually is marked as nullable in the database schema.

## Suggested solution
Not sure why the database schema is out of sync with our models.

## This can be closed when
- The non-nullable constraint for the `flow_cell_name` is reflected in the database schema

**Comment by seallard** [comment]
The same is true for the `sample_internal_id` column, but it does not contain any null values at the moment.

**Comment by islean** [comment]
The big thing to decide here is what to do with the "null entries" in this case. We can quite easily add a constraint using alembic, but the revision will fail if there are "null entries" present meaning that we either need to drop the entries or set a flow_cell before applying the revision. Any recommendation @seallard ?

**Comment by islean** [comment]
Also, is there a need to have this as a separate issue?

**Comment by ChrOertlin** [comment]
@islean  you addressed this, right?
