### ISSUE TITLE
Error when querying using cg get family -c [X] -n [Y]

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#216]
As a person, that wants to map external ids per customer to corresponding internal ids.

Problem: 
$ cg get family -c cust003 -n 81 - return errors

Steps to reproduce
  1. Log in as hiseq.clinical
  2. $ up
  3. $ cg get family -c cust003 -n 81
  4. "TypeError: families() got an unexpected keyword argument 'query'"

Expected outcome / suggested solution:
Output internal family id

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by patrikgrenfeldt** [comment]
Solved by #217
