### ISSUE TITLE
Support novaseqx in demultiplex post processing

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#2168]
## Description
The new novaseqx machines have an onboard `dragen` FPGA which runs the demultiplexing software `bclconvert`. We cannot configure the `bclconvert` software running on the FPGA, which means we cannot control the structure of the output and it will differ from the one we have configured for the off-machine `bclconvert`.

The demultiplexed flow cell directories generated by the new novaseqx machines will not be processed correctly in the `cg demultiplex finish` command since the output structure differs. The new structure is completely flat, with all output files in the root directory and each sample fastq file has the sample id in its filename.

@karlnyr made very clear that the novaseqx output is not similar to that of the current demultiplex strategies. Meaning we need to move files coming from the novaseqx dragen onboard demultiplex run into the demultiplex-runs/ folder with the appropriate formatting required for the DemuxPostProcessing.

This needs to happen before we start using the novaseqx in production

UPDATE:

the ONBOARD-dragen to hasta file transfer is done with lsync. 
There seem to be two scenarios that can happen.

1. Sequencing and finished demultiplexing files are transferred during the lsync
2. Only sequencing files are transferred during the lsync due to buggy software on the dragen.

Assuming the files from either scenarios will be lsynced to ```home/proj/production/runs```
we can start this logic in the ```cg/apps/demultiplex/``` module.

## Suggested solution

Solution for scenario 1:
Demultiplexing and sequencing files are finished, we do not need to demultiplex again. We can add a demultiplex_complete.txt. Nevertheless we will need to add logic to move the demultiplex files into the demultiplex-runs directory in a properly formatted way for the DemuxPostProcessing to work.

Solution scenario 2:
The demultiplexing has not finished - so we let the demultiplexing start from with our normal system D demultiplexing. 
@diitaz93's code would allow us to start the demultiplexing using the novaseqx samplesheets.

General solutions:
- Make the post processing independent of output structure (avoid hard coded file paths)
- Add the currently used off-machine bclconvert output formatting option to the on-machine bclconvert software

## This can be closed when
- `cg demultiplex finish` works for flow cells demultiplexed with bclconvert on the new novaseqx machines

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
BCL convert - so the parsing will have to be in that format. I will start a PR for this issue and get it going. :)

**Comment by diitaz93** [comment]
> Do we know what BCL software the new novaseqx machines are using?

@seallard 4.1.5 https://emea.support.illumina.com/downloads/bcl-convert-v4-1-5-installer.html

**Comment by seallard** [comment]
I think we should consider these possible solutions besides restructuring the output from the machines

- Make the post processing independent of output structure (avoid hard coded file paths)
- Add the currently used off-machine output formatting option to the on-machine bclconvert software

**Comment by karlnyr** [comment]
I would like us to try and skip using the option which creates the sample and project directories - the reason being that the structure from the local dragen and on-deck dragen would be similar - reducing code complexity as well as most likely creating a more sustainable code by only looking for any fastq that belongs to a sample. As said, this would have to be tested by doing a demultiplex of a NovaSeq 6000 and using the option `--bcl-sampleproject-subdirectories false`.

Then look at these structures and try to determine the most generic parser we can find. Also, I know for a fact that the on-deck dragen will create only one folder, with subfolders containing fastq and raw data. This could be fixed (pulling out the fastq data from the folder, into demultiplexed-runs) when we transfer the files from cg-nas@scilifelab.se. However, I have one major issue with that - the demultiplexing on the on-deck dragen can fail, leaving the directory we would like to move... well empty. What I would like to do instead then is that we have a demultiplexing workflow which can check if the demultiplexing was finished from the on-deck dragen, and if so the demultiplexing job can just be to move the files out from the transferred directory to demultiplexed-runs and if not we start demultiplexing with our local dragen machines.

**Comment by diitaz93** [comment]
The NovaSeqX flow cell I demultiplexed on `cg-dragen2` is
```shell
20230508_LH00188_0003_A22522YLT3 
```

**Comment by ChrOertlin** [comment]
https://github.com/Clinical-Genomics/cg/pull/2227 
should deal with that in does not matter how the bcl convert output is formatted within a given run directory

**Comment by ChrOertlin** [comment]
issues related to statusDB are fixed for the novaseqx flow cell demultiplex post processing.
They can now be read into the statusDB models:
FlowCell
SampleLaneSequencingMetrics

relevant PRs:
https://github.com/Clinical-Genomics/cg/pull/2248
https://github.com/Clinical-Genomics/cg/pull/2252
https://github.com/Clinical-Genomics/cg/pull/2239
https://github.com/Clinical-Genomics/cg/pull/2244

**Comment by ChrOertlin** [comment]
The new flow supports novaseqx flow cells with a flat structure now
