### ISSUE TITLE
parallel upload of analysis

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2171]
## Description

Currently upload of completed analyses is done one by one. It would be nice to allow parallelization (even if capped to a certain max). Uploads can take long time depending on the type of analysis. This would speed this step up.

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
Seems like this was addressed in the PR @Vince-janv  mentioned. Closing this issue here. Re-open if required.
