### ISSUE TITLE
New demultiplex finish does not account for low q30 score

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2197]
## Description
Apparently, we don't want to track fastq files which received to low of a q30 score in housekeeper and we don't want to use that data when assigning read counts for the sample in the new `cg demultiplex finish` flow.

## Suggested solution
- Check q30 score before tracking fastq file in housekeeper
- Check q30 score before using metrics to calculate sample read count

## This can be closed when
- Fastq files with too low q30 score are not tracked in housekeeper or used for calculating sample read count.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
https://github.com/Clinical-Genomics/cg/pull/2201
https://github.com/Clinical-Genomics/cg/pull/2199

Seems like this has been addressed.
