### ISSUE TITLE
Internal RNA controls not being cleaned

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2215]
## Description
Since MIP-RNA cases are not uploaded automatically some of the do not get an `uploaded_at` date set due to them being internal samples and thus not being uploaded manually. Since that is not done, no uploaded_at is set, and the case is never picked up for cleaning.

### Fix 1
- Implement automatic upload for MIP-RNA
- Make sure the upload code can handle the possible exceptions without croaking (DNA-case not complete etc.)
- Make sure all internal orders have the `data_delivery` type `No_delivery`

### Fix 2
- Introduce cleaning after store for all pipelines. (would free up ~260 TB of storage space)
- Re-write delivery-report code to adapt to this.
## This can be closed when
- [ ] All cases that are run are also cleaned, independent of analysis or delivery type.

**Comment by vwirta** [comment]
Nice catch!

**Comment by henrikstranneheim** [comment]
260 TB 🙌

**Comment by Vince-janv** [comment]
Fix 1 implemented here: https://github.com/Clinical-Genomics/cg/pull/1734
