### ISSUE TITLE
Store demux logs in housekeeper

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2217]
## Description
Should we perhaps add the demux log files for the post-demultiplexing onto the flow cell bundle to trace back what happened to the post demux in the future - Since we do remove, or at least plan on removing demultiplexing directories, they would be lost otherwise.

## Suggested solution
Store log files for demux in housekeeper

## This can be closed when
Log files are kept for each demux run

**Comment by henrikstranneheim** [comment]
Sounds great 👍
