### ISSUE TITLE
Missing limitations in RNAFUSION delivery report

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2219]
## Description

Limitations are missing in report. 

Issues:
- Not apptag specific (apptag used in several analyses)
- Where should we store this information (short and long term)

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by fevac** [comment]
Limitations:
- Add limitations of analysis
- Add information about validated apptags and include message that all other apptags should only be used for research purposes.

**Comment by fevac** [comment]
Decision:
if priority: 
- short term: constant in cg
else:
- change in the database related to bigger issue: add link here

Add limitations text to documentation  (in open documentation issue)

**Comment by fevac** [comment]
I started to draft the rnafusion limitations. Please comment using `suggestion` mode: https://docs.google.com/document/d/1exf9XswV-qG7fC2m5qOwtqJ0ZIrUsUSoEAAonLx4jYQ/edit

@rannick @ivadym @karlnyr

**Comment by ivadym** [comment]
We may need to rewrite it to comply with the new structure. We should have a common limitations field in the application, and include RNA fusion-specific information in the new table.

**Comment by ivadym** [comment]
Completed!
