### ISSUE TITLE
Inconsistent locations for sample sheets

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2223]
## Description
A demultiplexed flow cell run directory often contain several sample sheets (`SampleSheet.csv`) and in varying locations. Sometimes it is stored in the root of the flow cell directory, sometimes in the `Unaligned` folder, sometimes in the `Unaligned/Reports` folder.

## Suggested solution
- What is going on and why? Are these sample sheets the same? 

## This can be closed when
- There is a single `SampleSheet.csv` in the flow cell directory in one single location which is the same not matter what

**Comment by ChrOertlin** [comment]
The sample sheet gets copied from the flow-cell-runs/FlowcellA to the demultiplexed-runs/FlowCellA parent folder.
We should use the SampleSheet in the parent dir (i.e. demultiplexed-runs/FlowCellA).
We have a comment in the code that it might not be needed with the new workflow of the novaseqs, the copying only happens there.
See here the function that copies the SampleSheet. 
    @staticmethod
    def copy_sample_sheet(demux_results: DemuxResults) -> None:
        """Copy the sample sheet from run dir to demux dir"""
        LOG.info(
            f"Copy sample sheet {demux_results.sample_sheet_path} from flow cell to demuxed result dir {demux_results.demux_sample_sheet_path}"
        )
        shutil.copy(
            demux_results.sample_sheet_path.as_posix(),
            demux_results.demux_sample_sheet_path.as_posix(),
        )

**Comment by ChrOertlin** [comment]
duplication of topic: https://github.com/Clinical-Genomics/cg/issues/2246
