### ISSUE TITLE
Pass external sample, tissue type to scout

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#223]
Samples can be flagged as external, and given tissue designations in the order portal. Users expect to see these in scout. Both are of potential interest to analysis and quality asessment.

See scout issue [#967](https://github.com/Clinical-Genomics/scout/issues/967).

**Comment by emiliaol** [comment]
@dnil Is the tissue type displayed anywhere else but the delivery report right now?

**Comment by dnil** [comment]
Not in Scout, no. A straight-forward way would be to add a couple of tags to the load config yaml. Parsing the info out of the delivery report might work too, but currently it seems to mix the categories (e.g. "Vävnad: Data från OGT (exom)") which is not ideal.

**Comment by emiliaol** [comment]
I think the comment you are referring to there is a Sample comment, not the UDF that is used for the non-external samples. We are currently not storing tissue information for the external samples but we can add that and then it would be displayed like for the regular samples. Want any other information that you usually get from the clinical samples but missing for the external while we're at it?

**Comment by emiliaol** [comment]
@northwestwitch This is something you are working on, right?

**Comment by northwestwitch** [comment]
I've opened #523 to collect tissue type from LIMS and pass it to scout config files. Waiting for a review. I don't know about  external sample tho

**Comment by emiliaol** [comment]
Cool, then let's leave it open for the external sample.

**Comment by patrikgrenfeldt** [comment]
I grep:ed for scout_upload.yamls for "external" without getting any hits. The tissue_type seems to be there.

-> external needs to be fetched from the application of each sample and put in the scout_upload.yaml as I understand it

**Comment by Mropat** [comment]
@henrikstranneheim is this an important feature which has to be completed in current version of cg?

**Comment by ChrOertlin** [comment]
@dnil, @northwestwitch has this been resolved?

**Comment by northwestwitch** [comment]
I don't think it was ever resolved, but I don't know if it's still actual. @dnil ?

**Comment by dnil** [comment]
No, agreed, it was patched in Scout (see that referenced issue https://github.com/Clinical-Genomics/scout/issues/967), but I can't find any samples in the database with sequencing type set to "external". We have plenty of "panel" and e.g. some "wts". Also not sure about the interaction with the new order portal, but I assume it still sets application "external" for the samples?

**Comment by dnil** [comment]
I do think the tissue types are there and work as intended though. Reading through the previous discussion, I agree previous speakers that the label level isn't super. Adding a separate "external" flag rather than replacing the `analysis_type` flag would have been better. And that if we do have that info on the current delivery reports, it is perhaps not needed?

**Comment by Vince-janv** [comment]
I'm not sure how much time we should spend on making our system support external samples as theses are a minuscule part of our sample influx. I say we close this as won't fix for now. Anyone very much against?
