### ISSUE TITLE
Incorrect read counts in StatusDB when sample is top-up

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2241]
## Description

Sometimes StatusDB displays an incorrect number of reads when samples have been top-up. 
This is problematic because files will be only partially transferred: a partial deliver will succeed but files will still be missing, making it difficult to catch.

This occurred with `wholespider`. After top up, the reads displayed in statusdb were`627032062` (26%) instead of the total. 
For this case a `wholespider_partial` rsync job successfully completed but the customer realised that there were missing files.  
Note that the number of reads for this case has been now manually updated in statusdb. 

## Suggested solution

- Investigate were the bug is
- Store total number of reads (pre and post top-up)

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
https://github.com/Clinical-Genomics/cg/issues/1286 are these the same issues?

For the new sample lane sequencing metrics we implemented a way to calculate and update read counts over multiple flow cells automatically. So it can be the case that this issue will be resolved once we are done with that implementation.

**Comment by fevac** [comment]
I'm not sure if they are the same. I guess if this would happen quite often (as the other issue points to) it would have been fixed by now. But unclear. 

Please link the PR of the implementation you mention as a fixing PR. Hopefully that would solve it. Otherwise we could reopen this issue if it pops up again.

**Comment by ChrOertlin** [comment]
https://github.com/Clinical-Genomics/project-planning/issues/482
it is part of this implementation plan - the functionality exists but is not yet implemented fully since we are validating the workflow.

**Comment by ChrOertlin** [comment]
We now merged the relevant PRs, it would be good to monitor the calculated read counts column for sample when they receive top-ups

**Comment by fevac** [comment]
Closing as resolved. We will reopen if we encounter issues again.
