### ISSUE TITLE
Copy sample sheet from run directory into demux directory in new post processing flow

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2246]
## Description
We are not copying the sample sheet from the run directory to the demux directory. This has not caused any errors so far because we have only tested the command on previously demuxed flow cells which contained a sample sheet. 

The existing `cg demultiplex finish` command copies the sample sheet in the following function
```python
    @staticmethod
    def copy_sample_sheet(demux_results: DemuxResults) -> None:
        """Copy the sample sheet from run dir to demux dir"""
        LOG.info(
            f"Copy sample sheet {demux_results.sample_sheet_path} from flow cell to demuxed result dir {demux_results.demux_sample_sheet_path}"
        )
        shutil.copy(
            demux_results.sample_sheet_path.as_posix(),
            demux_results.demux_sample_sheet_path.as_posix(),
        )
```

## Suggested solution
Add a function which copies the sample sheet from the run dir to the demux dir in the new post processing flow (`finish_flow_cell_temp`).

## This can be closed when
The sample sheet is copied as expected

**Comment by ChrOertlin** [comment]
There was a discussion open regarding the sample sheets already: https://github.com/Clinical-Genomics/cg/issues/2223
Let's keep them centralised.

There is a comment in the code from a meeting where we mentioned moving the sample sheets might not be needed anymore in the new workflow. 

@karlnyr , @henrikstranneheim  We should decide on how to handle sample sheet in the new demux workflow. 

What makes them?
Where should they go?
Can we limited the sample sheet generation to 1 per flow cell?

**Comment by ChrOertlin** [comment]
Create sample sheet copy addressed in the following PR:
https://github.com/Clinical-Genomics/cg/pull/2257 

Open: Once cgstats is deprecated and we know how future demux runs will look like we can revisit this point.
