### ISSUE TITLE
Move scout API to CLI calls

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#226]
Contact person: @moonso 

As a developer, I want to be able to use scout from the CLI from within CG so that I can change the interinternals of scout so I am not breaking functionality in CG.

Problem:
Now CG import code directly from scout. and when the API changes in scout, this might break the execution of CG.

Suggested solution:
Rewrite CG so that it only talks to scout through the CLI.

- go through the CG code and look for the `import scout` code references
- ... describe the code that needs to be modified (WIP)

DoD:
- when the new code is working in prod
- described how to add an app to Cg in the cg documentation (https://github.com/Clinical-Genomics/cg/tree/master/documentation)

**Comment by emiliaol** [comment]
Trying to figure out the priority of this. What type of US is this? Bugfix, improvement of exisiting code, fixing of issue for the Scout team or something else?

**Comment by ingkebil** [comment]
aha :) You're fast!

So, this is not refined enough yet. It is a suggested redesign of the CG code. There is more explanation here: https://zube.io/clinical-genomics/pbl-team-lessteamnamegreater/epics/18

Mans will now go over the CG code and list all instances where we call Scout. Once we have the list, we can expand this US with how we move the scout code out of CG and replace it with calls to the scout CLI instead.

We can get back to you at that point

**Comment by emiliaol** [comment]
Awesome, thanks!

**Comment by emiliaol** [comment]
@ingkebil Guess we won't get back to this? Think I've seen something regarding this elsewhere?

**Comment by ingkebil** [comment]
This has been done for loqusdb, not for scout as far as I know. Feel free to discuss this with MM

**Comment by emiliaol** [comment]
@moonso Should I add this to the backlog?

**Comment by moonso** [comment]
Yes that would be great

**Comment by Mropat** [comment]
This can be closed I think!
@henrikstranneheim @moonso
