### ISSUE TITLE
Move loqus API to CLI calls

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#227]
Contact person: @moonso 

As a developer, I want to be able to use loqus from the CLI from within CG so that I can change the internals of loqus so I am not breaking functionality in CG.

Problem:
Now CG import code directly from loqus. and when the API changes in loqus, this might break the execution of CG.

Suggested solution:
Rewrite CG so that it only talks to loqus through the CLI.

- [x] go through the CG code and look for the import loqus code references
- [x] ... describe the code that needs to be modified (WIP)
- Loqus
  - [x] change exit code for non standard behaviour. e.g. when we run `loqus load` and the case does exist, loqus should not exit with '0' but with '1'.
- cg
  - [ ] convert link.sample.loqusdb_id to a bool as it seems to hold the case_id
  - [x] re/move all calls that are not made in the loqusAPI
  - [x] remove get_case
  - [x] Move `load` to a subprocess call
  - [ ] Remove all checks whether or not a case is in loqusdb

DoD:
- when there are no longer any imports of loqusdb in CG
- don't forget the tests!

**Comment by ingkebil** [comment]
@emiliaol we need this for the loqusdb deviation

**Comment by ingkebil** [comment]
Has been implemented here #239 and is missing test on stage.

**Comment by patrikgrenfeldt** [comment]
@ingkebil I think this is done since it has been implemented in #239 and merged with master?
