### ISSUE TITLE
Ignore missing files for panel cases when storing analysis in housekeeper

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#228]
As a member of TA, I want to be able to skip adding files to a HK results bundle so that I don't have fake them. Missing files now result in the failure to create such bundle.

Problem: 
See bioitdev#199: During analysis of quickfowl the selected SV vcf was not created as there were not variants located within the genes in the gene panels. When cg tried to store the analysis files in HK an error occured due to the file missing in the analysis folder.

Suggested solution:
- Must have: `cg store analysis` on PA* samples does not fail on missing keys/files in the case_config.yaml.
- Should have :Add a flag `--ignore-missing-files` to `cg store analysis` that would list but ignore when an expected file is not found.

Questions: 

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by emiliaol** [comment]
One problem related to this now is the storing of PAN samples analysed in MIP. We always miss SV files and cg always expect those files to be present in the qc_sample_info.yaml but now they won't be. So cg needs to be flexible in what it expects to store, and only try to store things it can find in the qc_sample_info.yaml file AS WELL AS be able to ignore missing files when needed.

**Comment by barrystokman** [comment]
Rejected, will be solved by https://github.com/Clinical-Genomics/cg/issues/536
