### ISSUE TITLE
Q30 values for NIPT flow cells  not being calculated correctly

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2285]
## Description

Q30 values for NIPT flow cells are not being normalised correctly here cg.apps.cgstats.stats.StatsAPI.flow_cell_reads_and_q30_summary (according to me).  @ChrOertlin and I agreed to keep the old logic in [his PR](https://github.com/Clinical-Genomics/cg/pull/2218) pending refinement with others.

It is now the sum of Q30 per sample divided by the number of samples. If one sample has twice as many reads as an other it's Q30 will still be weighted the same.

## Suggested solution

Normalise Q30 by reads so that a Q30 value is always multiplied by the number of reads it concerns and then divide by the total number of reads on all samples

## This can be closed when

Either my suggestion is merged or someone convinces me that the current way is correct.

**Comment by seallard** [comment]
Can this be closed then? @ChrOertlin @Vince-janv

**Comment by Vince-janv** [comment]
> Can this be closed then? @ChrOertlin @Vince-janv

No, we agreed to keep the old flow when cgstats was removed to not change two things at once, but I still feel like this should be done differently. It is not very prioritised though

**Comment by ChrOertlin** [comment]
Added to refinement 19-06-2024

**Comment by Vince-janv** [comment]
Solved by https://github.com/Clinical-Genomics/cg/pull/3348
