### ISSUE TITLE
Flowcell - Sample connection was not created when the sample recieved 0 reads

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg#2292]
## Description

It seems like the flowcell - sample association in cg wasn't created between `HGN7YDSX7` and `ACC12418A13`. I assume this might be because it had 0 reads across all lanes as a result of an incorrect index pair being registered in LIMS (see deviation https://github.com/Clinical-Genomics/Deviations/issues/548). 

I ran the re-demux outside the normal demultiplexing folder to avoid it being picked up by the automation as we still don't want to delete data from cgstats. After this I linked the fastq manually to housekeeper but the analysis still could not be started as it didn't find any connected flow cells:
```
[hiseq.clinical@hasta:/home/proj/production/rare-disease/cases] [P_base] 2 $ cg workflow mip-dna start poeticpuma
Case poeticpuma exists in Status DB
Starting full MIP analysis workflow for case poeticpuma
Case poeticpuma exists in Status DB
No flow cells found
Analysis cannot be started: all flow cells need to be on disk to run the analysis
```

The issue was fixed by manually updating the database:
```
INSERT INTO flowcell_sample (flowcell_id, sample_id)
SELECT flowcell.id, sample.id
FROM flowcell, sample
WHERE flowcell.name IN ('HGN7YDSX7') AND sample.internal_id IN ('ACC12418A13');
```

## Suggested solution

Investigate what the cause of this could be. Haven't seen it behaving like this in the past when fixing index issues.

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
Can you describe what you mean by "re-demux outside the normal demultiplexing folder"?

**Comment by henrikstranneheim** [comment]
@ChrOertlin Done?

**Comment by ChrOertlin** [comment]
Yes, this was fixed in the attached PR, closing
