### ISSUE TITLE
Parallelize uploads of analyses

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/cg#23]
It takes very long to upload analyses (especially the observations...)

It would be nice to paralellize it which means we need to keep better track of what's uploading and not. A good start would be to add another action/status category "processing" so multiple upload processes can be started manually to begin with.

**Comment by emiliaol** [comment]
@ingkebil Still think this is needed on Hasta?

**Comment by emiliaol** [comment]
I think it is. Upload is taking forever...

**Comment by henrikstranneheim** [comment]
@emmser Is this still an issue?

**Comment by emmser** [comment]
Upload is still slow, it depends on how much time we want to remove from delivery? Now when we deliver manually it's maybe not very critical, but if delivery should be automated this can reduce time for delivery with hours.

**Comment by Mropat** [comment]
Stale issue. Will not be completed within current planning schedule
