### ISSUE TITLE
Conda channel for clinical genomics or tools run by cg

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#232]
This is not exactly an issue with cg, but I had nowhere to put it. Given that we don't discuss these often, I want to start a discussion here and get feedback. 

Problem: 
The libraries and dependencies in Conda channels are changing and updating often. Conda usually takes the most recent and compatible version of a package without actually knowing if it works or not. This might happen if one creates an environment through a yaml file without specifying every single dependencies.

Suggested solutions:
1. Install every single dependencies with versions, builds, and channels.
2. Create an Anaconda channel for packages that are tested with the said workflow.

Questions: 
Q: Does this overlap with Singularity/Docker solutions?
A: No.
Q: Does it need to be maintained?
A: Yes and this will make validation process much easier.
Q: Where can I read about creating Conda channels and uploading packages?
A: https://docs.anaconda.com/anaconda-cloud/user-guide/tasks/work-with-packages/
Q: Can I create local custom channels as well?
A: Yes. https://conda.io/docs/user-guide/tasks/create-custom-channels.html

**Comment by patrikgrenfeldt** [comment]
@hassanfa Could you elaborate on the benefits and the drawbacks of using conda compared to what we do today, using pip?

**Comment by hassanfa** [comment]
Obsolete.
