### ISSUE TITLE
Move demultiplexing of hiseqx and hiseq2500 to cg

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#2327]
## Description

Demultiplexing of hiseqx and hiseq2500 flow cells is currently done using a crontab that utilises scripts from the demultiplex repository. 

In cg there is functionality to demultiplex novaseq flow cells, which is hardcoded. By making this code dynamic we can also allow for demultiplexing of hiseq2500 and hiseqx flow cells within cg and deprecate the demultiplex repository scripts.

Part of: 
https://github.com/Clinical-Genomics/project-planning/issues/482
https://github.com/Clinical-Genomics/cg/issues/2316

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
Linked to: https://github.com/Clinical-Genomics/servers/pull/1094

**Comment by ChrOertlin** [comment]
https://github.com/Clinical-Genomics/cg/pull/2338
