### ISSUE TITLE
Document the vision on how to develop in CG (decoupling tools)

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#233]
As a developer at CG, I would like other developers to understand how to to write CG integrations as CLI calls, so that applications can be decoupled.

Suggested Solution:
Document how to develop integrations in the documentation in the CG repo

**Comment by patrikgrenfeldt** [comment]
I suggest that this could also be mentioned in or the development guide

**Comment by emiliaol** [comment]
@ingkebil Still relevant?

**Comment by ingkebil** [comment]
Yes. This is now being done but has not been documented.

**Comment by emiliaol** [comment]
Should I add it to the backlog?

**Comment by ingkebil** [comment]
Yes, it seems relevant to do that.

**Comment by moonso** [comment]
# List of tools to decouple

- [x] Chanjo
- [x] loqusdb
- [ ] trailblazer (@Mropat working on this)
- [ ] housekeeper (@Mropat and @moonso  working on this) 
- [ ] genotype
- [ ] scout-browser
- [ ] cgstats
- [ ] cgbeacon (do you have any idea how this can be decoupled @northwestwitch ?)

**Comment by northwestwitch** [comment]
For cgbeacon is very easy, we should just remove it from cg. I'll try to make a PR on the next few days. The new beacon should not be coupled with cg, so yes, easy!

**Comment by moonso** [comment]
Perfect @northwestwitch !

> I'll try to make a PR on the next few days.

That would be great

**Comment by moonso** [comment]
the idea about this one is changed so let's continue this discussion elsewhere
