### ISSUE TITLE
sql duplicate entry error in upload-auto-mip-dna.sh

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#2331]
**Describe the bug**

We have received CRON alerts for `upload-auto-mip-dna.sh` with the following error:

> sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '<CASE_ID>/2023-08-13/delivery-report.html' for key 'file.path'")
> [SQL: UPDATE file SET path=%(path)s WHERE file.id = %(file_id)s]
> [parameters: {'path': '<CASE_ID>/2023-08-13/delivery-report.html', 'file_id': 4388941}]

This seems to stop the upload of other cases as well:

> sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1062, "Duplicate entry '<CASE_ID>/2023-08-13/delivery-report.html' for key 'file.path'")
> [SQL: UPDATE file SET path=%(path)s WHERE [file.id](http://file.id/) = %(file_id)s]
> [parameters: {'path': '<CASE_ID>/2023-08-13/delivery-report.html', 'file_id': 4391889}]

The affected cases later upload without a problem.
The first error seems to have popped up on 20230703.

Spreadsheet to keep track of affected cases: https://docs.google.com/spreadsheets/d/1wdo9DX_Av6hJyZH4Bx03E6zxmhlO3kye46QZAPRE6gY/edit?usp=sharing

---

> 2023-08-14 09:40:19 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.report.report_api[194874] INFO Adding a new delivery report to housekeeper for <CASE_ID>
> 2023-08-14 09:40:19 [hasta.scilifelab.se](http://hasta.scilifelab.se/) housekeeper.store.api.handlers.read[194874] INFO Fetching tag with name: <CASE_ID>
> 2023-08-14 09:40:19 [hasta.scilifelab.se](http://hasta.scilifelab.se/) housekeeper.store.api.handlers.read[194874] INFO Fetching tag with name: delivery-report
> 2023-08-14 09:40:19 [hasta.scilifelab.se](http://hasta.scilifelab.se/) housekeeper.store.api.handlers.read[194874] INFO Fetching tag with name: <CASE_ID>
> 2023-08-14 09:40:19 [hasta.scilifelab.se](http://hasta.scilifelab.se/) housekeeper.store.api.handlers.read[194874] INFO Fetching tag with name: delivery-report
> 2023-08-14 09:40:19 [hasta.scilifelab.se](http://hasta.scilifelab.se/) [cg.apps.housekeeper.hk](http://cg.apps.housekeeper.hk/)[194874] INFO Created new bundle version dir: /home/proj/production/housekeeper-bundles/<CASE_ID>/2023-08-13
> 2023-08-14 09:40:19 [hasta.scilifelab.se](http://hasta.scilifelab.se/) [cg.apps.housekeeper.hk](http://cg.apps.housekeeper.hk/)[194874] WARNING Another file with identical included file path: /home/proj/production/housekeeper-bundles/<CASE_ID>/2023-08-13/delivery-report.html already exist. Skip linking of: /home/proj/production/rare-disease/cases/<CASE_ID>/delivery-report.html
> 2023-08-14 09:40:19 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.cli.upload.base[194874] ERROR Case <CASE_ID> upload failed

**Comment by islean** [comment]
I think I see the issue, will create a PR for it.

**Comment by islean** [comment]
https://github.com/Clinical-Genomics/cg/pull/2332

**Comment by islean** [comment]
Misremembered where the change was done in Housekeeper and it should only affect CLI commands, so I will need to keep digging a bit.

**Comment by islean** [comment]
Seems as if at least the sample case has an analysis which started its upload at 09:14, and was successfully uploaded at 09:32. My guess is that the analysis was picked up for this job somewhere in between, although I do not as of yet know why multiple instances of the upload would run in parallel.

**Comment by ivadym** [comment]
I kind of came to the same conclusion this morning. From the logs I added to the original message we can see that it checks if the delivery report exists in HK. It doesn't. Then it generates it, validates the report, and saves it in the case folder. However, when trying to link it to the HK folder,  it appears that the file is already there.

Very strange that's happening for only a small subset of cases 🤔

**Comment by islean** [comment]
@ivadym We do some weird shuffling of analyses when checking if they have been uploaded at the start of the auto command. For me it would make more sense to have analysis_obj.uploaded_at is not None. Trying to think if all the "order by" makes the switch make sense at the moment.

<img width="732" alt="image" src="https://github.com/Clinical-Genomics/cg/assets/40887124/db9d36e5-d76b-4f36-aa2f-b956d06eb235">

**Comment by islean** [comment]
@henrikstranneheim If we would receive any updates from Matt I will probably prioritize the DDN work, but otherwise I will probably sit with this.

**Comment by beatrizsavinhas** [comment]
Spreadsheet to keep track of affected cases: https://docs.google.com/spreadsheets/d/1wdo9DX_Av6hJyZH4Bx03E6zxmhlO3kye46QZAPRE6gY/edit?usp=sharing

**Comment by ChrOertlin** [comment]
@beatrizsavinhas Has this issue re-occured in the time period 21-08-2023 to now? If not I think we can close this issue.

**Comment by Vince-janv** [comment]
Closing as this seems to not happen anymore. Reopen if it does
