### ISSUE TITLE
Add command for copying demultiplexed novaseqx flow cell

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2336]
## Description
In a meeting regarding the new novaseqx machines 2023-08-15 (and subsequent refinements) it was decided that a new command copying data from the demultiplexed novaseqx flow cell from the input directory (`/home/proj/production/flowcells/`) to the demultiplexed flow cells directory (`/home/proj/production/demultiplexed-runs/`) should be implemented. This command will be run with a system d task.

The motivation is that the new novaseqx machines cannot be configured to output the demultiplexed files in the same way the old machines are.

## Suggested solution
Name of command: `cg demultiplex copy completed`

1. Check if demultiplexing is completed for the flow cell.
2. Create flow cell directory in demultiplexed runs.
3. Hard link latest novaseqx analysis directory to the flow cell in demultiplexed runs directory. 
4. Create `demuxcomplete.txt` in demultiplexed runs flow cell dir.

For the automation, update the servers repo with a system d task which runs this command.

Example flow cell: `/srv/seqdata/seqdata/20230427_LH00188_0001_B223YYCLT3/`

Demultiplexing is complete for a novaseqx flow cell if
- The latest analysis directory contains a `CopyComplete.txt` and `Secondary_Analysis_Complete.txt` in the `Data` directory.

## This can be closed when
- Demultiplexed novaseqx flow cells are automatically copied from the flow cells dir to the demultiplexed runs dir

**Comment by henrikstranneheim** [comment]
@seallard Let's use systemD instead of crontab.

**Comment by seallard** [comment]
For refinement:
- What should be copied?

**Comment by ChrOertlin** [comment]
If we have a given novaseqx analysis path:
`20230530_LH00202_0005_B2257WYLT3/Analysis/<any digit>/Data/`

I think we should copy everything in `Data` and drop `Analysis/<any digit>/`

**Comment by seallard** [comment]
> If we have a given novaseqx analysis path: `20230530_LH00202_0005_B2257WYLT3/Analysis/<any digit>/Data/`
> 
> I think we should copy everything in `Data` and drop `Analysis/<any digit>/`

Do you mean that we should copy everything in the latest analysis dir directly into the `Analysis` directory in the demultiplexed runs directory? That sounds reasonable

**Comment by ChrOertlin** [comment]
_"How do we avoid hard linking a completed novaseqx flow cell over and over? Given that this command will run regularly and the flow cell will remain in the dir after demultiplexing has completed"_

It can check whether a directory exists for the novaseqx flow cell in demultiplexed runs, if so skip it. Then we can also add a force flag if we want to force an update manually if that is needed.

**Comment by ChrOertlin** [comment]
> > If we have a given novaseqx analysis path: `20230530_LH00202_0005_B2257WYLT3/Analysis/<any digit>/Data/`
> > I think we should copy everything in `Data` and drop `Analysis/<any digit>/`
> 
> Do you mean that we should copy everything in the latest analysis dir directly into the `Analysis` directory in the demultiplexed runs directory? That sounds reasonable

Yes indeed. Not sure if we need the `Analysis` either. I think `demultiplexed-runs/20230530_LH00202_0005_B2257WYLT3/ <everything in data>` should be good enough

**Comment by seallard** [comment]
> _"How do we avoid hard linking a completed novaseqx flow cell over and over? Given that this command will run regularly and the flow cell will remain in the dir after demultiplexing has completed"_
> 
> It can check whether a directory exists for the novaseqx flow cell in demultiplexed runs, if so skip it. Then we can also add a force flag if we want to force an update manually if that is needed.

Maybe this would cause an issue if there are multiple versions of the analysis. Not sure as to why multiple versions can exist, I guess it is if the demultiplexing is re-run for the flow cell. But that might be an edge case that we want to handle with a manual force-flag. I would prefer it to be completely automated though

**Comment by ChrOertlin** [comment]
> Maybe this would cause an issue if there are multiple versions of the analysis. Not sure as to why multiple versions can exist, I guess it is if the demultiplexing is re-run for the flow cell. But that might be an edge case that we want to handle with a manual force-flag. It would be better to keep it automated though

I think the automation should pick up the latest analysis folder once. If in any case we would add an analysis version (not sure how or why) I think it would be nice to force the command to pick the latest. @karlnyr What do you think, is this a reasonable scenario?

**Comment by seallard** [comment]
If we keep the analysis version, we can check whether the most recent one has been copied already. It is also necessary to remove the delivery file to ensure we pick it up for post processing in the new flow at least

**Comment by ChrOertlin** [comment]
Actually I we demux novaseqX on the sequencer, so all we get is final. If we then demux again it would likely be with the `cg demultiplex` command and that will give an output to demultiplexed runs folder, or?

**Comment by seallard** [comment]
> Actually we demux novaseqX on the sequencer, so all we get is final. If we then demux again it would likely be with the `cg demultiplex` command and that will give an output to demultiplexed runs folder, or? Is it even possible to demux a novaseqX flow cell like this?

Hm, not sure I follow. Maybe @karlnyr knows

**Comment by ChrOertlin** [comment]
The novaseqX flow cells are demultiplexed directly on the sequencer and what we copy from there to flow cell runs is the raw data and the demultiplexed data (`Analysis`). 

Other flow cells are sequenced and then we copy the raw data to  the flow cell runs directory. Then we run the demultiplexing (`cg demultiplex`) on hasta. 

They are two different workflows. So what if we want to re-demultiplex a novaseqX flow cell? What would the output of that look like? and could we do that with the `cg demultiplex` command

**Comment by seallard** [comment]
Q: How do we handle re-demultiplexing for novaseqx in relation to this command? Is this something we need to consider now?
A: Yes, add check that the flow cell does not exist in the demultiplexed runs dir. Will be deleted manually in demultiplex. 

Q: Would we ever have multiple analysis directories in a novaseqx flow cell?
A: Yes, there is also a bug where empty analysis folders are output. These should be ignored, add check that verifies that the needed that is present
