### ISSUE TITLE
Keep flow cell data in a single directory

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2341]
## Description
Maintaining two directories for flow cell data complicates the data flow and logic for processing flow cells. There's a need to simplify this structure.

Note: the backup logic would need to be adjusted as to not backup both raw and converted data.

## Suggested solution
Merge the two directories (/home/proj/production/flowcells and /home/proj/production/demultiplexed-runs) into a single location, ensuring data consistency and simplified processing flow.

- Patch demultiplexing workflow to output data into `/home/proj/production/flowcells` only
- Patch any dependencies relying on `/home/proj/production/demultiplexed-runs` to exist
- Remove `/home/proj/production/demultiplexed-runs`

## This can be closed when
We have a single location for flow cell data

## Blocked by
Supporting the new novaseqx machines has higher prio

**Comment by seallard** [comment]
For first refinement session: do we want to do this? If so, when should we do it and how important is it?

For subsequent refinement:
- Identify dependencies and create smaller subtasks

**Comment by ChrOertlin** [comment]
servers isssue related to this: https://github.com/Clinical-Genomics/servers/issues/1086

**Comment by seallard** [comment]
No clear gain and will not be prioritized or done soon.
