### ISSUE TITLE
Use Flat flowcell runs structure

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#2342]
## Description

We are moving from a nested flow cell runs directory structure to a flat one where all flow cells will reside `/home/proj/production/flow_cells/`

Some api rely on the nested structure.

 - [x] BackupAPI https://github.com/Clinical-Genomics/cg/pull/2344
 - [x] DemuxPostProcessingAPI https://github.com/Clinical-Genomics/cg/pull/2349
 - [x] DemultiplexingAPI 
-  [x] Clean

## Suggested solution

We need to change the config paths for these modules

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
https://github.com/Clinical-Genomics/cg/pull/2340

**Comment by henrikstranneheim** [comment]
@ChrOertlin They will be in `/home/proj/production/flow_cells/`
