### ISSUE TITLE
Updates to MIP CLI v7.1: analyse rd_dna, from Order Portal to delivery

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#235]
MIPs CLI has been refactored and now has three pipelines within the same framework.

Problem: 
MIP now uses subcommands and options has been changed
```
$mip analyse rd_dna [CASE_ID] --config [MIP_RD_DNA_CONFIG] #This is the pipe that is in production now
```
See other user stories for these CLI commands:

$mip analyse rd_dna_vcf_rerun [CASE_ID] --config [MIP_RD_DNA_VCF_RERUN_CONFIG] #New pipeline for light reruns starting from bcf
$mip analyse rd_rna [CASE_ID] --config [MIP_RD_RNA_CONFIG] #New RNA pipeline

Steps to reproduce
  1. Install mip 7.1 using the master branch
  2. Run MIP for the rare disease pipeline

Expected outcome / suggested solution:
Trailblazer/CG will not be able to start MIP analyses until the CLI calls have been changed

What do we need before we can start?
~0. Create env for the three systems involved: MIP, cg, tb. Install scripts are needed for a long term stage environment.
~- Create an S_MIP7 for cg and tb and MIP7. 
~- Create a use_MIP7.sh, based on use-stage.sh
~- Create an update-MIP7.sh that will pull the **correct**  and **current** branches from tb, cg and MIP and install them.

What we need to do:
~1. Create the configs, one for each pipeline, here: dna (See MIP template dir for examples: help from HS)
~2. implement the analysis start ~~(optional: move into cg from tb)~~
 - config creation: what is the template? What doed MIP expect? Check MIP repo.
 - pedigree: what is the template? What doed MIP expect? Check MIP repo.
 - panels (rename the file aggregated_master.bed to gene_panels.bed)
 - link fastq-files (add folder wts (RNA only) as we do wgs/wes) (determined by apptag, apptag for wts not known yet)
~ - maybe also link panels, ask AJ.
~ - start analysis (based on data_analysis in status db)

Questions: 

What needs to be done on the planning meeting:
- ~~Estimate storypoints~~
- ~~**Remember to add label *PBL Teamname**~~

Q: What do we need to make this a success?
A: - Install MIP v7.1 in PROD and STAGE (action AJ)
     - config and pedigree (action AJ):located in `/home/proj/production/rare-disease/cases/justhusky`
     - reference directory (action AJ) to stage: `/home/proj/production/rare-disease/references/references_7.1`
     - validation

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

How to demo:

Order MIP as usual. The analysis is started and the results are deliverable. We can show the ordering and that the analysis has started. We can show how delivery works and looks.

DoD:

When we can make an order and that order can be delivered after analysis. DONE
**Documentation is updated.** FINAL MIP7.1 DOCUMENTATION WILL BE A SEPARATE US!
User Stories is validated according to the existing validation framework.

**Comment by emiliaol** [comment]
Check that program specific flags are still named the same way

**Comment by barrystokman** [comment]
Related to cg#236, maybe integrate that into this US instead.
