### ISSUE TITLE
Finish the RNA Order implementation

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#236]
What's left?:
- [ ] Implementation plan needs approval - @patrikgrenfeldt 
- [ ] Inform staff according to Imp Plan - @b4ckm4n 
- [ ] Inform customers according to Imp Plan - @Emilia-Ottosson-Laakso 

As a customer I want to be able to order RNA-sequencing and analysis so that I can diagnose and comfim diagnoses of patients.

Contact: @henrikstranneheim

Problem: 
Some information is missing in the current order process for RNA.

Steps to reproduce: 
1. Open the SuSy page for downloading [Orderforms](https://clinical-scilifelab.supportsystem.com/scp/kb.php?cid=11) and download  and open the Orderform for sequencing of RNA samples 
1. Enter an order into the RNA OF 
1. Specify "data_analysis"
1. Specify "is_for_sample" 
1. Specify "time_point" 
1. Go to the Orderportal and upload the OrderForm 
1. Submit the order

To do:
#orderform
update clinical OF to include the RNA information
needs to be tested
send for approval
upload to SuSy (inform customers)

#orderportal
start the timepoints at zero
hide ~~panels~~ capture kit 2019-09-17 after discussing with EOL
remove the cancer row
hide the baitset
~~hide formalin fixation~~ 2019-09-17 after discussing with EOL
rename RNA //> experimental design @Emilia-Ottosson-Laakso why is this change needed? Should we do anything in the OF? @barry @b4ckm4n @patrikgrenfeldt I have no clue what it actually mean, I think Patrik might know. I do not think anything should be renamed in the OF /EOL

#general
write a validation report, to make sure the new information is added in statusDB
run the validation
make implementation plan
implement

Q and A
1. only RNA apptags in an RNA order_
  1. no also allow all apptags available in the OF
  1. but for now only RNA

DoD:
- RNA analysis can be ordered
- Updated version of order form is implemented and published.

Expected outcome: 
1. There is an Orderform for sequencing of RNA samples. Question: Should this new information be part of an existing orderform or be a new OF?
 -  EOL - I suggest the same, because there is some information that's the same across the two analyses and in the future we want to be able to connect the RNA and DNA analysis in MIP.
1. These are the new value(s) to select ???
1. There is a column for specifying "is_from_sample":
- the name of the column is "Sampled from subject:"
- the column is placed to the right of column: Use artistic freedom
- the column is under the group with label "Required for RNA analysis"
- when is this value required: when an RNA analysis is ordered. I suggest we make a new analysis type called mip-rna that's supposed to be used when RN* apptags are used.
- the column should be exported to LIMS: EOL: No, only in status db. But is needs to be translated to our sample LIMS ID if we have one! So maybe it should be possible for the customer to select existing samples in the case they exist. And they should be available like with the DNA samples within the customer groups.
- there are also these requirements for these values when in the the Orderportal: EOL: Not sure there are any?
- An example value for this column is not very easy to give as the customers name their samples very differently
- This value need to be an existing sample in the same orderform: EOL: No - might be an existing sample in the database but I can also see that we do analysis of samples that are not in our databases.
- This value need to be an existing sample in the status-database: EOL: No. See previous answer.
4. There is a column for specifying "time_point":
- the name of the column is "Sampling time-point"
- the column is placed to the right of column: Use artistic freedom
- the column is under the group with label "Required for RNA analysis"
- when is this value required: EOL: When an RNA analysis is ordered with several RNA samples connected to the same original sample
- the column should be exported to LIMS: EOL: No
- An example value for this column is "1"
- When entering the value in excel there is this kind of help/limitations? EOL: Should be a drop down list with integers from 1 to ... 50?
- The creating the pedigree for this value it is translated to: EOL: "time_point"
- there are also these requirements for these values when in the the Orderportal?: EOL : yes
5. The Ordertype named "Sequencing + RNA analysis in MIP" in the Orderportal is selected and all the samples in the order is imported, the "is_for_sample" is imported into the Orderportal into the field 
- with the user visible name: EOL: "Sampled from sample:"
- The field is located on the row: EOL: Below existing fields, but use your artistic freedom here.
- The field is located where on that row: EOL: use artistic freedom
- this field is only visible when: EOL: Analysis type is the RNA one
- The field default contains: EOL: Nothing
- The field is of type: EOL: Not sure what you mean with this? Text, I presume? Like the sample name field.
- The restrictions on the field are: EOL: Same as for sample name
- The Orderportal validations on user entered values in the field are: EOL: Same as for sample name
, the "time_point" is imported into the Orderportal into the field 
- with the user visible name "Sampling time-point"
- The field is located on the row: EOL - same as the other RNA specific fields. But use artistic freedom here.
- The field is located where on that row: EOL: artistic freedom
- this field is only visible when: EOL: RNA analysis has been selected 
- The field default contains: EOL: Nothing
- The field is of type: EOL: integer
- The restrictions on the field are: EOL: Only integers
- The Orderportal validations on user entered values in the field are: EOL: Don't know. What do you think?
6. The rna order with the new columns "is_for_sample" and "timepoint" is accepted and saved in LIMS and Status-db.

Suggested solution:
A customer can order RNA-sequencing and subsequent MIP analysis (mip analyse rd_rna).

* is_from_sample (sample name that we need to translate to sample ID for MIP)
* time_point (integer)

~Delivery of files to caesar (later Scout).
Need to know from team MIP what should be saved in housekeeper~

Questions: 
Q1. Do we need a new data analysis value or can we use the MIP one?
A1: Up to developer.
Q2. What information does MIP need for RNA samples that MIP does not already get for the WGS/WES samples?
A2: In pedigree 
```
samples:
  - analysis_type: wts
  - is_from_sample: [sample_id] (optional)
  - time_point (optional)
```
Q3. Where does MIP want the fastq-files linked for analysis? Same as for regular analysis?
A3: Same as regular, according to PG
Q4. Is there another user story for making cg start an RNA analysis?
A4: yes, more info on the cli framework here: Clinical-Genomics/cg#235 
Q5. Where should the results be saved? In Housekeeper?
A5: Yes, in HK -> new US
Q6: How should the results be delivered?
A6: Caesar. -> new US

DoD:
- RNA analysis can be ordered
- Updated version of order form is implemented and published.
~~ Pedigree is updated with RNA-related information (ask AJ/HS if this can be added to the existing (DNA pedigree, or that a separate RNA pedigree needs to be made) ~ see start RNA analysis US ~~ 

How do we demo?:
- show mockup order

**Comment by emiliaol** [comment]
You can order RNA-sequencing now but we need to develop the back-end part a bit and possibly flesh out the ordering. So I would love to know:

1. What information do you need for RNA samples that you do not have for the WGS/WES samples today?
2. Where do you want the fastq-files linked for analysis? Same as for regular analysis?
3. Is there another user story for making cg start an RNA analysis?
4. Where do you want the results saved? Housekeeper?
5. How do you want the results delivered?

Maybe we can sit down and discuss this when your kids are feeling better?

**Comment by henrikstranneheim** [comment]
Sounds like a plan

**Comment by hassanfa** [comment]
I noticed today that some RNA samples that are marked as tumor on statusdb are also marked for balsamic.
![image](https://user-images.githubusercontent.com/1086877/61712734-4604f200-ad57-11e9-8545-56a4b5c65940.png)

While this is ok, but it is caused on errors on linking. Please see issues: #320 and #395 for more context.

**Comment by patrikgrenfeldt** [comment]
@henrikstranneheim Should the new data is_from_sample and timepoint be displayed back to the user in the ordered-sample-information page at https://clinical.scilifelab.se/samples/[sampleid]?

**Comment by henrikstranneheim** [comment]
Yes, that would be nice
