### ISSUE TITLE
Finding fastq files patterns for BCLConvert pattern without the moving of files

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#2362]
## Description

With the deprecation of the demultiplexing repo we are not moving files anymore, we need to support a new file path pattern to find fastq files.

## Suggested solution

Support the following pattern:

```Python
bcl_convert_pattern = f"Unaligned*/*/Sample_{sample_internal_id}_*{FileExtensions.FASTQ}{FileExtensions.GZIP}"
```

## This can be closed when

We can parse flow cells that has been demultiplexed with BCLConvert without any files being moved.

## Blocked by

*NA*

**Comment by karlnyr** [comment]
Directory with the structure

```Command
/home/proj/production/demultiplexed-runs/230822_A00621_0892_AHGTHYDSX7/
```

**Comment by seallard** [comment]
Refinement: 
- Should we match sample fastqs with and without the `Sample_` prefix?
- Should we match sample fastqs with and without a trailing sequence?

**Comment by henrikstranneheim** [comment]
@seallard Fixed?

**Comment by seallard** [comment]
> @seallard Fixed?

@ChrOertlin did you take over this?
