### ISSUE TITLE
The automation tries (and fails) to start a demultiplex process of NovaSeq X flow cells after copying is complete

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg#2368]
## Description
We just saw that the automation tried to start a demux of NovaSeq X flow cell 225CW7LT3. This probably because both CopyComplete.txt and SampleSheet.csv existed in the run folder `/home/proj/production/flow_cells/20230824_LH00217_0004_A225CW7LT3`

This process then failed as the sample sheet located there was the one generated by lims and then used to start the run. This one at the moment don't have sample project information added to it, which is required by the process on hasta.

Full error msg:
```
[2023-08-25T15:30:34] Running on: [cg-dragen.scilifelab.se](http://cg-dragen.scilifelab.se/)
[2023-08-25T15:30:34] dragen --bcl-conversion-only true --bcl-input-directory /home/proj/production/flow_cells/20230824_LH00217_0004_A225CW7LT3 --output-directory /home/proj/production/demultiplexed-runs/20230824_LH00217_0004_A225CW7LT3/Unaligned --bcl-sampleproject-subdirectories true --force
touch /home/proj/production/demultiplexed-runs/20230824_LH00217_0004_A225CW7LT3/demuxcomplete.txt
Sample Sheet Error: Command line indicates to create per-project subdirectories, but 'Sample_Project' is not a column in the provided sample sheet.
Assertion failed in ../src/host/dragen_api/file_io/bcl/process_bcl_directory.cpp line 720 -- version_one_samplesheet -- 
Dumping diagnostics....
DRAGEN replay file saved to /var/log/dragen/dragen_replay_1692970234648_264417.json
sh: pidof: command not found
DRAGEN registers saved to /var/log/dragen/dragen_info_1692970234648_264417.log
Hang diagnostic saved to /var/log/dragen/hang_diag_1692970234648_264417.txt
pstack saved to /var/log/dragen/pstack_1692970234887_264417.log
DRAGEN Host Software Version 07.021.645.4.0.3
[...]
``` 

There are two issues with this:
- Why was the demux started when the plan is to perform this on the machine.
- If we want to use the sample sheets generated by lims to start demuxes on hasta then they need to be updated. And probably also modified on hasta afterwards as the BCLConvert software will not always be the same on the hasta-dragen and sequencer-dragen

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
Q: If we want to use the sample sheets generated by lims to start demuxes on hasta then they need to be updated. And probably also modified on hasta afterwards as the BCLConvert software will not always be the same on the hasta-dragen and sequencer-drage
A: We do not. We want to use the one created by cg and stored in HK.

**Comment by ChrOertlin** [comment]
The issue described here should be handled in this PR: https://github.com/Clinical-Genomics/cg/pull/2426

- We now do not rely on the sample project column any longer when demultiplexing ANY flow cell with BCL Convert on hasta. We changed the demultiplexing command
- We now only generate sample sheets without the Sample_Project column in cg and store them in housekeeper

**Comment by diitaz93** [comment]
Can this be closed, or is there still something to resolve? @Karl-Svard @ChrOertlin

**Comment by Karl-Svard** [comment]
We plan to demux on hasta for now, so the first question has been answered. 

The second one should I guess be fixed by your most recent PR. But we will know for certain when the next 6000 and X flow cells are sequenced in the coming days

**Comment by Karl-Svard** [comment]
Resolved.
