### ISSUE TITLE
Add expansionhunter vcf file to housekeeper and include in Scout load

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#237]
As a clinican I want to be able to investigate short tandem repeats in Scout

Problem: 
MIP v7 performs the analysis which is recorded in a file (see https://github.com/Clinical-Genomics/MIP/issues/252). Scout has a view for this type of analysis (see https://github.com/Clinical-Genomics/scout/issues/787). However, the vcf file needs to be available to Scout and stored in housekeeper.

Expected outcome / suggested solution:
Housekeeper stores the analysis file and Scout loads it during the case load to Scout.

Questions: 
Q: 
A: 

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by emiliaol** [comment]
Same as related card. Closing this.
