### ISSUE TITLE
Set correct sequenced_at when using new finish flow cell commands

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2388]
## Description

As part of hot fix #2373 the sequenced_at date was set to the current date to allow for analyses to start. It should be set to the flow cell it was ran on's sequenced_at date.

## Suggested solution

Get the flow cell's sequenced_at value and set it for the samples at around the same time as the samples' read counts are being updated.

## This can be closed when

When the flow cell's sequenced_at date matches the samples'.

**Comment by Vince-janv** [comment]
### Decision
- Change column name `Sample.sequenced_at` to `Sample.reads_updated_at`

**Comment by diitaz93** [comment]
Can this be closed? @islean @Vince-janv

**Comment by islean** [comment]
In about 5 min when it is deployed! @diitaz93

**Comment by islean** [comment]
Solved with the deployment of #2414
