### ISSUE TITLE
Rename NextflowSample class and children

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2391]
Ok, should the class be renamed to align with the intent? `sample_sheet_entry = TaxprofilerSample` is not immediately clear to me. The class name seems very general and it is hard to understand it holds a sample sheet entry.

_Originally posted by @henrikstranneheim in https://github.com/Clinical-Genomics/cg/pull/2360#discussion_r1308912635_

**Comment by henrikstranneheim** [comment]
I think your suggestion: `TaxprofilerSampleSheetEntry` is good
