### ISSUE TITLE
fix(post processing flow -  dont add sample lane metrics if we dont have fastq files)

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#2395]
## Description

There is an edge case scenario where if we have found the data present in the samplesheet we will add any data available. This means that if we are missing something - FastQ files for instance - we will continue with adding them with the data that is available.
  
## Suggested solution

Make a data class for the samples to be added which validates that we both have the sample lane metrics for the sample as well as the associated FastQ files. 

## This can be closed when

We have the same data added to all (cg, housekeeper) services instead of having them split.

## Blocked by

*NA*

**Comment by seallard** [comment]
Also might need some clarification on what we want to happen if data is indeed missing. Should the flow terminate and not populate any data for the flow cell anywhere?

**Comment by ChrOertlin** [comment]
Yes I think in instances were single samples have failed we should continue with the ones that have all data available otherwise we might end up blocking the whole flow cell.

**Comment by diitaz93** [comment]
Where is the adding of the data done exactly? @karlnyr @seallard @ChrOertlin
