### ISSUE TITLE
Delivery working on Hasta

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#241]
As a production team member, I want the deliver bash functions to work so I can deliver files to customer INBOXes

Problem: nothing is installed. Not even the customer inboxes.

Suggested solution:
- describe how the procedure would work
  - TA logs in as hiseq.clinical to perform delivery
- open up connection to caesar
- add TA to sudo hiseq.clinical
- install `cglims` and `deliver`
  - [x] create a update-deliver-{stage,prod}.sh script
- deliver bash scripts needs to be made available:
  - [x] source the deliver functions bash script so bash functions become available -> put this in use prod and use stage, and in update prod and update stage scripts. This bash script needs to be cloned to ```/home/proj/production/bin/git/deliver```
- [x] change customer inbox: ```/home/proj/production/customers/<customer_name>/inbox```
- [x] change cg.cli.deliver -> inbox: ```@click.option('-i', '--inbox', default='/mnt/hds/proj/{customer}/INBOX/{family}/', help='customer inbox')```
- [x] change deliver package on following lines:
```
deliver/cli.py:@click.option('-s', '--sample', help='Sample name. If set, will deliver to cust/INBOX/{family}/{sample}')
deliver/cli.py:@click.option('-p', '--project', help='Project ID. If set, will deliver to cust/INBOX/{family}')
deliver/cli.py:@click.option('-c', '--case', help='case name. If set, will deliver to cust/INBOX/{family}')
deliver/cli.py:    """links files to cust/INBOX/project"""
deliver/modules/inbox.py:        'INBOX': 'INBOX',
deliver/modules/inbox.py:        outdir_template = '{outdir}/{cust}/INBOX/{group}/'
deliver/modules/inbox.py:        outdir_template = '{outdir}/{cust}/INBOX/{group}/'
deliver/modules/inbox.py:        outdir_template = '{outdir}/{cust}/INBOX/{group}/{sample}'
scripts/checkfornewdemux.bash:            # link the fastq files to cust/INBOX
scripts/deliver.functions:    # deliver files based on a case id and a housekeeper category to the cust/INBOX
scripts/deliver.functions:    # Deliver files based on a sample id and a housekeeper category to the cust/INBOX
scripts/deliver.functions:    # Based on a sample id, deliver the bam/bai:s and vcfs to the cust/INBOX
scripts/deliver.functions:    # Deliver files based on a sample id and a housekeeper category to the cust/INBOX
scripts/deliver.functions:    # based on a sample id, deliver all fastq files of a sample to the cust/INBOX
scripts/deliver.functions:    # based on a case_id, deliver all fastq files of the sample belonging to a case to the cust/INBOX
scripts/deliver.functions:    # based on a project_id, deliver all fastq files of the sample belonging of the project to the cust/INBOX
scripts/deliver.functions:    # based on a fc, deliver all fastq files of the samples on a FC to the cust/INBOX
scripts/deliver.functions:    # link to our INBOX first .. with a proper name
scripts/deliver.functions:        deliver inbox --outdir /mnt/hds/proj/INBOX/ --sample ${sample_id} ${fastq}
scripts/deliver.functions:    for inbox_fastq in /mnt/hds/proj/INBOX/${cust_id}/INBOX/*/${name}/*.fastq.gz; do
```

# Remaining tasks:
- Install `cglims` and `deliver`
- Test PRs
- Deploy
- Document in AMDoc 1060

 
How to Demo:

Login to Hasta
activate stage (```us```)
link fastq files to customer inbox: hasta: CLI-command ```deliver_fastqs_samples```
show linked (and renamed to customer_ids) samples in correct customer inbox

DoD:
- we can link files to cust INBOXes
- we can sync files to caesar
- documents are updated: 1060 in AM

**Comment by emiliaol** [comment]
I have updated 1060, please send for publishing when you feel ready!

**Comment by ingkebil** [comment]
No more remarks. Changed some words here and there (e.g. in the same section family and case was used interchangeably, moved all to family).

Sending out now.
