### ISSUE TITLE
Working MIP on Hasta

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#242]
As a member of TA, I want MIP to be installed so I can start analysing cases

problem: nothing is installed!

Suggested solution:

All commands are taken from the MIP manual on the MIP GH page.

As hiseq.clinical
- [x] set up perlbrew so that we can install perl packages in a conda-like env
- [x] clone MIP to /home/proj/bin/git/
- [x] run: `perl mip_install.pl -cdp <conda_dir_path> -env <mip.vX.Y>
- install all tools with conflicting packages
  - [x] py3
  - [x] svdb
  - [x] peddy
  - [x] freebayes
  - [x] vep
  - [x] tiddit
  - [x] CNVnator
- [x] need to add perlbrew to hasta's activate-stage.sh (see: `servers/resources/hasta.scilifelab.se/`) (commented out now)

Additional tasks:
- [x] sync fastq files for testing (one test case) to hasta. Put them in the analysis folder.
- [x] check if the references are installed with mip. Or else copy from rasta. 
- [x] add case_config and pedigree from rasta to analysis folder and Check all paths to be hasta specific.
- [ ] test mip -c analysis/config-file.yaml. 

#### Questions
1. What is conda_dir_path?
   1. The root dir where conda is installed: $CONDA_HOME
1. What is conda PATH?
   1. See 1.
1.  
   1.
2. Should we document this?
  - Let's do that when we move prod to hasta.

# Remaining tasks
- Sit with AJ
- Run a case, validation case solidmoose (end goal: analysisrunstatus module completed)

Extra documentation:
- Based on AM#1203:20
- https://github.com/Clinical-Genomics/mip
- https://github.com/Clinical-Genomics/development/blob/7ccf34366fa51bc63f94c46e349b4314b18dd343/perl/installation/installation.md

DoD:
- `mip -c analysis/config-file.yaml` works for a test case.

How to Demo:
- show the analysis folder

**Comment by ingkebil** [comment]
```
[0|0|0] [hiseq.clinical@hasta:/home/proj/bin/git/MIP] [S_MIP_20181204] master* ± mip --version

mip v6.0.18

[0|0|0] [hiseq.clinical@hasta:/home/proj/bin/git/MIP] [S_MIP_20181204] master* 3s ± which mip
/home/proj/bin/conda/envs/S_MIP_20181204/bin/mip
```

**Comment by barrystokman** [comment]
Only issue remaining (as far as we know): GATK, Anders is working on it. Then reinstall MIP: ```/servers/resources/hasta/update-mip-stage.sh```
