### ISSUE TITLE
Changing demux path for novaseq6000 flow cells requires samplesheet manipulation for previously demultiplexed flow cells

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#2430]
## Description

We introduced a modification in the demultiplexing flow (#2426) that requires an adaptation of the SampleSheets for flow cells sequenced on the NovaSeq6000. SampleSheets that do not conform the the format created with `SampleSheetCreatorBCLConvert` need to be deleted in housekeeper and re-created. If not, re-demultiplexing of old flow cells will fail in the automation process. 

## Suggested solution

We would need to check all samplesheets for novaseq6000 flow cells demultiplexed with blc convert, check their header and if it does not corresponds to the required one, delete the sample sheet from housekeeper and re-create it

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
@karlnyr can we have you input on this.

**Comment by ChrOertlin** [comment]
# Conclusion

Sample sheets will have to be fixed manually if any issues occur with the sample sheet during demultiplexing.

@Vince-janv investigates validity of ONDISK label for flow cells.

**Comment by Vince-janv** [comment]
50/50 randomly selected `ondisk` `novaseq` flow cells had SPRING and/or FASTQ files store in housekeeper. I think we can assume that `ondisk` is accurate

**Comment by henrikstranneheim** [comment]
👍
