### ISSUE TITLE
Fastq files for Analysis from X demultiplexing on Hasta

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#244]
As a TA member, I would like to have X fastq files on hasta so that I can start analyzing them

Problem: the X pipeline is now set up rasta. Maybe we can leave it on rasta until the X's are shut down. We need to transfer the fastq files to hasta instead of linking them on rasta. 

Suggested solution:
- use rsync script (will be provided by KB)
- let `checkfornewdemux` rsync files to hasta

DoD:
- show that hasta has received X fastq files

Q1: When will the X's shut down?
A1:
Q2: Does this mean we will still run production on rasta? What will happen if rasta fails outside of warranty?
A2:
Q3: Who do we need to inform so that there is no confusion? 
A3:

**Comment by barrystokman** [comment]
Prerefined 20181206

**Comment by ingkebil** [comment]
This US has one out of two purposes depending on how necessary it is that fastq files are available right away on hasta:
- if needed right away: we need this US
- if not needed right away: we can skip this US and instead do [Zube #2235](https://zube.io/clinical-genomics/pbl-team-lessteamnamegreater/c/2235) (I know it says bundles in the title)

**Comment by emiliaol** [comment]
I would like to know what the time line is for transferring MIP stage/production to Hasta (as in when it's ready to be used)? Because we need to be able to have the fastq-files on Hasta and with Hasta specific HK links available then. And that's what this US is about, I guess. So should it be planned for this sprint or next?

**Comment by barrystokman** [comment]
Solution identical to sync 2500/novaseq fastq files US, but we also need to fix symlinks

**Comment by ingkebil** [comment]
Fixed here: https://github.com/Clinical-Genomics/deliver/pull/51
