### ISSUE TITLE
Validate the stuffs!

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#245]
As a harmonious member of CG, I want to move all hasta into production so that SWEDAC and AL are not pissed off.

Problem: too late! AL is already mildly annoyed.

Suggested solution:
- revalidate MIP?
- validate delivery
- validate raw data acquisition
- document all the things.

DoD:
when we finished the implementation plan ;)
I need some sleep now.

**Comment by patrikgrenfeldt** [comment]
@ingkebil I think this is done, please reopen if you are of a different opinion
