### ISSUE TITLE
Add software and software version used for demultiplexing

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#2450]
## Description

For publications customers ask for what version of the demultiplexing software was used - We need to store this somehow. We could either store it on the `SequencingLaneMetrics` or the `Flowcell` model. Still, since we might demultiplex a flow cell again we need to be able to store somehow the version of DRAGEN that was used for a specific analysis - The more I think about it: Should demultiplexing become an analysis type? That way we could store the analysis, with the dragen version that was used, and that way be able to trace it back. The old way we tracked this was through `cgstats` and was on my command not transferred to the new structure.

## Suggested solution

- Store software and software version used on SeqLaneMatrics, Flowcell, or Analysis

## This can be closed when

We can track which software, and which version of the software was used for a demultiplexing analysis 

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
### Conclusions
- [ ] Adding the logs from demultiplexing to housekeeper is sufficient for future flow-cells.
- [ ] Somehow parse the cgstats demux version data into a more accessible format giving time periods and software version used.
- [ ] Log the information of the two preceding points in the demultiplexing in production document in atlas.

**Comment by seallard** [comment]
Can this be closed @karlnyr? We are currently storing the demultiplexing logs in housekeeper https://github.com/Clinical-Genomics/cg/pull/2258

**Comment by henrikstranneheim** [comment]
Closing. Reopen if needed.
