### ISSUE TITLE
Fix Priority parsing for RML orderform

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2452]
## Description

There are some problems with parsing the priority from excel orderforms. Currently "research" in rmlsample2 in the rml excel orderform sample is not parsed correctly.

## Suggested solution

Fix the validation of the sample sheet and ensure that it is parsed correctly.

## This can be closed when

Priority is filled in correctly for "research" in all sample orderforms.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
Reverted a commit migrating the order sample model https://github.com/Clinical-Genomics/cg/pull/2453.
When submitting the `1604.17.rml.xlsx`, it seems like the priority in rmlsample2 is parsed correctly (set to `clinical_trials`). I suggest we merge this revert and redo the migration + patch in a new branch

**Comment by Vince-janv** [comment]
Fixed by #2441
