### ISSUE TITLE
Move data_analysis from sample to family for MIP and Balsamic

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#249]
As a customer, I want to be able to have the data_analysis specified on the family level so that I include old samples (do reruns).

Problem: 
We store the data_analysis on sample level and we don't change samples when creating new families for existing samples. Cg only looks at the sample level.

Steps to reproduce
  1. Order some samples with Balsamic
  2. Create a new order for MIP with the same samples

Expected outcome / suggested solution:
MIP starts an analysis of the family and samples

Actual outcome:
MIP doesn't pick up the samples for analysis because the analysis type is still Balsamic

Suggested solution: 
Move/copy data_analysis to the newly created family:
Code needs to be changed in samples_to_analyze()
Remove hardcoded data_analysis: 'MIP' where data_analysis is missing (maybe put value on all existing samples). 
Delivery report: we should handle it on case level in stead of on sample level

Questions: 
Q1: Does the same problem occur for the reverse?
A1: Not yet since Balsamic doesn't start anything yet.
Q2: Can we put fastq on all samples?
A2: Only if it doesn't cause any problems
Q3: Can we know which samples were created with MIP? 
A3: metagenome -> fastq
fastq -> fastq
rml -> fastq
MIP -> MIP 
Q4: how to distinguish MIP samples from fastq + familiy for MAF
A4: if the customer don't have scout instance then it is a fastq
Q5: Will the world collapse if we put all as fastq?
A5: the statistics might show wrong results (if we create statistics on samples.data_analysis)
Q6: Can we have the same sample name in different cases and only get one sample in LIMS?
A6: No, only by ordering it once and then pointing the cases to an existing one

**Comment by barrystokman** [comment]
@patrikgrenfeldt  Can you analyze Q6 before next refinement?
