### ISSUE TITLE
Demultiplexing flow using bcl2fastq requires adjustments

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#2492]
## Description

In the previous demultiplexing post processing flow folders and sample fastq files were renamed when demultiplexing was done with bcl2fastq.

The new flow does not account for that files are not renamend any longer which causes the flow to fail when looking for fastq files.

The default behaviour of bcl2fast v2.20 is to write fastq files as follows:

`If the Sample_ID and Sample_Name columns are specified but do not match, the FASTQ files reside in a  subdirectory where files use the Sample_Name value.`

We do not want that the file names are stored under the `Sample_Name` attribute. Instead they should use the `Sample_ID`. So that the automation can pick these up.

The proposed change is to change the sample sheet creation to set the "Sample_Name" values in the sample sheet to "Sample_ID" values. Alternatively, remove the "Sample_Name" column in its entirety. 

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by diitaz93** [comment]
Removing the sample name would be great, better than renaming it, in my opinion

**Comment by Vince-janv** [comment]
### Decision
- [ ] Remove Sample_Name column in SampleSheet creation
- [ ] Validate that the demultiplexing output is as expected after removal, if not change post-processing.
- [ ] Add validation of sample sheet before demultiplexing starts
- [ ] Retroactively change existing sample sheets to conform to the new standard (future issue and refinement)

**Comment by Vince-janv** [comment]
### Additional decisions:
- [ ] Try removing Project column to get a flat structure
- [ ] Also consider changing BCLConvert V1 samplesheet to fit BCLConvert V2
