### ISSUE TITLE
Microsalt cases are not storing

### ISSUE THREAD

**Issue by SofiaOtero** [Clinical-Genomics/cg#2500]
## Description

Microsalt cases are stuck on "Running" in statusdb which is causing them to not store in housekeeper.

## Suggested solution

Set cases to "Empty" in statusdb when they have completed in trailblazer.

## This can be closed when

Cases are stored in housekeeper again.

## Blocked by

Nothing

**Comment by Vince-janv** [comment]
### Decision
- [ ] Temporarily disable MicroSalt QC service until we have time to fix it

**Comment by SofiaOtero** [comment]
It is not possible to store the current cases as we get an issue with the negative control samples in the cases:
```
Error storing deliverables for case <case_name> - /home/proj/production/microbial/results//<sample_id>_2023.9.20_1.9.31/<sample_id>/assembly/quast/<sample_id>_report.tsv
```
Has something changed with handling negative controls for microsalt?

**Comment by Vince-janv** [comment]
> It is not possible to store the current cases as we get an issue with the negative control samples in the cases:
> 
> ```
> Error storing deliverables for case <case_name> - /home/proj/production/microbial/results//<sample_id>_2023.9.20_1.9.31/<sample_id>/assembly/quast/<sample_id>_report.tsv
> ```
> 
> Has something changed with handling negative controls for microsalt?

Hmm, I think the actions we decided upon will not solve the root issue. Will need to look a bit deeper at this

**Comment by islean** [comment]
Command has been run and succeeded after the merging of #2522.
