### ISSUE TITLE
Add has_backup to flow cell table in StatusDB

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#2507]
## Description

To decouple cg from any external archiving site, we need to store the information if a flow cell has a backup or not in StatusDB. Where the actual backup is archived is retrieved from a customer level field. 

Part of: https://github.com/Clinical-Genomics/project-planning/issues/518

## Suggested solution

- Add `has_backuo` to the flow cell table in StatusDB. Start using the `updated_at` field in the flow cell table.
- Set all flow cells,except NovaseqX, to True for `has_backup`

## This can be closed when

- We kow from statusDB if a flow cell has a backup or not.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@Clinical-Genomics/sysdev What do you think?

@diitaz93 Could you start working on this?

**Comment by diitaz93** [comment]
1. I am assuming that the field would be `nullable=False`. Should I set it as `False` by default? @henrikstranneheim 
2. I see that the file `updated_at` is empty in StatusDB but it is defined as `onupdate=dt.datetime.now`. What is it meant by updated_at and when should it be updated?

**Comment by henrikstranneheim** [comment]
> 1. I am assuming that the field `has_backup`would be `nullable=False`. Should I set it as `False` by default? @henrikstranneheim

Yes

> 
>     2. What do you mean exactly by "Start using the updated_at field"?

I think it makes sense to always update that field whenever we change a row in the table. Either that or we drop it.

**Comment by diitaz93** [comment]
> I think it makes sense to always update that field whenever we change a row in the table. Either that or we drop it.
The field is supposed to do that already, as it is defined as `updated_at = Column(types.DateTime, onupdate=dt.datetime.now)`. I see several flow cells in statusdb with that field having an `updated_at` much more recent than `sequenced_at`
