### ISSUE TITLE
Deprecate `archived_sample_sheet`

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2514]
## Description

Some sample sheets are tagged with `archived_sample_sheet`. We want to remove this tag and use only `sample_sheet` tag.

## Suggested solution

SD vague solution: Replace all usages of `arcived_smaple_sheet` with `sample_sheet` and remove the duplicated logic (checking for either of the two tags when fetching sample sheets from Housekeeper)

## This can be closed when

There are no references to `archived_sample_sheet`

## Blocked by

*N/A*

**Comment by ChrOertlin** [comment]
The logic that generates the archived sample sheets has been removed here: https://github.com/Clinical-Genomics/cg/pull/2516 

I guess we can remove the tag from the HK database replace existing `archived-sample-sheet` tags with `samplesheet`

**Comment by henrikstranneheim** [comment]
@diitaz93 Done?

**Comment by diitaz93** [comment]
> @diitaz93 Done?

yes, closing
