### ISSUE TITLE
Delivery report missing Sekvenserad field

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#2520]
## Description

`sample.sequenced_at` has been changed to  `reads_updated_at` (https://github.com/Clinical-Genomics/cg/pull/2414). However this change hasn't been reflected in the delivery report templates (`mip`, `balsamic` and `rnafusion`)

https://github.com/Clinical-Genomics/cg/blob/410882ed3f75eb5df93c705a23c4bdc0c3fd2312/cg/meta/report/templates/balsamic_report.html#L128

## Suggested solution

Update it to `reads_updated_at`

## This can be closed when

- [ ] The delivery reports are fixed
- [ ] Open deviation to track and fix the affected cases

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@islean Could you fix this?

**Comment by islean** [comment]
> @islean Could you fix this?

Creating a PR!

**Comment by henrikstranneheim** [comment]
Resolved
