### ISSUE TITLE
Decompress spring files to know their flow cell

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2530]
## Description

In adding the flow cell id as a tag to spring/fastq files, we encountered some spring files with either a flow cell id in their file path that does not correspond to the one in statusDB or with no flow cell id at all. To verify the flow cell id of these spring files, we decided to decompress the first lines and take it from the fastq file header, as discussed in #2131. @islean detected a total of 555 spring files that need decompression and created a file with their paths. To decompress them, we need a slurm job for each file.

## Suggested solution

I created the folder in hasta `/home/hiseq.clinical/decompress_spring_sebastian` with the following structure:
```shell
[hiseq.clinical@hasta:~/decompress_spring_sebastian] [base] $ ll
total 256
drwxrwx--- 2 hiseq.clinical users  4096 Sep 26 15:40 fastq_files
-rw-r----- 1 hiseq.clinical users  1058 Sep 26 16:01 sbatch_script_generator.sh
drwxrwx--- 2 hiseq.clinical users  4096 Sep 26 15:52 sbatch_scripts
-rw-r----- 1 hiseq.clinical users 32911 Sep 26 15:40 spring_files_to_decompress.txt
```
`spring_files_to_decompress.txt` is the list of files to be decompressed generated by @islean, `sbatch_script_generator.sh` is a script that generates and submit slurm job scripts, and `fastq_files` and `sbatch_scripts` are empty folders where the decompressed fatsq files and the scripts will be saved, respectively.

The file `sbatch_script_generator.sh` looks like this:
UPDATED:
```bash
#!/bin/bash

# Read the list of files from spring_files_to_decompress.txt
while IFS= read -r spring_file_path; do
    # Extract the sample_id from the file path
    sample_id=$(echo "$spring_file_path" | awk -F'/' '{print $1}')
    echo "${sample_id}"

    # Define the job name using the extracted sample_id
    jobname="spring_job_${sample_id}"

    # Define the output filename with the .fastq extension
    out_file_path="fastq_files/${sample_id}.fastq"

    # Prepend the prefix to the spring_file_path
    in_file_path="/home/proj/production/housekeeper-bundles/$spring_file_path"

    # Create an Slurm submission script for each file
    cat > "generated_scripts/submit_${sample_id}.sh" <<EOF
#!/bin/bash -l
#SBATCH --ntasks=8
#SBATCH -t 00:15:00
#SBATCH -J $jobname
#SBATCH --mem=10GB
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=juan.sebastian.diaz.boada@scilifelab.se
#SBATCH --qos=low
#SBATCH --output=slurm_output/%j.out

/home/proj/production/bin/miniconda3/envs/P_crunchy/bin/spring -d --decompress-range 1 1 -r -i "$in_file_path" -o "$out_file_path" -t 8
EOF

    # Submit the Slurm job
    sbatch "generated_scripts/submit_${sample_id}.sh"

done < spring_files_to_decompress.txt
```
and the entries of `spring_files_to_decompress.txt` have the form `<sample_id>/YYY-MM-DD/<file_name>_L00?.spring`

## This can be closed when

All the spring files in `spring_files_to_decompress.txt` have been decompressed and we have identified their flow cells.

## Blocked by

*N/A*

**Comment by Vince-janv** [comment]
I'm not a BASH specialist but I think this looks great! I think you might want to change --mail-type to `FAIL` if you want to avoid 555 mails 😅 . Also what does the last line do?

**Comment by diitaz93** [comment]
> I'm not a BASH specialist but I think this looks great! I think you might want to change --mail-type to `FAIL` if you want to avoid 555 mails 😅 . Also what does the last line do?

The last line is the input to the while, the file in which is going to iterate

**Comment by Vince-janv** [comment]
> The last line is the input to the while, the file in which is going to iterate

Ah, I see 👍

**Comment by diitaz93** [comment]
Ran script for 3610 spring files

**Comment by diitaz93** [comment]
Some runs finish with this error:
```shell
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot create temporary directory.
```

**Comment by diitaz93** [comment]
## Results
All spring files decompressed

**Comment by henrikstranneheim** [comment]
@diitaz93 Well done
