### ISSUE TITLE
Add flow cell id as a tag of decompressed spring files and their metadata

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2535]
## Description

After the decompression of spring files with unknown flow cell id discussed in #2131, I have generated a CVS file of the form:
```shell
#spring2FCID.csv
<file_path>,<flow_cell_id>
...
```
Where `file_path` is the path of the spring file according to Housekeeper but **without the `.spring` extension**.
The task now is to add the flow cell id as a tag for the `.spring` and `.json` files matching with the file path.
## Suggested solution (UPDATED WITH COMMENTS)
```python
import csv
from cg.apps.housekeeper.hk import HousekeeperAPI
from housekeeper.store.models import File, Tag

# Define the input and output file names
input_file = 'spring2FCID.csv'


# Define Housekeeper API
def get_hk_api():
    return HousekeeperAPI(...)


hk_api = get_hk_api()

# Read the input file and add tags
with open(input_file, 'r') as csvfile:
    for line in csv.reader(csvfile):
        spring_root, flow_cell_id = line
        flow_cell_tag: Tag = hk_api.get_tag(name=flow_cell_id)
        if not flow_cell_tag:
            flow_cell_tag: Tag = hk_api.new_tag(name=flow_cell_id)

        spring_path: str = f"{spring_root}.spring"
        spring_file: File = hk_api.files(path=spring_path).first()
        if spring_file:
            if flow_cell_tag not in spring_file.tags:
                spring_file.tags.append(flow_cell_tag)
        else:
            print(f"File {spring_path} not found")

        metadata_path: str = f"{spring_root}.json"
        metadata_file: File = hk_api.files(path=metadata_path).first()
        if metadata_file:
            if flow_cell_tag not in metadata_file.tags:
                metadata_file.tags.append(flow_cell_tag)
        else:
            print(f"File {metadata_path} not found")

hk_api.commit()
```

## This can be closed when

The script has been run and all the spring and metadata files have their corresponding flow cell id as a tag.

## Blocked by

*N/A*

**Comment by diitaz93** [comment]
## Test on stage
Works successfully in a subset in stage

**Comment by islean** [comment]
Looks good @diitaz93! Would we want to add some error handling for cases where either the spring file or spring metadata file isn't found?

Given that we started out with spring files and then decompressed fastq files, that might not be necessary. But on the other hand, it wouldn't hurt.

**Comment by diitaz93** [comment]
> Looks good @diitaz93! Would we want to add some error handling for cases where either the spring file or spring metadata file isn't found?
> 
> Given that we started out with spring files and then decompressed fastq files, that might not be necessary. But on the other hand, it wouldn't hurt.

done!

**Comment by diitaz93** [comment]
## Ran subset of 10 files on production, worked as expected
