### ISSUE TITLE
Removal of mismatched spring metadata files

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2547]
## Description

Part of #2131 and #2541. This issue handles removal of spring metadata files for which there is no corresponding spring file. In such instances, the metadata files and their corresponding entries in Housekeeper should be deleted. Similarly, any spring file entries in the Housekeeper database which do not exist on Hasta should be removed.

## Suggested solution

The following script is intended to compile three lists of file paths, split into three files; 

- `metadata_files_no_spring.txt` containing paths from the database entries of all files tagged with spring_metadata, and whose corresponding spring file does not exist on Hasta.
- `metadata_files_non_metadata.txt` containing paths from the database entries all files tagged with spring_metadata, but where the path does not exist on Hasta.
- `metadata_files_both_missing.txt` containing the intersection of the two former files.

```Python
# INITIALIZE DATABASE CONNECTIONS

spring_metadata_files: [File] = housekeeper_api.get_files(tag_names=[SequencingFileTag.SPRING_METADATA]).all()

def get_spring_path_from_metadata_path(metadata_path: Path):
    return str(metadata_path).replace(str(metadata_path.suffix), ".spring")

metadata_files_nonexistent_spring: List[File] = []
metadata_files_nonexistent_metadata: List[File] = []
metadata_files_both_missing: List[File] = []

counter = 0
for metadata_file in spring_metadata_files:
    if counter % 1000 == 0:
        # For tracking purposes
        print(counter)
        print(len(metadata_files_nonexistent_spring))
        print(len(metadata_files_nonexistent_metadata))
        print(len(metadata_files_both_missing))
    spring_path = get_spring_path_from_metadata_path(Path(metadata_file.full_path))
    if not Path(spring_path).exists():
        metadata_files_nonexistent_spring.append(metadata_file)
        if not Path(metadata_file.full_path).exists():
            metadata_files_both_missing.append(metadata_file)
    if not Path(metadata_file.full_path).exists():
        metadata_files_nonexistent_metadata.append(metadata_file)
    counter += 1

file =  open('metadata_files_no_spring.txt', 'w')
for file_name in [file.path for file in metadata_files_nonexistent_spring]:
    file.write(file_name+"\n")
file.close()

file = open('metadata_files_non_metadata.txt', 'w')
for file_name in [file.path for file in metadata_files_nonexistent_metadata]:
    file.write(file_name+"\n")
file.close()

file = open('metadata_files_both_missing.txt', 'w')
for file_name in [file.path for file in metadata_files_both_missing]:
    file.write(file_name+"\n")
file.close()
```

Below follows a suggested script aiming to delete all metadata files found in the previous script which had no corresponding spring file on Hasta.

```Python
# INITIALIZE DATABASE CONNECTIONS

spring_files_to_delete: List[File] = []

file = open('metadata_files_no_spring.txt', 'r')
for line in file:
    spring_file: File = housekeeper_api.get_files(file_path=line[:-1])
    if spring_file:
        spring_files_to_delete.append(spring_file)
        
for spring_file in spring_files_to_delete:
    housekeeper_api.session.delete(spring_file)

housekeeper_api.session.commit()
```

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by islean** [comment]
I guess we would also want to loop through all entries in the HK DB tagged with 'spring' and remove entries where the spring file does not exist?

**Comment by islean** [comment]
Also - do we need any additional checks for human errors, where someone might have renamed the spring file?

**Comment by diitaz93** [comment]
The first script looks good 👍 
I have some suggestions for the second one:
```python
# INITIALIZE DATABASE CONNECTIONS

spring_files_to_delete: List[File] = []

file = open('metadata_files_no_spring.txt', 'r')
for line in file:
    spring_file: File = housekeeper_api.get_files(file_path=line.strip()) # strip.() instead of [:-1]
    if spring_file:
        housekeeper_api.session.delete(spring_file)
housekeeper_api.session.commit()
```

**Comment by diitaz93** [comment]
> I guess we would also want to loop through all entries in the HK DB tagged with 'spring' and remove entries where the spring file does not exist?

Yes I would say so

**Comment by diitaz93** [comment]
> Also - do we need any additional checks for human errors, where someone might have renamed the spring file?

Not sure how we would do this though 🤔

**Comment by islean** [comment]
New second script addressing comments by @diitaz93:

```Python

```Python
# INITIALIZE DATABASE CONNECTIONS

spring_files_to_delete: List[File] = []

file = open('metadata_files_no_spring.txt', 'r')
for line in file:
    spring_file: File = housekeeper_api.get_files(file_path=line.strip()).first()
    if spring_file:
        housekeeper_api.session.delete(spring_file)
    
housekeeper_api.session.commit()
```
```

**Comment by islean** [comment]
Updated with @henrikstranneheim's suggestion to check if compression is ongoing:

```Python
file = open('metadata_files_no_spring.txt', 'r')
for line in file:
    spring_metadata_file: File = housekeeper_api.get_files(file_path=line.strip())
    if spring_metadata_file:
        compression_data: CompressionData = files.get_compression_data([spring_metadata_file])[0]
        if not compression_data.spring_exists():
            if not compression_data.pending_exists():
                housekeeper_api.session.delete(spring_metadata_file)

housekeeper_api.session.commit()
```

**Comment by islean** [comment]
The spring metadata files have now been removed from stage and production!
