### ISSUE TITLE
Update flow cells in statusDB for samples with unknown flow cell

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2548]
## Description

Part of #2131. 
In #2535, the flow cell id was added as a tag to some spring files by decompressing them and extracting the flow cell id from the fastq file. This had to be done because those samples' flow cells in statusDB were incorrect (did not coincide with the flow cell id in the file path) or missing. Now, statusDB needs to be updated with those flow cell ids extracted from the fastq files.

## Suggested solution

As we have the spring files that were decompressed in the file `spring2FCID.csv`, we can loop over them, fetch their corresponding samples from statusDB and update them with the flow cell id added as a tag to the spring files in Housekeeper.

For the spring file having a flow cell id tag which does not match any flow cell in statusdb, the update is excluded as they are most likely external samples.

NOTE: Modifying the `Sample` attribute `.flowcells` was attempted, but it failed as not all samples have that attribute (it is not even defined as an attribute in the model but as a backref link). Therefore, modifying the `samples` attribute in `Flowcell` is used instead.

```python
input_file = 'spring2FCID.csv'
hk_api: HousekeeperAPI = get_hk_api()
status_db: Store = get_status_db()

with open(input_file, 'r') as file:
    for line in csv.reader(file):
        spring_root = line[0].strip()
        spring_file: File = hk_api.files(path=f"{spring_root}.spring").first()
        sample_id = spring_root.split("/")[0]
        flow_cell_id_tag: str = [tag.name for tag in spring_file.tags if tag.name not in [sample_id, "spring"]][0]
        sample: Sample = status_db.get_sample_by_internal_id(sample_id)
        sample_flow_cell_ids: List[str] = [flow_cell.name for flow_cell in sample.flowcells]
        flow_cell_from_tag: Flowcell = status_db.get_flow_cell_by_name(flow_cell_id_tag)
        if flow_cell_id_tag not in sample_flow_cell_ids:
            if flow_cell_from_tag:
                flow_cell_from_tag.samples.append(sample)
                print(f"Added sample {sample_id} to list of samples of flow_cell {flow_cell_id}")
            else:
                print(f"Ommiting sample {sample_id} as its flow cell does not exist in StatusDB")
status_db.commit()
```

## This can be closed when

The code has been run and the samples updated in statusDB

## Blocked by

*N/A*

**Comment by islean** [comment]
Small addition but we decompressed whenever the path did not contain any of the flow cells the sample was run on, according to status db. This includes cases where the sample was not malformed, e.g. when the path did not contain any flow cell.

**Comment by islean** [comment]
Slight preference for using `sample_id = spring_file.version.bundle.name` rather than `sample_id = spring_root.split("/")[0]` just because the paths might have some outliers which do not follow the expected pattern.

**Comment by diitaz93** [comment]
> Looks nice! Some comments:
> 
> * Slight preference for using `sample_id = spring_file.version.bundle.name` rather than `sample_id = spring_root.split("/")[0]` just because the paths might have some outliers which do not follow the expected pattern.

agree

> * We should probably use `SequencingFileTag.SPRING` when referring to the spring tag name.

I guess as this is not production code this might not be needed, it is very clear that the tag has no typos.

> * We could lessen the load on the database slightly by moving the instantiation of `flow_cell_from_tag` within the `if flow_cell_id_tag not in sample_flow_cell_ids:` clause.

agree

**Comment by ChrOertlin** [comment]
I guess we made sure that all samples in the input are present in statusdb?

**Comment by diitaz93** [comment]
> I guess we made sure that all samples in the input are present in statusdb?

checked

**Comment by diitaz93** [comment]
Ran in stage without committing, worked as expected

**Comment by diitaz93** [comment]
Ran in stage, committed to database and was updated as expected

**Comment by diitaz93** [comment]
Ran successfully in production, updated 661 entries, omitted 186 external samples
