### ISSUE TITLE
RNA alignment files for Scout upload

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#2564]
## Description

When RNA alignment files are produced in a pipeline (e.g. MIP RNA or RNA fusion) they can be displayed in Scout, starting from the upcoming release v4.72 (https://github.com/Clinical-Genomics/scout/pull/4075). Scout expects a key `rna_alignment_path` for  samples in the scout load config, or as an option to the `scout update individual` command.

## Suggested solution

Connect the RNA alignment file (cram) from pipelines via CG from HK / Hermes to Scout.

## This can be closed when

- [x] RNAfusion alignment files are automagically loaded to Scout. https://github.com/Clinical-Genomics/cg/pull/2661
- [ ] MIP-RNA alignment files are automagically loaded to Scout. https://github.com/Clinical-Genomics/cg/pull/2920

**Comment by henrikstranneheim** [comment]
@ivadym Are doing this one? Would be fantastic and if so could you assign yourself and also add to tracadero BL?
