### ISSUE TITLE
Sample concentration is given as a string

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2626]
## Description

As part of the [bypass qc control](https://github.com/Clinical-Genomics/project-planning/issues/485) project, we need to fetch the allowed concentration per sample from the Application table in status db. Currently the value is formatted as a string of various forms and for automation purposes, we would like to fetch the min/max thresholds as number types instead. 

## Suggested solution

Create two columns, e.g. "sample_min_concentration" and "sample_max_concentration" in the Application table and transfer the values currently in string format to these.

## This can be closed when

The allowed sample concentration range can be fetched without needing to parse any strings.

**Comment by islean** [comment]
Suggested mode of operation is:

1. Add the two new columns to the Application table.
2. Run a script populating the new columns.
3. Verify that the values are correct (needed also because some values might be outdated).
4. Remove the old column (might need some work in the frontend if used).

**Comment by seallard** [comment]
Can this be closed @islean?

**Comment by henrikstranneheim** [comment]
Closing. Reopen if needed.
