### ISSUE TITLE
Delivery report key existence check at time of upload

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/cg#2627]
## Description

This whole issue comes from my limited understanding of prodbioinfo and Scout, but after talking to @karlnyr and @northwestwitch it seems like the new version of Scout should allow prodbioinfo to no longer have to double-check that a case has been uploaded. Basically the exit code from the upload should be possible to fully trust.

The one caveat is that of delivery reports. To ensure that a delivery report is attached to the Scout case, there needs to be a key for the report at the time of upload. If there is, scout will ensure that it is uploaded and will complain if not.

So this issue is to start a discussion on how we ensure that the automatic upload of Scout is done in such a way that prodbioinfo no longer have to double-check that it worked. 

## Suggested solution

One thing that might be still needed is some kind of check which will fail if a delivery report does not exist at the time of upload.

## This can be closed when

- [ ] The cg scout upload is enough for automatic delivery of cases

**Comment by pbiology** [comment]
Would be great to have a refinement session about this

**Comment by henrikstranneheim** [comment]
Added to refinement 9/11

**Comment by ivadym** [comment]
With the current upload automation, it seems unlikely to miss a delivery report unless there's a bug. If a delivery report isn't successfully generated and stored in HK, the Scout upload will be canceled for that specific case.

The pipelines uploading to Scout are MIP-DNA, Balsamic, and Rnafusion. MIP-RNA uploads to an existing MIP/Cancer case and updates the case file by file. All these pipelines generate delivery reports, so it might be a good idea to make the delivery report field mandatory in the Scout config model just to ensure it's always filled in:
https://github.com/Clinical-Genomics/cg/blob/61e69bd2184edf6b1f071e36e84499c71da15d7c/cg/models/scout/scout_load_config.py#L95

I think this solution is somewhat redundant given the current upload process, but having this field as mandatory could be useful to prevent individual (and manual) command uploading cases without a delivery report

**Comment by northwestwitch** [comment]
> I meant that we should make it mandatory on our side, referring to the model I highlighted in CG

Ah OK, sure! 👍🏻

**Comment by pbiology** [comment]
## DECISION
- We implement the solution suggested by @ivadym
