### ISSUE TITLE
Ambiguous housekeeper tags for GENS upload

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/cg#2630]
## Description

Housekeeper tags in MIP is ambiguous for GENS upload for baf, cov, and their indexes 

![image](https://github.com/Clinical-Genomics/cg/assets/14308912/3195754e-c572-4f95-bba5-ef9a465d9251)

In GENS upload the first file that is encountered with the right tags is chosen, which means that the file that is chosen to be uploaded to GENS is determined by the order that they were added to HK, which doesn't seem like the ideal solution as the index-files can be chosen by mistake if the link to HK is done manually.

in **upload_to_gens**
```
    for sample in family.samples:
        hk_coverage: File = housekeeper_api.get_file_from_latest_version(
            bundle_name=case_id, tags=[sample.internal_id] + GensAnalysisTag.COVERAGE
        )
        hk_fracsnp: File = housekeeper_api.get_file_from_latest_version(
            bundle_name=case_id, tags=[sample.internal_id] + GensAnalysisTag.FRACSNP
        )

        if hk_fracsnp and hk_coverage:
            gens_api.load(
                baf_path=hk_fracsnp.full_path,
                case_id=case_id,
                coverage_path=hk_coverage.full_path,
                genome_build=GENOME_BUILD_37,
                sample_id=sample.internal_id,
            )
```

**get_file_from_latest_version**
```
    def get_file_from_latest_version(self, bundle_name: str, tags: set[str]) -> Optional[File]:
        """Return a file in the latest version of a bundle."""
        version: Version = self.last_version(bundle=bundle_name)
        if not version:
            LOG.warning(f"Bundle: {bundle_name} not found in Housekeeper")
            raise HousekeeperBundleVersionMissingError
        return self.files(version=version.id, tags=tags).first()
```

## Suggested solution

A solution could be to add unique tags for upload to GENS to HK for the files that should be uploaded. 

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ivadym** [comment]
It's an already reported problem for the files MIP produces: https://github.com/Clinical-Genomics/hermes/issues/73.

I'll add this files to that issue. Thanks!
