### ISSUE TITLE
Populate sample concentration thresholds

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2634]
## Description

With the columns `sample_concentration_minimum` and `sample_concentration_maximum` added to application, these need to be populated by using the string found in `sample_concentration`. Suggested script is below.

## Suggested solution

```Python
from cg.store.database import initialize_database

from cg.store.models import Application

from cg.store import Store as CgStore

initialize_database("URI")

status_db = CgStore()

applications: list[Application] = status_db.get_applications()

def remove_units(input: str | None) -> str:
    if input and "ng/uL" in input:
        return input.replace("ng/uL", "")
    if input and "ng/ul" in input:
        return input.replace("ng/ul", "")
    return ""

for application in applications:
    concentration_string: str = remove_units(application.sample_concentration)
    concentration_minimum = None
    concentration_maximum = None
    if "-" in concentration_string:
        concentration_min_max: list[float] = [float(number.strip()) for number in concentration_string.split("-")]
        concentration_minimum = concentration_min_max[0]
        concentration_maximum = concentration_min_max[1]
        application.sample_concentration_minimum = concentration_minimum
        application.sample_concentration_maximum = concentration_maximum
    if concentration_string.startswith(">"):
        concentration_minimum = float(concentration_string.replace(">", "").strip())
        application.sample_concentration_minimum = concentration_minimum
    if application.sample_concentration and not application.sample_concentration_minimum:
        print(f"ERROR sample_concentration = {application.sample_concentration} not parsed for {application.tag}")

status_db.session.commit()
```

## This can be closed when

The columns are populated and match `sample_concentration`

**Comment by seallard** [comment]
Looks good!

**Comment by diitaz93** [comment]
Looks great! I would change the second `if` in the `for` for an `elif`, so:
```python
elif concentration_string.startswith(">"):
```
Maybe it will save some time, unless there is an entry like `>50-100`, which I think is unlikely

**Comment by islean** [comment]
> Looks great! I would change the second `if` in the `for` for an `elif`, so:
> 
> ```python
> elif concentration_string.startswith(">"):
> ```
> 
> Maybe it will save some time, unless there is an entry like `>50-100`, which I think is unlikely

There were no such entries! Just ran it and I think the time was not an issue since there are less than 300 applications. Closing this issue and will await the next step wherein AG validates the concentrations.
