### ISSUE TITLE
Refactor workflow tests for the nextflow pipelines

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/cg#2643]
## Description

We now have three identical tests for the current nextflow pipelines, with unnecessary duplication.

## Suggested solution

We could refactor these to have one shared test. A very good solution is given by @fevac in https://github.com/Clinical-Genomics/cg/pull/2592, copied below for completeness:

there are 3 tests that are basically the same for rnafusion, taxprofiler and raredisease. I would refactor so this becomes a single parametrised test.

I'm thinking something like:

add a new file: cg/tests/cli/workflow/nf_analysis/test_cli.py
make a parametrised function similar to:
```

@pytest.mark.parametrize(
    "pipeline, context",
    [(Pipeline.RNAFUSION, "rnafusion_context"),
     (Pipeline.TAXPROFILER, "taxprofiler_context"),
     (Pipeline.RAREDISEASE, "raredisease_context"),
    ],
)
def test_workflow_no_args(cli_runner: CliRunner, pipeline: Pipeline, context: CGConfig):  
    """Test to assess that NF workflows without options successfully print help and exist without error."""
    context = request.getfixturevalue(context)

    # GIVEN no arguments or options besides the command call

    # WHEN running command
    result = cli_runner.invoke(pipeline, [], obj=context)

    # THEN command runs successfully
    print(result.output)

    assert result.exit_code == EXIT_SUCCESS

    # THEN help should be printed
    assert "help" in result.output


```
## This can be closed when

There is one shared test.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@peterpru What is the status of this one?

**Comment by peterpru** [comment]
@henrikstranneheim This one flew under the radar. There is about half an hour of work left on this one, I can finish it when I am back 5 March.

**Comment by peterpru** [comment]
PR here for this work: https://github.com/Clinical-Genomics/cg/pull/3039

**Comment by peterpru** [comment]
Closed as completed.
