### ISSUE TITLE
Reads Updated At behaviour

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2647]
## Description

- Currently some workflows automatically start when they get new reads
- The problem comes when flowcells are re-added or re-demux, then automatic start is also triggered even if there is no new reads and the analysis was already delivered
- It would be good to update the logic to avoid this from happening

This is related to: https://github.com/Clinical-Genomics/MTP-RNAFUSION/issues/45

## Suggested solution

- Maybe if the flowcell should be taken into account together with its `Sequenced at` date 
- Alternatively the reads could be checked, prior updating. If there is no new reads coming then the `Reads Updated At` date should not be modified
- Other ideas

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
Same as https://github.com/Clinical-Genomics/cg/issues/2658 which has been resolved
