### ISSUE TITLE
Extract index and read length from RunParameters of HiSeq flow cells

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2651]
## Description

As a first step of the deprecation of bcl2fastq described in https://github.com/Clinical-Genomics/project-planning/issues/521, the sample sheets from HiSeq2500 and HiSeqX need to be transformed from V1 to V2 sample sheets. This is with the purpose of unifying even further the demultiplex process among the different flow cell types. Note that a new sample sheet can't be generated from scratch as its samples are no longer in LIMS.

A requisite for this new sample sheet is to add the OverrideCycles column to the BCLConvert_Data section. This section has the length of the reads and the indexes for a sample. **This information is not present in the current sample sheet and needs to be fetched from the `RunParameters.xml` file**. There is currently no support for reading RunParameters of HiSeq flow cells in cg, but there is one for NovaSeq flow cells.

## Suggested solution

Expand the RunParameters module in cg to add support for HiSeq flow cell reading. This can be done by creating a new child class of `RunParameters` for HiSeq flow cells.

## For refinement

There are 612 HiSeq flow cells for which we only have the sample sheet (in housekeeper) but no Run parameters because they are stored in PDC. It is clear that many of these sample sheets require manual labour for the demultiplex process. What kind of different sample sheet cases would we expect from the fetched sample sheets?

## This can be closed when

The run parameters are correctly parsed from HiSeq flow cells into cg.

## Blocked by

*N/A*

**Comment by Vince-janv** [comment]
To discuss during refinement:
- Acceptability and possibility of solution proposed here: https://github.com/Clinical-Genomics/project-planning/issues/521#issuecomment-1788626595
