### ISSUE TITLE
Add Mutant QC

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#2652]
## Description

Add a check for MUTANT to fail cases where the results file contains > 20% failed samples

## Suggested solution

- Find `MUTANT` cases to store
- On store, run the QC check (similar to `microSALT`)
- QC check should open results file
- `If > 20% of samples has QC == FALSE` - set `trailblazer` status to `FAILED`

## This can be closed when

- `MUTANT` cases where > 20% of samples have `QC_pass == FALSE` are set to `FAILED` in `trailblazer` when stored
- `MUTANT` cases where =< 20% of samples have `QC_pass == TRUE` are left with `COMPLETED` status in `trailblazer` when stored

## Blocked by

*NA*

**Comment by beatrizsavinhas** [comment]
[`store_available`](https://github.com/Clinical-Genomics/cg/blob/21b42e8473e6c9c5d4d6ac568f1f82b3c97a3aa9/cg/cli/workflow/commands.py#L122C2-L122C2) calls mutant/[`get_cases_to_store`](https://github.com/Clinical-Genomics/cg/blob/5323f147ca003825f2aa831eb479197344fefdef/cg/meta/workflow/mutant.py#L189)

**Comment by beatrizsavinhas** [comment]
Decisions:
* `cg worfkflow store case` will store regardless of the QC
* only automation will check the QC upon storing
* add cli command to check QC per case manually

**Comment by beatrizsavinhas** [comment]
To test:
* get correct results file
* get correct QC check
* set correct TB status
* call store on passed cases only

**Comment by beatrizsavinhas** [comment]
Work in progress at https://github.com/Clinical-Genomics/cg/pull/2664

**Comment by beatrizsavinhas** [comment]
Add Atlas instructions when handling a single case - first run qc and then run store. Store case will just store anything.

**Comment by karlnyr** [comment]
### Information

Can we get the internal CG control somehow?

- Need the correct step from the pooling.
- The pooling artifact might have the entire ticket + 1 extra sample
- The extra sample would be the negative control
- get artifact call for a sample and a specific process type
