### ISSUE TITLE
Unwanted analyses starting after re-demultiplexing of old flow cells

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2658]
## Description

The function `cg.store.api.status.StatusHandler.cases_to_analyze` is fetching cases we do not want to start. The query (amongst other criteria) fetches cases where a sample has a later `Reads Updated At` date than the latest Analysis date. 

When we re-demultiplex an old flow cell we may update the reads for other samples then the one we want to analyse resulting in unnecessary analyses starting. This is also confusing for production as they have to try to find the corresponding ticket.

These cases are re-uploaded to the customer causing confusion on their side as well.

### Example cases:
modernmullet
supercivet
justpug

## Suggested solution

The intention of `Reads Updated At` is to restart analyses when more data has been added compared to the existing analyses. I think this logic is good. However I think the date should not be `datetime.now()` and instead be the date where the sequencing was started i.e. 2023-11-06 in the case of `231106_A01901_0242_BXXXXXXXX`.

## This can be closed when

Only cases that we actually want to analyse are fetched by `cases_to_analyze`

**Comment by seallard** [comment]
I'm not sure if the suggested solution is sufficient. Would not the problem remain since all samples will receive the flow cells new `sequenced_at` date - ensuring that they all would be fetched with `cases_to_analyze` anyway? 

That is how I understand the problem - that all samples have their `reads_updated_at` reset after re-demultiplexing when they actually have not received any new data.

It seems like a check that verifies that new reads actually have been added is necessary, and only then set the sample `reads_updated_at`. For instance comparing the new read count with the old. But this approach is problematic based on

1. demultiplexing is not deterministic
2. read count is a quantitative measure, the same read count does not mean that the actual reads are the same

Point one can be circumvented by using some error margin. Not sure about point 2.

I need to understand more about when re-demultiplexing is done and what input data is used.

**Comment by Vince-janv** [comment]
> I'm not sure if the suggested solution is sufficient. Would not the problem remain since all samples will receive the flow cells new `sequenced_at` date - ensuring that they all would be fetched with `cases_to_analyze` anyway?

The flow cells `sequenced_at` date is also `datetime.now()` as you point out. I suggest using the actual date that the flow cell was run (ie disregarding the demultiplexing). So a flow cell from 2018 would have that date set.

> That is how I understand the problem - that all samples have their `reads_updated_at` set after re-demultiplexing when they actually have not received any new data.

^^ That is correctly understood, but even if we add some data (if we for example are missing some sequencing metrics) I don't think we should start the analysis.

Let me know if you want a chat to straighten out some question marks, and thanks for taking this on 😊

**Comment by seallard** [comment]
> > I'm not sure if the suggested solution is sufficient. Would not the problem remain since all samples will receive the flow cells new `sequenced_at` date - ensuring that they all would be fetched with `cases_to_analyze` anyway?
> 
> The flow cells `sequenced_at` date is also `datetime.now()` as you point out. I suggest using the actual date that the flow cell was run (ie disregarding the demultiplexing). So a flow cell from 2018 would have that date set.
> 
> > That is how I understand the problem - that all samples have their `reads_updated_at` set after re-demultiplexing when they actually have not received any new data.
> 
> ^^ That is correctly understood, but even if we add some data (if we for example are missing some sequencing metrics) I don't think we should start the analysis.
> 
> Let me know if you want a chat to straighten out some question marks, and thanks for taking this on 😊

Yeah :+1: Hm, I misunderstood the date part - I guess it will have the old date in the dir name. But I think that means the cases that actually have samples with new data would not be filtered for re-analysis since the sequencing date will be older than the most recent analysis date.

**Comment by islean** [comment]
Seems as if this would render a column on the `sample` table unnecessary. Or is the plan to modify how the flow cell `sequenced_at` is set, and let `sample.sequenced_at` be a property fetching the latest flow cell `sequenced_at` we can find for the sample?

**Comment by seallard** [comment]
But how are we supposed to determine that a case has a sample with new data? I assume we need this filter to work with that field
```python

def filter_cases_for_analysis(cases: Query, **kwargs) -> Query:
    """Filter cases in need of analysis by:
    1. Action set to analyze or
    2. Internally created cases with no action set and no prior analysis or
    3. Cases with no action, but new sequence data
    """
    return cases.filter(
        or_(
            Family.action == CaseActions.ANALYZE,
            and_(
                Application.is_external.isnot(True),
                Family.action.is_(None),
                Analysis.created_at.is_(None),
            ),
            and_(
                Family.action.is_(None),
                Analysis.created_at < Sample.reads_updated_at,
            ),
        )
    )

```
