### ISSUE TITLE
Deliveries and storage of incomplete analyses AND proper tracking of deliveries.

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#2702]
## Description

Recently we have been having issues with completing analyses for samples received from a specific customer, `cust127`. This issue has then required production to deliver vcf, fastq, bam, etc. to the delivery server manually as the current logic requires the files to be there before storing. I think it is due time that we change this logic - in case this would be needed. The same logic applies when we have had to skip steps for an analysis, resulting in a kind of partial analysis.

However, we cannot simply start to deliver incomplete analyses without also tracking properly what has been delivered. That leads to the next point - updating the delivery report. We should be able to add content to the delivery report in free text. I also think that the delivery report itself can have an additional page, containing each file that is to be included in the delivery and a short explanation of what the purpose of the file is. This would add clarity, and reduce any possible misinformation that could be kept in the ticket rather than in the Scout case or the file deliveries.

## Suggested solution

- Override the current store, allowing the user to store partial cases
   - store information that the analysis stored is partial
- Enable the user to add a comment to the delivery report somehow
- Add a summary of the files that are delivered to the delivery report

## This can be closed when

Above is discussed and implemented or closed

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
### Decision

### Phase 1
- Somehow set Analysis to "FAILED" (or similar) which should avoid automatic upload
- Ability to generate Delivery-report with force-flag
- Using the force flag should also require a comment flag to be used
- The comment is stored in the Analysis table
### Phase 2
- Creation of delivery-report checks status-db for comment and adds to report
- Add which files are delivered to caesar as a section in the delivery-report
- Short description of the aforementioned files
- Add description of all generated files for all pipelines to an available resource
