### ISSUE TITLE
(Archiving) How to determine archive location for files

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2716]
## Description

Archive location is determined on customer level, while the proposed new DDN/Miria archiving flow starts with fetching non-archived spring files from Housekeeper. Given that `Customer` and `File` are in different database schemas (StatusDB and Housekeeper), we need to do a call to StatusDB for each file to fetch the sample corresponding to the bundle and working out the archive location from there.

This has the unfortunate consequence that spring files for PDC customers are included when fetching non-archived spring files, since no PDC spring file will have an entry in the Archive table. We would want to not fetch any PDC spring files from the database when starting the DDN/Miria flow.

## Suggested solution

Tag all spring files with the archive location. Would mean a change in the storing of spring files flow, and running a script for all current files.

## This can be closed when

All spring files are tagged with their archive_location and any new spring files get the tag added automatically.

**Comment by islean** [comment]
Proposed script for tagging Spring files which are already in the database:

```Python
spring_files: List[File] = [housekeeper_api.get_files(tag_names=[SequencingFileTag.SPRING]).all()]

count = 0
for file in spring_files:
    if count % 1000 == 0:
        # Just to keep track of the progress
        print(count)
    sample: Sample = status_db.get_sample_by_internal_id(file.version.bundle.name)
    archive_location: str = sample.archive_location
    archive_location_tag: Tag = housekeeper_api.get_tag(archive_location) if housekeeper_api.get_tag(archive_location) \
        else housekeeper_api.new_tag(name=archive_location)
    file.tags.append(archive_location_tag)
    count += 1

housekeeper_api.session.commit()
```

**Comment by henrikstranneheim** [comment]
Nice 👍

**Comment by diitaz93** [comment]
@islean Are the squared brackets necessary here?
```python
spring_files: List[File] = [housekeeper_api.get_files(tag_names=[SequencingFileTag.SPRING]).all()]
```
I understand that `.all()` turns the Query into a list already. Correct me if I'm wrong

**Comment by islean** [comment]
> @islean Are the squared brackets necessary here?
> 
> ```python
> spring_files: List[File] = [housekeeper_api.get_files(tag_names=[SequencingFileTag.SPRING]).all()]
> ```
> 
> I understand that `.all()` turns the Query into a list already. Correct me if I'm wrong

Good catch! Remnant from me testing it with .first() locally! Changing it.

**Comment by islean** [comment]
Upon discussion, there is no need to tag PDC files since we have no intention of fetching such files in this flow yet. So there is no need to run the script currently.
