### ISSUE TITLE
Remove required -r option from cg workflow balsamic

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2722]
## Description

Currently balsamic runs as dry-run by default, unless added `-r` flag. This is contrary to all other workflows and confusing. It would be nice to homogenise. 

If changes are made they need to be reflected in the automation and atlas documentation. 

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
No mention of the `-r` or `--run-analysis` in the servers repo. It seems like automation runs `start-available` which in turn calls `start` which no longer takes the `--run-analysis` option.

**Comment by seallard** [comment]
I'll leave removing the flag from the balsamic code base to someone more familiar with it.
