### ISSUE TITLE
Variants for a cust000 case has been uploaded to Loqusdb

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/cg#274]
Local observations in Loqusdb seems to contain cust000-cases

Problem: 
Variant for a cust000-case (in-house) has been uploaded to Loqusdb, that should not happen.

**Steps to reproduce:**
See Scout, Local observations
https://scout.scilifelab.se/cust003/18263/efe9fd872b259ea062a51f8df53a8628
Shows 2 observations
In Loqusdb:
  1. Rasta
  2. Use production env
  3. loqusdb variants --variant-id 15_89876838_G_GCTA
  4. observations': 2, 'families': ['fancycobra', 'topskitten']
fancycobra = cust000 case for Twist-development
topskitten = cust003 case

Expected outcome / suggested solution:
Only one observation in Scout for this variant since one case is cust000

Questions: 
Q: what should happen with the erroneous case(s) in loqus?
A: 
Q2:how did this happen?
A2:

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by patrikgrenfeldt** [comment]
Resolved by #341, #323, #299 and by removing samples. There is also a plan to readd all samples to an empty db to make sure we have the right set of samples
