### ISSUE TITLE
Update drop-down presets for flow cell status in statusdb

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg#2748]
## Description

The current presets for flow cell statuses in statusdb are currently incorrect after the recent refactoring. See example:

![Screenshot 2023-12-07 at 15 40 01](https://github.com/Clinical-Genomics/cg/assets/60181709/b6a56e69-7200-4471-b537-bd80ae5b63b5)

## Suggested solution

Update the constants for it in cg.

## This can be closed when

You can manually change the flow cell status in statusdb.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by islean** [comment]
This is a wider issue than flow cell statuses - it also affects for example case actions:

<img width="369" alt="image" src="https://github.com/Clinical-Genomics/cg/assets/40887124/2728dc3c-3cbd-4650-bf53-b5f99b0c9da2">

Probably related to some enum refactoring in https://github.com/Clinical-Genomics/cg/pull/2712

**Comment by islean** [comment]
Addressed by #2752.
