### ISSUE TITLE
Add all files uploaded to scout in delivery report

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2753]
## Description

- Currently only vcf files are added. Other reports and files should also be included
- This should be done for all pipelines 

<img width="754" alt="image" src="https://github.com/Clinical-Genomics/cg/assets/29628428/f992cb8a-1380-4833-b786-7e715a255fad">

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ivadym** [comment]
Duplicated issue. Overlaps with https://github.com/orgs/Clinical-Genomics/projects/47/views/3?pane=issue&itemId=50502150 and https://github.com/Clinical-Genomics/cg/issues/2702.
