### ISSUE TITLE
Produce parameter file generator for microSALT runs

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/cg#276]
Problem: 
As microSALT is currently not included in the CG infrastructure; key sample information is gathered internally in the software. With the integration into CG; this functionality needs to be offloaded to CG.
TT has been chosen for this issue as they best know which sample specific parameters may be of interest; and the task also provides a light-weight way to produce code both relevant for CG and uSALT.

Suggested solution:

1. Gather which parameters are sample specific
2. Determine if any non-sample specific parameters are relevant to override
3. Write a plugin that:
3.1. Fetch said parameters from LIMS/StatusDB in concordance with existing standards
3.2. Produce a file containing said parameters in concordance with existing standards (likely either YAML or JSON)
4. Assign the plugin an automatic invocation whenever a microSALT project is started through CG.

Q: Importance of task?
A: Task is of high importance as it blocks integration of microSALT into CG environment. Task is however awaiting standardization of CG, also known as "Making CG less MIP'y".

What needs to be done on the planning meeting:
- Estimate storypoints
- Discuss relevant parameters (see point 1 & 2)
- Review data fetching standards (see 3.1 & 3.2)

**Comment by emiliaol** [comment]
@sylvinite Could you update or close this issue? If it's stuff you want done please also add it to the backlog
