### ISSUE TITLE
Redefine flow cell and sequencing data status

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#2771]
## Description

Currently, we have a field in the `Flowcell` table called `Status`. It is used to track the progress of flow cell processing. However, the `ondisk` status actually means that we have spring/fastq files in Housekeeper and not the actual flow cell folder on disk. This is confusing and incorrect.

## Suggested solution

- The `Status` field in the `flowcell` only reflect flow cell and not Housekeeper status. of sequencing data
- Add new field in the `sample` table to reflect sequencing data status: ´on_disk´, `archived`
- Update all samples with the current status in the `sample` table based on sample sheet(s) and Housekeeper status
- Update all flow cells  with the current status in the `flowcell` table based on presence in `/home/proj/production/flow_cells/`
- Rewrite cg logic to work on the new statuses

## This can be closed when

There is a clear distinction between flow cells and sequencing data status 

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
We will not adress it in the near future. When the PDC archiving is revisited this will have to change
