### ISSUE TITLE
Update database to fit new sequencing technologies

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2792]
## Description

The cg database is very closely coupled to Illumina sequencing. For the implementation of data from ONT, Bionano and Pacbio instruments we need to modify and add some table to the database.

## Suggested solution

See https://miro.com/app/board/uXjVN-I19i8=/ for up-to-date suggestions

- [ ] General: Modify existing tables (Change name of Sequencing_metrics and flow_cell, replace reads with yield)
- [ ] Nanopore: https://github.com/Clinical-Genomics/cg/pull/2793
- [ ] Bionano
- [ ] PacBio

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by diitaz93** [comment]
is this linked to https://github.com/Clinical-Genomics/servers/issues/1222 ?

**Comment by Vince-janv** [comment]
- Remove current link-sample (Attempted, but broke MIP)
- Attempt common flow_cell table
- Look into base_model for sequencing metrics which supports different instruments via polymorphism (https://docs.sqlalchemy.org/en/20/orm/inheritance.html)
- Look into read lengths in the past
- Look at illumina documentation to make sure `yield = read_lengths * nr_reads`

**Comment by Vince-janv** [comment]
Tracked in https://github.com/Clinical-Genomics/add-new-tech/milestone/8
