### ISSUE TITLE
Increase characters in Click help

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2821]
## Description

In our CLI, the descriptions of commands are often not shown in their entirety, see below

<img width="655" alt="image" src="https://github.com/Clinical-Genomics/cg/assets/40887124/72fde5ab-20ca-4f57-bc3f-27fb78ad776b">

I would guess that this is a setting which can be modified in Click, which I suggest we set higher.

## Suggested solution

Increase allowed characters in the CLI command prints.

## This can be closed when

Help descriptions are shown in their entirety.

**Comment by henrikstranneheim** [comment]
@islean https://click.palletsprojects.com/en/8.1.x/documentation/
```
To change the maximum width, pass max_content_width when calling the command.

cli(max_content_width=120)

**Comment by islean** [comment]
@henrikstranneheim Might be this instead https://click.palletsprojects.com/en/8.1.x/documentation/#command-short-help? I interpret the max_content_width as allowing the lines to be wider than the terminal, whereas this is an issue only with the shorter help messages being truncated much earlier than that.

**Comment by henrikstranneheim** [comment]
@eliottBo would you like to look into this once the dry run issue is solved?

**Comment by eliottBo** [comment]
Yes I can look into it after the dry-run 👍

**Comment by eliottBo** [comment]
Solved with https://github.com/Clinical-Genomics/cg/pull/3315
Closing
