### ISSUE TITLE
Submit upload commands to SLURM instead of running on the head node

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2826]
## Description
Uploads of cases to databases take between 10 mins and an hour, are done sequentially and are running on the head node. This is frustrating, since uploads are not trackable and fails are hard to detect. It also delays deliveries. Solving this is needed for the [streamline delivery proejct](https://github.com/Clinical-Genomics/project-planning/issues/515)

There is already an issue regarding the making them parallell #2171 .

## Suggested solution

- Split the upload part into each individual upload and submit them to SLURM.
- Keep track of them in trailblazer (more refinement needed)

## This can be closed when

Uploads are parallell and not running on the head node. Failures in the uploads should be clearly reported.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
Tracked in https://github.com/Clinical-Genomics/streamline-delivery/milestone/1
