### ISSUE TITLE
Create an Order table in the database

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2827]
## Description

To keep track of active orders we need a table representing them in the database. Part of [the streamline delivery project](https://github.com/Clinical-Genomics/project-planning/issues/515)

## Suggested solution

- Create an order table, suggested fields.
  - ticket_id
  - name
  - ordered_at
  - status (or just is_delivered)
  - It should link to samples and cases
 
## This can be closed when

Orders are represented as tables and not just ticket_ids in different tables

**Comment by henrikstranneheim** [comment]
Would be nice to also consider the request to save/resume an order in the order portal. A properly formatted table might enable this.

**Comment by henrikstranneheim** [comment]
Done . Reopen if needed!
