### ISSUE TITLE
Update all sample sheets to v2 before bcl2fastq is deprecated

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2837]
## Description

Removing all the logic around `bcl2fastq` is the final part of https://github.com/Clinical-Genomics/project-planning/issues/521. This step will make all flow cells with v1 sample sheets obliged to upgrade to a v2 sample sheet, which is compatible with `BCLConvert` on the DRAGEN.

## Suggested solution

1. Upgrade all sample sheets at once: Create a script that iterates over all flow cell bundles, and validates that the sample sheet is v2 and has the correct structure, if it doesn't create a correct sample sheet and replace the old one.
3. Upgrade on the run: Add code to cg that creates a correct v2 sample sheet automatically if it fails validation and updates the sample sheet in Housekeeper.
   1. Cons: Hard to keep track of which flow cells have the updated sample sheet and which don't.

_Both solutions should include the cases when the sample sheet can't be generated automatically by cg because the flow cell samples are not in LIMS. For that case, a **translation script** or function will be developed to translate a v1 sample sheet to v2._

## Concerns

- Taking into account that the results in terms of reads, yield and quality score may vary between `BCLConvert` and `bcl2fastq`, should we do a risk assessment on this upgrade? Or should we do more tests on more flow cells to better understand the reason of this discrepancy? (The results of the experiment comparing `bcl2fastq` and `BCLConvert` are [here](https://github.com/Clinical-Genomics/cg/pull/2736#issuecomment-1867421688).
- What should we do with the old sample sheets? Store/archive them somehow?

## This can be closed when

All Illumina sample sheets have the correct structure (v2) and can be used for demultiplexing on DRAGEN using `BCLConvert`.

## Blocked by

*N/A*

**Comment by diitaz93** [comment]
A question that arose during the Trocadero meeting: Should an error message pop up when trying to demux a v1 sample sheet meanwhile this is properly fixed?

**Comment by henrikstranneheim** [comment]
@diitaz93 Done?

**Comment by diitaz93** [comment]
@henrikstranneheim not yet, we still need to do the translation from V1 to V2 for the flow cells that lack their samples in LIMS. More details in #2975

**Comment by diitaz93** [comment]
Actually, this could be marked as duplicate as #2975 solves the same problem and has more details about the proposed implementation
