### ISSUE TITLE
Organise demultiplex tests and fixtures around only 7 flow cell cases

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2842]
## Description

In the context of demultiplexing, I have identified 7 different Illumina flow cell cases that share many characteristics:
- HiSeqX single index
- HiSeqX double index
- HiSeq2500 double index
- HiSeq2500 custom index
- NovaSeq6000 pre 1.56 kits
- NovaSeq6000 post 1.5 kits
- NovaSeqX

The idea is that the demultiplexing test suite is designed around these 7 cases. For this, I chose one example from each group and added the flow cell directory data to the folder `tests/fixtures/apps/demultiplexing/flow_cells` in #2736. However, many tests and fixtures still use elements spread around the test directory from different flow cells in a disorganised way.

## Suggested solution

With the help of fixture plugins introduced in #2816, create an organised set of fixtures that replaces old ones pointing to inconsistent flow cells with correct fixtures pointing to one of the 7 case flow cells.

PRs:
- https://github.com/Clinical-Genomics/cg/pull/2841
- https://github.com/Clinical-Genomics/cg/pull/2847

Pending tasks:
- [ ] Remove all fixtures referring to other flow cells
- [ ] Remove fixtures named `CorrectSampleSheet.csv` as all sample sheets in the flow cell folders should be correct, ill-shaped sample sheets should be in the `broken_flow_cells` fixture directory

## This can be closed when

The demultiplexing testing suite is designed around the 7 flow cell cases.

## Blocked by

*N/A*

**Comment by henrikstranneheim** [comment]
@diitaz93 Done?

**Comment by diitaz93** [comment]
> @diitaz93 Done?

@henrikstranneheim Not yet, there is still a lot of debris from old fixtures that unfortunately are still used in some tests. A further cleaning is needed. I want to do this this summer if I have time but this is low prio

**Comment by diitaz93** [comment]
Very low prio, not keeping as an issue
