### ISSUE TITLE
Create a log for MUTANT uploads to GISAID / FOHM

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg#2856]
## Description

We have an old deviation open (https://github.com/Clinical-Genomics/Deviations/issues/471) that was caused by some odd upload behavior of MUTANT results to the GISAID database. 

This is normally done manually by us in prod bioinfo via the CLI command:
```
cg upload fohm preprocess-all -c <case_id> -c <case_id>
``` 

However, because of this, there isn't any log left afterward to look at. Only old output in your tmux/screen session if you're lucky. 
This made the issue a lot more complicated to investigate and adding some type of saved log would be helpful for future such cases. 

## Suggested solution

Either update the CLI command to also dump the output into a log, or wait until we have automated the process further and do it then.

## This can be closed when

A decision has been taken or a log added.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
Done here: https://github.com/Clinical-Genomics/atlas/pull/2329
