### ISSUE TITLE
Flow cells not removed

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2861]
## Description

Some flow cell directories are not removed correctly. 

Examples:
22FWKKLT3
22FYY7LT3
22FJMMLT3 - Missing fastq files in housekeepr

## Suggested solution
- Look into the logs (`journalctl --user-unit cg-clean-flow-cells.service`) and see which criteria is blocking the removal
- See if the criterias are too strict

## This can be closed when

Any flow cell, (barring crashed runs) are removed once demultiplexed and added to the databases

**Comment by ChrOertlin** [comment]
## 22FWKKLT3

 Trying to delete /home/proj/production/encrypt/20231219_LH00188_0048_A22FWKKLT3
Jan 11 15:25:03 hasta.scilifelab.se bash[116761]: 2024-01-11 15:25:03 hasta.scilifelab.se cg.apps.housekeeper.hk[116761] WARNING Bundle: ACC13504A4 not found in Housekeeper
Jan 11 15:25:03 hasta.scilifelab.se bash[116761]: 2024-01-11 15:25:03 hasta.scilifelab.se cg.cli.clean[116761] ERROR CleanFlowCellFailedError("Flow cell with path /home/proj/production/encrypt/20231219_LH00188_0048_A22FWKKLT3 not removed: HousekeeperBundleVersionMissingError('')")

## 22FYY7LT3

Trying to delete /home/proj/production/demultiplexed-runs/20231215_LH00188_0046_B22FYY7LT3
Jan 07 09:19:43 hasta.scilifelab.se bash[202219]: 2024-01-07 09:19:43 hasta.scilifelab.se cg.apps.housekeeper.hk[202219] WARNING Bundle: ACC12068A30 not found in Housekeeper
Jan 07 09:19:43 hasta.scilifelab.se bash[202219]: 2024-01-07 09:19:43 hasta.scilifelab.se cg.cli.clean[202219] ERROR CleanFlowCellFailedError("Flow cell with path /home/proj/production/demultiplexed-runs/20231215_LH00188_0046_B22FYY7LT3 not removed: HousekeeperBundleVersionMissingError('')")

## 22FJMMLT3

Jan 11 15:24:52 hasta.scilifelab.se bash[116761]: 2024-01-11 15:24:52 hasta.scilifelab.se cg.cli.clean[116761] ERROR CleanFlowCellFailedError("Flow cell with path /home/proj/production/demultiplexed-runs/20231205_LH00217_0032_B22FJMMLT3 not removed: HousekeeperFileMissingError('Flow cell 22FJMMLT3 is missing fastq and spring files for some samples. Info can be found in debug mode.')")
