### ISSUE TITLE
Refactor endpoint for submitting an order

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2879]
## Description
The existing logic in the `submit_order` endpoint is messy.

1. Document requirements
2. Discuss and decide on technical implementation

### Questions
- What **SHOULD** happen when an order is submitted? (On a macro level)
- How can customers place orders?

## Suggested solution
Document the answers to the questions above. Then do a technical refinement on how to implement it.

**Comment by seallard** [comment]
## How can customers place orders?

## What do the requests look like?

## What do the responses look like?

## What should happen when an order is submitted?
- An order is created in the database
- Cases are created in the database
- Samples are created in the database
- A ticket is created in the ticketing system

**Comment by seallard** [comment]
## Technical implementation

**Comment by islean** [comment]
Additional comment before I forget - currently there are bugs with regards to the order in which things are done. One can for example test putting an order with sample ids which already exist. In this case the SuSy ticket is still created although you get an error in the frontend.

**Comment by seallard** [comment]
### Order request validation - technical refinement
- What do order requests look like currently?
- Do we want to change what the request looks like?
- What validation should be applied?

**Comment by seallard** [comment]
Replaced by project https://github.com/Clinical-Genomics/project-planning/issues/540
