### ISSUE TITLE
Saving Subject ID for all orders

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/cg#2884]
## Description

Subject ID is mandatory to provide in the orderform (1508) for clinical samples but for orders with Data Delivery "fastq" or "no delivery" the Subject ID is not saved in statusdb. The customer invest time to provide it and it's useful to have for future re-runs of the sample.

## Suggested solution

Start saving it in the database at the field "Subject ID".

## This can be closed when

Subject ID is saved for all clinical samples.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@islean Do you have time to fix this?

**Comment by islean** [comment]
> @islean Do you have time to fix this?

Looking into it!

**Comment by henrikstranneheim** [comment]
Seems done!
