### ISSUE TITLE
(Streamline delivery) Script for populating the orders table

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#2887]
## Description

We need to populate the Order table with old orders. 

## Suggested solution

```Python
status_db = Store()

all_cases: list[Case] = status_db.get_cases()
print(len(all_cases))
for case in all_cases:
    ticket_id: str = case.latest_ticket
    if ticket_id:
        if status_db._get_query(table=Order).filter(Order.ticket_id == ticket_id).first():
            continue
        new_order = Order(workflow=case.data_analysis, customer_id=case.customer_id, order_date=case.ordered_at.date())
        status_db.session.add(new_order)

status_db.session.commit()

```
## This can be closed when

All old SuSy tickets have a corresponding order entry

**Comment by Vince-janv** [comment]
This looks great! There is a column called original_ticket on Sample. It predates the tickets column on Case. I think we need to make sure all of those are created as well. I think the difference between the two sets will be minimal (maybe 0) but I think we should check.

**Comment by islean** [comment]
> This looks great! There is a column called original_ticket on Sample. It predates the tickets column on Case. I think we need to make sure all of those are created as well. I think the difference between the two sets will be minimal (maybe 0) but I think we should check.

Alright! When we tie the cases to the order_id, which one will we use?

**Comment by Vince-janv** [comment]
> Alright! When we tie the cases to the order_id, which one will we use?

To be refined!

**Comment by seallard** [comment]
I think it looks good 👍 Since we have hooked up the creation of orders, this script should be enough to run once 👍

**Comment by islean** [comment]
> This looks great! There is a column called original_ticket on Sample. It predates the tickets column on Case. I think we need to make sure all of those are created as well. I think the difference between the two sets will be minimal (maybe 0) but I think we should check.

Are samples always part of the same workflow? Or how is that determined if they can be submitted in multiple tickets with different workflows?

**Comment by islean** [comment]
Script has been run in both Production and stage, with some additional orders created where the cases and samples were connected unconventionally. Thanks for the help with those @Vince-janv.

**Comment by islean** [comment]
Should I re-run this script @Vince-janv to remedy the bug from last week?

**Comment by islean** [comment]
> Should I re-run this script @Vince-janv to remedy the bug from last week?

And then https://github.com/Clinical-Genomics/cg/issues/2968

**Comment by Vince-janv** [comment]
Yes, I think both should be re-run 👍

**Comment by islean** [comment]
Created 3 orders
