### ISSUE TITLE
CG easily updateable with new baitset

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#290]
As cg user, I want to easily add new baitsets so that cg doesn't development work to get new baitsets.

Problem: 
The baitsets are hardcoded in cg and it might take development effort to add new baitsets.

Steps to reproduce
  1. add new baitset in an Orderform
  2.  ask team teamname to add the new baitset

Expected outcome / suggested solution:
The new baitset is orderable the same day in the orderportal.

Questions: 
Q: A:

**Comment by emiliaol** [comment]
@patrikgrenfeldt Still something we need to do?

**Comment by Mropat** [comment]
Stale issue. Will not be completed in this version of orderportal
