### ISSUE TITLE
baitsets in CG from PanelDB

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#291]
As a panel developer, I want Orderportal to have the baitset in the PanelDB so that the developed baitsets are orderable.

Problem: 
The baitset name should be selectable in the OrderPortal.

Steps to reproduce
  1. Add a baitset in PanelDB
  2. Create an order in the orderportal

Expected outcome / suggested solution:
The panel shows up in the orderportal

Questions: 
Q: 
A:

**Comment by emiliaol** [comment]
@patrikgrenfeldt Is this not implemented?

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt Is this not done?

**Comment by hassanfa** [comment]
paneldb repo is deprecated and we have target_bed_capture instead.
