### ISSUE TITLE
Unify various definitions of dry-run option

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#2947]
## Description

The dry-run option for CLI commands is defined multiple times in several places and with different names.

## Suggested solution

Keep the definition in `cg/constants/constants.py` and delete the rest

## This can be closed when

Only one definition of dry run is used

## Blocked by

*N/A*

**Comment by eliottBo** [comment]
I will work on this issue 😃
The dry run command is defined in these files and need to be removed:
- [ ] cg/cli/add.py
- [ ] cg/cli/deliver/base.py:
- [ ] cg/cli/demultiplex/demux.py:
- [ ] cg/cli/generate/report/options.py:
- [ ] cg/cli/upload/delivery_report.py:
- [ ] cg/cli/upload/fohm.py:
- [ ] cg/cli/upload/mutacc.py:
- [ ] cg/cli/upload/nipt/base.py:
- [ ] cg/cli/upload/nipt/ftp.py:
- [ ] cg/cli/upload/nipt/statina.py:
- [ ] cg/cli/workflow/commands.py:
- [ ] cg/cli/workflow/fluffy/base.py:
- [ ] cg/cli/workflow/microsalt/base.py:
- [ ] cg/cli/workflow/mip/options.py:

**Comment by diitaz93** [comment]
Great @eliottBo! Link a PR as soon as you have one. It could be an early draft
