### ISSUE TITLE
Changing microbial apptags in LIMS

### ISSUE THREAD

**Issue by KarinSollander** [Clinical-Genomics/cg#296]
As a lab person, I want to change many microbial apptags in LIMS at the same time so that I don't need to do it manually in LIMS.

Problem: 
cg/cli/set sample only change the apptag in status-db not in LIMS.

Steps to reproduce
  1. us
  2. cg set microbial-order ORDER_ID SIGNATURE -a APPTAG

Expected outcome / suggested solution:
all samples for the have the new apptag both in statusdb and in LIMS

Questions: 
Q: 
A:

**Comment by ingkebil** [comment]
Wauw! Välskriven!

**Comment by KarinSollander** [comment]
Tack! :)
Jag fick hjälp från Patrik (han skrev "Steps to reproduce")

**Comment by emiliaol** [comment]
Thanks for the issue, I've added it to the backlog of TTN. Because of Hasta and some data privacy issues it might take a bit of time before we can take it into a sprint, but we have seen it and are planning to do fix it "in the near future".
