### ISSUE TITLE
Add validation of well positions

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#3020]
## Description

When customers submit order forms containing faulty well_positions, the error is caught by Lims. But that happens after a ticket is opened in SuSy, meaning that the customer can go on thinking that all went well. We will not have any records in Lims or status db though.

## Suggested solution

Implement validation for this upon order submission (and/or when parsing the order form)

## This can be closed when

No such orders result in tickets being created.

**Comment by Karl-Svard** [comment]
### Allowed values in lims:

#### Tube container
Only `1:1`. One sample per container.

#### 96 well plate container
`A:1` to `H:12`

**Comment by Vince-janv** [comment]
According to @islean the "A:1 to H:12" validation is missing from the `improve-order-flow` branch

**Comment by diitaz93** [comment]
## Technical refinement
- Implement in a PR to be merged into the dev branch of the implement order flow project
- There are two rules to be implemented:
  - Container names for tubes should be unique among samples
  - Well-plate positions should be formatted as A-H:1-12

**Comment by eliottBo** [comment]
- [x] Add well position validation for sample
- [ ] Add well position validation for case_sample
- [ ] Add tube name validation for sample
- [ ] Add tube name validation for case_sample

**Comment by diitaz93** [comment]
Finished
