### ISSUE TITLE
Order validation rules

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#3035]
Please document any order validation rules that you discover in this list.

### Order validation rules
- For an order with plates, only one sample is allowed in each well.
- For an order with plates, at most one is allowed to have empty wells.
- If skip reception control is ticked, then the Concentration_ng_ul should be required to be within the limits specified in the Application table. If source is cell-free DNA, specific concentration limits are found in the same table.
- If skip reception control is ticked, then the elution buffer is not allowed to be "other".
- If the container is a tube, the only allowed well_position should be 1:1. (Alternatively it should not be required perhaps? It is a single tube)
-

**Comment by islean** [comment]
Just adding that the tube name is not required. Only plates are required to have a container name. By default the tubes will get the sample name instead.

**Comment by islean** [comment]
These are validations we do via the ExcelOrderFormParser:

- Is the orderform of the correct version (every update means a new version)?
- There exists a sheet in the xlsx file called "orderform", "Orderform" or "order form".
- There are no blank lines between samples.
- There is a parseable and correct document number, e.g. 1508.
- All samples have the same data_analysis/workflow specified (should it be like this?)
- The data analysis is converted to lower with " " replaced with "-" (not really a validation per se but still weird behaviour).
- The data delivery with " + " exchanged for "-" and " " for "_" should be in the DataDelivery StrEnum.
- Data analysis should be in the data_analysis_alternatives in the validate_data_analysis method.
- index_number should be numeric
- quantity should be numeric
- Source should be one of the alternatives found in SOURCE_TYPES.
- volume should be numeric

**Comment by islean** [comment]
Tomte fields needed in the order:

https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/426

**Comment by seallard** [comment]
Documented in Atlas.
