### ISSUE TITLE
Feature to filter out cancelled samples

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3058]
## Description

It is currently not possible to filter for cancelled samples in StatusDB. This means that cancelled samples still show up as existing samples in the order portal and therefore the customers often place orders containing cancelled samples for which there is no data. 

Related to https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/431.

Furthermore, the current action of cancelling a sample in StatusDB also deleted all the associated entries in the Case Sample and Case tables. If by any reason the cancelling needs to be reversed, all information has to be re-entered in the database manually which is error prone (and has caused issues in the past). The action to cancel the sample should be reversible.

## Suggested solution

Add field `is_cancelled` to the `Sample` table in StatusDB.
The action to cancel the sample should be reversible (no data should be deleted from the database).

## This can be closed when

It is possible to filter for cancelled samples.

## Blocked by

Nothing to my knowledge.

### Clarification
This issue describes two problems:
- Customers can select old cancelled samples when placing an order. Tracked here instead https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/431

- Cancelled samples are deleted permanently which is annoying for production since customers often want to re-add them.

### Further clarification
Production wants a simple "un-cancel" action which restores all data for a case/sample. Not clear if it is a restore action for a case, for a sample or both. I'm guessing this action/actions should be added to the status db admin interface.

Analyses should not be started for cancelled cases. Analyses should not be started for cases containing cancelled samples.

# Clarification 3
see https://github.com/Clinical-Genomics/cg/issues/3058#issuecomment-2264823297

**Comment by beatrizsavinhas** [comment]
According to @annagellerbring, we are expecting big orders in the following weeks for reruns of samples for which there are corresponding duplicated cancelled samples so it would be good to have this in place before then.

**Comment by henrikstranneheim** [comment]
@beatrizsavinhas Or is a status in the Action field? When should it be set and by whom (from GUI/TB/CLI/Automation/manually)?

**Comment by beatrizsavinhas** [comment]
Do you mean the case `Action` field? Not sure if the case action would need any change. (Even though cases that contain cancelled samples should not be able to start, but that would be another issue.)

Since we cancel the sequencing of samples, I think this should be a field in the `Sample` table.

This would be set manually as it currently is done by clicking `With selected > Cancel samples".

**Comment by henrikstranneheim** [comment]
Ok, thx for explaining, then this would be used to not show these samples as cancelled in the order? Or exclude them from the order when getting pre-existing samples? I guess there is no point including them in another order if they have been cancelled once.

**Comment by beatrizsavinhas** [comment]
Exactly, in the order portal we would want to exclude these cancelled samples from the list of existing samples so that the customers cannot place new orders with them (I've also written a related issue on this in the cg-ui repo https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/431).

**Comment by Vince-janv** [comment]
Having talked to @beatrizsavinhas I think adding a column (is_cancelled) to the sample table makes sense. We could then filter those out from the samples we return to the front-end. I think this should be on sample level rather than case level.

**Comment by seallard** [comment]
What does it mean that a sample is cancelled? Is it cancelled in one order specifically? 

Given that the sample can occur in multiple cases and orders, I'd advise against storing this information on the sample.

**Comment by beatrizsavinhas** [comment]
In general, a cancelled sample is a sample that cannot be analysed. Usually it is a sample where the prep or sequencing failed and, in most cases, we do not have any data for that sample. But we have received it, prepped it and worked on it so we still want to both bill it and keep track of the work we did - for traceability (and likely for other reasons), I don't think it is a good idea to simply remove cancelled samples from status db.

As a cancelled sample cannot be analysed, the analysis of existing cases connected to the sample should be prevented from starting and we also want to prevent customers from placing new orders with it. This is why I think proposed that this information is stored on sample level.

But please do suggest alternative solutions if you think they would work better!

**Comment by seallard** [comment]
Alright, I see - thanks 👍 

I think we should do some more technical refinement. Maybe there is a better way to model it. For instance, adding a separate `SampleStatus` table. Our sample model is already quite bloated.

**Comment by beatrizsavinhas** [comment]
We just had a sample that a customer requested to uncancel and we had to re-add all the information to the database manually, which is error prone - one more argument against deleting any data from StatusDB in this situation.
Reverting the cancelling action is also something we would like to have! Will add this to the description of the issue and suggested solution as well.

**Comment by diitaz93** [comment]
## Technical refinement
- Change the behaviour of the "cancel samples" functionality in statusDB so that it does not delete the sample
- Depends on https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/431
  - Do another refinement with production after this is implemented

**Comment by beatrizsavinhas** [comment]
> ## Technical refinement
> * Change the behaviour of the "cancel samples" functionality in statusDB so that it does not delete the sample
> * Add a filter for the case table that filters out cases containing cancelled samples so that they would never start the analysis
> * Depends on [Cancelled samples can currently be selected in new orders clinical-genomics-ui#431](https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/431)
>   
>   * Do another refinement when this is implemented

Just a small correction: The "cancel samples" functionality in statusDB does not delete the sample (I think the title of this issue is misleading, sorry), it deletes the CaseSample relationship and the corresponding Case too. We often have to delete the cancelled samples so the customers don't place more orders with them.

**Comment by seallard** [comment]
> > ## Technical refinement
> > 
> > * Change the behaviour of the "cancel samples" functionality in statusDB so that it does not delete the sample
> > * Add a filter for the case table that filters out cases containing cancelled samples so that they would never start the analysis
> > * Depends on [Cancelled samples can currently be selected in new orders clinical-genomics-ui#431](https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/431)
> >   
> >   * Do another refinement when this is implemented
> 
> Just a small correction: The "cancel samples" functionality in statusDB does not delete the sample (I think the title of this issue is misleading, sorry), it deletes the CaseSample relationship and the corresponding Case too. We often have to delete the cancelled samples so the customers don't place more orders with them.

So the annoying work you need to do is re-associate the sample with all cases?

**Comment by beatrizsavinhas** [comment]
> So the annoying work you need to do is recreate the cases and associate the samples with them?

Yes. And since we and the lab often manually delete the cancelled samples from the database (to prevent re-order), if, for some reason, we need them again, we have to re-create the samples manually too.

I will think of a better title and change it so it's more understandable.

Basically what we need is what I had written above in `Suggested solution`:
* No data is deleted from the database when cancelling a sample;
* Cancelling is reversible;
* There is a way to differentiate/filter away cancelled samples;
* (Additionally, no analysis should run if the case contains a cancelled sample)

**Comment by seallard** [comment]
It seems like production wants to keep all data for cancelled cases and samples.
The reason they delete samples manually is to prevent customers from placing orders with the cancelled samples.

Ideally, production wants a simple "un-cancel" action which restores all data for a case/sample. Not clear if it is a restore action for a case, for a sample or both.

Analyses should not be started for cancelled cases. Analyses should not be started for cases containing cancelled samples.

**Comment by islean** [comment]
Adding here but it might be more suited for a separate issue but the current cancel action seem to at times result in ghost orders without any cases/samples in them.

**Comment by Vince-janv** [comment]
Closing this issue as it has fulfilled the acceptance criteria and has crept our of the initial scope. Please create a new issue for the "un-cancel" action
