### ISSUE TITLE
Define nextflow context

### ISSUE THREAD

**Issue by sofstam** [Clinical-Genomics/cg#3066]
## Description

From a [review suggestion]( https://github.com/Clinical-Genomics/cg/pull/3059/files/daab0c4b54d3f172473b3c4c6b86f9d3a29162fd#r1535389818), some lines have been repeated across tests. It would be good to define them as nextflow context instead.

**Comment by ivadym** [comment]
I think we can close it. With the parametrisation those pytest are way cleaner now and we've defined a HK rnafusion API inside the pipelines specific context
