### ISSUE TITLE
Drop delivery table in cg?

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#3070]
## Description

We have added a delivery table to Trailblazer: https://github.com/Clinical-Genomics/trailblazer/pull/408.

We also have a delivery table in StatusDB: https://cg-statusdb.scilifelab.se/admin/delivery/.
It seems to only be used when creating a sample from the ordering. It usefulness is very unclear to me.

## Suggested solution

Drop the delivery table in cg.

## This can be closed when

Decision has been taken on keeping the table (with a clear motivation) or dropping it.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
The `Delivery` table was introduced in this PR https://github.com/Clinical-Genomics/cg/pull/10.
We have no logic related to reading from the table, so the only question is whether production relies on this table somehow for their work today. If not, I think we can safely just drop it.

**Comment by Vince-janv** [comment]
I think CG as an organisation should have a delivery table where we would store information about which files the customer wants delivered for an order. The current table seems to do something similar but is not used anywhere (I think). I vote that we remove it and reimplement a proper one in a future project
