### ISSUE TITLE
Duplicate case sample filters base queries

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#3073]
We have two base queries for case samples

```python
    def _get_join_case_sample_query(self) -> Query:
        """Return join case sample query."""
        return self._get_query(table=CaseSample).join(CaseSample.case).join(CaseSample.sample)

    def _join_sample_and_case(self):
        return (
            self._get_query(Case)
            .join(CaseSample, Case.id == CaseSample.case_id)
            .join(Sample, CaseSample.sample_id == Sample.id)
        )
```

They are slightly different, the latter starts from the case table. It is confusing that we have different base queries for these though. Tests break when replacing them with each other.

Find a way to ensure we use the same base query for the case sample filters, alternatively extract the filters relying on the `_join_sample_and_case` query.

**Comment by Vince-janv** [comment]
Closing since this is not causing any bugs
