### ISSUE TITLE
Script for marking archived files as archived

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#3075]
## Description

A maintenance job was running on the DDN catalogue server, deleting any jobs which were over a month old. This coupled with the restapi being down for a long time, meant that the ordinary way of updating job statuses was not feasible for files archived before the server going down. This issue suggests a script for marking the files with ongoing archiving status with an updated status.

All should 🤞 be archived.

## Suggested solution

```Python
import datetime
from pathlib import Path
from typing import List
from urllib.parse import urljoin

import requests
from housekeeper.store.database import initialize_database as initialize_hk_db

from cg.meta.archive.ddn.ddn_data_flow_client import DDNDataFlowClient
from cg.models.cg_config import DataFlowConfig
from housekeeper.store.store import Store as HKStore

from housekeeper.store.models import Archive

initialize_hk_db(<DB_URI>)

housekeeper_api = HKStore(root="<root_dir>")


data_flow_config = DataFlowConfig(
    database_name="****",
    user="****",
    password="****",
    url="https://cg-df-cat.scilifelab.se/restapi/",
    local_storage="gpfs@Hasta:",
    archive_repository="archive@CGStage:/",
)

data_flow_client = DDNDataFlowClient(data_flow_config)
ongoing_archivals: list[Archive] = housekeeper_api.get_ongoing_archivals()

headers = dict(data_flow_client.headers, **data_flow_client.auth_header)

url_for_browser_handle = urljoin(data_flow_client.url, "datamanagement/repositories/<production_id>/browser")
url_for_browse = urljoin(data_flow_client.url, "datamanagement/repositories/<production_id>/browse/")
url_for_close_browser = urljoin(data_flow_client.url, "datamanagement/repositories/<production_id>/browser")


browser_handle_response = requests.get(
    url=url_for_browser_handle,
    verify=False,
    headers=headers
)
browser_handle = browser_handle_response.json()["browserHandle"]

for archive in ongoing_archivals:
    sample_name: str = archive.file.version.bundle.name
    body = {"browserHandle": browser_handle, "path": f"/{sample_name}"}
    response_body = requests.post(
        url=url_for_browse,
        verify=False,
        json=body,
        headers=headers
    ).json()
    file_names: list[str] = [file["name"] for file in response_body["object"]]
    if Path(archive.file.path).name in file_names:
        print(f"File {Path(archive.file.path).name} is archived!")
        archive.archived_at=datetime.datetime.now()
        housekeeper_api.session.add(archive)

requests.delete(
    url=url_for_close_browser,
    params={"browserHandle": browser_handle},
    headers=headers,
    verify=False
)

housekeeper_api.session.commit()
```

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
Make sure to change the repo so that it is not stage (`archive_repository="archive@CGStage:/"`).
So for a sample with 8 files we will browse the same file 8 times? Probably not a problem though since this is just a script...

Otherwise this looks great!

**Comment by islean** [comment]
> Make sure to change the repo so that it is not stage (`archive_repository="archive@CGStage:/"`). So for a sample with 8 files we will browse the same file 8 times? Probably not a problem though since this is just a script...
> 
> Otherwise this looks great!

Oh that parameter is not even used afterwards. But good spotting!

And yeah, the script is not optimized but it runs in maybe 10-20 seconds (tried with only prints) so I do not think it is worth it changing that it goes through the whole sample for each file.

**Comment by islean** [comment]
Run in production - all files were successfully archived and are now marked as such.
