### ISSUE TITLE
Create Taxprofiler order flow

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#3076]
### User story:
As a customer, I would like to be able to analyse metagenome samples with taxprofiler,
so that I don't have to analyse my own FASTQ files.

### Acceptance criteria:
- A customer should be able to place orders to be analysed with taxprofiler
- This option should only be available for metagenome samples
- The case added to status_db should have `data_analysis=taxprofiler`
- The data_delivery options `ANALYSIS` and `FASTQ_ANALYSIS`

### Priority:
- Taxprofiler will be ready for production (other than this) within a month and should then be orderable

**Comment by Vince-janv** [comment]
## Technical implementation
### cg
- In orderform 1508 add the data_analysis option taxprofiler
### clinical-genomics-ui
- In orderTypes add entry for taxprofiler.
```
  {
    text: 'To be decided by @annagellerbring  and @sofstam',
    orderType: <new constant pointing to "taxprofiler">,
    applications: ['wgs'],
    dataAnalysis: <new constant pointing to "taxprofiler">,
  }
```
- In deliveryOptions add entry for taxprofiler.
```
taxprofiler: [deliveryOptions.analysis, deliveryOptions.no_delivery],
```
- The rendering and validation should be the same as for metagenome orders

**Comment by islean** [comment]
Added to blocked since it is unclear who creates the order form and we have no info on what to display in the FE

**Comment by diitaz93** [comment]
Finished 🥳
