### ISSUE TITLE
Non-existent run parameters file raises an error

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#3083]
## Description

If there is no run parameters file in a flow cell directory, the property `run_parameters_path` from `FlowCellDirectoryData` raises an error. This behaviour is counterintuitive as it should probably return None.

## Suggested solution

SD: Modify the property and the codebase so that it returns None when there is no RunParameters file.

Other solutions are welcome

## This can be closed when

The property has been modified to return None and the codebase modified to cope with this change

## Blocked by

*N/A*

**Comment by Vince-janv** [comment]
Not causing a bug and will therefore not be patched in the near future
