### ISSUE TITLE
Re-runs of cases with a different workflow

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#3086]
## Description

We have had an instance wherein a customer placed an order containing old FASTQ cases. They were now being requested to be run with MIP-DNA. Since the order was mip, the cases' actions were set to "ANALYZE", which meant that they were picked up for automation everytime. But since the cases were FASTQ, there is no start command which would trigger a decompression. Hence the spring files were never decompressed whence the upload failed. (At least that is my understanding). 

What should we do in these instances?

## Suggested solution

There are a couple of ways we could handle this:

1. Do not allow these re-runs. If chosen, should all cases be forced to use the same workflow? Or is it specifically for fastq?
2. Allow these re-runs and add a decompression step in the fastq command.
3. Allow these re-runs and do even heavier modifications such as changing the workflow on case-level in status db.
4. Other alternative?

## This can be closed when

These re-runs either return an error for the customer or is handled properly.

**Comment by diitaz93** [comment]
How often does this happens? is it something that could be handled manually or needs automation? How did production solve the problem?

**Comment by Vince-janv** [comment]
I think the issue stems from the fact that when one searches for existing cases in the orderportal all cases, regardless of workflow are returned. I think that we should only return cases that match the order type the customer is trying to place. The endpoint in cg `families_in_collaboration` has that functionality, but we don't pass workflow as a parameter

**Comment by seallard** [comment]
I don't think we should store the workflow on a case, it does not make sense. A case is a collection of samples and it should be possible to run through whatever suitable workflow. The workflow only belongs on the order and corresponding analyses. So I think the best solution is to only rely on the workflow specified on the order.

We could introduce a new column where we delimit which workflows that are possible to run for a case. Alternatively on the sample level instead.

**Comment by Vince-janv** [comment]
### Decision:
- Only return cases (from the back-end) that match the current order-type

**Comment by seallard** [comment]
Problem pointed out by @islean: customers can select the original workflow, the case and then change to a new workflow.

If we are trying to introduce a rule that customers are not allowed to resuse cases for different workflows, adjustments are probably required in several places.
