### ISSUE TITLE
Merge OF for external samples and MIP/Balsamic to avoid burden of maintaining both

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#310]
As a OP DEVELOPER, I want external samples to use OF 1508 so that the OF for external samples don't diverge from OF 1508.

Problem: 
The OF for external samples is not the same as OF 1508, but 1508 is mainly use for MIP samples and the requirements for MIP samples should be up to date in the OF for external but it is forgotten over and over. 

Steps to reproduce
  1. Add new MIP requirement in OF 1508
  1. Open the OF for external samples

Expected outcome: 
The new requirement is included in the OF for external samples

Actual outcome:
The two OFs diverged

Suggested solution:
* Change the OP to use 1508 as external OF
* Change susy to point to the 1508 for external
* Remove the AM document for external samples
* Add information about external samples to 1508 in AM 

Questions: 
Q: 
A:

**Comment by Mropat** [comment]
Feature will be addressed in new orderportal
