### ISSUE TITLE
No TB analysis is created for cases with no associated order even though jobs start running

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3152]
## Description

When starting a case that, for some reason, does not have an associated order, the start command fails with the following error:

```
Could not run analysis: list index out of range
Aborted!
```

But the jobs are created and start running while no analysis is created on Trailblazer.

## Suggested solution

* Prevent the analysis from starting in situations like this and print a more explanative error.

## This can be closed when

* Analyses that do not have an associated order are prevented from starting and the error is communicated to the user.

## Blocked by

Nothing, to my knowledge.

**Comment by islean** [comment]
A bit uncertain if we just want to print a warning. Given that such cases should not be able to exist, I feel like we should not implement checks for it, rather we should get to the bottom of why these cases were malformed in the first place.

**Comment by henrikstranneheim** [comment]
@beatrizsavinhas How could this case be created? We should make sure it cannot happen.

**Comment by beatrizsavinhas** [comment]
This happened with cases that were created manually by us in production, which happens somewhat frequently. I see that now though, when creating a new case with the cli command `cg add case`, the new case is automatically connected to an order, so this is not an issue anymore. 

https://github.com/Clinical-Genomics/cg/blob/64c2e2eccecfd951bcda0e2dec0a08c8b307a67f/cg/cli/add.py#L296

**Comment by henrikstranneheim** [comment]
Great! Thx!
