### ISSUE TITLE
Add tissue check before uploading to loqus

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/cg#3159]
## Description

After discussiong with @moahaegglund it seems like cg only uses customer id to decide which loqus database to upload the vcf to. Sometimes tumour samples are sent through cust002 and it would be preferable to not have that sample uploaded to the germline database.

## Suggested solution

Add a check to see if the sample is a tumour sample before uploading to loqusDB. 

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
We also have this for MIP-DNA uploads:

```python
        if case.tumour_samples:
            LOG.error(f"Case {case.internal_id} has tumour samples. Cancelling upload.")
            raise LoqusdbUploadCaseError

**Comment by jemten** [comment]
Ah, that looks like the check we wanted. Right @moahaegglund?

**Comment by ivadym** [comment]
> Ah, that looks like the check we wanted. Right @moahaegglund?

But do we have any cases that shouldn’t have been uploaded to Loqusdb? If that's the case, you can send me those, and I can look more into what's going on

**Comment by moahaegglund** [comment]
Good that we have this check, we missed in the code when we looked the other day. 
A question to this is if it would be good to also include a check on the sample source from LIMS and only allow certain sources to be uploaded to loqusDB?
I do not know how frequent this is but we have just had a sample that's been reanalysed in balsamic instead of mip-dna as it was in the first analysis a couple of years ago. We marked it as tumor now, it's an exome and sample source is `tissue (FFPE)`.

**Comment by henrikstranneheim** [comment]
I wonder if `FFEP` would be a problem? @dnil @ivadym @jemten 

Really important to keep the cancer samples out. Do we need to improve any documentation? @moahaegglund @karlnyr

**Comment by dnil** [comment]
Yes, I agree on blocking FFPE. It is different enough from our usual blood samples, and will often be from tissues with expected non-constitutional mutation load. It seems they are not always flagged as tumor when intended for MIP analysis. They certainly also not just from solid tumors: e.g. overgrowth syndromes etc.

We can also open a new customer for KGG for somatic work, and repeat the wish to expect constitutional samples from `cust002`.

**Comment by ivadym** [comment]
I think it also makes sense to bock them for Balsamic, but I'll bring it to a cancer refinement

**Comment by ivadym** [comment]
We've decided to block them for Cancer uploads too.

After merging https://github.com/Clinical-Genomics/cg/pull/3215, any cases with a sample source in LIMS containing `ffpe`/`FFPE` won't be uploaded to Loqusdb.
