### ISSUE TITLE
Update LIMS API

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#3163]
## Description

The LIMS API hasn't been updated for a while, and it needs some attention since it doesn't follow the current coding guidelines.

Some of the issues we've identified so far:
- Outdated methods and method names.
- Interchangeable use of the LIMS API methods and sample object properties caused by poor type hinting (?).
- Lack of constants to describe the UDF fields.

Review comments (https://github.com/Clinical-Genomics/cg/pull/3153):
- Do we still have anything in AM? Remove `DocumentationMethod.AM` support after checking with AL.
- What's the `PA1` constant? Can we make it a named variable?

## Suggested solution

Address the issues pointed out above.

## This can be closed when

- [ ] LIMS API is up to date with our code practices.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by Vince-janv** [comment]
Indeed, this module is in need of some love. We will not refactor it as a stand alone project. But it may be replaced if new LIMS functionality needs to be added.
