### ISSUE TITLE
Revise behaviour of get_aggregated_panels, document behaviour and refactor if needed

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#3167]
## Description

get_aggregated_panels has some inconsistent behaviour. This method needs to be revised and the logic documented. 

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
Can you describe the inconsistent behaviour that you have observed?

added to refinment for 19-06-2024

**Comment by henrikstranneheim** [comment]
Refactored here: https://github.com/Clinical-Genomics/cg/pull/3383

**Comment by Vince-janv** [comment]
Solved in #3383
