### ISSUE TITLE
Upload of reruns from vcf to Scout works with reduced analysis output

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#317]
When uploading rerun cases to Scout some analysis files will be missing. We need to be able to update the case with the new info while keeping the old basic info

**Comment by barrystokman** [comment]
Do we only need to merge the complete bundle with new light bundle during the upload?

**Comment by Mropat** [comment]
Stale, needs new clear definition if this is still necessary to solve
