### ISSUE TITLE
NEXTFLOW_WORKFLOWS constant(s) while developping pipelines

### ISSUE THREAD

**Issue by rannick** [Clinical-Genomics/cg#3170]
## Description

To avoid listing all the nextflow pipelines in the tests, a constant is defined. However while a new pipeline is added, not all tests should be executed

## Suggested solution

i) Use two constants NEXTFLOW_WORKFLOWS_DEV and NEXTFLOW_WORKFLOWS
ii) Come back to a explicit list
iii) Adapt tests so they do not fail if a command is not yet implemented 

At the moment i) is implemented (https://github.com/Clinical-Genomics/cg/pull/3128)

## This can be closed when

Solution i) is proving good enough or a decision is taken and implemented providing an alternative solution to the issue

**Comment by samuell** [comment]
What is it that happens, if a command is not fully implented? I thought that if a workflow command is added without subcommands, it should not fail any tests?

**Comment by rannick** [comment]
If the test execute the command but the command is not implemented, the test will fail

**Comment by rannick** [comment]
"""
cg workflow jasen config-case funkitten
Usage: cg workflow jasen [OPTIONS] COMMAND [ARGS]...
Try 'cg workflow jasen --help' for help.

Error: No such command 'config-case'.
"""

**Comment by samuell** [comment]
Great, thanks for the clarification!

But off arm my spontaneous reaction is that then either there is something wrong with how the tests are executed, or else with the strategy of iteratively adding pipelines.

I'm quite worried that having dev versions of constants is only making things more confusing.

I would personally advocate for something either being regarded as implemented, or not, although perhaps regarding different parts.

**Comment by samuell** [comment]
But sure, if this is a way to get through the tests for now, I guess that is fine.

But in the long run, I think it would be preferably to solve the problem more deeply.

**Comment by ivadym** [comment]
We went with this suggestion from HS at the end: https://github.com/Clinical-Genomics/cg/pull/3128#discussion_r1582717912. Closing it!
