### ISSUE TITLE
Incorrect analysis started_at fields in Statusdb

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#3183]
## Description

We've been incorrectly populating the `started_at` field in Statusdb. This field is supposed to be derived from the creation date of the `<case_id>_deliverables.yaml` file. For MIP, the deliverables file is created at the start of the analysis, while for Balsamic, Nextflow pipelines, etc., it's generated at the time of storing the bundle in Housekeeper.

## Suggested solution

Implement workflow-specific `get_bundle_created_date` methods to retrieve the creation date of the config files, for example.

## This can be closed when 

`analysis_at` is updated correctly for the following workflows:
- [ ] Balsamic
- [ ] Nextflow pipelines (Rnafusion, Tomte, Taxprofiler, Raredisease)
- [ ] Mutant (?)

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
Do we use the analysis table in status db for anything?

**Comment by henrikstranneheim** [comment]
> Do we use the analysis table in status db for anything?

As input and trigger for the store in HK I think. This logic should be refactored.

**Comment by ivadym** [comment]
> Do we use the analysis table in status db for anything?

It also appears that we're depending on the `analysis_started_at` field for extracting files from HK (MIP coverage files, delivery report) and filtering (clean files from HK), which has created a peculiar dependancy between `created_at` in HK and analysis `started_at` in Statusdb

**Comment by ivadym** [comment]
Refinement:
- This issue is part of a larger problem where we use dates for versioning our bundles.
- It's best to tackle this comprehensively by including it as a task in the refactoring of the data models/analysis table project.

Let's leave this issue open until we refine that project.

**Comment by Vince-janv** [comment]
Here is a milestone touching upon these database models:
https://github.com/Clinical-Genomics/improve-order-flow/milestone/1

**Comment by Vince-janv** [comment]
We will not adress this in the near future. Closing
