### ISSUE TITLE
Avoid MIP analysis of tumor samples

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#320]
As a clinical genomics production member, I want MIP avoiding tumor samples so that I don't have to remove them from Scout

Problem: 
When a customer orders MIP+Balsamic analysis but only submits one sample, marked as tumor sample, this sample is run through MIP and we have to remove it from Scout since it should not be included since it is a cancer sample

Note: Leukemia samples should be run through MIP

Steps to reproduce
1. order MIP+Balsamic
1. Add only tumour sample
1. submit

Expected outcome / suggested solution:
Only Balsamic analysis is run for the sample, no MIP analysis

**Comment by hassanfa** [comment]
More context I encountered today:

If there is a RNA sample and it is tagged as tumor `is_tumour` on status db, it is tagged as balsamic. Will it be linked to balsamic analysis path? It might be intended behavior, but with missing RNA fastq files linked, `cg analysis link -f` fails. Please see issue #395  for more context.

**Comment by emiliaol** [comment]
@patrikgrenfeldt Is this still an issue? Add to backlog?
