### ISSUE TITLE
Speedup test action

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#3214]
We could halve the execution time of our test action in cg for 9 $/month. Should we do it?

## Background
- **Current Average Execution Time:** 3 minutes per CG test action (with 2 cores).
- **Frequency of Execution:** 750 times per month (upper bound based on 9,000 runs in total).

- **Optimization Strategy:** Double the number of cores to halve the execution time.
- **Expected Execution Time:** 1.5 minutes per run after doubling the cores.

### Cost
- **Cost for 4-core Linux Runner:** $0.016 per minute.
- **New Execution Time per Month:** `750 runs/month * 1.5 min/run = 1,125 minutes/month`.
- **Projected Cost per Month:** `1,125 min/month * $0.016/min = $18/month`.

This assumes that we run the action 750 times per month, which is not true. We probably run it at most half of that. So the monthly costs would be more like 9 $.

We could prevent abuse by capping the total minutes, maybe also restricting who is allowed to open a PR/execute actions.

**Comment by vwirta** [comment]
The cost is negligible, so if this helps productivity and increases the ease of work, then we should go for this.

**Comment by henrikstranneheim** [comment]
👍

**Comment by Vince-janv** [comment]
### Decision
- Set to 8-cores and see how much time it shaves

**Comment by henrikstranneheim** [comment]
@seallard was 8 cores good enough?

**Comment by seallard** [comment]
> @seallard was 8 cores good enough?

Locally there was no benefit going with more than 4, so we provisioned that. We have still not been able to get the action to use it properly. @Vince-janv  and I will look at it today (?)

**Comment by seallard** [comment]
@henrikstranneheim did some tests with Vincent now.

The free runner in a public repo already has 4 cores, doubling it to 8 provided a 2x speedup.
![image](https://github.com/Clinical-Genomics/cg/assets/33596072/becbe573-a015-464e-91cc-f68cd5d1b661)

 In terms of costs, this would approximately be 25 $/month. I think we should go for it.

**Comment by henrikstranneheim** [comment]
Great 👍
