### ISSUE TITLE
Calculation of case sequencing QC slows down /orders

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#3223]
## Description

The calculations done by the `QualityControllerService` are expensive, meaning that usage of the methods in the web services, e.g. CiGRID, adds quite a lot of latency. As an example found in #3198, calculating the number of cases failing sequencing QC within orders roughly doubles the response time when rendering the orders page. Since this data is useful, we should think of a better way to calculate this.

## Suggested solution

Easiest would probably be to save this data on case and sample level in status db. Would require refinement on when these values should be set. At the end of demultiplexing?

## This can be closed when

Finding cases which fail sequencing qc can be done quickly.

**Comment by seallard** [comment]
I think the calculation is fine as longs as we store the result

**Comment by seallard** [comment]
Given that the sequencing QC is calculated per case (and pass on individual samples but not on the case level) and the analyses are started per case (given that the sequencing QC passes), we should store the overall case sequencing QC on the case. We can also store the sample QC on the samples.

**Comment by seallard** [comment]
### Implementation plan

- Add `sequencing_qc_status` to case model with enum `pending`, `passed`, `failed` (default is `pending`).
- Add new CLI command which picks up cases for which the qc needs to be done and updates the `sequencing_qc_status`.
- Refactor old logic to decouple the sequencing qc from the other logic and just filter based on the stored `sequencing_qc_status`.

**Comment by seallard** [comment]
Leaving this for a future project

**Comment by seallard** [comment]
This is very straightforward to implement, we just need to have a meeting to get everyone on the same page and as to ensure the required PR:s do not get blocked.

**Comment by seallard** [comment]
Rename field on case to `ready_for_analysis`.

**Comment by seallard** [comment]
Pick up the same as `start-available`.
Wait with changing the `start-available` logic to use the cached database value.

**Comment by seallard** [comment]
Replacing the calculations with db queries brings down the response time for 500 ms. I think the overall implementation of the order status summary logic needs to be revisited and a better design for tracking the status of our samples and statuses is merited. See https://github.com/Clinical-Genomics/cg/issues/3452.
