### ISSUE TITLE
LoqusDB instances for cancer and germline cancer in place

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#325]
## Description

Currently, `cg upload observations` only uploads to one loqusDB instance.

## Suggested solution:
(We should update these)
- Have two additional loqusDB instances: `loqusdb_cancer` and `loqus_germline_cancer`
- Samples with the `Analysis Type = MIP + Balsamic` and `Is Tumor = no` should go to `loqusdb_germline_cancer`.
- Samples with `Analysis Type = MIP + Balsamic` and `Is Tumour = yes` + samples with `Analysis Type = Balsamic` should go to `loqusdb_cancer`.

## This can be closed when

- [ ] variants get uploaded to corresponding locks instance depending on analysis type
- [ ] scout fetch information from loqus instance depending in the analysis type

**Comment by emiliaol** [comment]
@henrikstranneheim  Something we want to add to the backlog? Or is it already another issue for this?

**Comment by henrikstranneheim** [comment]
I will add it to the backlog, but it is not urgent

**Comment by dnil** [comment]
Ping @henrikstranneheim @hassanfa @moonso - time to just do this? Looks something like medium urgent, highly useful, and not very difficult, but please modify according to your scale!

**Comment by dnil** [comment]
(We keep getting requests and questions on this from the cancer side users..)

**Comment by moonso** [comment]
It is definitely doable but will need some work for the automation parts

**Comment by dnil** [comment]
@hassanfa and I have convinced ourselves we only need one `cancer` instance for now. Ideally this will then be extended with a rich meta data collection for the variants at a later stage.

**Comment by Mropat** [comment]
Exists as a project in project planning
