### ISSUE TITLE
multiqc_report not delivered for mip-dna cases

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3258]
## Description

When delivering files, if `--delivery-type mip-dna` the `multiqc_report` is not delivered.

## Suggested solution

Add "multiqc-html" tag to "MIP_DNA_ANALYSIS_CASE_TAGS."

## This can be closed when

The `multiqc_report` is delivered when `--delivery-type mip-dna`.

## Blocked by

Nothing.

**Comment by islean** [comment]
Can this be closed @beatrizsavinhas ?

**Comment by beatrizsavinhas** [comment]
Yes! Thanks for the notification!
