### ISSUE TITLE
Alter the ordering of microbial samples

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#3276]
## Description

We need to change the order form for microbial samples to align with other ordering logic, and make delivery of microbial sample data more logical for production members and customers. Thus, we need to create two types of microbial workflows, one where we do the typing and quality report - which requires customers to give us a reference, and one where we only sequence the microbial samples for the customers. After discussions with SVA, the current QC report is of little value, so diverging away from the current flow, and decoupling us a bit more from microSALT is a good decision. Further, with this logic, we would also be able to remove some strange delivery types tailored for only microSALT and change the microbial deliveries to use delivery types like `fastq` and `analysis` like other workflows. 

### New microbial orders

New order: `Sequencing of Microbial WGS` - We do not require the customer to give the references of the samples. It would be similar to the `Sequencing of clinical samples` order. The difference is that the application tags in the `Sequencing of Microbial WGS` would include the `MWR/MWX/VWR` apptags. We are also adding new application tags in [this project](https://github.com/Clinical-Genomics/project-planning/issues/537), so the orders must include them as allowed application tags.

New order: `microSALT typing and quality report (sequencing/existing samples)` - This is the same order as we have for `Microbial WGS`, but changing the name, and in the future, when we implement `JASEN` the swap will be more clear for customers.

### Removal of delivery types

Remove the following delivery types from `cg`:

- FASTQ_QC
- FASTQ_QC_ANALYSIS

### Change delivery types for microSALT

Change the delivery types available to microSALT to be:

- ANALYSIS
- ANALYSIS + FASTQ

## This can be closed when

- The customer can choose whether to analyse microbial samples or not when ordering. 
- Production only has one delivery option (analysis) for the microbial workflow

## Blocked by

- Analysis of VWG samples in microSALT, I am uncertain if they need the QC report. It is uncertain if they do care about it today. If they do, we would need to somehow make an order for microsalt, where either in the delivery or in the workflow, it is clear that we are to only care about the quality report.

**Comment by karlnyr** [comment]
Will add this to the refinement for 5th of June if approved in the LGM meeting on the 29th.

**Comment by beatrizsavinhas** [comment]
@karlnyr I believe the customers that order VWG samples look through the QC report!
I just handled a ticket of VWG samples where there was something wrong with attaching the QC report to the email and they wrote to us asking to send the file again - [Ticket #324745](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=69427).

**Comment by karlnyr** [comment]
I do not think that is the way to go. I will have a talk with the customer ordering VWG, because the current analysis that we are offering them is shoehorned into their needs - we want to decouple ourselves from microSALT, and this is a way forward to that. The discussion on LGM is to go with delivery types ANALYSIS, and ANALYSIS + FASTQ, and then FASTQ as well, but when only FASTQ is ordered we do not run microSALT. Further, VWG will not be an option when ordering microSALT analysis.

**Comment by ChrOertlin** [comment]
# Refinement 12-06-2024

Break up this issue into smaller work items with defined scope and outcome. @karlnyr and @Vince-janv

**Comment by Vince-janv** [comment]
As previously mentioned there are two issues here:
1. Microsalt delivery options are different than all other workflows. This creates confusion. Only Analysis an ANALYSIS + FASTQ should be available (same as for other workflows)
2. Microbial samples should be able to be ordered as FASTQ orders. Currently this is only supported for human and metagenome samples.

I will create separate issues to track these

**Comment by Vince-janv** [comment]
Split into:
https://github.com/Clinical-Genomics/cg/issues/3339
https://github.com/Clinical-Genomics/cg/issues/3338
