### ISSUE TITLE
Let users specify if eluation buffer contains EDTA in OF 1508

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#328]
contact: @annaengstrom 

As a lab person, I want customers to specify if the eluation buffer contains EDTA or not so that I know if the sampels need to be bead cleaned or not.

Problem: 
The customers sometimes send in samples that were eluated with EDTA and we need to know so we can do the required cleaning steps and charge the customer 

Steps to reproduce:
  1. Let the customers order balsamic samples

Expected outcome:
The EDTA eluation buffer information is in LIMS

Actual outcome: 
There is no information on EDTA in eluation buffer

Suggested solution: 
Let the customers specify in the OF (and OP) if they used EDTA eluation buffer

Questions: 
Q: Do we need this information for all samples ordered with OF 1508?
A: No only those with Application starting with EX? and PAN

**Comment by annaengstrom** [comment]
Adding @annagellerbring to the thread.

This is relevant for app tags EXO/EXT/PAN.

**Comment by emiliaol** [comment]
@patrikgrenfeldt Is this what's being implemented now?

**Comment by annagellerbring** [comment]
Waiting only for MB to update new app-tags in statusdb.

**Comment by patrikgrenfeldt** [comment]
Japp detta är implementerat :)

Den ons 15 maj 2019 09:10emiliaol <notifications@github.com> skrev:

**Comment by patrikgrenfeldt** [comment]
Resolved by #354
