### ISSUE TITLE
Add flexibility to the sample sheet validation

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#3288]
## Description

This week a flow cell needed to have manual modifications to its sample sheet, in a way that it failed the implemented validation. This modified sample sheet will be needed when the flow cell is set for re-demultiplexing. However, at the start of the demultiplexing, the automation overwrites any sample sheet (in Housekeeper or in the Flow cell directory) that fails validation with a new one. This means that the modified sample sheet can't be saved in Housekeeper or in the flow cell directory as a normal sheet.

## Suggested solution

We most likely need to allow sample sheets that fail validations for these cases somehow, but it is unclear how.

## This can be closed when

This flow cell can be re-demultiplexed without errors

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by diitaz93** [comment]
Set for refinement 2024-05-29 @Karl-Svard @karlnyr

**Comment by diitaz93** [comment]
I understand that the modified sample sheet has different copies of the same sample in the same lane, but with different sets of indices. This will make the sample sheet fail validation in the function `validate_samples_are_unique`

**Comment by ChrOertlin** [comment]
@diitaz93 I will move this to the ready column in trocadero.

**Comment by diitaz93** [comment]
## Acceptance criteria

- [ ] The old Bcl2Fastq sample sheets should still be overwritten
- [ ] BCLConvert sample sheets that fail validation should not be re-generated
- [ ] Demultiplexing should be possible with a manually modified BCLConvert sample sheet
