### ISSUE TITLE
Not exiting multi-case upload process when one gens upload fails

### ISSUE THREAD

**Issue by raysloks** [Clinical-Genomics/cg#3307]
As mentioned in https://github.com/Clinical-Genomics/cg/issues/3197, it'd be good to not exit the upload process entirely when singular Gens samples fail to upload to a duplicate key error.

I'm not entirely sure how to accomplish this in the best way. Would simply putting a `try except CalledProcessError` somewhere like here https://github.com/Clinical-Genomics/cg/blob/985acfbf7bf60718cefc3b54bf9ee3cc74d70662/cg/apps/gens.py#L45 be enough?

**Comment by islean** [comment]
Hmm I think a try/except would be nice, but I would rather have it where the samples are being looped through. There could be benefits to having an error raised from GensAPI.load which is caught by the upload_to_gens method, say if you would want a method which uploads only a single sample. There it might make sense that an error is raised.

**Comment by henrikstranneheim** [comment]
@raysloks Sounds good! Let's make it so.
