### ISSUE TITLE
Wrong links in hk after `cg transfer flowcell` on an FC X on hasta

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#331]
There seems to be a problem with adding links to HK for an (or all?) X flowcells on hasta. The link points to a rasta path:

![Skärmavbild 2019-04-11 kl  16 01 40](https://user-images.githubusercontent.com/12113434/55963387-05cfa700-5c73-11e9-8630-ca5f4f4c354a.png)

I tried solving it by deleting the files in HK `housekeeper delete file` and adding them again but with the same result.

**Comment by ingkebil** [comment]
Did you include the right screenshot? Those links are hasta links, right?

wkr,
Kenny
--
Composed and sent on the road

**Comment by patrikgrenfeldt** [comment]
Last line in the pic seems to point to /mnt/hds.. something

Den tors 11 apr. 2019 16:30Kenny Billiau <notifications@github.com> skrev:

> Did you include the right screenshot? Those links are hasta links, right?
>
> wkr,
> Kenny
> --
> Composed and sent on the road
>

**Comment by ingkebil** [comment]
Alright. Looking into it.

**Comment by ingkebil** [comment]
Did you have to fix the links yourself?

**Comment by ingkebil** [comment]
As now, the links are pointing to the right files.

**Comment by ingkebil** [comment]
Is this still happening?

**Comment by patrikgrenfeldt** [comment]
@emiliaol can we close this issue?

**Comment by emiliaol** [comment]
Yes, let's close this issue :D
