### ISSUE TITLE
Support delivery message for "analysis" type

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#3312]
As a prodbioinfo
I want to get a delivery message for cases with `analysis` as delivery option
So that I don't have to write it manually for each case and I can speed up delivery.

# Acceptance Criteria

- [ ] When clicking on `Copy delivery message` on cigrid for a case with Analysis as delivery type, I get a delivery message

# Notes

Template for delivery message:
```Shell
Hello,﻿
The analysis files are currently being uploaded to your inbox on Caesar:
/home/custID/inbox/TICKET_ID
```
# Implementation plan

- [ ] Work item 1
- [ ] Work item 2

**Comment by seallard** [comment]
What should the format be for the delivery message? Does it vary depending on workflow or is it always the same for the `analysis` delivery option?

**Comment by fevac** [comment]
The pipelines I work with (balsamic, rnafusion, tomte) would have the same behaviour regardless of the workflow but I'm not familiar with all of them. @beatrizsavinhas has a better understanding and might know if this is the same for all workflows

**Comment by seallard** [comment]
Alright, nice! 👍 Would be great to have an example template for the messages

**Comment by islean** [comment]
> The pipelines I work with (balsamic, rnafusion, tomte) would have the same behaviour regardless of the workflow but I'm not familiar with all of them. @beatrizsavinhas has a better understanding and might know if this is the same for all workflows

The problem is not with the workflow, it is with the delivery type. You would get precisely the same behaviour with balsamic if it had the same delivery type, so extrapolating from other workflows is not really possible here.

**Comment by beatrizsavinhas** [comment]
This issue has already been reported here as well: https://github.com/Clinical-Genomics/cigrid-ui/issues/632

The format would be the same as the already existing template for `data_delivery` types which include `analysis`. Added to the notes above in the user story description.

**Comment by fevac** [comment]
that's great! @seallard @islean do you need more info, or do you understand what's needed?

**Comment by seallard** [comment]
> that's great! @seallard @islean do you need more info, or do you understand what's needed?

No, the acceptance criteria are clear. We need to do a tech refinement before it is ready to be implemented.

**Comment by ChrOertlin** [comment]
Added to refinement 19-06-2024
