### ISSUE TITLE
Pages in the `Sample Lane Sequencing Metrics` table are not disjoint

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3316]
# Describe the bug

The pages in the `Sample Lane Sequencing Metrics` table are not disjoint.
The same sample/lane entries appear in several pages.

# To Reproduce Steps to reproduce the behavior:

- Search for flow cell in the `Sample Lane Sequencing Metrics`
- Sort by `Flow Cell Lane Number`
- Entries of samples from Lane 1 in page 1 appear duplicated in page 2

When searching for a sample in the same table, there is only one entry per lane.

# Expected behavior

An entry should appear in one page only.

# Additional context

**Comment by ChrOertlin** [comment]
The sample lane sequencing metrics table will be discontinued as part of a project within a shorter time frame.
Does this bug cause any issues other that displaying information twice? If not I'd propose to close this issue, since it will solved soon.

**Comment by ChrOertlin** [comment]
Closing
