### ISSUE TITLE
Concise re-analysis of old cases

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/cg#3318]
As a Bioinformatician,
I want to reduce re-analysis time of old cases,
So that load on Hasta caused by re-analysis is reduced.

As a Clinicians,
I want to receive my re-analysis cases faster,
So that the case can be processed in a shorter amount of time.

# Acceptance Criteria

- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria 3
...

# Notes
During the ESHG2024 conference a re-analysis solution was presented where bam/cram or VCF files were used as input, where the main change to the analysis was an updated OMIM panel and updated databases. For CG this would speed up the data analysis, and hopefully reduce the number of errors which are often encountered by production when dealing with old cases.

- Additional information.
- Dependencies.
- Related user stories.

# Implementation plan

- [ ] Work item 1
- [ ] Work item 2

**Comment by ChrOertlin** [comment]
added to refinement meeting on 19-06-2024

**Comment by Vince-janv** [comment]
For this to be done, there first needs to be a way to start the pipelines we run at CG from certain checkpoints. I suggest creating an issue for this in the project-planning repo as it needs a lot of coordination between multiple teams. Closing here for now
