### ISSUE TITLE
Automatic decompression of samples when uploading

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#3319]
Feature request from @RasmusBurge-CG

When I run `cg upload` for a case, it fails with an error about a single sample being compressed. Then I go and manually decompress that specific sample and try uploading again. However, it will most likely fail with a new error about another sample in the case being compressed. Repeat ad infinitum. 

It would be great if decompression of samples was done automatically in the upload command. I don't want to have to manually decompress the samples one by one because it is super annoying! 

# Clarification
Sample files (FASTQ) are compressed after a certain amount of time. Any case where the upload fails because of sample compression is an old case. 

When customers want old files re-delivered, they have to contact production via the ticketing system

**Comment by seallard** [comment]
Question: why can we not upload compressed files?

**Comment by henrikstranneheim** [comment]
What are we uploading to that needs fastq files?

**Comment by Vince-janv** [comment]
@Clinical-Genomics/prodbioinfo 
One can use `cg decompress ticket` and `cg decompress case` to decompress multiple samples at ones and thus circumvent the issue. Is that acceptable?

Do you think that an updated error message and updated documentation would help

**Comment by diitaz93** [comment]
Closing due to lack of response
