### ISSUE TITLE
cg link for balsamic links in cancer root directory

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#332]
As a balsamic developer, I want to gather linked fastq files in a directory so that I when I want to check all the cases I can only search in a single directory.

Problem: 
Right now `cg analysis link -f purerhino` tries to link into the following directory for MIP: `/home/proj/stage/rare-disease/cases/purerhino`. But for BALSAMIC it is: `/home/proj/stage/cancer/purerhino`. The `cases` is missing from BALSAMIC, which is specified within cg[-stage].yaml.

Steps to reproduce
  1. `us` or `up`
  2. `cg analysis link -f purerhino`
  3. fastqs will be linked into `/home/proj/{stage,production}/cancer/purerhino`

Expected outcome / suggested solution:
- fastqs linked into `/home/proj/{stage,production}/cancer/cases/purehino´
- suggested solution: update the path for balsamic by adding `cases` to the end of  `config['balsamic']['root']` at https://github.com/Clinical-Genomics/servers/blob/9189f8f13220167c7f589abdb47b743009935072/config/hasta.scilifelab.se/cg-stage.yaml#L41 and https://github.com/Clinical-Genomics/servers/blob/9189f8f13220167c7f589abdb47b743009935072/config/hasta.scilifelab.se/cg.yaml#L41

Questions: 
Q: Does this problem occur for any cancer sample regardless?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by barrystokman** [comment]
@emiliaol I will probably pick this up as a quick fix before the Easter weekend, no need to move it to the PBL.

**Comment by patrikgrenfeldt** [comment]
@barrystokman is this fiexed?

**Comment by barrystokman** [comment]
yes see https://github.com/Clinical-Genomics/servers/pull/118
