### ISSUE TITLE
Upload mip analyses with different analysis types

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#3324]
# User story

As a production team member I would like to be able to upload mip dna analyses for cases that contain samples with different analysis types.

# Acceptance Criteria

- [ ] MIP DNA cases containing samples of different analysis types can be uploaded

...

# Notes

# Implementation plan

**Comment by Vince-janv** [comment]
Resolved by https://github.com/Clinical-Genomics/cg/pull/3332
