### ISSUE TITLE
Unable to link files in stage due to permission

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#333]
As a bioinformatician, I want to link balsamic related files in stage so that I can run analysis in stage.

Problem: 
When a case is associated with mip, i get permission error at: https://github.com/Clinical-Genomics/cg/blob/899519148b1bcaa8e6c5ee69defdd0d2800ea038/cg/meta/analysis.py#L237 since I don't have permission.

Steps to reproduce
  1. `us`
  2. `cg analysis link -f purerhino`
  3. `PermissionError: [Errno 13] Permission denied: '/home/proj/stage/rare-disease/cases/purerhino/wes/ACC5464A9/fastq'`

Expected outcome / suggested solution:
- I expect files to be linked into: `/home/proj/stage/cancer/purerhino`
- Solution some sort of try/except to check permission. Something like https://docs.python.org/3/library/os.html#os.W_OK or whatever that checks for permission.

Questions: 
Q1: Does this problem occur for all samples for balsamic+mip?
A1: Yes.
Q2: @hassanfa  Should the sample in question be analysed by MIP? (otherwise that is what we should skip) 
A2:

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by barrystokman** [comment]
@emiliaol Might also be a quick fix instead of a backlog item

**Comment by hassanfa** [comment]
I don't want to interfere with your plans, but this might be an issue for MIP developers as well. If it is balsamic+mip, they can't link it either without having proper permission. There should be some sort of try/except _and_ logging of what was not been able to link.

My point is: the fix is easy, but the depth of the fix might need a reevaluation. (just my two cents)

**Comment by ingkebil** [comment]
The permissions for stage have now been set to `hasta-development`. Please have another go at it :)

**Comment by hassanfa** [comment]
It is working!
![giphy](https://user-images.githubusercontent.com/1086877/56952253-30a67000-6b3a-11e9-8f1b-f215c3f378ee.gif)

**Comment by patrikgrenfeldt** [comment]
@hassanfa can we close this issue?

**Comment by patrikgrenfeldt** [comment]
Resolved by #362
