### ISSUE TITLE
Create orderflow for microbial sequencing only

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#3338]
### Description
For human DNA samples customers can order different analysis workflow but they can also order sequencing only (FASTQ) where we just send them the FASTQ files.

This option does not exist for microbial samples where only a microSALT analyses are available and require input parameters which the customers might not have.

### Acceptance Criteria
- [ ] Customers can order sequencing for microbial samples without further analyses
- [ ] The FASTQ files are automatically uploaded once sequencing is done

### Notes
- We need input on which input fields are needed for the lab when ordering @annagellerbring 
- Should ideally create on case per sample IMO

# Implementation plan

- ...

**Comment by ChrOertlin** [comment]
@Vince-janv does this issue need a technical refinement? If not we should add it to the trocadero "ready" column.

**Comment by annagellerbring** [comment]
**Lab UDFs in new workflow:** (in discussion with @FayKanellidou)

**Keep:**
- Sample/Name
- UDF/Control
- UDF/Sequencing Analysis (Application tag)
- UDF/customer
- UDF/Sample Buffer
- UDF/Volume
- UDF/Priority
- Container/Tube (Container Type)
- Container/Name (Plate Name)
- Sample/Well location (Well)
- UDF/Comment

**Remove:**
- UDF/Extraction method
- UDF/Sample conc.
- UDF/Quantity

FYI @annaengstrom @AnnaZetterlund

**Comment by Vince-janv** [comment]
# Technical Refinement
## FE
- Add new "orderType" to the front end called Sequencing of microbial samples
    - text: "Sequencing of microbial samples"
    - orderType: microbial-fastq
    - applications:[mic, cov]
    - dataAnalysis: fastq
- deliveryOptions: [fastq: { text: 'Raw sequencing data (fastq)', value: 'fastq' }, no_delivery: { text: 'No Delivery', value: 'no-delivery' },]
- The fields should be those described in AGs comment

## BE
- Allow for new ordertype in submit-endpoint
- New OrderInSample child class called MicrobialFastqSample
- Add new MicrobialFastqSubmitter (avoid MicrobialSubmitter....)
- The Case database object should have case.data_analysis="fastq" and case.data_delivery="fastq"

**Comment by ChrOertlin** [comment]
Backend solutions are in place now. Waiting on FE implementaiton to test.

**Comment by ChrOertlin** [comment]
@Vince-janv What are the fields that need to be displayed on the front end. @moedarrah and I are testing and we run into issues with validation errors when fields become hidden on the fornt end. 

For example when putting no container then the volume disappears which is required when putting a microbial fastq order

**Comment by moedarrah** [comment]
An error will occur if we don't specify the "Volume (μL)", which will be hidden when "No Container" is selected.
![Image](https://github.com/user-attachments/assets/2d164a27-fdb5-4560-a0f1-08db0241ae47)

![Image](https://github.com/user-attachments/assets/6b2bfdba-57bc-4a2d-84ac-d9a4ff39f2d4)

**Comment by diitaz93** [comment]
@Vince-janv

**Comment by Vince-janv** [comment]
> @Vince-janv What are the fields that need to be displayed on the front end. @moedarrah and I are testing and we run into issues with validation errors when fields become hidden on the fornt end.
> 
> For example when putting no container then the volume disappears which is required when putting a microbial fastq order

@moedarrah Was Volume the only example? I looked into it and the same bug is present for the exists in the current microbial workflow in production. I'm in contact with prod whether to disallow No container for both or allow it for both (and fix the bug)

**Comment by Vince-janv** [comment]
After discussion with KN we decided that for both the existing microbial flow and for this one, the option No-container should not be available. @moedarrah Not sure what the best way to implement this is. If it is a hassle in the front-end we can sit down and refine it a bit

**Comment by Vince-janv** [comment]
@moedarrah It's rather the countrary, we always want to receive the volume for thesw so the option No-container should not be available (ie the option that hides the volume field)

**Comment by karlnyr** [comment]
@ChrOertlin, @moedarrah, @Vince-janv this issue could be closed right? Or is there something missing except the merge of the front end?

**Comment by Vince-janv** [comment]
Done!
