### ISSUE TITLE
microSALT analysis output is stored in houskeeper using `cg store`

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#335]
As a production team member I want the results from all analyses to be stored in a common way using cg store so that the data can be backed up, maintained, delivered, checked and so on using cg or housekeeper.

Problem: Analysis output from microSALT is now saved directly under the analysis folder on the cluster, and in order to backup and keep track of analysis output this should be included in housekeeper instead.

Suggested solution:
* add the functionality to `cg store`. It should check the analysis output (/home/proj/production/microbial/*/) for the project finished file (run_complete.out).
* The tags needs to be defined as part of the work. Also add a microsalt specific tag for all the files and a project tag (use the LIMS project ID).
*  Check existing code for interactions with bundles to make sure that we don't introduce bugs when using latest bundle version - what happens if there are two bundle versions with the same date?

DoD:
* `cg store` stores microSALT files in production
* Documented in AM microSALT method (1760?)
* Communicated to relevant staff

How to demo:
On hasta -
`cg store analysis Project_LIMS_ID` (the microbial order ID)
Expected output -> stored files in housekeeper
`housekeeper get bundleID` one sampel in the order

What to store:
* assembly
* alignment bam/sam
* log-files
 - job_output
 - microsalt_log
 - app_specific_logs
* analysis
 - coverage
 - blast output

**Comment by patrikgrenfeldt** [comment]
Resolved by #363

**Comment by emiliaol** [comment]
This is not worked on yet :)
