### ISSUE TITLE
usalt fastq files are linked to the analysis folder on hasta

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#336]
Contact: EOL

As a production team member I want the fastq files of microbial samples to be available for analysis on hasta so that I can stop using rasta for this.

Problem: There is no linking of microbial fastq files in place on hasta right now. 

Suggested solution:
link microbial samples to housekeeper `cg transfer flowcell` -> to be done in US 2806
`cg analysis link` also handles the microbial samples. The fastq files should be linked to `/home/proj/production/microbial/fastq/<project>/<sample>/*.fastq.gz`.

The linking should be done based on apptag prep category `mic`

- [x] rename analysis to `mip-analysis` or `analysis mip`
- [x] add `analysis microbial link` that links the microbial files

Q&A:
1. Shouldn't the structure be more MIP like? 
2. No, because we think it's easier to have an overview if the input and output is more separated for the microbial analysis.

**Comment by patrikgrenfeldt** [comment]
Resolved by #362
