### ISSUE TITLE
Updates to the text in the delivery report

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#3363]
Me and AL looked through the delivery report and we found some things that should be changed.

- [x] kvalitetskontrollsmetrik —> kvalitetsmått

- [x] metrik —> kvalitetsmått

- [x] "Medelvärdet av täckningsgraden i baser över en genomisk region."  —> "Medelvärdet av täckningsgraden i baser över genpanelen/genpanelerna angivna under dataanalys."

- [x] "Andel baser som är sekvenserade med ett djup över en specificerad gräns (10x)." —> "Andel baser som är sekvenserade med ett djup över en specificerad gräns (10x) över genpanelen/genpanelerna angivna under dataanalys."

- [x] "CN varianter "—> CNVs

- [x] “Sekvenseringsläsningar som är i duplikat och därmed ej unika sekvenser. Hög mängd duplikat kan tyda på dålig komplexitet av sekvenserad bibliotek eller djup sekvensering.” —> “Sekvenseringsläsningar som är i duplikat och därmed ej unika sekvenser. Hög mängd duplikat kan tyda på dålig komplexitet av sekvenserat bibliotek eller djup sekvensering.”

This is from the descriptions of the quality metrics in the balsamic report:

- [x] Remove "< 200bp kan tyda på degraderade provmaterial (t.ex. FFPE), innan biblioteksberedning."

- [x] Remove "Ett värde mellan 1.0-1.8 visar god jämnhet."

The ticket ID in the end of the report, is it possible to change that to a link to the ticket?

**Comment by ivadym** [comment]
Another requirements we talked about:

- [x] Update apptags removing the Novaseq X info
  - Bulk manual update
- [ ] Show the apptag version in the apptag description and ordering sections

**Comment by ivadym** [comment]
Regarding the ticket link: I don't think it's possible right now since there doesn't seem to be a direct relationship between the ticket ID and the SuSy link
