### ISSUE TITLE
Tomte delivered results contain ACC number instead of family number

### ISSUE THREAD

**Issue by Lucpen** [Clinical-Genomics/cg#3368]
Looking at some Tomte results I realized that the files delivered (both vcfs and tsvs) contain the ACC number instead of the family number. In the vcf it's on the vcf header and on the tsv it is one of the columns. 

@ivadym suggested to use the family number as the sample ID in the sample sheet instead of the ACC number. How ever it should be tried before to make sure nothing breaks.

# Clarification
We provide the case internal is and sample internal ids to the pipelines and these are put in the output files of the pipelines. When we send the files to the customer they expect the family name and sample name (chosen by the customer) to be how we refer to the samples/cases.

This is only a problem when we deliver the actual files, in scout we only show the identifier they chose. So this problem exists for MIP-DNA, MIP-RNA, RNAFUSION and tomte at least. 

It is only problematic for cases with multiple samples since there is no risk of confusion if files only contain one sample.

In the delivery-report (which we also provide) there is a translation between our internal_ids and the customer ones so even if a file contains multiple samples they can be translated using the aforementioned report

**Comment by ivadym** [comment]
I've added this issue for refinement. Including the sample name in the sample sheet results in the output files having the sample's external name, which is currently inconsistent with our Housekeeper file naming (we store files with `sample_id` and `case_id`).

Taxprofiler is already implemented this way, so we should set some requirements before it's in production to make sure we use a consistent (or at least documented) naming conventions.

FYI: @fevac @sofstam

**Comment by sofstam** [comment]
@ivadym Is there anything that I should do on my end regarding this?

**Comment by Vince-janv** [comment]
@ivadym Thanks for having a look! Do you know how our older pipelines (mip and balsamic) swap the internal_id for the names?

**Comment by ivadym** [comment]
> @ivadym Thanks for having a look! Do you know how our older pipelines (mip and balsamic) swap the internal_id for the names?

We rename specific files within the pipelines, with some exceptions due to legacy code. But this seems to be a general issue with Nextflow pipelines. Rnafusion also includes internal case names in the delivered results.

We should align with the Nextflow developers (Eva returns next week).

Summarising:
- Add case/sample names to output files:
    - Solves the issue Lucía raised.
    - Adds case/sample IDs to files we store in HK, which may not be ideal for prod bioinfo and would break our current file naming convention.
- Keep case/sample internal IDs in the sample sheets.
    - Requires handling the sample id > sample name translation within pipelines.

**Comment by Vince-janv** [comment]
We deliver mip-files with ACC names in the header. What are the issues we encounter in Tomte when using our internal IDs?

**Comment by ivadym** [comment]
It’s mainly the customers who would like to have the sample names inside those files instead of the ACCs, which  makes sense since we replace the sample IDs with the sample names during delivery

**Comment by Vince-janv** [comment]
It would be nice to know more specifically which problems this poses to our users and why users of other pipelines do not find this problematic (maybe they do 🤔). 

@Lucpen and @ivadym, who reported this to us and what is the specific problem they encountered?

**Comment by Lucpen** [comment]
Our users view the results on Scout where the ACCs in vcf files are automatically translated to the sample number. In tomte, at the time being, the data is only delivered through Caesar where we supply vcfs and tsvs. In these files the ACCs are not translated, they come only with ACC number so that's why we don't have that problem with other pipelines.

**Comment by Lucpen** [comment]
I think that id [this issue](https://github.com/Clinical-Genomics/scout/issues/4702) is solved, this one could be closed too, I am not sure what is easier or less hard to solve

**Comment by Vince-janv** [comment]
I think we understand the root of the issue but we're having problems prioritising it since we don't know what impact it has on the customers. Ie, are the files unusable for them, is it a slight inconvenience, do they have to translate the ideas manually etc? Could you provide som insight?

**Comment by Lucpen** [comment]
It depends on two things:
-If its just one sample then it is not a problem as they can assume that the patient they can see is there own
- If it's a duo or a trio it depends on whether they get a key with the ACC number and sample ID somewhere. If they get it then it's an inconvenience, if they don't then they can't use it. I will look for it within the delivered files and get back to you.

**Comment by Lucpen** [comment]
Found it within the delivery report, I guess we can just wait with this then. If they ask, we can just point out that it is temporary and that there is a key within the deliverables.

**Comment by Vince-janv** [comment]
Thank you for checking @Lucpen!

Adding a summary to the first comment of the issue

**Comment by Vince-janv** [comment]
This will amount to a projekt and needs a task-force of both sys-devs and bioinformaticians. Closing as too big. This should be handled as a project addressing this problem for all pipelines
