### ISSUE TITLE
Add price information to the sample table in cg

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/cg#3417]
As a project manager,
I want to have information about the invoicing price in the sample table in statusDB,
So that I can trend prices for samples over time.

# Acceptance Criteria
- [ ] The sample table has a column called "invoice_price"

# Notes
Today we do have information about application_version_id and priority in the cg sample table. We also have application price by priority in the application_version table. This would be more useful if this was linked together in a new column in the sample table which just takes the information about application_version_id and priority from the sample table and pulls price info from the application_version table (columns: price_standard, price_priority... etc)

- Additional information.
- Dependencies.
- Related user stories.

# Implementation plan

- [ ] Work item 1
- [ ] Work item 2

**Comment by vwirta** [comment]
I am working on new pricing. Hopefully done during this week

**Comment by Vince-janv** [comment]
@pbiology Each sample has an application version with the cost of that sample. If it's trending you want do we not have access to how much we charged for that sample via that information?

I the problem that one needs to map the sample priority to the correct column?

Is providing a functioning SQL query sufficient to solve this issue?

**Comment by Vince-janv** [comment]
If you need any help to get it working in Tableau, just ping us and we'll help you figure it out!
