### ISSUE TITLE
Improve KI invoice specification

### ISSUE THREAD

**Issue by vwirta** [Clinical-Genomics/cg#343]
As an invoicing user, I would like to avoid having to manually do copy-pasting to get invoice specifications into the format they need to be in so that the time doing invoicing is reduced

**Steps to reproduce:**
Create an invoice

**Expected outcome / suggested solution:**
Included in the KI invoice specification is the KTH cost for each sample, and have the KI and KTH costs summed in yet another column. Basically, far to the right of the KI specification, please add KTH cost and sum of KI+KTH costs 

I would also appreciate if the font size can be a few notches larger. 

**Questions:** 
Q1: 
A1: 

I think this is to @mayabrandi

**Comment by emiliaol** [comment]
@vwirta @mayabrandi  Still needed?

**Comment by henrikstranneheim** [comment]
@mayabrandi What is the status of this one?

**Comment by mayabrandi** [comment]
Its done! Ill close it!

**Comment by henrikstranneheim** [comment]
👍
