### ISSUE TITLE
The removal of the `--force-all` flag from the DeliveryAPI logic and cli calls

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#3432]
As a production user,
We want all data to be delivered for a sample regardless of the amount of data,
So that we don't have to do another transfer for exceptions, thus reducing the number of human errors. 

# Acceptance Criteria

- [ ] When the automation runs delivery of fastq files then it should include all samples with fastq files
- [ ] When the user runs any of the `cg deliver <subcommand> -d fastq` subcommands the user should not have to specify the `--foce-all` flag to include all the fastq data for samples

# Notes

- Additional information.
- Dependencies.
- Related user stories.

# Implementation plan

- [ ] Work item 1
- [ ] Work item 2

**Comment by Vince-janv** [comment]
Solved in new delivery flow
