### ISSUE TITLE
Change is_delivered in Order table

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#3463]
Backend part of https://github.com/Clinical-Genomics/cigrid-ui/issues/638

- In `cg` rename the `is_delivered` field of the Order table to `status`
- Change this field from bool to Enum containing the values "open"/"closed" 
- Update the filtering

**Comment by islean** [comment]
Does it not make more sense for the database to store it as a bool and the enum being how it is rendered?

**Comment by islean** [comment]
I am quite opposed to changing the actual datatype from a bool, given that we only want a visual update

**Comment by seallard** [comment]
Lets keep everything in the original issue
