### ISSUE TITLE
Bug: Raredisease not storing d4 coverage file

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#3470]
**Describe the bug**

The Raredisease workflow is not storing the d4 coverage file necessary for reporting coverage in the delivery report.

As per the implementation in [Clinical-Genomics/cg#3459](https://github.com/Clinical-Genomics/cg/pull/3459), the workflow should store a file with the following tags: {"coverage", "d4", "sample_id"}.

**Comment by rannick** [comment]
Closed with https://github.com/Clinical-Genomics/cg/pull/3560
