### ISSUE TITLE
SPIKE: just format my code

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#348]
As a developer of CG, I want code to be PEP8 formatted so I spend less time code reviewing

Problem: 
We now have linter that checks for coding style irregularities. which halts merging. Black will format your code so only those PEP8 issues remain that actually need a human hand.

https://github.com/python/black
"Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead."

Expected outcome / suggested solution:
How can we incorporate black in our workflow?

Questions: 

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by ingkebil** [comment]
@barrystokman @patrikgrenfeldt 

This one might be fun to investigate if you have an hour of idle time. Feel free to pick up at any time.

**Comment by patrikgrenfeldt** [comment]
Resolved by #499 and #503
