### ISSUE TITLE
Validation of coverage before upload

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#35]
A case should not be uploaded if the coverage of the OMIM-panel is too low (which is defined based on app-tag) even if the case has status finished.

In the case of cuddlythrush this seems to have happened anyway. Not a major issue but causes confusion for the customer and us.

**Comment by ingkebil** [comment]
Should this always be OMIM-panel coverage that is tested or the requested panel(s)?

**Comment by emmser** [comment]
This should be OMIM. We have the limits for wgs and wes analyses in AM.

**Comment by Mropat** [comment]
@henrikstranneheim  is this still happening? Can this be handled in MIP (analysisrunstatus to check for coverage?)

**Comment by henrikstranneheim** [comment]
It is a bit unclear what "upload" actually means here. I guess Emilia meant Scout. I do not know if the upload will fail if the validate part is not fulfilled. From the cron job:
```
----------------- VALIDATE --------------------
2021-01-26 00:56:39 hasta.scilifelab.se cg.utils.commands[102452] INFO Running command /home/proj/bin/conda/envs/P_chanjo/bin/chanjo --config /home/proj/stage/servers/config/hasta.scilifelab.se/chanjo.yaml db samples -s ACC7492A12
2021-01-26 00:56:42 hasta.scilifelab.se cg.utils.commands[102452] INFO Running command /home/proj/bin/conda/envs/P_chanjo/bin/chanjo --config /home/proj/stage/servers/config/hasta.scilifelab.se/chanjo.yaml calculate coverage --omim -s ACC7492A12
ACC7492A12: 53.99X - 99.71%
```
We have the usually check the entire default capture target regions in MIP (both WGS and WES) and MIP usually get the gene panel master list and not a particular panel (as this is not supplied to MIP in any distinct option). I wonder if this really is an issue. @emmser ?

**Comment by Mropat** [comment]
@henrikstranneheim still an issue?

**Comment by henrikstranneheim** [comment]
I guess not since there was no answer and I am not aware of any current issues regarding this. Let's close it and reopen if needed
