### ISSUE TITLE
Add CLI to create validation cases

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#3533]
As a bioinformatician,
I want to be able to create validation cases in a straight forward and standarised manner,
So that our validation cases are consistent and easy to generate.

Note: I could not find any issue related to this https://github.com/Clinical-Genomics/cg/pull/3148 but there's some additional information added there.

Note 2: not sure what was the original acceptance criteria of the PR but something to take into account is that validation cases are usually downsampled cases, so this should be done in a way that does not to overlap with the downsample CLI too much, or perharps build on top of it and extend functionality. 

# Clarification
There already is a PR for this (https://github.com/Clinical-Genomics/cg/pull/3148). The steps that the PR performs is currently being performed manually by dev-bioinformaticians.

**Comment by diitaz93** [comment]
@ChrOertlin is on it

**Comment by Vince-janv** [comment]
Validation and downsampling are not prioritised at the moment. CG as an organisation needs a solution for this, but it is unclear cg should take care of it
