### ISSUE TITLE
Add information on internal negative control for a given sample

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3535]
As a production user and cg developer,
I want to be able to easily get information on which internal negative control was used for the prep of a given sample,
So that I don't have to manually search for it in lims.

# Acceptance Criteria

- It is possible to search for a sample and get its internal negative control.

# Notes

This functionality would much facilitate QC checks for analyses that require internal controls, which is currently done manually.

Would be an important tool for this project: [Improve the comparison and analysis of control samples in production](https://github.com/Clinical-Genomics/project-planning/issues/562)

**Suggested solution:**

~~_Alternative 1_~~

~~- Add a `Pool` table listing pools~~
~~- Add a `SamplePool` table displaying pool and samples relationship~~
~~- A pool object includes corresponding sample links~~
~~- The tables are populated from lims - relevant lims step: Target Enrichment TWIST~~

_Alternative 1_ was decided against so as to not repeat in cg the information that is in LIMS.

_Alternative 2_

- Add internal_control field to the `Sample` model and populate it with the corresponding internal control sample

# Implementation plan

- [ ] Work item 1
- [ ] Work item 2

**Comment by karlnyr** [comment]
We should redefine this so that it would solve " Create a connection between our internal control and related samples of that same prep" in https://github.com/Clinical-Genomics/project-planning/issues/562

**Comment by karlnyr** [comment]
### Discussion

- Alternative 2 sounds good - we could fetch information from lims of the latest prep and fill up the field of the "LatestInternalControl" (or  something similar to that)

**Comment by beatrizsavinhas** [comment]
After our discussion in Issue Refinement @Clinical-Genomics/sysdev, I decided to clean up this issue to make it more clear! Feel free to change the description if you think something needs to be clarified.

**Comment by karlnyr** [comment]
### Discussion

- WE ARE HUNGRY FOR TABLUE/SUPERSET AND WAY OVERDUE FOR IT!!!!!! SEE https://github.com/Clinical-Genomics/audits/issues/125 and https://github.com/Clinical-Genomics/audits/issues/84 and https://github.com/Clinical-Genomics/Deviations/issues/183
- We (in prodbioinfo) will create something to fetch the corresponding TGA controls and do regular QC for it. This will do for now, but we might be able to push the above-mentioned if things take too long.

**Comment by diitaz93** [comment]
Understood, prodbioinfo will handle this. Closing
