### ISSUE TITLE
CG can handle step name changes in LIMS

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#355]
As a lims user I want to have the NovaSeq protocol as default sequencing protocol in all workflows so that the lab doesn't waste time switching workflows.

Problem:
We have a new NovaSeq protocol in LIMS that will be used for most of the runs in the future. We therefor want to put this protocol as default for all workflows, instead of HiSeq 2500 or HiSeq X. 

We have also, since a long time, moved all invoicing information about samples to a separate invoicing tool. This means there is no need for the invoicing step in any workflow.

To switch NovaSeq protocol and the removal of the invoicing step will require new version numbers of all LIMS workflows, protocols and steps that are currently in production. This will in turn,  potentially have effect on some code in cg

Someone needs to identify all places in cg where lims workflow, protocol and steps are used. And update them with the new names.

Suggested solution:
- [x] create a constants file that holds all lims workflow, protocol and steps names used in `cg`: https://github.com/Clinical-Genomics/cg/blob/master/cg/apps/lims/constants.py
- [ ] replace all lims workflow, protocol and steps names  with the constants from the above file

All changes should be concentrated https://github.com/Clinical-Genomics/cg/tree/master/cg/apps/lims

Tools affected:
- upstream: LIMS
- downstream: following cg commands are affected:
  - transfer
  - orders
  - report
The commands need to be tested manually with a "how to test"-scenario.

Update after sprint 11:

- [x] finish up last 1% of code
- [x] specify test cases in pull request
- [x] check and update unit tests
- [ ] ~~documentation~~

Update after sprint 12:
- [ ] fix defects found in testing
- [ ] add testing for capture kit
- [ ] ~~documentation~~

People involved:
MB, HS, AJ

DoD:
- constant file is implemented and deployed
- inform MB

**Comment by emiliaol** [comment]
@ingkebil A backlog issue or extra task?

**Comment by ingkebil** [comment]
Backlog :)

**Comment by mayabrandi** [comment]
The test specification for this is now approved and avalible on AM: 1978:1 @ingkebil

**Comment by ingkebil** [comment]
Looks like we will only be able to do this in June. For this sprint, we focus on getting all services from rasta transferred to hasta.

**Comment by ingkebil** [comment]
We're taking this in this sprint now @mayabrandi

**Comment by mayabrandi** [comment]
Yey!
