### ISSUE TITLE
provide vogue with app tag category from status-db and run with cron job

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#356]
Contact: MB

As a vogue developer, I need application tag data provided as input to the cli command:  load application_tag. 

Problem: 
The App tag category is stored in status db. I have made a cli to load app-tag data, but I also need cg to produce the data and give it as input to the cli. And a cronjob that will load the data regularly.

Command:  `vogue load apptag <app tag input sting>`

The expected input format is  a string of a list with app-tags:
`'[{"tag": "WGSPCFC030", "category": "wgs"}, {"tag": "WGSPCFC060", "category": "wgs"},...]'`

If it is more suitable wit another format, we can talk about that!

Suggested solution:

`cg transfer vogue apptag` or `cg upload apptag` or ...

- The command should export app-tags in JSON as described above and pass it to vogue load apptag in the same way we call loqus. Create the 'vogue app' in `cg/apps/vogue.py`. Add config sections for vogue in `cg.yaml` and `cg-stage.yaml`.
- Vogue needs to be set up in its own production and stage environments on hasta. Create update-vogue-*.sh for hasta. See clinical-db update-vogue-*.sh scripts.

Questions:
1. 'category' in statusdb has been depricated. Do you want to use prep-category instead?
1. Is this transfer production or stage? If stage, does this really need to be put into a crontab?

DoD:
- when deployed

Minor: extending and not modifyin' the public API.

How to demo?
- run on hasta production `cg xxx vogue apptag` and show in mongodb that the apptag documents are filled in. (How and where do you do that?)

**Comment by emiliaol** [comment]
@mayabrandi Should be added to the backlog?

**Comment by mayabrandi** [comment]
its done actually. Not up and runing, but the code is there so I think we can archive this

**Comment by mayabrandi** [comment]
I have a PR floating around for this. I should make sure it gets approved and closed.

**Comment by emiliaol** [comment]
👍
