### ISSUE TITLE
Option to set cg analysis --output-dir

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#357]
As a developer I want to be able to link fastq files, create pedigrees and fetch gene panels to a dir outside of production using the cg analysis CLI.

Problem: 
There is not "--output-dir" option in cg analysis 

Steps to reproduce
```
cg analysis --help
Usage: cg analysis [OPTIONS] COMMAND [ARGS]...

  Prepare and start a MIP analysis for a FAMILY_ID.

Options:
  -p, --priority [low|normal|high]
  -e, --email TEXT                email to send errors to
  -sw, --start-with TEXT          start mip from this program.
  -f, --family TEXT               family to prepare and start an analysis for
  --help                          Show this message and exit.

Commands:
  auto          Start all analyses that are ready for...
  config        Generate a config for the FAMILY_ID.
  link          Link FASTQ files for a SAMPLE_ID.
  panel         Write aggregated gene panel file.
  remove_fastq  remove fastq folder
  start         Start the analysis pipeline for a family.
```

Expected outcome / suggested solution:
Adding "--output-dir" or similar so I can direct where to create prerequisites for starting an analysis workflow.

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by hassanfa** [comment]
This is a useful feature for me as well. Right now there is no possibility to link to any other place than stage or production. So I have to manually copy/move files each time.

**Comment by patrikgrenfeldt** [comment]
Please feel free to get inspiration from the templates from https://en.wikipedia.org/wiki/User_story#Common_templates and add the WHY/BENEFIT part so we can minimize the risk of the [XY-problem](https://en.wikipedia.org/wiki/XY_problem)

**Comment by hassanfa** [comment]
I am reopening this, as it might be relevant to https://github.com/Clinical-Genomics/cg/issues/838 as well.

Lots of custom analysis that I do through `cg` on production samples might need a different result directory to avoid storing, trailblazing, and  breaking production.

Examples include:
1. re-analysis of production samples under different condition
2. answer customer questions by looking into intermediate files that are not stored
3. aggregate multiple analysis results from multiple intermediate file from multiple cases

I understand `stage` exists, but it'd be cool to be able to utilize `long-term-stage` more often.
