### ISSUE TITLE
Show gene panel details in a new tab on status db

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#358]
As a bioinformatician I want to be able to see gene panel design details on statusdb. This is to be able to see gene panel version, size in bp/kb/mbp/.., possibly short description, name, and short alias.

Steps to reproduce:
1. https://clinical-api.scilifelab.se
2. There is no gene panel design tab.

Questions: 
Q: Example of how it might look like?
A: https://docs.google.com/spreadsheets/d/1Zvp6DZMgOfpoLsGKWRD9iQ_6iAh0BYhmP5xsK5SJxIM/edit#gid=0

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by hassanfa** [comment]
@vwirta @annagellerbring @annaengstrom what extra detail about panels would be useful to show?

**Comment by emiliaol** [comment]
So this is for the cancer panels? Isn't there an app being developed for that? @northwestwitch

**Comment by hassanfa** [comment]
Could be. This issue is aimed towards designs that we get. Is paneldb going to do this and a summary to statusdb?

Currently samples are tagged as Wes, wgs, etc. For the genepanel ones it is unclear which panel design was used.

Finally paneldb is going to hold gene and region information (as far as I can understand from the git repo). The information  on statusdb doesn't need to have gene/region information.

**Comment by northwestwitch** [comment]
The development of paneldb is lagging behind our initial expectations unfortunately. We started building the app with @emmser but it's still in its initial phase. Good news is that this way you can decide exactly what you need in it and contribute to its development!

**Comment by hassanfa** [comment]
Talked with @keyvanelhami : app tags can be related to gene panel design (i.e. capture kit), which is already in statusdb. However, the name for the capture kit is not standardized and it is not possible to track their version.

I had a look at panelDB repo, but I'm still confused what is panelDB or what it is going to be. BALSAMIC has to know which panel design to use, and this information will be provided before running the analysis. I think it will be `cg`'s decision to choose the correct version and bed file  based on the order.

**Comment by emiliaol** [comment]
@ingkebil What's your thoughts about this? Where should the information go?

**Comment by emiliaol** [comment]
@hassanfa Where are we with this? Should be added to backlog?

**Comment by hassanfa** [comment]
We are doing it here: https://github.com/Clinical-Genomics/target_capture_bed/issues/28 and https://github.com/Clinical-Genomics/target_capture_bed/pull/33

**Comment by emiliaol** [comment]
👍  I'll add it then for tracking purposes

**Comment by annaengstrom** [comment]
We now have Bed and Bed version (which agrees with https://github.com/Clinical-Genomics/target_capture_bed), can we close this issue?

**Comment by hassanfa** [comment]
Yes finally! Great! 👍
