### ISSUE TITLE
Cancel actions creates orders without cases

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#3590]
The cancel action seem to at times result in ghost orders without any cases/samples in them. As reported by @islean here https://github.com/Clinical-Genomics/cg/issues/3058#issuecomment-2293636249.

**Comment by seallard** [comment]
Unclear what issues this cause, closing for now.

**Comment by islean** [comment]
The orders clutter the orders list view in CiGRID with an unclear summary - no cases at all?

**Comment by diitaz93** [comment]
## Clarification
When you cancel a sample in statusdb, the case-sample entry is deleted. If the case has no remaining samples the case entry is also deleted. But if an order has no cases left, it is not deleted.

### Acceptance criteria:
- I When we cancel a sample and this leads to an order without any cases/samples, the order must be deleted too
