### ISSUE TITLE
script to load application tags to the application table in  status-db

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#361]
Valtteri usually comes with batches of new application taggs that he wants to add to the application table in status db.  

Problem: 
There should be a script that can load these from a csv or excel. And there should be a template with requiered columns and fixed presets that he can use to fill these in. Maybe??? Or du you have other suggestions?

  1. Decide on a solution
  2. implement soultion

Expected outcome / suggested solution:
Easy and fast way to load many application tags in one go.

Questions: 
Q: There is allrady a script for loading application versions to the application_version table. Should we just add to that script so that it can load application tags with another option?

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

**Comment by emiliaol** [comment]
@patrikgrenfeldt This is already done, right?

**Comment by mayabrandi** [comment]
Yes

**Comment by emiliaol** [comment]
Thanks Maya :). I'll close this issue then.
