### ISSUE TITLE
Critical conda bug prevents creation of environments and installing packages from file

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#364]
As a bioinfo person, I want to install environments in conda without any error.

Problem: 
conda 4.5.xx has a bug while resolving environments: https://github.com/conda/conda/pull/7780

Steps to reproduce
1. conda env create -f my_conda_env.yaml --quite --name some_conda_env_name

Example conda_env.yaml

```
channels:
  - bioconda
  - conda-forge 
dependencies:
  - python=3.6
  - pip=9.0.3
  - snakemake=4.8.0
  - r-data.table=1.11.4
  - r-optparse=1.6.0
  - r-deconstructsigs=1.8.0.1
  - r-reshape2=1.4.3
  - bioconductor-bsgenome=1.48.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
```

and this is the command: `conda env create -f abovefile.yaml --quiet --name S_test_190524_HFA`

Expected outcome / suggested solution:
A conda environment to be created with this name: some_conda_env_name

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by hassanfa** [comment]
Also, I can't install any environment on hasta. Works well on my Centos VM on conda 4.6. Did we change anything on Hasta?

**Comment by ingkebil** [comment]
No changes to conda since we installed it.

Did this used to work?

**Comment by hassanfa** [comment]
Yes, it used to work. Henrik also tried the same command and didn't for him either.

**Comment by ingkebil** [comment]
What error are you actually getting?

**Comment by hassanfa** [comment]
```
Solving environment: ...working... failed

CondaValueError: Malformed version string '~': invalid character(s).
```

**Comment by ingkebil** [comment]
So far we have only used `conda create` instead `conda env create` to create environments, which is most likely why it hasn't popped up before.

**Comment by hassanfa** [comment]
I added an example to my original post.

**Comment by ingkebil** [comment]
OK, so the fix seems to be to upgrade conda :o That's not a trivial matter or something I want to push to production on a Friday afternoon.

Plan is pending.

**Comment by hassanfa** [comment]
We are don't have any cancer related samples to analyze, so it can wait until next week. I recommend avoid removing current conda environments.

I wonder what might have been the trigger for this. I suspect some sort config for conda is changed (a similar situation to perlbrew). Or I don't know :-)

**Comment by ingkebil** [comment]
Yes, weird indeed! So, no software updates have happened since last time Hasta went down. The conda config is really basic:

```
# installing a new environments add these packages by default
create_default_packages:
  - python
  - pip
  - ipython

# implies always using the --yes option whenever asked to proceed
# always_yes: true

# change ps1 when using activate (default True)
changeps1: False

channels:
  - bioconda
  - defaults
```

I'm unsure what situation of perlbrew you're referring to.

**Comment by hassanfa** [comment]
I thought maybe since we have a shared conda installation, something like index cache or metadata was updated for the rest of the users (similar to switch/use in perlbrew that happened in Rasta last year).

**Comment by hassanfa** [comment]
On conda's github, someone pointed to compatible release on pep. https://www.python.org/dev/peps/pep-0440/#compatible-release . Essentially, conda doesn't understand how to resolve `~` in the version.

**Comment by ingkebil** [comment]
So might it be that nothing changed for conda or the installation rather, your dependencies in the dependency file changed?

**Comment by hassanfa** [comment]
There are no changes to the version for packages in the yml file. conda create fails even during installing `snakemake`.

example yml file:
```
channels:
  - bioconda
  - conda-forge 
dependencies:
  - snakemake=4.8.0
```

**Comment by ingkebil** [comment]
Yes, but it might be a dependency of snakemake or even further down the chain, right?

**Comment by ingkebil** [comment]
And yes, it looks like the solution is to upgrade conda. We can do it when the analyses of the novaseq from this weekend are finished.

**Comment by hassanfa** [comment]
So far it is `Snakemake`. I can try to dig deeper next week and find out what are the exact dependencies. `~` is a `pip` thing.

But it'd be great if we can update conda. Conda 4.6 comes with faster environment solve as well (which might be useful for quickly creating conda envs).

**Comment by ingkebil** [comment]
I'll prepare a verification which we can run at the beginning of next week. If that one passes, we can upgrade as soon as production is ready.

And yes, I'm all for upgrading and using the latest versions :)

**Comment by ingkebil** [comment]
How blocked are you by this? I cannot look into this before Wednesday unless this is absolutely life threatening.

**Comment by hassanfa** [comment]
Short answer: Not until next week Wednesday.

Long answer: It is all good. As long as we don't have any cancer sample in sequencing OR a re-analysis of previous research/clinical samples. BALSAMIC is now a singularity container. Even if there is a critical re-analysis/analysis, it can be handled.

**Comment by ingkebil** [comment]
So, I'm need to test if sourcing and running certain programs still works. Do you think we're going to be fine by testing the latest conda?

**Comment by hassanfa** [comment]
That's not an easy question. I think we have to look into what changes we have to make to bashrc and PATH if we update conda: https://github.com/conda/conda/blob/master/CHANGELOG.md

As far as I can see from the link above, it shouldn't be a major issue. Are we using `conda init`?

**Comment by ingkebil** [comment]
We are using `conda init`

**Comment by ingkebil** [comment]
oh, wait, we are not! We are sourcing the relevant parts of `conda init` ourselves

**Comment by hassanfa** [comment]
Huh, then it might be easy. Can we use aliases for another `conda` version?  If yes, then I have a better solution. We can ditch all conda stuff, and alias it to a version controlled and exact version of conda.

```
cd /home/proj/stage/cancer
singularity pull shub://Clinical-Genomics/BALSAMIC:miniconda3_4_6_14
singularity exec BALSAMIC_miniconda3_4_6_14.sif conda create \
   --prefix /home/proj/bin/conda/envs/S_BALSAMIC-snakemake_190415 \
   -c defaults -c bioconda -c conda-forge snakemake
```

**Comment by hassanfa** [comment]
I can use the above solution for now. But we can move the move everything conda to the container above. Then we won't even need conda installation at all. Which will simplify bashrc a lot!

**Comment by ingkebil** [comment]
But this is only for tools running in singularity, right?

**Comment by hassanfa** [comment]
Right, our core tools still need conda. Scratch that. Let's update conda. 😓

**Comment by hassanfa** [comment]
Obsolete. Found another solution: pip and container.
