### ISSUE TITLE
Bug: Application Versions with malformed `updated_at`

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#3643]
When searching for existing samples, the `application_version` table is parsed in part for the response. Among the included fields is the `updated_at` field, which is marked as an optional datetime object. 63 applications have an `updated_at` set to 0000-00-00 00:00:00, making the endpoint crash.

**To Reproduce**
1. Try to add an existing sample to an order with app tag MWRNXTR003, v.2.

**Expected behavior**
The sample is found and can be added.

**Comment by diitaz93** [comment]
## Technical refinement
- Replace the wrong `updated_at` field of the affected samples with the value of `valid_from`

**Comment by islean** [comment]
Suggested script to run:

```MYSQL
UPDATE application_version av SET updated_at = valid_from WHERE CAST(av.updated_at AS CHAR(20)) = '0000-00-00 00:00:00'
```

**Comment by Vince-janv** [comment]
Looks good 👍

**Comment by islean** [comment]
Ran in stage successfully

**Comment by islean** [comment]
Ran successfully in production
