### ISSUE TITLE
Rename managed_variants file to critical variants?

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/cg#3646]
We had some discussion in the @Clinical-Genomics/rare-disease team and we find the filename `managed_variants.vcf` to be somewhat confusing. The file name is  ambiguous as it is not clear whether these are recurring variants that have been managed and can be safely dismissed or are variants that should always be displayed. We would like to rename the file to `critical_variants.vcf` to indicate their importance. 

https://github.com/Clinical-Genomics/cg/blob/097651227590627de8ff55ab4779fc8eff69b774/cg/constants/scout.py#L15

**Comment by vwirta** [comment]
I am not a big fan of the suggestion **critical variants**, but I agree that **managed variants** is not that clear either.
What about **pathogenic variants**, or **clinically relevant variants**?

**Comment by rannick** [comment]
Keeping managed_variants for now
