### ISSUE TITLE
Update contact person for invoicing workflow

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/cg#3655]
**Replace AG with:**

- Anna Zetterlund
- anna.zetterlund@scilifelab.se
- +46 701 523 463

**Comment by annagellerbring** [comment]
discussed with @islean and @Vince-janv.
FYI @AnnaZetterlund

**Comment by diitaz93** [comment]
## Technical refinement
- Change the email, name and phone number in `cg/apps/invoice/templates`

**Comment by AnnaZetterlund** [comment]
Hej, when doing a new invoice today Anna G is still the contact person.

**Comment by Vince-janv** [comment]
@ChrOertlin Did you deploy the change to the VM?

**Comment by islean** [comment]
Can not recreate. An old branch without recent changes ( `improve-order-flow-main` most likely) was probably deployed to the VM during the refinement when I checked before.
