### ISSUE TITLE
Make CG and HK aware of analysis_result_and_qc json file to load into trending db through vogue cli

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#369]
What: Use Vogue CLI to load analysis_result_and_qc.json into trending db

Problem: 
CG/HK don't know where the json file is.

Steps to reproduce
N/A

Expected outcome / suggested solution:
`cg load vogue` or something like that.
CG needs to know casename, sample_ids (LIMS) for each sample in case, workflow name and analysis_result_and_qc.json file above.

Questions: 
Q: 
A: 

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by hassanfa** [comment]
Tagging relevant parties to initiate a discussion. @emiliaol @ingkebil @henrikstranneheim @mayabrandi

**Comment by emiliaol** [comment]
Was this what we discussed at the operations meeting? That we need to add the files to housekeeper and then let vogue pick it up from there?

**Comment by henrikstranneheim** [comment]
See #185

**Comment by emiliaol** [comment]
@henrikstranneheim @hassanfa Close or add to backlog?

**Comment by henrikstranneheim** [comment]
Added to backlog

**Comment by henrikstranneheim** [comment]
For the MIP DNA workflow one can find the case multiqc json under the `multiqc-json ` tag in housekeeper. Example is from stage, but this is implemented in production. 
<img width="709" alt="Screenshot 2020-02-21 at 08 31 40" src="https://user-images.githubusercontent.com/584738/75013552-c96cfa00-5484-11ea-80e0-4837af6dfdec.png">

**Comment by henrikstranneheim** [comment]
@hassanfa Is this also done now for Balsamic? Meaning the capability of cg to store the json file in housekeeper? Or is this part of the next store version of balsamic files in cg?

**Comment by hassanfa** [comment]
It is part of Balsamic store through HK/CG, and I think it in blocked status on Backlog.

Multiqc's data is part of delivery file for Balsamic. But I can't push into production as it will break current release of CG for storing Balsamic results.

**Comment by henrikstranneheim** [comment]
@hassanfa Done right?

**Comment by hassanfa** [comment]
It is done! ⭐
