### ISSUE TITLE
Bug: Freshdesk tickets may match SuSy ticket ids

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#3702]
**Describe the bug**

Our current filtering for cases belonging to a ticket is oftentimes using the `case.tickets` column, which contains a comma separated list of ticket ids. There are instances where, provided a ticket_id, we just check if the column value contains the ticket_id. This is error prone since the freshdesk ticket ids may very well contain a SuSy ticket id just because they are longer (e.g. 1234567 contains 123456). 

**To Reproduce**
1. Create a case with a Freshdesk 7 number ticket id
2. Use the filtering method using a 6 number ticket id and see if the case created in 1. is returned.

**Expected behavior**

**Additional context**

**Comment by diitaz93** [comment]
## Technical refinement

- In the `filter_cases_by_ticket_id` function in the filter case module filter using the Case-Order table instead of the tickets column
