### ISSUE TITLE
(Improve order flow) Add validation for required container names for containerised samples

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/cg#3723]
We need to add validation ensuring:

If: Sample is in a container (tube or well plate)
Then: The container needs to be named

To clarify: What do we do with the default value for tubes?

**Comment by islean** [comment]
In standalone orders: 96 well plate and not RML -> Required. 
In Case orders: 96 well plate -> Required

**Comment by islean** [comment]
Clarifications from the slack discussions:

- This is to be implemented in the `improve-order-flow-main` branch, i.e. not master.
- There is a difference between orders containing cases and samples, vs only samples. These are divided in the code with the main differences being how the cases and samples are being looped through and what is required to specify in the errors (case index and sample index, vs only sample index).
- The rules in the `order_validation_service` and for all workflows. Although RML and Fluffy seem to be exceptions, these are not yet implemented and can be disregarded for this issue.
- A unit test is always good to have.

**Comment by RasmusBurge-CG** [comment]
It seems like there is a case sample rule:
in: cg/services/order_validation_service/rules/case_sample/rules.py
```
def validate_container_name_required(
    order: OrderWithCases, **kwargs
) -> list[ContainerNameMissingError]:
    errors: list[ContainerNameMissingError] = []
    for case_index, case in order.enumerated_new_cases:
        for sample_index, sample in case.enumerated_new_samples:
            if is_container_name_missing(sample):
                error = ContainerNameMissingError(
                    case_index=case_index,
                    sample_index=sample_index,
                )
                errors.append(error)
    return errors
```


I was under the impression that adding a case sample rule was also in the scope of this issue? :)

**Comment by RasmusBurge-CG** [comment]
https://github.com/Clinical-Genomics/cg/pull/3736
