### ISSUE TITLE
Bug: Copied delivery link in TB does not correspond caesar file structure

### ISSUE THREAD

**Issue by eliottBo** [Clinical-Genomics/cg#3728]
**Describe the bug**
(mip-dna, fastq-analysis, case `fairsheepdog`)
The path to the delivered files in caesar when copying from the Trailblazer order view button (`/home/cust185/inbox/1000237`) indicates the ticket ID as the directory. However, in caesar the directory is called by the sample name (`/home/cust185/inbox/2024-30512-03/`)

If we, in production, do not check caesar, we send an incorrect path to the customer.

**To Reproduce**
1. Go to TB
2. search for fairsheepdog in all analyses
3. click on the case name of the completed mip-dna analysis
4. click the copy delivery message button next to the case name
5. paste it in an editor
6. log in to caesar
7. go to `/mnt/cg_deliver/chroot//home/cust185/inbox/` (dir name is sample name)

**Expected behavior**
The link generated by the "copy delivery message" in TB reflects the actual path in caesar (starting from `/home`)
**Additional context**

**Comment by diitaz93** [comment]
Could not be replicated when running the `cg deliver` command. The suspicion is that the customer moved the file. Closing
