### ISSUE TITLE
Delivery file tags restructuring

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#3729]
# Description

Fetching of delivery files is workflow centric, perhaps a data delivery centric approach would be beneficial and reduce logic complexity. 

See initial discussion here: https://github.com/Clinical-Genomics/cg/pull/3721

## Clarification
After the refactoring of fastq -> raw-data, the delivery of raw-data cases will look for both fastq and bam files. This ideally should be based on delivery type instead of only workflow

**Comment by diitaz93** [comment]
We won't fix the delivery logic for now as it works. This is a proposal for improvement that would be prioritised very low. Closing
