### ISSUE TITLE
Automatic delivery message for uploaded analyses

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#3730]
As a production member,
I want a delivery message to be sent out when an analysis is complete and fully uploaded,
So that customers could start analysing the data, and paving the way for fewer manual steps in the delivery of data.

# Acceptance Criteria

- [ ] Given that the conditions below are met for a workflow, a message, similar to the one currently available through the cigrid-ui's "Copy delivery message".
    - If we deliver only raw data, we only require the data amount to be enough, and then we can count it as ready
    - If we deliver analysis files, the analysis should have a QC check post-analysis, checking if the analysis is reliable and ready
    - The analysis is uploaded

Given the conditions required above, the following workflows are eligible for this message:

```yaml
- balsamic
- balsamic-umi
- mip-dna
- mip-rna
- fluffy
- mutant
- rnafusion
- tomte
- raw-data
```

Two types of services are created:
   - One that will be run after the upload command is run, bulking together uploaded analyses from the same order and sending out one message per order
   - One that will send out a delivery message to a ticket when asked, which could then be accessed by cigrid-ui in the "deliver" button

# Notes

- Additional information.
- Dependencies.
- Related user stories.

# Implementation plan

- [ ] Work item 1
- [ ] Work item 2

**Comment by beatrizsavinhas** [comment]
To consider: Should customers receive a message for every completed+uploaded analysis? Or should an automatic message contain several analyses? And if so, when and how many?

**Comment by karlnyr** [comment]
To be reformatted when we have the project set-up.
