### ISSUE TITLE
Create orderform for microbial sequencing -  raw data delivery

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#3767]
### Description

Related to https://github.com/Clinical-Genomics/cg/issues/3338, we also need an orderform that the customers may use to place orders through the orderportal.

This orderform needs to have the following columns:

- name
- control - None, Negative, Positive
- priority
- Application tag - Same as those available from https://github.com/Clinical-Genomics/cg/issues/3338
- Buffer - Nuclease free-water, Tris-HCL, Other(yada yada)
- Container - Tube, 96 Well plate
- Container name
- If 96 Well plate, position
- Volume (ul)

**Comment by diitaz93** [comment]
## Technical refinement
- Create the excel sheet based on existing microbial one and remove unused fields (see columns above)
- Add the new sheets to the allowed sheets in cg
- Make sure the correct order type is sent to the front end when parsing the sheet
- Double check the excel order form parser
