### ISSUE TITLE
Long sample names becomes problematic in madeline files 

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#377]
As a scout user it is impossible to read some of the madeline files produced by CG 

Problem: 
Madeline abbreviates longer sample names. This is sometimes fine, but becomes a bother for trios from eg cust002, where names like 2019-00001-01 2019-00002-01 2019-00003-01 are shown as "2019-000..."

Steps to reproduce
  1. Investigate if there is a way to handle long sample names in madeline
  2. Implement solution

Expected outcome / suggested solution:
Madeline files with content that makes sense

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

**Comment by patrikgrenfeldt** [comment]
Could you test and see if #405 solves this issue?

**Comment by northwestwitch** [comment]
This was solved by #405, wasn't it?

**Comment by emiliaol** [comment]
Closing then
