### ISSUE TITLE
Increase the slurm job priority of decompression jobs on Hasta

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg#3804]
As a prod bioinfo member or customer,
I want spring decompression jobs to run with higher priority,
So that high prio re-runs aren't bottlenecked by a queue system bogged down by development jobs.

# Work impact

Answer the following questions:
- Is there currently a workaround for this issue? If so, what is it?
    - Manually upping the QOS of slurm jobs (NOTE: there are a minimum of 8(!) jobs per sample)
- How much time would be saved by implementing this feature on a weekly basis?
    - 0.5 to 1h of manual work. But we'll save up to DAYS of turn around time for deliveries.
- How many users are affected by this issue?
    - All customers ordering re-runs. All users working in prod.
- Are customers affected by this issue?
    - Yes. All re-runs are affected by this.

# Acceptance Criteria

- [ ] The default QOS of spring decompression jobs on Hasta is changed from low -> high

# Notes

- Additional information.
- Dependencies.
- Related user stories.

**Comment by Vince-janv** [comment]
## Technical refinement
- Make spring-fastq QOS = high
