### ISSUE TITLE
Add validation preventing ordering mip cases with samples as "unknown"

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3821]
As a production user,
I want there to be validation preventing customers from ordering cases which contain samples with status "unknown",
So that the corresponding mip analyses can successfully complete without errors.

# Work impact

Answer the following questions:
- Is there currently a workaround for this issue? If so, what is it?
    - No.
- How much time would be saved by implementing this feature on a weekly basis?
    - This is a somewhat rare issue as most of the orders are placed correctly. But when this does happen, the analyses start and run but cannot complete.
- How many users are affected by this issue?
    - All production users and customers. Analyses are also run unnecessarily as in the end, they cannot be completed.
- Are customers affected by this issue?
    - Yes, the analyses they request cannot be completed.

# Acceptance Criteria

- [ ] It is not possible to order a mip case containing all samples with status "unknown".

**Comment by Vince-janv** [comment]
Question to @Clinical-Genomics/prodbioinfo :
Should MIP-cases with ANY status "unknown" sample be prohibited or MIP-cases with ONLY "unknown" sample

**Comment by moahaegglund** [comment]
Just adding a note here: mip-dna can handle WGS samples with sex=unknown, it is exome samples where this is problematic. @jemten is it possible to add the same functionality to check gender in the analysis for exome samples?

**Comment by jemten** [comment]
I think @beatrizsavinhas is referring to setting the phenotype to unknown. I would have to double check but I think the problematic part is having all samples set to unknown. If the phenotype in one of the samples in a case is set to unknown and the other are affected and unaffected it should be fine. I would have to double check though. I agree that this is a check we should have in the pipeline as well. Currently the error message in MIP isn't clear at all.

**Comment by moahaegglund** [comment]
Oops, completely misread this one! sorry @beatrizsavinhas 🙈

**Comment by karlnyr** [comment]
@Vince-janv @jemten We had another case today, `closingshepard`, and it cannot handle if there is ANY sample in a case with status unknown.

**Comment by jemten** [comment]
> @Vince-janv @jemten We had another case today, `closingshepard`, and it cannot handle if there is ANY sample in a case with status unknown.

Alight, that sounds bad. I'll look into it

**Comment by beatrizsavinhas** [comment]
Updated the acceptance criteria and move the issue to Technical refinement!

**Comment by Karl-Svard** [comment]
A new case in prod has showed up with this issue: `stirringcalf`

**Comment by diitaz93** [comment]
We will schedule a meeting to discuss this and https://github.com/Clinical-Genomics/cigrid-ui/issues/722 @jemten @karlnyr
