### ISSUE TITLE
Add HiFi Yield column to PacBio Sample Sequencing Metrics

### ISSUE THREAD

**Issue by fellen31** [Clinical-Genomics/cg#3825]
As someone who wants information about PacBio samples, 
I want to have a HiFi Yield column in the "PacBio Sample Sequencing Metrics" view of statusdb,
Since that is the most interesting metric to get (more so than read length, number of reads and quality). 

# Work impact

Answer the following questions:
- Is there currently a workaround for this issue? If so, what is it?
    - Take hifi reads x mean read length
- How much time would be saved by implementing this feature on a weekly basis?
    - very little
- How many users are affected by this issue?
    - a few
- Are customers affected by this issue?
    - no

# Acceptance Criteria

- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria 3
...

# Notes

- Additional information.
- Dependencies.
- Related user stories.

**Comment by Vince-janv** [comment]
# Technical refinement
- Show column
