### ISSUE TITLE
Support OF 1508:18 in the orderportal

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#383]
As a lab person, I want Orderportal to support OF 1508:18 so that it is clear that we use Kapa instead of Twist.

Contact: @annagellerbring 

Problem: 
The 1508:17 has no Kapa applikations and we'll be switching to Kappa after the summer vacations.

Steps to reproduce
  1. open the OF 1508, create order with PAx or EXx 
  1. import the excel in the order portal

Expected outcome / suggested solution:
  1. The samples should have the application PAxKTT or EXxKTT

Actual Outcome:
  1. The samples have the application PAxTTT or EXxTTT

Suggested solution: 
1. Copy applications PAxTTT and EXxTTT to PAxKTT and EXxKTT (only active ones) in the applications table in status db. `cg import application` -> get the applications from the cancer team
1. import prices for PAxKTT and EXxKTT to the application version table in status db  `cg import application-version` -> get the prices from VW
1. Update Orderportal to allow 1508:18 (change the constant VALID_ORDERFORMS in orderform.py)

Questions: 
Q: Can we rename PAxTTT and EXxTTT to PAxKTT and EXxKTT?
A: No, then we would be changing old samples to look like they had another application than they actually had
Q: Is 1508:18 already existing?
A: 

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by barrystokman** [comment]
> import prices for PAxKTT and EXxKTT to the application version table in status db cg import application-version -> get the prices from VW

@vwirta Can you send me the prices? Thanks!

**Comment by barrystokman** [comment]
> Copy applications PAxTTT and EXxTTT to PAxKTT and EXxKTT (only active ones) in the applications table in status db. cg import application -> get the applications from the cancer team

@emiliaol Can you send me the applications? Thanks!

**Comment by emiliaol** [comment]
Here are the applications:
https://docs.google.com/spreadsheets/d/1kS6cVZRvmi6kGpdI_2dG57LU4wcFl6HLu-wmXRlPtFI/edit#gid=16765201

**Comment by vwirta** [comment]
@barrystokman @emiliaol attached the price export document

I have also added the apptags we discussed today EOL
And there are a bunch of new app tags for cust001

[Prisexport 190703.xlsx](https://github.com/Clinical-Genomics/cg/files/3355484/Prisexport.190703.xlsx)

**Comment by barrystokman** [comment]
Thanks @vwirta. I deleted the file from your comment just in case it's not supposed to be public.
