### ISSUE TITLE
Bug: Not possible to generate delivery reports for external RNA samples

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3834]
**Describe the bug**
Not possible to generate delivery reports for external RNA samples due to missing data from lims.

**To Reproduce**
1. Run `cg generate delivery-report <case_id>` for a case with external RNA samples
2. Generation of the report fails due to empty data fields in LIMS.

**Expected behavior**
If the samples are external these checks for missing data in LIMS should be skipped.

**Comment by diitaz93** [comment]
## Initial technical refinement
@ChrOertlin will technically refine this as this require diving deep into the delivery report code

**Comment by Vince-janv** [comment]
Will close this as the frequency of external RNA-samples is extremely low. Will address this if we take on a new external-RNA project.
