### ISSUE TITLE
Add information of what cases are being delivered in the delivery message for analysis files deliveries

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#3846]
As a production member,
I want the delivery message to be altered when we are delivering only analysis files so that it includes information on what cases are being delivered,
So that we do not have to fetch that information from elsewhere or allow us to forget to inform the customer what cases they should expect to be transferred. Today, it would also allow for easier closing of tickets, as we would enforce the information about which cases have been delivered in the message.

# Work impact

Answer the following questions:
- Is there currently a workaround for this issue? If so, what is it?
    - Yes, one can find out the case name from other sources, but it does require you to leave the cigrid view
- How much time would be saved by implementing this feature on a weekly basis?
    - Maybe ten seconds per case?
- How many users are affected by this issue?
    - All production members
- Are customers affected by this issue?
    - Yes and no. Yes if we forget to do this manually.

# Acceptance Criteria

Given that a case(s) have delivery options: `fastq, fastq+analysis, analysis`:
- [ ] When we copy the delivery message for a case/cases the delivery message should first state which `case.name(s)` we have selected and started the transfer for, then give the path that we are transferring those cases to (as we currently do)

Suggested message for a single case:

```plaintext
Hi,

The analysis files for the following case are currently being uploaded to your inbox on Caesar:

<customer_case_name>

Available under:

/home/<customer>/inbox/<ticket_id>
```

Suggested message for multiple cases:

```plaintext
Hi,

The analysis files for the following cases are currently being uploaded to your inbox on Caesar:

<customer_case_name_1>
<customer_case_name_2>

Available under:

/home/<customer>/inbox/<ticket_id>
```

# Notes

- Additional information.
- Dependencies.
- Related user stories.

**Comment by diitaz93** [comment]
## Clarification

Add the case names to the delivery messages for which files have been delivered when the delivery type is: fastq, analysis or fastq+analysis
These are for cases that have not Scout delivery as for those the case is already in the url

**Comment by Vince-janv** [comment]
## Technical refinement
- Change the files: analysis_message.py, fastq_analysis_message.py and fastq_message.py in `cg/services/delivery_message/messages`
- Add a list of case.name to the the message.
- The case names should be split on newlines
