### ISSUE TITLE
The mip pedigree uses the term `case` instead of `family`

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#386]
MIP 7 uses key "case" instead of "family" in the pedigree file.

Problem: 
If the pedigree lacks the key "case" - MIP 7 will tell you so and not start.

Steps to reproduce
  1. Run MIP 7 with a pedigree file lacking the key "case"
  2. Error is displayed:
```
Pedigree file: livingox/livingox_pedigree.yaml cannot find mandatory key: case in file
```

Expected outcome / suggested solution:
1. Replace key "family: [PETNAME]"  with "case: [PETNAME]" to pedigree file created by cg

Questions: 
Q: 
A: 

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by emiliaol** [comment]
@henrikstranneheim Is this something you want help from TTN to do?

**Comment by henrikstranneheim** [comment]
It needs to be synced to the future cg MIP 7.1 feature branch. It is mostly a heads up and a reminder. We can plan who does what together later. This one should be really easy but it depends on how you want to generalize the workflows.

**Comment by emiliaol** [comment]
Cool, I'll put it on the BL though so we don't miss it as part of the update.
