### ISSUE TITLE
Bug: Unable to Submit Microbial Order on Stage

### ISSUE THREAD

**Issue by moedarrah** [Clinical-Genomics/cg#3862]
**Describe the bug**
I'm getting a 500 Internal Server Error on the Clinical-Genomics-UI stage when submitting a microbial order.

It looks like it has something to do with FreshDesk

`t 17 15:08:31 [cg-services-stage.scilifelab.se](http://cg-services-stage.scilifelab.se/) podman[2750097]: 2024-10-17 15:08:31 c7f5f455a285 cg.clients.freshdesk.utils[9] ERROR Failed request to Freshdesk: 401 Client Error: Unauthorized for url: https://company.freshdesk.com/api/v2/tickets - Status code: N/A, Details: {'code': 'invalid_credentials', 'message': 'You have to be logged in to perform this a>
Oct 17 15:08:31 [cg-services-stage.scilifelab.se](http://cg-services-stage.scilifelab.se/) podman[2750097]: 2024-10-17 15:08:31 c7f5f455a285 cg.meta.orders.ticket_handler[9] INFO Could not detected ticket number in name MyTestOrder`

**To Reproduce**
1. Go to: [https://clinical-stage.scilifelab.se/]( https://clinical-stage.scilifelab.se/)
2. Create a new order with the type Typing of microbial isolates
3. Submit the order

**Expected behavior**
On the Frontend:
<img width="1438" alt="Screenshot 2024-10-17 at 15 17 32" src="https://github.com/user-attachments/assets/eb2d7b37-530b-405c-8cb3-3f3096fb4f3b">

on the Backend log:
![image](https://github.com/user-attachments/assets/83ee0a64-aac2-4c56-ab0f-e8771e3c30b5)

**Additional context**

**Comment by moedarrah** [comment]
Hi, could you take a look at this? It seems to be related to FreshDesk. @Vince-janv  @ahdamin

**Comment by ahdamin** [comment]
@moedarrah, can you check it on https://clinical-stage.scilifelab.se/ ?

ENV variables on the stage server were not updated

**Comment by moedarrah** [comment]
It’s working now, thanks Amin  👍
