### ISSUE TITLE
Update of RML order form to include two new sets of index

### ISSUE THREAD

**Issue by AnnaZetterlund** [Clinical-Genomics/cg#3869]
A new version (1604-19) of the RML order form with new index sets is added to this issue. Please do your magic with the order portal! 
[1604-19_order_form_Ready_Made_Libraries.xlsx](https://github.com/user-attachments/files/17460792/1604-19_order_form_Ready_Made_Libraries.xlsx)

# Clarification
For RML-orders we store the indices available in a constant in the front-end. With new index-sets we need to add them to this constant. This can also we chosen in the excel sheet.

## Acceptance criteria
RML and fluffy orders are submittable using the new excel sheet.

**Comment by diitaz93** [comment]
## Technical refinement

### BE
- Update the excel sheet fixture (download the current one and add the current index to the new file)
- In the excel orderform parser we should bump the existing accepted excel sheet from 1604:17 to 1604:18

### Frontend
- Send the modified file to MOD
- In the file `indexSequence.ts` update the index object

### Testing
- Verify that the UDF sets in LIMS match the labelled group where the indices are added

# Important:
These PRs have to be merged simultaneously and with the approval of AZ/KN

**Comment by AnnaZetterlund** [comment]
I think it should be bumped from 1604:18 to 1604:19?

**Comment by diitaz93** [comment]
> I think it should be bumped from 1604:18 to 1604:19?

Fixed

**Comment by diitaz93** [comment]
Hej @AnnaZetterlund! I think the information page of the excel file you sent may be outdated, as the "Changes since last version" section and "Document name" hold the same changes as the 1604:18. Could you send an updated version?

**Comment by AnnaZetterlund** [comment]
[1604-19_order_form_Ready_Made_Libraries.xlsx](https://github.com/user-attachments/files/17619110/1604-19_order_form_Ready_Made_Libraries.xlsx)

**Comment by diitaz93** [comment]
Final version of orderform used @moedarrah : 
[1604.19.rml.xlsx](https://github.com/user-attachments/files/17620865/1604.19.rml.xlsx)

**Comment by mariarevenikioti** [comment]
Sent information e-mail to the relevant customers about the update.
New version of the Order Form uploaded to Freshdesk.
