### ISSUE TITLE
Bug: Control samples show up as 'Express' in Trailblazer

### ISSUE THREAD

**Issue by Karl-Svard** [Clinical-Genomics/cg#3889]
**Describe the bug**
Control cases show up as 'Express' priority in Trailblazer, no matter the level set in StatusDB. This is after a recent update that increased the priorities of the jobs on Hasta. See https://github.com/Clinical-Genomics/cg/pull/3816

![Screenshot 2024-10-24 at 14 44 33](https://github.com/user-attachments/assets/2ef4b91e-afb9-4d77-9d24-b67d61f445cb)

**To Reproduce**
1. Run any internal control case in prod or stage

**Expected behavior**
The priority of the TB analysis should be the same as the case in StatusDB. Another alternative is to add a brand new value like 'Control', but that might be better kept as a separate feature request.

**Additional context**
-

**Comment by Vince-janv** [comment]
## Technical refinement
- Change the parameter `slurm_quality_of_service` in `cg.apps.tb.api.TrailblazerAPI.add_pending_analysis` to `priority`
- Create method called get_trailblazer_priority(case_id) which returns the priority to send to TB
´´´python
    def get_trailblazer_priority(self, case_id: str) -> str:
        """Get Quality of service (SLURM QOS) for the case."""
        case: Case = self.status_db.get_case_by_internal_id(internal_id=case_id)
        priority: int = case.priority or Priority.research
        return map_to_trailblazer_priority(priority)
```
- Create a class `TrailblazerPriority` which is the same as the QOS one except it does not have maintenance
- Create a utils class that translate the int to the correct member of `TrailblazerPriority`
- Use `get_trailblazer_priority` in `cg.apps.tb.api.TrailblazerAPI.add_pending_analysis` to get the correct priority
