### ISSUE TITLE
Create MutantSampleFileFormatter

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#3907]
# Description

Create class MutantSampleNameGenerator

1. Create sample file names for mutant sample files

Reason: since we require to rename files in the upload as well as delivery this module should be atomic as possible for re-use.

Create class MutantSampleFileFormatter

responsibilities

1. create sample folders
3. create sample file names
4. rename sample files with appropriate names
5. Needs to concatenate fastq files
6. Make use of MutantSampleNameGenerator

# Implementation

Create class MutantFileFormatter that inherit SampleFileConcatenationFormatter

init super (requires concatenation service)
inject lims api

```Python
def format_files()
    formatted_files = super().format_files
    meta_data_files= _add_lims_meta_data(formatted_files)
    return self._format_sample_files(meta_data_files)
``` 

Add function s
```Python
def _add_lims_metadata():
# for sample file in formatted_files.sample_file
# call get lims meta data(sample_id)

    def get_lims_naming_metadata(self, sample_id -> str | None:
        region_code = self.lims_api.get_sample_attribute(
            lims_id=sample.internal_id, key="region_code"
        ).split(" ")[0]
        lab_code = self.lims_api.get_sample_attribute(
            lims_id=sample.internal_id, key="lab_code"
        ).split(" ")[0]

        return f"{region_code}_{lab_code}"

```

**Comment by Vince-janv** [comment]
Current naming is done by this function: `cg.meta.workflow.fastq.FastqHandler.get_concatenated_name`

**Comment by Vince-janv** [comment]
We should compare the new directory structure with the current one and notify the customer (via KN or MAR) if this will change. Just to not crash any automation they might have

**Comment by Vince-janv** [comment]
Can you add that the FASTQ files should be concatenated?

**Comment by ChrOertlin** [comment]
Closing completed when https://github.com/Clinical-Genomics/cg/pull/3916 merged
