### ISSUE TITLE
Fetch FASTQ files from sample bundles for FOHM upload

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#3910]
### Description

The  function: `cg.meta.upload.fohm.fohm.FOHMUploadAPI.link_sample_raw_data_files` fetches FASTQ files from the case-bundle of a mutant case. These are the same stored on the sample bundles except concatenated and renamed.

As part of https://github.com/Clinical-Genomics/improve-order-flow/issues/94 we want to deprecate FASTQ storage on cases. This requires the files to fetched and concatenated from the sample bundle when we upload them to FOHM.

### Acceptance criteria
- FASTQ files should not be fetched from the case bundle
- FASTQ files need to be identical and named the same way as they are now

### Notes
- The FOHMUploadAPI is a mess. I'd like to limit the scope to only touch the function mentioned above and possibly the init of the class

**Comment by ChrOertlin** [comment]
Closing completed when https://github.com/Clinical-Genomics/cg/pull/3916 merged
