### ISSUE TITLE
Generation of sample sheets hindering cleaning of Illumina runs

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/cg#3915]
## Description
- Illumina sequencing runs are not getting cleaned
- The cleaning relies on the timestamp of the sequencing folder (cleaning runs older than certain time)
- The timestamps of the folders seems to be always no more than 10 minutes old
- @Vince-janv did some experiments (see https://github.com/Clinical-Genomics/bug-reports/issues/16) and concluded that the system in charge of the generation of the sample sheets is the one updating the timestamp of the sequencing run folders (`cg demultiplex sample-sheet create-all`)
- The generation of the sample sheets is designed to overwrite the sample sheet in the directory (using `os.link()`) with the sample sheet in housekeeper if the later passes validation. This was designed to overwrite any sample sheet in an old format fetched from pdc.

**To Reproduce**
Turn off the sample sheet generator timer and the directories don't get their timestamps updated
See https://github.com/Clinical-Genomics/bug-reports/issues/16

**Expected behavior**
An Illumina sequencing run directory which has a valid sample sheet will not have its time stamp updated.

**Comment by Vince-janv** [comment]
## Technical refinement

In `cg.apps.demultiplex.sample_sheet.api.IlluminaSampleSheetService._use_sample_sheet_from_housekeeper` add the line `if sample_sheet_path.samefile(run_directory_data.sample_sheet_path):` before the overwriting of samplesheet
