### ISSUE TITLE
Update Order Form for Clinical samples and Externally sequenced samples for Taxprofiler

### ISSUE THREAD

**Issue by mariarevenikioti** [Clinical-Genomics/cg#3932]
A new version (1508-32) of the 'Clinical samples and Externally sequenced samples' (CE) Order Form with Taxprofiler added as a Data Analysis option is added to this issue.

[1508-32_Order_Form_Clinical_samples_and_Externally_sequenced_samples.xlsx](https://github.com/user-attachments/files/17714889/1508-32_Order_Form_Clinical_samples_and_Externally_sequenced_samples.xlsx)

# Clarification
For CE-orders we now have the Taxprofiler pipeline as a Data Analysis option.

## Acceptance criteria
Clinical- and externally sequenced samples as well as Taxprofiler pipeline orders are submittable using the new excel sheet.

**Comment by diitaz93** [comment]
Implemented in https://github.com/Clinical-Genomics/cg/pull/3935
