### ISSUE TITLE
Remove feature to link order to existing ticket

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#3942]
As a developer,
I want to remove the existing ticket logic when ordering,
So that we don't have to maintain that logic in the already complex order logc

# Work impact

Answer the following questions:
- Is there currently a workaround for this issue? If so, what is it?
    - N/A
- How much time would be saved by implementing this feature on a weekly basis?
    - Aggregate gains everytime we need to touch the ordering logic
- How many users are affected by this issue?
    - back-end devs
- Are customers affected by this issue?
    - No

# Acceptance Criteria

- [x] The FE option to connect to a ticket is removed
- [x] All logic pertaining to the existing ticket linking is removed
...

# Notes
- This feature was used regularly by one customer and very sporadically for some research projects
- @AnnaZetterlund has communicated with the customer to use our normal ordering flow 🙏

**Comment by diitaz93** [comment]
## Technical refinement

### FE
- Remove the checkbox in the order portal

### BE
- Remove the logic regarding connect to ticket in the OrdersAPI
- Remove the extra validation in the orders endpoint

**Comment by ahdamin** [comment]
[BE](https://github.com/Clinical-Genomics/cg/pull/4013) and [FE](https://github.com/Clinical-Genomics/clinical-genomics-ui/pull/623) PRs are ready. @diitaz93 Feel free to merge!
