### ISSUE TITLE
Improve the Delivery Message for RAW-DATA 🥩

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg#3949]
As a prod-bioinfo member that is delivering raw-data,
I want a delivery message to reflect what reached the required amount of reads and what did not,
So that we can give a clear status to the customer.

### Clarification 

The current message is this:

```
Hello,

The fastq files for the following samples have been uploaded to your inbox on Caesar:

Sample1
Sample2
Sample3

Available under: 

/home/custXXX/inbox/666666666
```

A danger with the current way this is implemented and this bug https://github.com/Clinical-Genomics/cg/issues/3948, is that the customer does not know what is delivered and what is going to get re-sequenced. 

# Work impact

Answer the following questions:
- Is there currently a workaround for this issue? If so, what is it?
    - Note all the sample that did not reach the required amount of reads.
- How much time would be saved by implementing this feature on a weekly basis?
    - Hours.
- How many users are affected by this issue?
    - All prod-bioinfo members.
- Are customers affected by this issue?
    - Yes, the status of the samples becomes confusing.

# Acceptance Criteria

- [ ] New smarter delivery message:

```
Hello,


The following sample did not reach the required amount of reads, and will be delivered at a later time:

Sample3

The fastq files for the following samples have been uploaded to your inbox on Caesar:

Sample1
Sample2

Available under: 

/home/custXXX/inbox/666666666
```

...

# Notes

- Additional information.
- Dependencies.
- Related user stories.

**Comment by diitaz93** [comment]
Already refined by production, moving to technical refinement

**Comment by Vince-janv** [comment]
The logic we have currently is:
1. Deliver all the RAW-DATA we have, regardless of required amount of reads.
2. The delivery message gives you all the samples in the case you have selected.

We believe introducing logic for required reads in the delivery message is not the right way to go. Informing the customers of which samples have been sent to re-sequencing is not the task of the delivery-message. This should be done in some other way.

**Comment by RasmusBurge-CG** [comment]
> This should be done in some other way.

In what way? It sounds like you have a great scalable idea that doesn’t involve manual checking. :)
