### ISSUE TITLE
New order tickets should have the status "pending"

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#3999]
As a production member,
I want tickets that are generated when a new order is submitted set with the status "pending",
So that we can have clearer filtering for what tickets we have yet to process into LIMS.

# Work impact

Answer the following questions:
- Is there currently a workaround for this issue? If so, what is it?
    - Yes, we go through all tickets with type order instead of having the possibility to filter on the status
- How much time would be saved by implementing this feature on a weekly basis?
    - 15-20 minutes per week 
- How many users are affected by this issue?
    - All members in production, especially the lab members
- Are customers affected by this issue?
    - No

# Acceptance Criteria

- [ ] When we open an order ticket it should have the status "pending"

# Notes

- Additional information.
- Dependencies.
- Related user stories.

**Comment by karlnyr** [comment]
Quite literally would just have to change this one line:

https://github.com/Clinical-Genomics/cg/blob/2456a194592c15c5073929dd12fd412b0b6e90ec/cg/clients/freshdesk/models.py#L18

from `status: int = Status.OPEN` to `status: int = Status.PENDING`

**Comment by parradam** [comment]
Hey there! I'm happy to take this one if there are no objections. I've had a read through the contributing guidelines - this would be my first OSS contribution!

- Are any tests required, or is this considered trivial enough?
- Am I right in thinking that this is a prerequisite for #4006 ?
- I would have to get my environment set up tomorrow and fork the repo, but then I would plan to go through the workflow of generating an order ticket before making the change

Thanks!

**Comment by Vince-janv** [comment]
> Hey there! I'm happy to take this one if there are no objections. I've had a read through the contributing guidelines - this would be my first OSS contribution!
> 
> * Are any tests required, or is this considered trivial enough?
> * Am I right in thinking that this is a prerequisite for [Order tickets containing ONLY existing samples should have the status "open"  #4006](https://github.com/Clinical-Genomics/cg/issues/4006) ?
> * I would have to get my environment set up tomorrow and fork the repo, but then I would plan to go through the workflow of generating an order ticket before making the change
> 
> Thanks!

@parradam Hi Adam.

Thank you for your offer to work on this. We're a tight group of developers within our organisation working on this repo, and we're not accepting outside collaborators. The repo is open source to allow other sites doing similar work to make use of it.

I've removed the label that suggested this could be picked up by outside collaborators. I apologise for the confusion and hope you find another repository where your help will be appreciated.

Best regards,
Vincent Janvid

**Comment by ChrOertlin** [comment]
Completed
