### ISSUE TITLE
Priority of FCs in the requested queue is possible to set manually for reruns

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#40]

**Comment by emiliaol** [comment]
As a member of team production I want to be able to set in which order requested flowcells are being fetched back from PDC.

**Comment by henrikstranneheim** [comment]
@emmser Do we still need this?

**Comment by emmser** [comment]
Not if we from now store all fast-files on hasta, more easily used for re-runs

**Comment by vwirta** [comment]
This has limited value, hence closing for now. Reopen if needed.
