### ISSUE TITLE
Rewrite set sample to work dynamically with attributes

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#419]
As a developer I want the production team have dynamic code to set any value on sample objects so that we don't have to extend the set method anymore so it becomes more maintainable.

Problem: 
Each time we want to set a new attribute on samples we have to extend the set sample method and the risk of new bugs increase

Steps to reproduce
1. login to hasta
1. us
1. cg set sample --attribute "data_analysis" --value "balsamic" LIMSID SIGN 

Expected outcome/suggested solution:
The attribute data_analysis should have been set both in status db and LIMS and a comment should have been added to the sample saying it happened and when and by whom

Questions: 
Q: 
A: 

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt Think this one is done right?

**Comment by patrikgrenfeldt** [comment]
resolved by #606
