### ISSUE TITLE
Remove or fix dry flag on cg deliver inbox

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#420]
Remove or fix dry flag on cg deliver inbox

**Comment by henrikstranneheim** [comment]
@karlnyr Would you like to have a quick look at this one and see if this is still an issue and if so if you can implement a working dry-run flag?

**Comment by karlnyr** [comment]
Sounds good, I'll give it a quick look @henrikstranneheim !

**Comment by henrikstranneheim** [comment]
This already done! Most likely when @moonso refactored and extended the cg delivery command.
