### ISSUE TITLE
Add library ID to fastq file name

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#430]
When marking duplicates for instance, it is vital to know the molecular library of the sample.

Problem: 
This is not propagated to the analysis workflows (at least MIP).

Steps to reproduce
  1. Go to the coffee machine on G4, small kitchen
  2. Put a cup in the dispenser
  3. Press to get any coffee
  4. Water should now be dripping from the right side of the machine. Move the microwave for better view.

Expected outcome / suggested solution:
It would be great if this could be added in the file name of the corresponding fast file e.g. {LANE}_{DATE}_{FLOW-CELL}_{SAMPLE-ID}_{LIBRARY_ID}_{BARCODE-SEQ}_{DIRECTION 1/2}.fastq[.qz]
Then we could get the library id from the filename and use it properly in all steps required by the workflows.

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by vwirta** [comment]
Can you please clarify what is the difference between sample ID and library id? @henrikstranneheim

**Comment by henrikstranneheim** [comment]
Sure! 
Sample ID is our LIMS ID.
Library ID is the molecular library from the sequencing preparation.
You can read more here: https://gatkforums.broadinstitute.org/gatk/discussion/6472/read-groups

**Comment by emiliaol** [comment]
I'll get back to you on planning this and clarifying some things for development. I'm unfortunately not able to give you a time estimate on when we can do this, but please let me know where on the urgent scale this is, that would be great.

**Comment by henrikstranneheim** [comment]
Not urgent

**Comment by Mropat** [comment]
@henrikstranneheim is this still relevant?

**Comment by henrikstranneheim** [comment]
It is, but it is a quality of life thing, and current settings work good enough. I will close this as I do not see us having a realistic chance of completing this in the near future. Will reopen if needed
