### ISSUE TITLE
[bug] `cg transfer flowcell` can store HJJM2CCXX

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#431]
As a bioinfo prod team member I want to be able to link flowcell HJJM2CCXX to housekeeper so that I can start analysis of meetstag as requested by customer.

Problem: 
I get the following error when trying to transfer the FC after demultiplexing:
<img width="984" alt="Skärmavbild 2019-09-17 kl  15 49 52" src="https://user-images.githubusercontent.com/12113434/65047796-57d3d180-d963-11e9-82de-f2bb76da21b7.png">

I think this problem is related to bundle versions not being properly removed in housekeeper when deleting them using `housekeeper delete bundle`, so most likely one of the samples on this FC has an empty bundle in the hk database.

Steps to reproduce
  1. On hasta as a production user: `up`
  2. `cg transfer flowcell HJJM2CCXX`
  3. The error message from above should appear.

Expected outcome / suggested solution:
That the samples are correctly linked to housekeeper and the FC is set to `ondisk` in status db.

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by emiliaol** [comment]
Might not be necessary to fix in cg, but perhaps just find the faulty sample in housekeeper. There is an issue regarding `housekeeper delete bundle` already.

**Comment by ingkebil** [comment]
I removed all sample bundles of this flowcell and readded the flowcell.

First, check which samples don't have a bundle. Those are potentially a bundle without version:
```
[0|0|208] [kenny.billiau@hasta:~] [P_main] $ for sample in $(cgstats samples --flowcell HJJM2CCXX); do echo $sample; housekeeper get $sample; done
ADM1240A1
ADM1241A1
ADM1242A1
ADM1239A1
ADM1252A1
ADM1245A1
ADM1244A1
ADM1243A1
```
Looks like all of them are affected.

Remove those bundles! If I am wrong and I am removing the wrong sample bundle, the database constraints will prevent me from removing the bundle entry :)

```
[0|0|208] [kenny.billiau@hasta:~] [P_main] $ for sample in $(cgstats samples --flowcell HJJM2CCXX); do echo $sample; housekeeper get $sample; mysql -u username -ppassword housekeeper -h host -P port -e "DELETE FROM housekeeper.bundle where name = '$sample';" done
ADM1240A1
ADM1241A1
ADM1242A1
ADM1239A1
ADM1252A1
ADM1245A1
ADM1244A1
ADM1243A1
```

TADA!

**Comment by ingkebil** [comment]
```
[0|0|205] [kenny.billiau@hasta:~] [P_main] $ cg transfer flowcell HJJM2CCXX
...
flowcell added: HJJM2CCXX
```

**Comment by emiliaol** [comment]
Thanks!
