### ISSUE TITLE
skip creating MAF cases for RNA orders

### ISSUE THREAD

**Issue by b4ckm4n** [Clinical-Genomics/cg#436]
As a production person, I want cg to skip creating MAF cases for RNA orders, so that I don't have to investigate analyses that were not meant to be started.

Contact: PG, EOL

Steps to reproduce:
1. RNA samples can be ordered with e g application prep category tag 'WTS' and Data Analysis 'fastq'
1. a case is created by cg, with customer set to cust000 and panels set to OMIM-AUTO and Action set to Empty
1. crontab for analysis-auto.sh picks up and tries to start created case, resulting in an error: `KeyError: 'pop from an empty set' ` (or something else, tries to start it with mip and complains about analysis type (prep category))

Expected outcome:
Cases are created for RNA fastq orders, but not started through MIP - instead we want it to run through MIP RNA (when this is in place)

Suggested solution:
1. `cg analysis auto`, should only process samples with Analysis Type property WGS or WES
1. fix the families_to_MIP_analyse method, to use the Analysis_Type instead of the Data_Analysis 
1. mixed cases should fail
1. verify the patch

DoD:
1. `cg analysis auto` only starts MIP_rd_DNA

Demo:
1. run families_to_MIP_analyse to get a set of MIP_rd_DNA cases
2. change application type for one of them
3. run families_to_MIP_analyse to get a set of MIP_rd_DNA cases, with the changed case missing from the set

**Comment by patrikgrenfeldt** [comment]
Resolved by #464
