### ISSUE TITLE
Heads up balsamic 3.2.0 changes

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#453]
BALSAMIC main environment updated to: `P_BALSAMIC-base_3.2.0`

And to create a config file, now it requires the path for container. If the sample is WGS it won't need a target_bed file.

```
balsamic config case 
    --panel <path to bed-file> located in:
      /home/proj/production/cancer/reference/panel/ (Note if sample is WGS, there is no need to provide a panel bed file)
    --reference-config /home/proj/production/cancer/reference/GRCh37/reference.json
    --singularity /home/proj/production/cancer/BALSAMIC/BALSAMIC/containers/BALSAMIC.3.2.0.sif
    --tumor <path to read 1 or 2 for tumor sample> 
    --normal <path to read 1 or 2 for normal sample (if paired analysis)>
    --case-id <case_id> 
    --analysis-dir /home/proj/production/cancer/cases
```

More on AMdoc under unpublished (but shard with prod people) document with the following name:
`BALSAMIC analysis for whole genome, whole exome, and panel`

Notes:
- Removing all the old environments for BALSAMIC
- `-p/--panel` option will be depricated and instead replaced with `--target-bed` All panel files will be stored on the following repository instead: https://github.com/Clinical-Genomics/target_capture_bed
- Singularity container version (last 3 digits) should match with current conda env

**Comment by emiliaol** [comment]
@hassanfa Seems the latest changes to the cg config to balsamic options isn't correct, what's the name of the most recent enviroment and singularity container to use?

**Comment by hassanfa** [comment]
Emilia,

Which parameters are you referring to?

**Comment by emiliaol** [comment]
Like I said, environment and singularity container. But this is fixed now. I'll close the issue
