### ISSUE TITLE
[sever bug] Concatenation concats fastq files twice for some samples

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#454]
I noticed a sever bug today, it might be also related to an issue @moahaegglund brought up couple of days ago about Housekeeper storing files twice.

Some reads end up twice due in the final concatenated file. Example:

```
hasta /home/proj/production/cancer/cases/stillaphid/analysis/fastq Conda env: S_BALSAMIC-py36_190905_HFA Git repo: None Git branch: None
$zcat concatenated_ACC5810A60_XXXXXX_R_1.fastq.gz | fgrep A00689:64:HLYVJDSXX:3:1673:26467:4429
@A00689:64:HLYVJDSXX:3:1673:26467:4429 1:N:0:TCGGACAACG+CCATCCAGAC
@A00689:64:HLYVJDSXX:3:1673:26467:4429 1:N:0:TCGGACAACG+CCATCCAGAC
```
This is a potentially harmful.

It seems housekeeper kept the same file twice , and due to the way concatenation is being done, same fastq file ends up in the final file twice. Or could this line be the culprit? I don't know.

https://github.com/Clinical-Genomics/cg/blob/080fce09538f56d14830d17af4af339d3e5a2c66/cg/apps/balsamic/fastq.py#L116

Affected cases so far are:
```
actualbobcat
actualguinea
brightmite
caringpiglet
casualfox
choicelion
closekoala
daringrhino
drivenurchin
enoughskunk
exoticcrow
finerswine
growngecko
handyadder
helpedboar
humanewhale
livingmagpie
masterhorse
maturerobin
modestmacaw
movedshark
primehusky
robustpika
sacredcorgi
squarellama
stillaphid
stillbeagle
subtlezebra
superbbird
```

@ingkebil @emiliaol I don't know the impact of this, maybe it just affected some cases and not all. Or could it be due to demux (as Moa mentioned the other day)?

**Comment by hassanfa** [comment]
Note: Moa already told me about duplicate files, but it seems concatenation should've mitigated this issue given the fastq files were different. Thus probable bug.

**Comment by hassanfa** [comment]
I have a suggestion to create an md5 hash of each fastq file for each lane and avoid concatenating same files with same md5.

**Comment by hassanfa** [comment]
Kenny, after operations meeting we forgot to talk about the strategy to ensure we mark duplicate fastq files from multiple demux runs. Of course, this will not address duplicate reads, but at least exactly identical files won't end up in same location. Here what I thought to do.

1. There is `filecmp` in python to do a shallow copy to files. Slow with non-shallow, but better than nothing.

2. There is `cmp` command we can use to compare files. Still too slow, but we can take first XXXX bytes, or random bytes. Can be implemented as bash script, very handy.
```bash
for file1 in *fastq.gz
do
    for file2 in *fastq.gz:
    do
        [ file1 != file2] && (cmp -s <(head -n1000000 file1) <(head -n1000000 file2) && echo $file1" is similar to "$file2)
    done
done
```

3. Third option is to compare files in first _N_ bytes of file. Something like below:
```python 
def compare_file(file1, file2, max_iter=100):
    file_diff = True
    iter_comp = 0
    # similar_count to decide if more than five chunks are similar and break
    similar_count = 0
    chunk_size = 1024
    while iter_comp < max_iter:
        with open(file1, 'rb') as fp1, open(file2, 'rb') as fp2:
            if fp1.read(chunk_size ) == fp2.read(chunk_size ):
                similar_count +=1
            if similar_count > 5:
                file_diff = False
     return file_diff
```

**Comment by ingkebil** [comment]
Thanks for the input!

Some additional info on why this problem is appearing. We used to have the index sequence in the file name, which has been replaced by the index name, which is nothing more then the line number in the samplesheet. In a certain sense, if we can have the index sequence in the file name again, then a redemux with two different samplesheets which would result in the same file names.

The 3rd option you propose would be the way to go to compare files imho. Entrypoint would be in `cg transfer flowcell`.

**Comment by hassanfa** [comment]
Makes sense why it is happening. Good luck. 👍

**Comment by hassanfa** [comment]
Seems like this happened again, related deviation is 41 and 42 on AMDoc from exactly a year ago :-)__

**Comment by Mropat** [comment]
Solved
