### ISSUE TITLE
cust080 wants to have a master list

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#471]
cust080 wants all their cases to always be analysed with the following panels:
**Full name - panel ID**
MSK Impact - MSKI
leukemi SV - LEUSV
leukemi SNV - LEUSNV
kidney cancer - NJU
Endocrine tumors - ET
Inherited cancer - Inherited cancer
Inherited myeloid - IMY
PGL - PGL

In order for the customer not to have to add all of these panels manually when making a new order a so called "master list" for cust080 like the one for cust000, cust002, cust003, cust004 and cust042 would be helpfull (see /cg/meta/analysis.py).

**Comment by Mropat** [comment]
@moahaegglund @henrikstranneheim  need help prioritizing importance of this feature

**Comment by henrikstranneheim** [comment]
@moahaegglund Great! Closing
