### ISSUE TITLE
Switch off SV part of MIP when apptag is "PAN*"

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#476]
As a member of produktion I want MIP not to fail in the SV part of MIP for PAN* samples so that I do not have to spend time on manually fixing this.

Problem: 
MIP will fail for very small cancer panels, requiring manual effort.

Expected outcome / suggested solution:
Make cg use a different MIP config when the samples have the "PAN*" apptag. This MIP config will have the SV part switched off.  

To do:
- [ ] make cg use the new config when starting PAN samples.
 
Questions: 
Q: Does the same problem occur for tea?
A: Yes.

**Comment by emiliaol** [comment]
But we still haven't made cg use the new config when analysing PAN samples, right?

**Comment by henrikstranneheim** [comment]
No, not yet

**Comment by emiliaol** [comment]
Re-opened for automatic use of new config
