### ISSUE TITLE
retry ticket creation

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#478]
As an orderportal user, I would like the system to retry creating my ticket so that I don't end up having no ticket for my order.

Problem: 
The system sometimes fails at creating a ticket:
189531-2019-11-19 09:15:48 clinical-db.scilifelab.se urllib3.connectionpool[1830] DEBUG https://clinical-scilifelab.supportsystem.com:443 "POST /api/tickets.json HTTP/1.1" 500 49
189532:2019-11-19 09:15:48 clinical-db.scilifelab.se cg.meta.orders.api[1830] WARNING <Response [500]>

Steps to reproduce
  1. Create a lot of orders

Expected outcome:
All orders get a ticket

Actual outcome:
Some orders (like 2 a month) gets a 500 as response

suggested solution:
Retry a couple of times  creating ticket whenever it fails

Questions: 
Q: 
A:

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by Mropat** [comment]
@henningonsbring @patrikgrenfeldt 
Need help evaluating whether this needs to be addressed immediately or in new orderportal

**Comment by henningonsbring** [comment]
I notice this is an old issue, I do not know if this is still a problem, I have never heard about it
