### ISSUE TITLE
Enable concurrent work on pipeline integrations cg/store

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#494]
As a developer, I want to separate the pipeline integrations into files  so that I know where to put my pipeline specific code

Problem: When I change something pipeline specific I'm afraid that I will break things for other pipelines

Steps to reproduce
  1. Go to cg repo
  2. open cg/store/
 
Expected outcome:
There is separate files for my specific pipeline so I know where to develop like 
cg/cli/store/balsamic.py
cg/cli/store/microsalt.py etc

Actual outcome: 
There is just one file store.py that contains all the code for all the pipelines 

Questions: 
Q: 
A:

**Comment by emiliaol** [comment]
@patrikgrenfeldt @henrikstranneheim Part of what you have done and merged already?

**Comment by henrikstranneheim** [comment]
I would say this is done
