### ISSUE TITLE
Tissue type should be passed on from lims (is it there?) to Scout.

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/cg#497]
So that is saved and displayed in the case page.
Maybe the option is already there, I don't know. To be checked and eventually implemented.

**Comment by emiliaol** [comment]
We pass it to the delivery report via cg so maybe that can be used for the upload as well?
Want this on the backlog?

**Comment by northwestwitch** [comment]
> We pass it to the delivery report via cg so maybe that can be used for the upload as well?
> Want this on the backlog?

Sure, thanks!

**Comment by hassanfa** [comment]
👍 This is useful for balsamic as well since cancer/tissue type is needed for scout upload. I'll keep my eyes open when I find out more about this, and please do let me know as well @northwestwitch if you see how-to.

**Comment by northwestwitch** [comment]
I could start working on this today if nobody has already started!
