### ISSUE TITLE
mip pedigree contains the bed file path from status db for the "capture_kit" value

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#500]
As a prod bioinfo team member I want that capture_kit value in mip pedigree to contain the bed file complete name so that I don't manually have to change the naming in status db for analysis of all panel samples.

Problem: 
The capture_kit value is now filled in from the `Sample` `Capture Kit` UDF in status db when created by `cg analysis config` but mip cannot figure out which bed file in the reference folder to use for the analysis based on this and the automatic start fails. To avoid this you can add the full file name (eg GMCKSolidv4.bed) to the `capture_kit` value in the pedigree.

Expected outcome / suggested solution:
1. `cg analysis config` looks up the `Bed version` `Filename` value in status db based on the value in `Sample` `Capture Kit` in status db. This value is in most cases based on a values in the `Bed` table in status db.

Questions: 
Q: 
A: 

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by henrikstranneheim** [comment]
Fixed in: https://github.com/Clinical-Genomics/cg/pull/605
