### ISSUE TITLE
Decouple chanjo and cg

### ISSUE THREAD

**Issue by adrosenbaum** [Clinical-Genomics/cg#507]
Decouple chanjo from cg

Problem: 
Currently _chanjo_ needs to be installed on the same environment as _cg_, and _cg_ uses the chanjo-api to interact with the database. The goal is to decouple chanjo from scout, and cg interacts with chanjo using its CLI. The steps needed to achieve this goal is to

- Prepare the chanjo CLI to be able to do all of the operations that is currently done through the chanjo-api
- Create new environments for chanjo
- create update scripts for chanjo (Currently it seems chanjo is installed with pip from PyPI as a resource of cg)
- Change the code in cg to interact with the CLI.

**Comment by henrikstranneheim** [comment]
@adrosenbaum Is this one done?

**Comment by adrosenbaum** [comment]
Yes! sorry, forgot to move 😃
