### ISSUE TITLE
Add `mip-dna` tags to MIP DNA bundles

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#508]
As a <type of user>, I want <some goal> so that <some reason>.

Problem: 
When adding MIP RNA bundles to HK, we assign tags `mip-rna` to the files in the bundle. Analogously, MIP DNA bundles should get the tag `mip-dna`.

Steps to reproduce
tbd

Expected outcome / suggested solution:
tbd

Questions: 
Q: 
A: 

@emiliaol Let's sit together and refine this :roll_eyes: 

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by henrikstranneheim** [comment]
Done in: https://github.com/Clinical-Genomics/cg/pull/621
