### ISSUE TITLE
Simplify parsing of pipeline paths and files in cg (RNA)

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#534]
As a MIP pipeline developer, I want cg to process `output-files.yaml` instead of the current files so that I can change the paths in the current files without worrying about breaking cg.

Problem: 

Expected outcome / suggested solution:

Questions: 
Q: What would be a useful way to contain this functionality?
A: Up to developer, class for reusability of code?
Q: where will the yaml file be found?
A: assume in root, ask HS.
Q: What is the root of the file called?
A: Something other than store.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by barrystokman** [comment]
See also https://github.com/Clinical-Genomics/cg/issues/536

**Comment by henrikstranneheim** [comment]
@barrystokman Seems done! I will close it. Reopen if you disagree
