### ISSUE TITLE
Update status-db for bed files / capture kit

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#535]
As a bioinfo/lab person, I want to be able to find the correct capture kit bed file and name to match bioinfo analysis and lims.

Problem: 
Names are complex  and file names are not following same standard. The standard for these files are now ready: https://github.com/Clinical-Genomics/target_capture_bed/tree/file_name_convention#summary

There are two pieces that are important for lab: shortname and bioinfo: filename.

Expected outcome / suggested solution:
Status-db to be update with correct meta data from https://github.com/Clinical-Genomics/target_capture_bed/tree/file_name_convention#summary

In https://clinical-api.scilifelab.se/admin/bed/ : Name --> ID or Shortname
In https://clinical-api.scilifelab.se/admin/bedversion/ : Description to --> Shortname or ID

Possibly remove unnecessary info columns if no one is going to use them. These columns will be kept updated in https://github.com/Clinical-Genomics/target_capture_bed and it might be unnecessary to keep two locations updated. So maybe remove the following columns from status-db

Genes | Unique Transcripts | Transcripts With All Exons Covered | Transcripts With At Least One Exon Covered | Padding | Cosmic Snps | Non Genic Regions | Independent Segments
-- | -- | -- | -- | -- | -- | -- | --

Questions: 
Q: Do shortnames need to be updated in lims?
A: Yes.
Q: .
A: .

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by hassanfa** [comment]
@henrikstranneheim regarding _in silico_ bed files for MIP, what else do you think would be needed to update in status-db?

**Comment by hassanfa** [comment]
@patrikgrenfeldt Here are some of the updates. Updating clinical_api would be much appreciated.

**Comment by hassanfa** [comment]
@patrikgrenfeldt any updates on this? What information do we need to proceed?

**Comment by annaengstrom** [comment]
@patrikgrenfeldt @hassanfa This is a very important issue for the cancer workflow, and should be done asap. I would actually argue that the gain is medium of high because using the incorrect bed file is not good at all...

**Comment by patrikgrenfeldt** [comment]
> @patrikgrenfeldt Here are some of the updates. Updating clinical_api would be much appreciated.

Where is "here"? Is it the issue description? If we need to change the data I hope everyone can do that?

**Comment by hassanfa** [comment]
Wow... Come on dude, you sure know what " here " means 😟 and you sure know what I am refering to... Here as in this issue... 

You were in the cancer meeting when we discussed  updating bait set information ~two weeks ago. This issue is part of those discussions we had. Should I all the discussion we had here?

**Comment by patrikgrenfeldt** [comment]
You wanted to point my attention to this issue. OK, Thanks :) 

So I'm a bit confused about what needs to be done. This data structure change described above I think I understand. 
I wonder if we are also talking about changing the actual data as well, is that the urgency??

**Comment by hassanfa** [comment]
This is hilarious. You second comment shows you clearly knew what might be needed to be done. Yet you asked what "here" means.

Anyway, to answer your qu, I suggest the following:

- review the meeting material
- talk to ALy to find out why and how this is urgent

This will tell how we want to sync statusdb and thereafter lims&bioinfo with proper baitset name and bed file.

**Comment by annaengstrom** [comment]
I would like to suggest that:

In https://clinical-api.scilifelab.se/admin/bed/ : Name --> shortname

**Comment by patrikgrenfeldt** [comment]
![IMG_20200221_122920000](https://user-images.githubusercontent.com/6697636/75031248-1614fd00-54a6-11ea-9a50-1ef54f8203c1.jpg)

**Comment by annaengstrom** [comment]
Updating Bed Version in statusdb:

**short   name** 
 - [ ] lymphomatic_2.1
- [ ] gi_cfdna_3.1
- [ ] gmck_solid_4.1
- [x] gms_myeloid_5.2
- [ ] lymphoma_6.1
- [ ] gms_lymphoid_7.1
- [ ] exome_8.1
- [ ] exome_refseq_9.1

**Comment by patrikgrenfeldt** [comment]
Bra jobbat!
Ska vi stänga ärendet eller är det något mer som ska göras innan vi kan anse att det är klart?

**Comment by annaengstrom** [comment]
> Bra jobbat!
> Ska vi stänga ärendet eller är det något mer som ska göras innan vi kan anse att det är klart?

Jag tycker vi kan stänga detta ärende.

**Comment by patrikgrenfeldt** [comment]
resolved by #563
