### ISSUE TITLE
_get_all_step_dates will not pick up dates for all process types.

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#545]
The function [_get_all_step_dates()
](https://github.com/Clinical-Genomics/cg/blob/afa5c1a0b4a21b222afcc43a6a9d88d040984f51/cg/apps/lims/api.py#L348) will not pick up dates for all process types. The function assumes the process has output artifacts which is not always the case. A process however, allways has input artifacts, so another way to find a specific process is to search by that. I suggest either to add a option to the funktion --search_by_input, or to create a new function for that.

**Comment by henrikstranneheim** [comment]
@mayabrandi Is this bug still in effect?

**Comment by mayabrandi** [comment]
This is fixed
