### ISSUE TITLE
KTH/KI exeptions in cg-invoice code

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#546]
Problem: 
The code in cg used to generate invoices is at some places customer specific. This would preferably be taken care of by storing more information in the database. Such as invoice templates. 

Steps to reproduce
 1. Identify all places where there are customer specific conditions in the code by searching for KI
2. Figure out if there is a good way to get rid of the KTH/KI conditions by adding information to the database
3. If it is possible, fix it.

Expected outcome / suggested solution:
code with no KTH/KI exeptions

**Comment by henrikstranneheim** [comment]
@mayabrandi What is the status of this?

**Comment by mayabrandi** [comment]
Nothing is done about it. I could take care of it at the same time as I’m working with NIPt in the invoicing

**Comment by henrikstranneheim** [comment]
@mayabrandi Is this still an issue?

**Comment by mayabrandi** [comment]
Wouldn't call it an issue. Rather a code cleanup. It has not been fixed though. As we have a project of decoupeling the invoicing from cg (make it a micro service), the whole invoicing app will be rewritten. I would say this enhancement can be fixed at the same time. So maybe just close this issue?

**Comment by henrikstranneheim** [comment]
Sounds like a good plan!
