### ISSUE TITLE
vogue specific data

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#547]
Problem: 
`vogue/parse/build/sample.py` of lims-specific functions to generate data for trending. This coud be lifted out and put into cg.

Steps to reproduce (i stora drag)
  1. Move vogue/parse/build/sample.py  into the lims API in cg
  2. Add to cg CLI: `cg upload vogue sample`
  3. Update Vogue CLI:` vogue load sample`  - this should take json as argument. 
  4. Remove `vogue/parse/build/sample.py` from vogue

Expected outcome / suggested solution:
`cg upload vogue sample
` should load data from lims into vogue. Samples existing in the database should not be changed by the command since it will do exactly the smae thing as `vogue load sample `does today

**Comment by henrikstranneheim** [comment]
@mayabrandi What is the status of this?

**Comment by henrikstranneheim** [comment]
@mayabrandi What is the status of this?

**Comment by mayabrandi** [comment]
This is no longer valid. Vogue lims code will be moved into cg_lims. That is not done yet since the lims projects continuously are being down prioritised :)
