### ISSUE TITLE
Balsamic delivery

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#555]
As a busy person, I want to drink coffee so that I wake up.

Vi har bestämt oss för två olika typer av delivery för cancer

1. Fastq-filer direkt från sekvensering. 
Detta kan vi idag redan göra genom funktionerna i Raw data delivery dokumentet. I framtiden ska det även levereras någon slags qc-rapport tillsammans med fastq-filerna. Men detta borde göras för alla projekt, så något vi måste sätta upp. 

Så för nu behöver vi sätta upp leverans-paketet för efter analys

2. Efter Balsamic-analys

- Processed fastq's: 
/home/proj/production/cancer/cases/chiefmarlin/analysis/fastq/

concatenated_ACC6203A12_XXXXXX_R_2.fp.fastq.gz

concatenated_ACC6203A12_XXXXXX_R_1.fp.fastq.gz

- bam (marked duplicate): 

/home/proj/production/cancer/cases/chiefmarlin/analysis/bam/

concatenated_ACC6203A12_XXXXXX_R.sorted.mrkdup.bam

concatenated_ACC6203A12_XXXXXX_R.sorted.mrkdup.bam.bai

vcf's (vardict) and manta:
.../chiefmarlin/analysis/vep/
SNV.somatic.chiefmarlin.vardict.vcf.gz
SV.somatic.chiefmarlin.manta.vcf.gz

cnvkit:  
.../chiefmarlin/analysis/cnv/ 
-tumor.merged.cnr
-tumor.merged.cns
-tumor.merged-diagram.pdf
-tumor.merged-scatter.pdf

multiqc report: 
.../chiefmarlin/analysis/qc/
multiqc_report.html

Problem: 
The coffee machine is leaking! Most likely the tube is not attached to the back very well.

Steps to reproduce
  1. Go to the coffee machine on G4, small kitchen
  2. Put a cup in the dispenser
  3. Press to get any coffee
  4. Water should now be dripping from the right side of the machine. Move the microwave for better view.

Expected outcome / suggested solution:
A coffee in my cup.

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by henrikstranneheim** [comment]
@Mropat and @emmser Do we still need this issue?

**Comment by moonso** [comment]
Fixed by #877
