### ISSUE TITLE
Automate initiation of microbial analysis

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/cg#557]
**Problem:** 
Microbial analysis can not be started automatically; as the microbial input files are not automatically identified.

Currently, for every flowcell that enters, the bioinformatician has to manually look up each individual project and run the starting command. This is both time consuming; but also blocks any form of further automation.

**Suggested solution:**
Automate the initiation of microbial analysis. This should, in practice, cut down the time to analyse microbial samples by about 2 hours / week.

**Comment by Mropat** [comment]
This is finished, please open new issue if not working as desired
