### ISSUE TITLE
Automatic fetching of bait set version from lims to cg

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cg#558]
As a lab and bioinfo person, I want to make sure, the correct bed file is used for every sample.

Problem: 
1. There is no link between lims (what indicates which bait set actually has been used for every sample) and cg - MIP/Balsamic.

2. There might also be another problem, that the orderportal assigns a versioned bait set to a sample based on the order date. The problem is that cg/statusdb (Bed and Bed Version) is not updated and samples might have been assigned to the wrong bait set (e.g. gms_myeloid_5.2) and re-runs cannot be done based on information based in cg/orderportal but must currently only be done based on the information in lims.

Steps to reproduce
  1. As far as I am aware, there is no automatic link between lims (udf bait set) and cg on a sample level.
  2. wrong assignment of bait set, I don't know, because I don't know where it is stored.

Expected outcome / suggested solution:
Fix automatic pickup of information from lims to cg.

Questions: 
Q: Am I right about problem no 2?
A: 

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by annaengstrom** [comment]
@patrikgrenfeldt could you please reply to my question?

**Comment by patrikgrenfeldt** [comment]
I think you are right yes

**Comment by annaengstrom** [comment]
Who at Clinical Genomics has information about Problem no 2?

**Comment by annaengstrom** [comment]
Automatic assignment of bedfile to order on a sample level has been removed, right @patrikgrenfeldt? 

To do: automatic assignment of bedfile to sample with information taken from lims

**Comment by patrikgrenfeldt** [comment]
I think this can be considered resolved

**Comment by annaengstrom** [comment]
@henrikstranneheim this is the issue we were talking about right now.

**Comment by henrikstranneheim** [comment]
Me and @patrikgrenfeldt  have decided to not relay the information from lims to statusDB, as it is better to keep it only lims. I think all of this was resolved in https://github.com/Clinical-Genomics/cg/pull/605. 

Do you agree @annaengstrom?

**Comment by annaengstrom** [comment]
Closing this issue.
