### ISSUE TITLE
Externally sequenced samples gets wrong data analysis

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#559]
Externally sequenced samples that are ordered gets the data analysis "scout", apptag: WGXCUSC000. It is not possible to link these samples in the mip pipeline without first changing the data analysis to "mip". 
The data analysis should be set to mip for samples with this apptag.

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt and @elevu Is this still the case?

**Comment by henrikstranneheim** [comment]
@emmser and @patrikgrenfeldt Is this still the case?

**Comment by Mropat** [comment]
This is fixed. data analysis can only be one of our pipelines or Fastq.
