### ISSUE TITLE
Bed-version error when starting Balsamic 

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/cg#574]
As a production person, I would like to start Balsamic

Problem: 
An error regarding bed-version when trying to run Balsamic

`ACC5831A5: config FASTQ file
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 75, in balsamic
    context.invoke(config_case, case_id=case_id, target_bed=target_bed)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 211, in config_case
    raise CgError("Bed-version %s does not exist" % target_bed_shortname)
cg.exc.CgError`

Steps to reproduce
  1. `up`
  2. `cg workflow balsamic --target-bed /home/proj/production/cancer/reference/panel/twistexomerefseq_9.1_hg19_design.bed -c helpeddrake -e keyvan.elhami@scilifelab.se`

Expected outcome / suggested solution:
Analysis should be start

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by patrikgrenfeldt** [comment]
@keyvanelhami  Which bed-version did it report as non-existing? 
`raise CgError("Bed-version %s does not exist" % target_bed_shortname) cg.exc.CgError`

That is the bed-version @annaengstrom might want to add in clinical-api

**Comment by keyvanelhami** [comment]
@patrikgrenfeldt I was trying to use following bed-file: `twistexomerefseq_9.1_hg19_design.bed`

**Comment by annaengstrom** [comment]
Have the bedfiles in `/home/proj/production/cancer/reference/panel/` been updated correctly @hassanfa ?

**Comment by hassanfa** [comment]
![image](https://user-images.githubusercontent.com/1086877/75541679-a27f6c80-5a1e-11ea-9032-3b0ad612b929.png)
 yes they are. 3 days ago.

**Comment by hassanfa** [comment]
![image](https://user-images.githubusercontent.com/1086877/75541837-dbb7dc80-5a1e-11ea-9476-1fcf81d10bc0.png)
bedfile exists in clinical-api as well.

**Comment by hassanfa** [comment]
@keyvanelhami try running without specifying `--target-bed`. CG should be able to pickup correct bed file.

**Comment by keyvanelhami** [comment]
I tried to run without --target-bed flag and I got the same error. I have also added the bed-file name in status db.

<img width="1293" alt="Screen Shot 2020-02-28 at 12 50 22 PM" src="https://user-images.githubusercontent.com/26735714/75546523-f8f1a880-5a28-11ea-927e-9699ced81942.png">


> @keyvanelhami try running without specifying `--target-bed`. CG should be able to pickup correct bed file.

**Comment by patrikgrenfeldt** [comment]
seems like it missbehaves if you give --target-bed-file and it still tries to use a value in statusDB, I'll look in to it straight away

**Comment by hassanfa** [comment]
> I tried to run without --target-bed flag and I got the same error. I have also added the bed-file name in status db.
> 
> <img alt="Screen Shot 2020-02-28 at 12 50 22 PM" width="1293" src="https://user-images.githubusercontent.com/26735714/75546523-f8f1a880-5a28-11ea-927e-9699ced81942.png">
> 
> > @keyvanelhami try running without specifying `--target-bed`. CG should be able to pickup correct bed file.

Is that correct though? AFAIK capture_kit is the name of the panel not file.

**Comment by patrikgrenfeldt** [comment]
I'm not sure why we have capture kit at all in status db.. Maybe it could be removed..

**Comment by keyvanelhami** [comment]
> I'm not sure why we have capture kit at all in status db.. Maybe it could be removed..

having capture kit in status db can be good for us to get an goo overview of what samples that have been ordered with what capture kit. LIMS doesn't have this overview so I would like to keep it

**Comment by patrikgrenfeldt** [comment]
EOL says it is needed for old analyses and maybe externally sequenced samples so we might need to keep it

**Comment by patrikgrenfeldt** [comment]
Is a fix needed for this today or is monday sufficient?

**Comment by keyvanelhami** [comment]
> Is a fix needed for this today or is monday sufficient?

Monday is sufficient. have a nice weekended :)
