### ISSUE TITLE
RNA samples get the Data Analysis set to "MIP + RNA" and are linked to the rare-disease/cases/ folder

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#576]
Sorry for the crappy issue, PG knows more :):

![20200228_182122](https://user-images.githubusercontent.com/12113434/75570570-af6c8200-5a57-11ea-973b-72363da9be7f.jpg)

Problem: 
The coffee machine is leaking! Most likely the tube is not attached to the back very well.

Steps to reproduce
  1. Go to the coffee machine on G4, small kitchen
  2. Put a cup in the dispenser
  3. Press to get any coffee
  4. Water should now be dripping from the right side of the machine. Move the microwave for better view.

Expected outcome / suggested solution:
A coffee in my cup.

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt Can we close this one?

**Comment by henrikstranneheim** [comment]
Seems stale - closing
