### ISSUE TITLE
Raw data delivery in cg

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/cg#579]
Today we have delivery scripts (called delivery package) on hasta written in bash to deliver fastq-files for sample/project/flowcell to a certain directory.
It would be better to use cg for this.

In cg we already have delivery of vcf/bam/cram files from MIP using 
```python
cg workflow <pipeline> deliver inbox <caseID>
```

**Comment by henrikstranneheim** [comment]
Duplicate of https://github.com/Clinical-Genomics/cg/issues/794. Closing this one as it not as complete
