### ISSUE TITLE
Cases that can't be stored block other cases from automatic storage

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/cg#583]
Problem: 
"cg workflow mip-dna store completed" fails when it can't upload a problematic case. As a result, problematic cases blocks other cases from uploading. 

Expected outcome / suggested solution:
Let it fail for the problematic case and carry on with storing the rest of the cases.

**Comment by henrikstranneheim** [comment]
@talnor: Is this fixed by  #591

**Comment by henrikstranneheim** [comment]
@talnor I will close this. Please reopen if the problem persists
