### ISSUE TITLE
Provide Scout with SMN file from MIP

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#593]
As a clinical geneticist, I want to be able to use wgs data to diagnose SMA.

Problem: 
An RnD group at Illumina has released a nifty tool to call SMA-releated genetic features not evident from regular SNV/SV calls, through SMNCopyNumber  https://github.com/Illumina/SMNCopyNumberCaller. 

Scout can display SMNCopyNumber output https://github.com/Clinical-Genomics/scout/pull/1704 and MIP can produce it https://github.com/Clinical-Genomics/MIP/issues/1290.

Expected outcome / suggested solution:
- [x] (parallel issue: SMN tsv files should be in HK)
- [x] SMN tsv file should be passed to scout config from cg

**Comment by henrikstranneheim** [comment]
Done! 🎉
