### ISSUE TITLE
WIP Implement starting NIPT NovaSeq analysis pipeline in cg

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#607]
**When** A NIPT sample has been sequenced on the NovaSeq
**I want** cg to pick up the sequenced sample
**so that** the analysis can be started automatically

#### Functional description:

When a NIPT sample has been sequenced on the NovaSeq, cg should be able to detect a sample that has been sequenced (but not analyzed), and start the analysis pipeline. This process can be automated via a cronjob.

#### Questions & Answer:
Q: WIll this be a seperate workflow?
A: Yes
Q: What will the workflow be called?
A: `cg workflow fluffy`

**Comment by Mropat** [comment]
fixed in https://github.com/Clinical-Genomics/cg/pull/844
