### ISSUE TITLE
WIP Link results of a NIPT NovaSeq analysis in Housekeeper

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#608]
**When** a NIPT NovaSeq sample has been analyzed
**I want** cg to store the results in Housekeeper
**so that** we have the have the results available for delivery to the customer.

#### Functional description:

When a NIPT NovaSeq sample has been analyzed the results are made available to cg. Next, cg parses these results for files to store in HK.

#### Questions & Answer:
Q:
A:

**Comment by Mropat** [comment]
FInished https://github.com/Clinical-Genomics/cg/pull/844
