### ISSUE TITLE
WIP Delivery of NIPT NovaSeq results 

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#609]
**When** delivering the results of the NIPT NovaSeq analysis
**I want** those results to be uploaded to the NIPT Viewer
**so that** the customer has access to the results.

#### Functional description:

The results should be uploaded to the NIPT Viewer. 

#### Questions & Answer:
Q: The project document mentions a 'hospital server'. What is this?
A:

**Comment by Mropat** [comment]
duplicate issue, deleting
