### ISSUE TITLE
WIP NIPT NovaSeq Data Management

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#610]
**When** 
**I want** 
**so that** 

#### Functional description:
From the project document: "Need to include data management principles, including FASTQ compression using SPRING"

#### Questions & Answer:
Q:
A:

**Comment by moonso** [comment]
Please elaborate the description

**Comment by henrikstranneheim** [comment]
Added question here: https://github.com/Clinical-Genomics/project-planning/issues/134. Closing
