### ISSUE TITLE
Bait Set in lims for externally sequenced samples

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#620]
As bioinfo production member I want to have a better process of importing and setting `Bait set` on externally sequenced samples.

Problem: 
- The order form for externally sequenced data does not contain ´Bait set` information, which should be required for ´tga | panel | exome´ analysis types.
- I would like to be able to set the `Bait set` in lims on sample level outside of workflows via cg using the already existing udf.

Steps to reproduce
  1. Run external data case: `cg workflow mip-dna config-case soundboar`:
```
raise LimsDataError("Target bed %s not found in LIMS" % target_bed_shortname)
```

Expected outcome / suggested solution:
1. Submitting an external sequenced data order form will set `Bait set` in lims on sample level for ´tga | panel | exome´ analysis types
1. `cg set sample` can set the Bait set in lims
 
Questions: 
Q: 
A:

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt @annaengstrom @emmser @moahaegglund @mayabrandi Starting an issue here for discussion and suggested solution

**Comment by henrikstranneheim** [comment]
Expected outcome
1. Is will be fixed in: https://github.com/Clinical-Genomics/cg/pull/624
2. Is fixed in https://github.com/Clinical-Genomics/cg/pull/622

**Comment by Mropat** [comment]
Additional workaround added in #759 to bypass LIMS query compeltely and provide panel bed name directly via MIP CLI if not set in LIMS or multiple ones are set in LIMS, raising a LimsDataError

Use:
`cg workflow mip-dna config-case soundboar --panel-bed grch37_agilent_sureselect_targets_cre_-v1-.bed`
