### ISSUE TITLE
Create documentation for statusDB and common CLI commands

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cg#628]
As a person working at Clinical Genomics I would like to have information how statusDB works and how certain scripts work

Problem: 
Go to AM systems or Github

Steps to reproduce
 1. Go to search or navigate in AM
2. Go to cg repo

Expected outcome / suggested solution:
Limited documentation for cg

Questions: 
Q: Does the same problem occur for tea?
A:

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by annaengstrom** [comment]
Should we consider this as equipment? @AnnaLeinfelt

**Comment by AnnaLeinfelt** [comment]
> Should we consider this as equipment? @AnnaLeinfelt
> I am thinking about AM document 1926


cg -  as a software
statusdb - database, we use it as a software


--

**Comment by annaengstrom** [comment]
New AM document created. @henrikstranneheim what is the outlook for working with it?

**Comment by henrikstranneheim** [comment]
This is added here: 
- https://clinical-genomics.github.io/atlas/infrastructure/databases/statusdb/
- https://clinical-genomics.github.io/atlas/production/handy_commands/

More documentation should be added as we go along
