### ISSUE TITLE
Library prep date missing in statusdb for WES and PAN

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/cg#636]
Problem: 
Library prep date 'Prepared at' is missing for WES and PAN samples in statusDB. There is a previous deviation (INFRA#47) and fix: https://github.com/Clinical-Genomics/cg/pull/549

This is also the case for some WGS cases.

Example of cases:
ACC6807A1 EXO
ACC6646A1 EXO
ACC6861A1 PAN

ACC6449A1 WGS
ACC6505A4 WGS
ACC6435A1 WGS LI
ACC6504A2 WGS LI
ACC6457A3 WGS LI

**Comment by emmser** [comment]
This is still not working, but I guess it's on your to-do list now MB?

**Comment by mayabrandi** [comment]
Yep

**Comment by mayabrandi** [comment]
This is fixed by the deploy of the following PRs:
https://github.com/Clinical-Genomics/clinical_EPPs/pull/154
https://github.com/Clinical-Genomics/cg/pull/647
