### ISSUE TITLE
Concatenate forward and reverse (sep) fastq reads at microbial delivery

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#64]
Contact person: DB

As a bioinformatician delivering fastq files in microbial projects I want the fastq files automatically concatenated (per read direction) to save time and reduce the risk of forgetting to do this.

Problem description: For delivery of microbial raw data the delivered fastq files need to be concatenated. In other words all forward reads in one file and all reverse reads in another. This step needs to be automated.

Suggested solution:
* Use the solution developed in [Zube #2088](https://zube.io/clinical-genomics/pbl-team-lessteamnamegreater/c/2088) to perform concatenation. concat-microbial.sh
* Link the concatenated files with existing use `cg deliver inbox fastq --concat --project/--sample/--familyID `.
 - link to inbox
 - do concatenation there
* cg would require the fastq files to first be linked to HK (not happening today for microbial samples), part of another US

DoD: 
Working on rasta!
Documented in 1060 Raw data delivery and --help

How to Demo:
* ssh to rasta 
* hiseq-user
* activate production (up)
* cg deliver inbox ACC1234 (lims-proj) A1 (sample)
* change directory to the customer inbox
* ll ACC1234*

Expected outcome:
file-listing showing the links, one per read direction per sample 

Questions:

**Comment by emiliaol** [comment]
You can maybe use the concat_mic.bash that's in the SCRITPS folder on rasta. Just takes the project folder as input (in the customer INBOX)

**Comment by ingkebil** [comment]
See also: https://github.com/Clinical-Genomics/deliver/issues/44

**Comment by emiliaol** [comment]
Closing, we will have other issues addressing this
