### ISSUE TITLE
store mip-dna fails when data_analysis is not set on sample

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#656]
Problem: 

The cronjob that runs `cg workflow mip-dna store completed` throws a PipelineUnknownError exception for cases that have no `data_analysis` set on samples. The value expected for this cronjob is `mip` or `MIP`. This happens for 1) reruns of older cases and 2) cases without `Type` set in the Order Portal.

Steps to reproduce
  1. Run `cg workflow mip-dna store completed` or `cg workflow store mip-dna analysis /path/to/case_config.yaml` for a case with no `data_analysis set` on samples
  2. Watch the PipelineUnknownError exception appear!
  3. Check the samples for that case and notice how there's no `data_analysis set`.

Expected outcome / suggested solution:
Suggested solution:
 1. For old cases: add `data_analysis` retroactively to samples in the cg database. This can be done using `cg set sample --skip-lims -y <internal_id> -kv data_analysis mip`
 2. For future cases: make the field `Type` in the order portal mandatory, since this is what is applied to `data_analysis` in the `sample` table.

Questions: 
Q: @henrikstranneheim Is there an easy way to determine what older cases should have this `data_analysis` value? Could we, for instance, run an update script that sets `data_analysis` on a sample to `MIP` based on the MIP version, or a date of some kind?
A: Yes, it should be possible, but the question is if we can find one or potentially a few keys in status or store to determine the type of analysis to set. Maybe @moahaegglund @emmser have a good idea on what to use. I also think this is only for older cases (usually reruns). 
Q: @patrikgrenfeldt Is there anything preventing us from making this a mandatory field in the order portal?
A: I think it is mandatory in orderportal

**Comment by barrystokman** [comment]
@patrikgrenfeldt @henrikstranneheim the cronjob is failing daily because of the missing `data_analysis`, I'd like to discuss a possible solution soon.

**Comment by barrystokman** [comment]
Preliminary solution suggested during zoom meeting 2020-06-15: set `data_analysis` of all samples belonging to `cust003` and `cust004` to `MIP`.

Follow up steps to be determined.

**Comment by barrystokman** [comment]
@henrikstranneheim @patrikgrenfeldt should this also include setting `Data Analysis` to MIP in LIMS?

**Comment by henrikstranneheim** [comment]
I do not know if it it is needed - perhaps for completeness? I have not done it so far for the samples I have added this to in production

**Comment by patrikgrenfeldt** [comment]
> 
> 
> @henrikstranneheim @patrikgrenfeldt should this also include setting `Data Analysis` to MIP in LIMS?

Do we usually have that value in LIMS? What is it used for? I don't we use it for anything in cg

**Comment by henrikstranneheim** [comment]
Done! This is handled on case level now. Reopen if you disagree
