### ISSUE TITLE
Start balsamic in QC mode for analysis_type

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#657]
As a bioinformatician I want to start cases in QC mode without variant calling. BALSAMIC can be invoked in QC mode, and it would helpful to add this to cg as well.

Problem: 
cg is not aware of `--analysis-type qc` option in BALSAMIC and always runs in variant calling mode.

Steps to reproduce
  1. `cg workflow balsamic -c case_id`
  2. Above command only runs BALSAMIC in variant calling mode

Expected outcome / suggested solution:
To have an option to `cg workflow balsamic -c case_id -a/--analysis-type qc ...`

Questions: 
Q: Does BALSAMIC know about what QCs to run?
A: Yes.

**Comment by Mropat** [comment]
A possible solution could be to to add this feature in cg/cg/cli/workflow/balsamic/base.py:

```
@balsamic.command()
@click.option("-d", "--dry-run", "dry", is_flag=True, help="print command to console")
@click.option(
    "-r", "--run-analysis", "run_analysis", is_flag=True, default=False, help="start " "analysis"
)
@click.option("-a","--analysis-type", "analysis_type", type=click.Choice(['qc', 'paired', 'single']), required=False)
@click.option("--config", "config_path", required=False, help="Optional")
@PRIORITY_OPTION
@EMAIL_OPTION
@click.argument("case_id")
@click.pass_context
def run(context, dry, run_analysis, config_path, priority, email, case_id, analysis_type):
    """Generate a config for the case_id."""

    conda_env = context.obj["balsamic"]["conda_env"]
    slurm_account = context.obj["balsamic"]["slurm"]["account"]
    priority = priority if priority else context.obj["balsamic"]["slurm"]["qos"]
    root_dir = Path(context.obj["balsamic"]["root"])
    if not config_path:
        config_path = Path.joinpath(root_dir, case_id, case_id + ".json")

    # Call Balsamic
    command_str = f" run analysis" f" --account {slurm_account}" f" -s {config_path}"

    if run_analysis:
        command_str += " --run-analysis"

    if email:
        command_str += f" --mail-user {email}"

    if analysis_type:
        command_str += f" -a {analysis_type}"

    command_str += f" --qos {priority}"

    command = [f"bash -c 'source activate {conda_env}; balsamic"]
    command_str += "'"
    command.extend(command_str.split(" "))

    if dry:
        click.echo(" ".join(command))
        return SUCCESS

    process = subprocess.run(" ".join(command), shell=True)
    return process
```

This will modify the bash command to balsamic to contain the -a option, which hopefully should work the same way as calling balsamic by itself.
This will not affect the config file (as is currently the case when calling balsamic with -a option), so it will contain a different analysis type.

**Comment by hassanfa** [comment]
I think it is a good solution. 👍
