### ISSUE TITLE
Update priority of samples in both statusDB and LIMS through command line doesn't work as intended

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#658]
When updating priority of samples in statusDB numbers has to be used, for example standard=1 and priority=2.

If updating through command line (`cg set sample -kv priority 2 <sampleID>`) and choosing to update LIMS as well, the priority is set to 2 in LIMS, and not priority as wanted.

When trying the command `cg set sample -kv priority priority ACC6930A9` you get a warning but the sample gets the priority research in statusDB if choosing to continue:
<img width="1198" alt="Screenshot 2020-06-05 at 11 37 46" src="https://user-images.githubusercontent.com/19236050/83861246-a2c78c00-a720-11ea-989a-8f9a1a4f74d1.png">

![Screenshot 2020-06-05 at 11 23 38](https://user-images.githubusercontent.com/19236050/83859809-b8d44d00-a71e-11ea-91be-2d05903d89de.png)

I want to be able to update the priority of a sample both in statusDB and LIMS through command line.

**Comment by annaengstrom** [comment]
When this issue is done, documentation should be updated in AM doc "Cg"

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt I think you have fixed this?

**Comment by AnnaLeinfelt** [comment]
Hi! I am cleaning ongoing documents in AM and found the ongoing AM doc "Cg" with a referral here. Is this still an issue?

**Comment by annaengstrom** [comment]
the Cg = statusDB document is Atlas now, so the AM doc can be removed

**Comment by AnnaLeinfelt** [comment]
> the Cg = statusDB document is Atlas now, so the AM doc can be removed

Great! I searched for cg... I'll remove the AM document.

**Comment by patrikgrenfeldt** [comment]
I tested this and it seems to be fixed. Works both with numbers and text as intended.
