### ISSUE TITLE
Express cases doesn't autostart if a sample has too few reads

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#663]
Express cases has to fulfil the same requirements as cases with lower priority in order to autostart. We have experienced that a case with express priority didn't start because it had too few reads. 

The analysis of an express case should always be started, there shouldn't be any requirement in number of reads for cases with this priority to autostart.

**Comment by Mropat** [comment]
Is this still an issue? Can someone elaborate when this is happening?
Currently there is no check performed for MIP cases and samples when it comes to read count  - only whether all flowcells have been loaded on disk. Do we still want to start those cases  when not all flowcells have been loaded?

@barrystokman @karlnyr @patrikgrenfeldt

**Comment by Mropat** [comment]
@moahaegglund 
Is this still an issue? Do we want the express cases to autostart regardless of number of reads?

**Comment by vwirta** [comment]
@Mropat @emmser @moahaegglund I think it would be good if Express samples autostart. We can always manually judge the quality after the analysis and before we deliver.

**Comment by moahaegglund** [comment]
Agree, would be good if express samples always autostart. Both if the sample has too few reads or if q30 is bad.

**Comment by Mropat** [comment]
Fixed by @karlnyr
