### ISSUE TITLE
Fetching flowcells from PDC: defect caused by incorrect flowcell status 'ondisk'

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#667]
Problem: 
Flowcellls 'on disk' are not being tracked properly. This leads to `cg backup fetch-flowcell` incorrectly halting with a `maximum flowcells ondisk reached` message.

Steps to reproduce:
1. `SELECT count(*) FROM cg.flowcell where status = 'ondisk'` -> 1016
~1. `find /home/proj/production/flowcells/hiseqx -maxdepth 1 -type d -print | wc -l` -> 45~
~1. `find /home/hiseq.clinical/RUNS/ -maxdepth 1 -type d -print | wc -l` -> 39~
1. `/home/proj/production/demultiplexed-runs/ -maxdepth 1 -type d -print | wc -l` -> 1435
1. `du -h --max-depth=999 /home/proj/production/demultiplexed-runs/` -> 373T ಠ_ಠ

![image](https://user-images.githubusercontent.com/26384108/84386036-e9b9f380-abf0-11ea-9bbf-7bd870f62eac.png)

Expected outcome / suggested solution:
1. `cg backup fetch-flowcell` transfers flowcells from PDC to NAS-9.
1. The flowcells are then rsynced to either `hasta` (`/home/proj/production/flowcells/hiseqx/`) or `thalamus` (`/home/hiseq.clinical/RUNS/`)
~1. When the flowcells are on one of the servers they should have the status `ondisk`~
1. When they are removed from the servers they should have the status `removed` -> there is currently no fcuntionality in place that handles this!
1. It should be possible to remove `ondisk` flowcells. ~Simply removing them and setting the `status` to `removed` should suffice.~ We need to think about how to remove: backup somewhere? Compress?
1. A one time script should correct all flowcell `status`es.
 

Questions: 
Q:  How should flowcells be removed?
A: CLI command should handle removal and setting the `status`
Q: How do we remove flowcells in batches?
A: 
Q: Should we have a clean up script/cron job, and when should it run?
A:

**Comment by henrikstranneheim** [comment]
@barrystokman What is the status of this one?

**Comment by barrystokman** [comment]
I haven't looked at it. I realize now that the problem is slightly different, but still an issue. The status `ondisk` refers to raw data being present on either hasta or thalamus, not demultiplexed data. That status however is not correctly set to `removed` by our clean up scripts however. There's two things that need to be done:

1) set flowcell status to removed in the clean up scripts, we should be able to use `cg set flowcell -s removed <flowcell_id>`. Although if a flowcell is removed it should be archived on PDC. Further investigation needed.
2) set all statuses to the correct ones.

**Comment by Mropat** [comment]
@barrystokman  is this fixed?

**Comment by barrystokman** [comment]
Yes.

I've introduced a new status called `retrieved` that solves this issue.
At the moment we don't want to remove flowcells from hasta,
We still need to look at point 5 of the suggested solution, but I think that should be its own issue.
I'm editing my comment of Oct 26 since it's incorrect.
