### ISSUE TITLE
Dependency resolution does not work

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#672]
There are tests to check if installation works, eg dependency tree is intact, when running the continuous integration. The problem is that when package is installed on the server pip will use cashed versions of the installed packages as long as they meet the specific requirements specified in `requirements.txt`.

## Example
This was discovered when part of the code that uses `marshmallow` broken unexplained since the unit tests work fine. Marshmallow is currently on version `3.6`, however in the stage environment on hasta version 2.18 was used since this was the cashed version:
![Skärmavbild 2020-06-16 kl  16 22 08](https://user-images.githubusercontent.com/405278/84786848-8f080980-afed-11ea-9cbd-ca80996bec49.png)

## Conclusion
The current idea of not specifying explicit versions in `requirements.txt` does not work. This error will not be catched in CI since there are no cashed versions when installing there

## Suggestion
As you might expect I would prefer to have locked files with versions that ensure that a installation will always work. Hos to produce this file can be discussed. The current setup with the update scripts does not work.
Any other ideas are welcome @barrystokman @patrikgrenfeldt

**Comment by moonso** [comment]
As you might see in the picture pip says:

    Requirement already satisfied, skipping upgrade

for many of the deps.
One ugly solution could be to update all update scripts to run `pip install --no-cache-dirs ...`

**Comment by patrikgrenfeldt** [comment]
If cg need a higher version of Marshmallow why not specify that version as a minimum in requirements.txt?

**Comment by patrikgrenfeldt** [comment]
I don't mind having a lock file but it's also nice to have latest and greatest when developing. I guess we can have both somehow?

**Comment by moonso** [comment]
> I don't mind having a lock file but it's also nice to have latest and greatest when developing. I guess we can have both somehow?

Yes this is the point with pipenv and poetry, I have tried to explain this multiple times. There is one file that is similar to `requirements.txt`, for Pipenv this is called `Pipfile`. In this file one does NOT specify locked dependency versions. Then pipenv resolves the dependency tree and generates a `Pipfile.lock` with locked versions. Whenever one want's it is possible to generate a new lock file. But pipenv will always make sure that the program will work if one installs what is defined in the lock file.

Hope that is clear :)
