### ISSUE TITLE
HK tags definition and context

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#673]
**HK Tag DNA**
| Current HK | MIP rd_dna 8.2.6 | Mandatory file | Used by |
| --- | --- | --- | --- |
| cram | gatk_baserecalibration | no | scout, audit |
| mip-config | config_analysis | yes | cg, audit |
| sampleinfo | sampleinfo | yes | cg, audit |
| multiqc-html | multiqc_ar, html | yes | scout, audit | 
| multiqc-json | multiqc_ar, json | yes | vogue |
| pedigree-yaml | pedigree | yes | audit |
|  pedigree | pedigree_fam | yes | scout |
| mip-log | log | yes | audit |
|  qcmetrics | qccollect_ar | yes | audit |
| snv-gbcf, snv-bcf | gatk_combinevariantcallsets, bcf | yes | genotype |
|  sv-bcf | sv_combinevariantcallsets, bcf | yes | audit |
| peddy, ped-check | peddy_ar, ped_check | yes | audit |
| peddy, ped | peddy_ar,peddy | yes | scout |
| peddy, sex-check | peddy_ar, sex_check | yes | audit |
| **exe-ver** | **version_collect_ar** | yes | audit |
| vcf-str | sv_str | yes | scout, audit |
| vcf-snv-clinical | clinical, endvariantannotationblock | yes | scout, audit |
|  vcf-snv-research | research, endvariantannotationblock | yes | scout, audit |
| vcf-sv-clinical | clinical, sv_reformat | no | scout, audit |
|  vcf-sv-research | research, sv_reformat | no | scout, audit |
| bam-mt | samtools_subsample_mt, bam | no | scout, audit |
| chromograph | chromograph_ar | no | (scout) |
| vcf2cytosure | vcf2cytosure_ar | no | scout |

Not part of cg dict, but still transferred to HK:
| Current HK | MIP rd_dna 8.2.6 | Mandatory file | Used by |
| --- | --- | --- | --- |
| chanjo_sexcheck | chanjo_sexcheck | no | audit |
| coverage, sambamba_depth | sambamba_depth | yes | chanjo |
| smncopynumbercaller | smncopynumbercaller | no | (scout)

**HK Tag RNA**
Current HK | MIP rd_rna 8.2.6 | mandatory file | Used by |
--- | --- | --- | --- |
salmon-quant | salmon_quant | yes |
star-fusion | star_fusion | yes |
arriba-report | arriba_ar | yes  | (scout) |
arriba-ar | arriba_ar | yes |
stringtie-ar | stringtie_ar | yes |
gffcompare-ar | gffcompare_ar | yes |
cram | markduplicates | yes | (scout) |
gatk-asereadcounter | gatk_asereadcounter | yes  |
bootstrapann | bootstrapann | yes |
bcftools-merge | bcftools_merge | yes |
varianteffectpredictor | varianteffectpredictor | yes |
**version-collect-ar** | **version_collect_ar** | yes |
multiqc-html | multiqc_ar | yes | scout |
multiqc-json | multiqc_ar | yes | vogue |
sample-info | sample_info | yes | cg, audit | 
reference-info | references_info | yes | audit |
| **log** | **log** | yes | audit |
**config-analysis** | **config_analysis** | yes | cg |
**pedigree** | **pedigree** | yes | audit |
config | config | yes | |
**pedigree-fam** | **pedigree_fam** | yes  | scout |
blobfish | blobfish | no | |

**audit**= Used for traceability or when doing error investigation retrospectively

**Comment by henrikstranneheim** [comment]
@moonso @patrikgrenfeldt @eriksjolund @hassanfa @sylvinite @barrystokman @jemten 

Here is the current map - as you see there are some discrepancies (bolded) already even though RNA is not in production yet.

**Comment by moonso** [comment]
Nice! Could you explain what you mean by discrepancies? Should we not have the same separator for all tags that are stored in HK, seems like `-` is the most common one but not always used

**Comment by henrikstranneheim** [comment]
> Should we not have the same separator for all tags that are stored in HK, seems like `-` is the most common one but not always used
Yes we should and I think we do (I think I did not update to the table properly - done now)

The discrepancies are in bold e.g. in HK log is either called mip-log (DNA) or log (RNA), but it always point to the log from MIP.

**Comment by hassanfa** [comment]
I think the bold ones and all those that are used by internal cg API are a very good candidate to build the first prototype.

Also, I think housekeeper tag for common ones should reflect the purpose of the tag and usage. Common tags should avoid having software names in them as much as they can; multiqc_json is an exception though.

**Comment by moonso** [comment]
Perhaps we should here create a table with common tags based on the ones that @henrikstranneheim listed above?

**Comment by henrikstranneheim** [comment]
@moonso I think this is solved by Hermes now right?

**Comment by moonso** [comment]
Yes refer to this place: http://www.clinicalgenomics.se/hermes/
