### ISSUE TITLE
Free up disk space by cleaning stored Balsamic cases

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#675]
As a IT responsible, I want processed Balsamic cases to be removed so that we free space back to the cluster.

Problem: 
No automation exists for cleaning old Balsamic analyses which slowly fill up the disk

Steps to reproduce
1. make a Balsamic analysIs
1. store in cg
1. wait a year

Expected outcome
Old analysis under /home/proj/production/cancer/cases is clean up after 21(?) days

Actual outcome
The analysis is not cleaned 

Questions: 
Q: 
A:

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by Mropat** [comment]
Solved temporarily!
