### ISSUE TITLE
FASTQ compression problematic cases

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#685]
## WHAT is the problem

The FASTQ compression is now running every night where fastq files gets compressed into SPRING archives. During the testing process it was discovered that the links in the housekeeper stage database points to actual production data fastq files. This has caused some problems that require investigation for a few cases. In this issue we will track what cases that are affected and what needs to be done.

Some cases was affected during testing, some seem to have funky fastq paths (from before) and some seems to have multiple inodes, that is multiple hard links. Fortunately it seems like no data is lost, it is more of a problem with paths and wrong pointers from housekeeper, there are not that many cases with problems that has been identified.

Please note that there has not been enough time to investigate this before summer so just use this as a reference for now.

## WHEN is this a problem

From now on (202007), whenever a case needs to be rerun we first need to check if the fastq files has been compressed. If that is the case we need to unpack the spring archive before initiating the rerun. There will be problems for some of the cases in the list below but hopefully we will be able to fix this soon.

## Cases

The problematic cases are:

|Case id|problem|
|-|-|
|`modernbee`| Messed up fastq/spring paths |
|`suremako`| Unknown |
|`expertalien`| Unknown |
|`wisestork`| Unknown |
|`richalien`| Unknown |
|`deepcub`| Unknown |
|`causalmite`| Unknown |
|`proudcollie`| Unknown |
|`wiseiguana`| More than one inode to fastq |
| `grandkoi` | Unknown |
| `fluenteagle` |  Unknown |
| `freetomcat` |  Empty fastq files |

## Cases with more than 1 inode for fastq files

These cases needs to handled manually with care

| Case id | Inds with problem | Comment |
| - | - | - |
| wiseiguana | ELH2910A1 | |
| nextjackal | ACC2782A5 | |
| sharpwhale | ACC2778A8, ACC2782A2 | |
| inferret |  |
| selectlynx | ACC2680A1 | |
| kindcaiman | ADM1688A1 | Same ind as grandshad? |
| vitalmouse | ADM1059A4, ADM1059A5, ADM1059A6 | |
| grandshad | ADM1688A1 | Same ind as kindcaiman? |

## Cases with symbolic links for fastq files

Needs to be decided how to handle these

| Case id | Inds with problem |
| - | - |
| worthybug | ADM1260A9 |
| frankvervet | ACC2599A1 |
| heroicakita | ACC3170A7, ACC3170A8, SVE2730A16 |
| immunekite | SOL2708A6, SOL2708A8 |
| restedkoi | ADM1855A21 |
| soundclam | SVE2126A23 |
| tendercollie | SVE2623A1 |
| civilstag | SVE2274A1 |
| moreraptor | ADM1593A1 |

## Cases where fastq files AND spring files are missing

| Case id | Inds with problem | comment |
| - | - |
| vitalkoi | ELH2904A3 | No bundle in housekeeper |
| vitalkoi | ACC4001A1,ACC4001A2 | Bundle exists but files seems to be completely missing |

**Comment by henningonsbring** [comment]
| aboveglider | no file exist at the path housekeeper suggest for the spring file |
| aceboa | spring file exist where housekeeper suggest |
| acecattle | housekeeper point to a fastq file |
| activejaguar | spring file exist where housekeeper suggest |
| actualgopher | spring file exist where housekeeper suggest |
| amazedraptor | spring file exist where housekeeper suggest for two out of three |
| amplecat | spring file exist where housekeeper suggest |
| aptboxer | spring file exist where housekeeper suggest |
| bosstarpon | no file exist at the path housekeeper suggest for the spring file |
| busytiger | Sequenced 1970-01-01 according to housekeeper (!!!) spring file exist where housekeeper suggest |
| calmgopher | spring file exist where housekeeper suggest |
| causalakita | housekeeper point to a fastq file |
| causalmite | housekeeper point to a link to a fastq file |
| choicemite | spring file exist where housekeeper suggest |
| civilghoul | spring file exist where housekeeper suggest |
| civilloon | no file exist at the path housekeeper suggest for the spring file |
| civilstag | housekeeper point to a link to a fastq file |
| clearsheep | housekeeper point to a fastq file |
| crispalpaca | spring file exist where housekeeper suggest |
| cutecod | no records of any files in housekeeper |
| decentrat | spring file exist where housekeeper suggest |
| deepcub | no records of any files in housekeeper |
| enoughjoey | spring file exist where housekeeper suggest |
| equalram | spring file exist where housekeeper suggest |
| exoticgull | no file exist at the path housekeeper suggest for the spring file |
| expertalien | housekeeper point to a link to a fastq file |
| expertbee | no records of any files in housekeeper |
| fancyfawn | housekeeper point to a fastq file |

**Comment by Mropat** [comment]
This seems to have been handled
