### ISSUE TITLE
Cron <hiseq.clinical@hasta> $CRONIC ${PRODUCTION_HOME}/servers/resources/hasta.scilifelab.se/crontabs/cron-cg-upload-delivery-report.sh >> ${LOG_BASE}/cg.upload-delivery-reports.log 2> >(tee -a ${LOG_BASE}/cg.upload-delivery-reports.log >&2)

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#690]
**Cron <hiseq.clinical@hasta> $CRONIC ${PRODUCTION_HOME}/servers/resources/hasta.scilifelab.se/crontabs/cron-cg-upload-delivery-report.sh >> ${LOG_BASE}/cg.upload-delivery-reports.log 2> >(tee -a ${LOG_BASE}/cg.upload-delivery-reports.log >&2)**

[Cron _hiseq.clinical@hasta_ $CRONIC ${PRODUCTION_HOME}_servers_resources_hasta.scilifelab.se_crontabs_cron-cg-upload-delivery-report.sh __ ${LOG_BASE}_cg.upload-delivery-reports.log 2_ _(tee -a ${LOG_BASE}_cg.upload-delivery-reports.log _&2).zip](https://github.com/Clinical-Genomics/cg/files/4912424/Cron._hiseq.clinical%40hasta_.CRONIC.PRODUCTION_HOME._servers_resources_hasta.scilifelab.se_crontabs_cron-cg-upload-delivery-report.sh.__.LOG_BASE._cg.upload-delivery-reports.log.2_._.tee.-a.LOG_BASE._cg.upload-delivery-reports.log._.2.zip)

**Comment by talnor** [comment]
cases with external data are missing dates (securefish).

**Comment by henrikstranneheim** [comment]
This has been handled and the current process is working fine as far as I know. Closing
