### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/cg#7]
Automation will rely on a new status database, a unified code base for central apps/functions, and a new rest API for an order portal!

**Comment by robinandeer** [comment]
## Order

- [ ] parse order forms to pre-fill order form
  - [ ] regular samples
  - [ ] RML samples
  - [ ] external samples

- [ ] handle import of orders to LIMS
  - [ ] fastq
  - [ ] scout
  - [ ] external
  - [ ] rml

- [ ] open a ticket for a new order, named and associate with user

- [ ] handle import of orders to CG Status
  - [ ] `scout` with family relations
  - [ ] `fastq` with generic families for non-tumour samples
  - [ ] `external`
  - [ ] `rml` with added pools

**Comment by robinandeer** [comment]
## Demux @ingkebil 

Demux should work the same. We will stop adding QC stats from analysis to the database tho. But we don't really need to test or update that part.

- [ ] call "transfer flowcell" when demux is done

**Comment by robinandeer** [comment]
## Analysis @robinandeer

- [ ] automate fetching families that are ready to analyze

-------------------------

- [ ] start analysis with Trailblazer
  - [ ] generate MIP config
  - [ ] link FASTQ files from Housekeeper
  - [ ] generate gene panel from Scout

-------------------------

- [ ] check which analyses that have recently completed

**Comment by robinandeer** [comment]
## Upload @robinandeer

- [ ] store analysis results in Housekeeper
- [ ] store analysis record in CG Status
- [ ] check analyses that are ready for upload

-------------------------------

- [ ] upload results to various apps
  - [ ] coverage to chanjo
  - [ ] observations to loqusdb
  - [ ] variants to Scout
  - [ ] genotypes to Genotype

**Comment by robinandeer** [comment]
## Deliver @ingkebil 

- [ ] check which samples (FASTQ) are ready to be delivered
- [ ] check which analyses are ready to be delivered (Caesar?)

**Comment by robinandeer** [comment]
# General

- [ ] update AM system documents
  - [ ] demux
  - [ ] delivery
  - [ ] MIP analysis
  - [ ] Scout
  - [ ] apps

**Comment by robinandeer** [comment]
Missing families?

family not found
cust048-BTB0001fam
cust048-BTB0001fam
cust002-F0014130
cust002-F0013626
cust003-17057
cust002-F0012608

**Comment by ingkebil** [comment]
SETUP
- [ ] write configuration: supervisord, env vars
  - [ ] genotype
  - [ ] trailblazer
  - [ ] cg
  - [ ] nipt
  - [ ] scout
  - [ ] scout archive

- installing tools on clinical-db
  - [ ] genotype
  - [ ] trailblazer
  - [ ] cg

- update documentation AM
  - [ ]  demux
  - [ ]  delivery
  - [ ]  MIP analysis
  - [ ]  Scout
  - [ ]  genotyping
  - [ ] apps

USABLE STATE
- [ ] curate statusdb
- [ ] migrate HK
- [ ] migrate chanjo
- [ ] update servers repo to work on rasta/clinical-db
  - [ ] crontab, alias, bashrc
  - [ ] double check crontab on clincial-db

DONT FORGET
- [ ] move mwgs from aws -> clincial-db

**Comment by henrikstranneheim** [comment]
@robinandeer The missing family (cust003-17057) was there any action I should take?

**Comment by robinandeer** [comment]
@henrikstranneheim no that's fine - that family was renamed in our LIMS to avoid overwriting the original analysis 👍

**Comment by emiliaol** [comment]
@ingkebil Can we close this or is there anything we still need to consider?

**Comment by moonso** [comment]
I'm closing this as it has grown out of bounds. Let's reopen if necessary and split into smaller ones
