### ISSUE TITLE
Clean customer inbox: cust??? not found

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#700]
Cronic detected failure for the command:
bash /home/proj/production/servers/resources/hasta.scilifelab.se/crontabs/clean-customer-inbox-past-dirs.sh

Sun Aug  2 20:00:01 CEST 2020 Deleting:
find: ‘/home/proj/production/customers/cust???’: No such file or directory
find: ‘/home/proj/production/customers/cust???’: No such file or directory

RESULT CODE: 1

**Comment by henrikstranneheim** [comment]
@barrystokman Is this reoccurring or can we close this one?

**Comment by barrystokman** [comment]
@henrikstranneheim the issue hasn't occurred, we can close this
