### ISSUE TITLE
CG MIP store blocking queued uploads

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#705]
## Description
Recently there has been errors regarding creation of vcf files for smaller gene panels (often coupled to inherited cancer cases). Due to this, cg.cli.workflow.mip.store throws an error resembling the one below:

```html
Cronic detected failure for the command:
/home/proj/production/servers/resources/hasta.scilifelab.se/crontabs/workflow-mip-dna-store-completed.sh

storing family: funwasp
missing file: /home/proj/production/rare-disease/cases/funwasp/analysis/funwasp/sv_reformat/funwasp_comb_ann_vep_parsed_ranked.selected.vcf.gz
2020-08-10 12:30:07 hasta.scilifelab.se cg.cli.workflow.mip.store[150056] ERROR case storage failed: funwasp
Traceback (most recent call last):
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 46, in analysis
   new_analysis = gather_files_and_bundle_in_housekeeper(config_stream, hk_api, status,)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/store/mip.py", line 23, in gather_files_and_bundle_in_housekeeper
   results = hk_api.add_bundle(bundle_data)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/hk.py", line 32, in add_bundle
   return self._store.add_bundle(bundle_data)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/housekeeper/store/api/add.py", line 56, in add_bundle
   raise FileNotFoundError(path)
FileNotFoundError: /home/proj/production/rare-disease/cases/funwasp/analysis/funwasp/sv_reformat/funwasp_comb_ann_vep_parsed_ranked.selected.vcf.gz
```

This error has been brought up and have been "solved" (if touching these files and tricking cg to store them is worthy of being called a solution).  

However, I discovered that when this error occur, the script stops processing completely. Meaning that if we have a list of 5 objects to be stored and it breaks at number 2, the remainder of the list don't seem to be processed at all. Meaning that the store gets stuck and the broken object until handled.  

## Summarized issue 
cg.cli.workflow.store does not attempt to process all queued objects. 

### Steps to reproduce
  1. create a break for the store function (i.e. remove the files mentioned in the error messages above)
  2. create new cases that will not break the store function
  3. Use `cg workflow store completed`

### Expected outcome / suggested solution:
The analysis to be stored in HK. 

I do not know if one can bypass this error by using the direct storing of a specific analysis (`cg workflow store analysis <path_to_analysis_config>`), thus circumventing the crontab function (`cg workflow store completed`).

**Comment by Mropat** [comment]
This issue is caused by this [script](https://github.com/Clinical-Genomics/cg/blob/master/cg/cli/workflow/mip/store.py)
A solution could be, instead of doing context.abort(), (which is not an error) in analysis method, raise click.Abort() (since it is an error and can be excepted) and catch it in completed method.

I think it is a very good first issue for @karlnyr !
