### ISSUE TITLE
microbial pipelines (mwgs/microSALT) must be started automatically

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#72]
Implement a way to start pipelines through trailblazer. Now this is very MIP focused.

- define an interface all pipelines should adhere to
- make MIP so
- make microSALT adhere to that interface

A weekly meeting is held between HI, IS, and KB to refactor Trailblazer for this purpose

**Comment by emiliaol** [comment]
@ingkebil @sylvinite @Hassan Should we archive this card? We have other better described US to make cg better at starting pipelines in general. Not sure if we have one specific to adding uSALT after that is done but it should be fairly uncomplicated so that the developers themselves can do that.

**Comment by hassanfa** [comment]
Ok I guess? Happy to be involved in other US as well.

**Comment by emiliaol** [comment]
Sorry Hassan, I was a bit quick on the keyboard and mentioned the wrong guy...

**Comment by ingkebil** [comment]
Yes, let's archive this one. The other USes are really better defined ;)
