### ISSUE TITLE
Add upload nipt to cg CLI

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#722]
Fetch latest NIPT files and load into the NIPT database via the CLI

**Comment by Mropat** [comment]
No longer blocked by https://github.com/Clinical-Genomics/cg/pull/844

**Comment by moonso** [comment]
Blocked in some way by Server farm project but the code can be implemented anyway!

**Comment by moonso** [comment]
It should be possible to proceed with this one now!

**Comment by barrystokman** [comment]
Blocked by NIPT refactor
