### ISSUE TITLE
Create a work around for cg with inheritance tests 

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#725]
**Background**
Currently cg is treating inheritance tests and other mip tests as equals. To create inheritance models, a case needs to contain a sample with status set to "affected". However, we would like to keep a logical phenotype for the clinician by reverting this status to unknown, see [this][cg_web_issue] issue for the requested solution in cgweb.

**Problem**
Inheritance testing cases are currently being uploaded as affected, when they should be uploaded as unknown.

**Solution**

* Retrieve information from cgweb that a case is to be analysed as an inheritance test. 
* Run the pipeline with the status set to affected. 
* Before upload, revert the status to unknown in the pedigree.

[cg_web_issue]: https://github.com/Clinical-Genomics/cgweb/issues/215

**Comment by Mropat** [comment]
Semi-handled with workaround, project open to handle properly elsewhere, closing
