### ISSUE TITLE
Status view in orderportal not updated

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cg#736]
It seems samples get stuck in Status steps, screenshot taken just now and this update is not correct, samples are not incoming and in library prep.

Is it correct for customers?

![Screen Shot 2020-08-31 at 9 49 06 PM](https://user-images.githubusercontent.com/36469416/91760828-4a474400-ebd4-11ea-9ee4-dfa2e7b349f2.png)

![Screen Shot 2020-08-31 at 9 48 54 PM](https://user-images.githubusercontent.com/36469416/91760847-503d2500-ebd4-11ea-92df-a7bc61e45a98.png)

**Comment by elevu** [comment]
Hi, I am moving this issue to CG since I think it is coming from there. When calling the endpoint: https://clinical-api.scilifelab.se/api/v1/cases?status=labprep  from the order portal the response includes cases that are not supposed to be there.

**Comment by patrikgrenfeldt** [comment]
I'm thinking that this issues arises since we limit how many samples we show and the sort order is oldest first, could it be something like that?

**Comment by annaengstrom** [comment]
What is the limit of samples?

**Comment by Mropat** [comment]
@patrikgrenfeldt @annagellerbring @henrikstranneheim 
Need help exaluating how critical this bug is, the gain in fixing, and whether it should be fixed in current version of cg

**Comment by annagellerbring** [comment]
I'm not familiar with this problem, @annaengstrom how critical is this bug?

**Comment by annaengstrom** [comment]
@annaengstrom I am not sure of the purpose of the view is but not all samples are visible, only about 45 samples or so.

**Comment by vwirta** [comment]
Hmmmm... is anyone actually using these views?

**Comment by henrikstranneheim** [comment]
@Clinical-Genomics/data-analysis @Clinical-Genomics/lab_prod Are any of you using these views? Are the customers?

**Comment by henningonsbring** [comment]
I have never used these views

**Comment by annagellerbring** [comment]
I know one customer that for sure have been using the samples-view in the past, but don't know how frequent or if other customers use it too.

**Comment by ChrOertlin** [comment]
Folllwing the link as of today gets me:
![image](https://github.com/Clinical-Genomics/cg/assets/8860786/6992f161-4659-492b-abe6-e007ce1a40d6)

Is this issue still relevant @annagellerbring ?

**Comment by annagellerbring** [comment]
This is the new link: https://clinical.scilifelab.se/samples and if the bug was that the oldest samples were sorted first, it's not relevant anymore.

**Comment by annagellerbring** [comment]
I think this can be closed

**Comment by ChrOertlin** [comment]
Thanks, closing then!
