### ISSUE TITLE
Mark cases as finished, is it possble?

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#748]
There are cases for BALSAMIC, that we disable variant callers for various reason. This manual override is done via BALSAMIC cli right now. There should be a way to mark an analysis as finished under manual intervention.

1. Detect if an analysis_finish file exists
2. Mark a case as finished via cg, is it possible?

**Comment by Mropat** [comment]
Solving this requires an overhaul of cg backend logic right now. We can mark analysis finished in Trailblazer, but there needs to be support on Balsamic side to generate delivery report from the incomplete run.
