### ISSUE TITLE
Force re-run of BALSAMIC analysis

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#760]
As a bioinformatician, there are cases that I do re-run by manually wiping the analysis directory. This is time consuming and could be a problem if the case is not stored.

Problem: 
Multiple steps to check if a case is stored, risk of data loss if we have not stored it.

Expected outcome / suggested solution:
For a `--forced` option to exist so when I do `cg workflow balsamic --force start googlybear` it passes the same `--force` to BALSAMIC, which wipes old results and creates everything from scratch.

Questions: 
Q: Does the same problem occur for MIP?
A: I do not know

**Comment by hassanfa** [comment]
what do you think @Mropat , can we pass --force to balsamic but double check for store first?

This is also linked to another issue. If `cg workflow balsamic start` fails midway of submitting jobs, the whole analysis directory will be locked, so a forced re-run will solve that one also.

**Comment by Mropat** [comment]
stale
