### ISSUE TITLE
Add support to force store incomplete BALSAMIC results in Housekeeper

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#762]
Problem: 
BALSAMIC workflow may have issues with analyzing certain samples with certain tools. These analyses may never be able to be restarted successfully.

Steps to reproduce
  1. Run a sample with high read count through the BALSAMIC pipeline
  2. Run is not completed due to time-out or one of the tools being unable to process many rads
  3. Try to store analysis in Housekeeper
  4. Analysis will not be stored because not all output files have been created

Expected outcome / suggested solution:
Be able to manually store incomplete analyses in Housekeeper

What needs to be done on the planning meeting:
- Find out what needs to be done on BALSAMIC side to produce deliverables file for incomplete analysis
- Add --force command line flag in CG workflow to store the files from incomplete analysis

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by hassanfa** [comment]
First the other issue has to be solved: https://github.com/Clinical-Genomics/cg/issues/760

**Comment by Mropat** [comment]
stale
