### ISSUE TITLE
BALSAMIC: support for non-human organism (other than microbes!)

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#763]
BALSAMIC (QC and non-QC workflow to some extent) will require a proper name of organism provided so it can take the correct reference (internally).

I'd like to have the following provided so it can be passed down to BALSAMIC:
1. Human genome the following version names: GRCh38, GRCh37
2. Dog genome the following version name: CanFam3.1

I'd like to have the following taxon ids to be used as a link to genomes above:
1. Human: 9606
2. Dog: 9615

In other words, one multiple genome versions can be linked to a single taxon id

For inspiration see the following:
1. grch38 https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.39
2. grch37 https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.25
3. canfam3.1 https://www.ncbi.nlm.nih.gov/assembly/GCF_000002285.3

Important notes:
1. version should not be case sensitive.
1. grch38 is synonym to hg38
1. grch37 is synonym to hg19
1. canfam3.1 is synonym to canFam3

**Comment by Mropat** [comment]
This can be done - we already have orgamism field on sample level. If BALSAMIC adds support for those organisms, we could utilize this and configure cases accordingly. Closing for now, can reopen when this can be procceeded on
