### ISSUE TITLE
Spring compression running on newly sequenced fastq files

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#767]
Problem: 

We are seeing a lot of errors when running `CRON cg workflow mip-dna start`
Example
```
[INFO] 2020/09/18 12:15:44 MIP_ANALYSE - Wrote reference YAML file to: /home/proj/production/rare-disease/cases/fleetibex/analysis/reference_info.yaml
[INFO] 2020/09/18 12:15:45 MIP_ANALYSE - Wrote: /home/proj/production/rare-disease/cases/fleetibex/analysis/fleetibex_config.yaml
 [31m[FATAL] 2020/09/18 12:15:45 MIP_ANALYSE - Could not find any '.fastq' files in supplied infiles directory /home/proj/production/rare-disease/cases/fleetibex/wgs/ACC6715A10/fastq [0m
```

case fleetibex is a fairly new case:
![image](https://user-images.githubusercontent.com/35531751/93780849-f3f48080-fc28-11ea-9b1a-ad9501581175.png)

Cases like these have to be manually decompressed and added back by the production team, which sometimes defeats the purpose of cg automation

Expected outcome / suggested solution:
Compress files in the ascending order of created_at field in cg 

@henrikstranneheim @moonso @karlnyr @henningonsbring input welcome

**Comment by henningonsbring** [comment]
To me this sounds like a very good idea. I can only see benefits, and no disadvantages, with compressing the oldest files first!

**Comment by moonso** [comment]
Sounds good! Feel free to open a PR

**Comment by Mropat** [comment]
> Sounds good! Feel free to open a PR

I should have expected this haha

**Comment by moonso** [comment]
Perhaps @karlnyr can do it with a little assistance from you @Mropat ?
