### ISSUE TITLE
Retry a BALSAMIC analysis no more than twice or thrice and take action according to type of failure

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#768]
Problem: Data analysis can fail, stall, or get cancelled due to reasons beyond bioinformatic workflow's capacity. There is not much can be done other than restart it after a while.

BALSAMIC doesn't support restart or retry _**WHILE**_ the analysis is running. `cg` has to wait through `trailblazer` for all the current jobs to finish, and then restart it. But no more than three times.

I'd like `cg` to do is to try the following:

#### Step 1: Try rerunning, steps below three times.

1. Check if analysis is running, if it is running don't restart it even a job has failed
2. Check if analysis is NOT running, and restart it.
- If BALSAMIC **does** complains about analysis directory to be locked, pass `--unlock` to BALSAMIC's CLI, and run again. So BALSAMIC's CLI will be called three times: i) try running the analysis: fail due to lock. ii) unlock by using BALSAMIC CLI. iii) re-run through BALSAMIC CLI
- If BALSAMIC **doesn't** complain, then it'll rerun by calling BALSAMIC CLI.
3. If analysis is NOT running, but we still need to start from beginning then force a re-run by sending `--force` to BALSAMIC CLI.

#### Step 2: After trying step 1 two or three times

1. Put case analysis **ON HOLD**
2. Trigger a manual review
3. Use BALSAMIC CLI to finish the analysis. If this fails, do not restart the analysis

**Comment by Mropat** [comment]
Current StatusDB architecture makes it very hard to implement. This potentially will be solved when we move our services to server farm and re-work how staging works
