### ISSUE TITLE
Add store completed functionality to microsalt workflow

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#779]
Since cg version 13.3.0 it is possible to store a completed microSALT analysis in Housekeeper with the command `cg workflow microsalt store analysis` and providing it with a path to a deliverables file.

New CLI functionality needs to be added that will enable storing of all completed microSALT analyses using `cg workflow microsalt store completed`

Typically the deliverables file is stored under the run directory of the ticket, e.g. `home/proj/production/microbial/results/ACC7093_2020.9.28_9.35.34` and is generated after the analysis.

Option: store all deliverables files in one folder.

Use https://github.com/Clinical-Genomics/cg/blob/30775ea7f7100d66a1d0cd02d24f80ddcc78c172/cg/store/api/status.py#L94 to get all microsalt analyses to be stored.

**Comment by henrikstranneheim** [comment]
@barrystokman Is this done?

**Comment by barrystokman** [comment]
@henrikstranneheim no, I actually need to implement a fix to get it to fully work, I'll put an item on the project board for it. It's about correcting the path to the deliverables file and the status of the analysis not being set in the `run` CLI command

**Comment by barrystokman** [comment]
WIP PR here: https://github.com/Clinical-Genomics/cg/pull/813

**Comment by Mropat** [comment]
All done now I think
