### ISSUE TITLE
Changing customer ID via CLI on family level

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#783]
Right now I can change the customer on sample level via:
`cg set sample -kv customer CUST_ID SAMPLE_ID`

I can also change the customer for all samples in a family via:
`cg set samples -kv customer CUST_ID FAMILY_ID`

However, to my knowledge, there is no way to change the customer ID on family level via the CLI. This is a feature we need to avoid spending long time with manually clicking in status DB, sometimes customer has to be changed for many families.

**Comment by patrikgrenfeldt** [comment]
There was already functionality to set customer on family level "cg set family -c [customer_id]". 

I think you miss the functionality to set customer on many families at once, for example all families in a ticket, that issue is resolved by #786
