### ISSUE TITLE
Keep track of trended cases

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#787]
## Description

As a Vogue developer and bioinformatician, I'd like to be able to keep track of what has been uploaded to Vogue. Right now clinical-db doesn't keep track of this, and one ends up uploading all cases every time.

I'd like to have an option to update every time a Vogue upload happens. I think this should be in the following table:

![image](https://user-images.githubusercontent.com/1086877/95971987-3406e780-0e12-11eb-88ea-cf86529e37c7.png)

### First PR
- [ ] Add column on analysis object that reveals when the analysis was uploaded to vogue
- [ ] Add file in `store/api/update/update_analysis.py` with function 

```python
def update_vogue_upload_date(status_db: Store, analysis_id: int, new_date: datetime.datetiem) -> models.Analysis:
    """Update the upload to vogue date"""
```

- [ ] Add functionality to fetch analyses that was not uploaded to vogue 

### Second PR
- [ ] make upload vogue logic use this new functionality

## This can be closed when
- [ ] vogue upload only loops over the analyses that was not uploaded to vogue

**Comment by hassanfa** [comment]
@Mropat could you please give this a go?

**Comment by hassanfa** [comment]
bump

**Comment by Mropat** [comment]
yes

**Comment by patrikgrenfeldt** [comment]
Do we have a branch to add the db-change-script to for this issue?

**Comment by Mropat** [comment]
@patrikgrenfeldt  No, this should be done after the alembic implementation

**Comment by barrystokman** [comment]
@hassanfa Is it okay to fetch the latest analysis based on when they were analysed, for instance all analyses from last week?

**Comment by hassanfa** [comment]
Yes, that's totally fine. As long as there is ability to re-upload certain cases based on a certain date cutoff (example last week), it is just fine.

Vogue can handle duplicates just fine, but keeping track of which cases are trended (i.e. uploaded to Vogue) makes it easier to process and avoid re-uploading them to Vogue again.

**Comment by hassanfa** [comment]
bump and tag @mayabrandi  FYI

**Comment by hassanfa** [comment]
I talked to Henrik about this on Monday Vogue meeting.

And to explain what I need is:

1. Keep track of what cases are uploaded to Vogue
2. Be able to upload latest "finished" analysis QC to Vogue

Please update me on the progress for this. Vogue is morphing and it'd be great to know the progress for this.
