### ISSUE TITLE
Deliver all Fastq files with CG

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/cg#794]
Today we have some bash-functions for delivery of fastq-files. Those collect the fastq-files for a sample/project or a flow cell and links the files in a dir on hasta. This makes it easier for us in production to deliver the files to caesar (syncing) since they are all collected in one place.
The functions below should be moved to options in cg instead.

Description of the bash-functions that we have today:

deliver_fastqs_sample $sample_id
Based on a sample id, deliver all fastq files of the sample to the cust/inbox

deliver_fastqs_project $LIMS_project_id
Based on a project_id, deliver all fastq files of the samples belonging to a project to the cust/inbox

deliver_fastqs_fc $flowcell_id
Based on a flowcell id, deliver all fastq files of the samples on a flowcell to the cust/inbox

## This can be closed when

- [ ] it is possible to run `cg deliver fastq --project-id ACCXXX`
- [ ] it is possible to run `cg deliver fastq --sample-id ACCXXX`

**Comment by moonso** [comment]
I'll be happy to implement this 😄 . 

## Some questions
- Who else has knowledge about the current process?
- Could you type exactly how the command is run today?

**Comment by moonso** [comment]
## Pipeline description (example)

Ge input: ACCXXXX
1. Räkna ut alla fastq-filer som existerar baserat på input från LIMS vilka som klarat QC
2. Skapa en folder döpt till ACCXXXX i rätt kunds inbox (kolla så inte folder redan existerar, om det behövs lägg på post-fix _2, _3 osv)
3. Skapa folders inne i ACCXXXX-mappen som motsvarar kundens namn på varje prov
4. Skapa hårdlänkar i varje sample-folder till fastq-filerna för respektive sample
5. Kolla vilken app-tag det är, om specifik app-tagg då ska konkatenering ske (printa varning om size ändras med mer än X% vid konkatenering)
6. Kolla om folder existerar i /home/custXXX/inbox/ticketnr, om folder existerar gör /home/custXXX/inbox/ticketnr_2, eller _3 osv...
7. Rsynca till den skapade foldern
8. Printa ut att filer har överförts till [path på caesar], kan t.o.m. ge förslag på komplett meddelande till kund

**Comment by moonso** [comment]
# Questions

## Do we check QC before adding fastqs to HK?

@henningonsbring 

## How do we check QC?

**Comment by henningonsbring** [comment]
> # Questions
> ## Do we check QC before adding fastqs to HK?
> @henningonsbring
> 
> ## How do we check QC?

QC is checked in LIMS when the sequencing is done and the flowcell is moved into the delivery step. Samples that fail QC will not be added to housekeeper.

**Comment by moonso** [comment]
> QC is checked in LIMS when the sequencing is done and the flowcell is moved into the delivery step. Samples that fail QC will not be added to housekeeper.

can you add a link to the code that does the check? It would be great for documenting these steps

**Comment by henningonsbring** [comment]
PR for Step 1: https://github.com/Clinical-Genomics/cg/pull/1048

**Comment by henningonsbring** [comment]
PR for Step 2: https://github.com/Clinical-Genomics/MUTANT/pull/12

**Comment by henningonsbring** [comment]
PR for Step 3: https://github.com/Clinical-Genomics/cg/pull/1093

**Comment by Mropat** [comment]
@henningonsbring  done?

**Comment by henningonsbring** [comment]
we got no pipeline that run step 1-3

**Comment by henningonsbring** [comment]
PR to run step 1-3 in one command: https://github.com/Clinical-Genomics/cg/pull/1167

**Comment by Mropat** [comment]
@henningonsbring  is this finished?

**Comment by henningonsbring** [comment]
Step 3 is "Automatic rsync delivery via slurm". Depends on definition of "Automatic". We do not have a cronjob yet, but otherwise everything is done.

**Comment by henrikstranneheim** [comment]
@henningonsbring @emmser I would advocate that this is finished. If you want a crontab entry it is to implement whenever you are ready. Please reopen if you disagree
