### ISSUE TITLE
Documentation of cg commands

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#80]
- [ ] add 
- [ ]  backup 
- [ ]  clean
- [ ]  deliver
- [ ]  get
- [ ]  init
- [ ]  set
- [ ]  status
- [ ]  store
- [ ]  transferinterface.
- [ ]  upload
- [ ]  report

**Comment by barrystokman** [comment]
To be documented in Github: cg repo
Create template first.
