### ISSUE TITLE
New fields in StatusDB

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#800]
Problem: 
There have been several requests for new fields to be added to StatusDB to track additional states of samples, cases and analyses. This Issue will be used to collect them all in once place and discuss implementation.

- Compression status field -  Sample/Family table
- Trended_at field - Family table
- Additional allowed values in status field - Family table (rerun, ignore)
- Delivery - Family table
- Skip Compression field - boolean to set cases to be skipped by compression from cli

Please add your suggestions if I have missed anything

Related issues:
#798 
#787 
#748 
#555

**Comment by hassanfa** [comment]
Could we consider having problematic and validation cases in statusdb as well?

It's be cool to add cases to no-compression list from CLI.

**Comment by Mropat** [comment]
@hassanfa great idea!

**Comment by moonso** [comment]
Sound good! Please link the other issues to this one

**Comment by Mropat** [comment]
@patrikgrenfeldt as someone most qualified for this, do you feel like you have time to perhaps implement some of these? Perhaps even all in one PR - since adding this is backwards compatible and enables further development

**Comment by hassanfa** [comment]
bump!

**Comment by Mropat** [comment]
This should start moving once we implement **alembic** for database migrations

**Comment by patrikgrenfeldt** [comment]
I'm no fan of introducing things in the code or database that could be useful one day but might on the other hand newer be implemented. I'm thinking each of these should be in the PR that makes use of them. 

I know its a bit undocumented how to run sql-scripts toward the database but MR suggested we change that by introducing Alembic in cg.

**Comment by Mropat** [comment]
Closing. Partially solved, and other issues have their own ticket
