### ISSUE TITLE
Compress fastq files based on date

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#819]
When compressing fastq files they are chosen by fetching all cases and then checking that `completed_at` exists on the latest analysis object. Sometimes when new samples are added to an existing family this type of search will think that the analysis is completed even though the new fastq files have not been analysed. 

## Problem
Fastq files sometimes get compressed to spring even though they have not been analysed

## Suggested solution
Check the date for when a fastq file was changed/created before compressing it. Only compress fastq files older than 3 weeks.

**Comment by emmser** [comment]
Looks good

**Comment by moonso** [comment]
Fixed in #820
