### ISSUE TITLE
before clean_up, make sure that no new analysis has been started for a case

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/cg#821]
Before cleaning up a case-folder in pipeline structure, make sure that no re-run analysis has been started for that case that haven't been stored yet. Case could have been started and failed analysis. In that case the analysis hasn't been stored. 
Happens for example when a sample has been added to an old case by the customer, the case already has an analysis that is completed, but will be analysed again and the new analysis will replace the older one.

**Comment by Mropat** [comment]
Can you provide names of cases where this happened?
Was the case started through cg or MIP directly?

**Comment by Mropat** [comment]
Affected case **mightystud**
