### ISSUE TITLE
[BUG] "cg workflow balsamic -a qc -d start CASEID" doesn't start qc workflow but "cg workflow balsamic start CASEID -a qc -d" does

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#823]
`cg workflow balsamic -a qc start CASEID` doesn't work but `cg workflow balsamic start CASEID -a qc -d` works.

Old text:
Related to #822 as well. `-a qc` doesn't instruct BALSAMIC to run QC only workflow and submits all jobs to cluster:

![image](https://user-images.githubusercontent.com/1086877/98342659-06781d00-2011-11eb-834a-14ed10fe6709.png)

Still says:

`Running analysis for keytahr
Running command /home/proj/bin/conda/envs/P_BALSAMIC/bin/balsamic run analysis --account production --mail-user clinical.delivery.cancer@scilifelab.se --qos low --sample-config /home/proj/production/cancer/cases/keytahr/keytahr.json --disable-variant-caller mutect --run-analysis`

**Comment by moonso** [comment]
Would it be possible that you have a look at the code @hassanfa ? Perhaps together with me or someone be else

**Comment by hassanfa** [comment]
I wish I could.... I am drowning in work.

**Comment by moonso** [comment]
We are all in the same situation. Clinical-db and thalamus are going to be shut down in 1,5 month. We all have to prioritize really hard now for a while. I think we will have a much better chance to fix this together with the expert, in this case the expert is you.

**Comment by hassanfa** [comment]
I disagree, but I don't have the whole picture.

I can't dedicate any time until next year, it is only BALSAMIC until early 2021.

**Comment by hassanfa** [comment]
So again a help message hiccup then. Thanks for checking this as well.

**Comment by moonso** [comment]
Perhaps just remove the `-d/--dry-run` flag on the subcommand `cg workflow balsamic`? It seems a bit confusing to have it in both places

**Comment by hassanfa** [comment]
Good point, lets keep it open then but it is low prio now. I changed main text body and title accordingly.

**Comment by Mropat** [comment]
@hassanfa The only reason the flags were added there is because when working on that code, we made a decision together to add them like this, in order to display available options from `cg workflow balsamic --help.`
The proper way to run these commands was already described and documented on Github and in Amdocs.
