### ISSUE TITLE
[BUG] Can't restart old un-stored, but storable cases for BALSAMIC

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#824]
Some cases that are not stored, blocking the rerun for re-analysis. All the cases in `${PROD_PATH}/cancer/cases` that are pre-`6.x.x` release are not possible to store.

This happened today when @keyvanelhami  was trying to rerun an old-unstored case.

For how to tackle this issue see: https://github.com/Clinical-Genomics/servers/issues/441 
For how to properly re-run a balsamic analysis see: https://github.com/Clinical-Genomics/cg/issues/768

**Comment by hassanfa** [comment]
This is also blocking restart and re-analysis of some positive control cases.

**Comment by henrikstranneheim** [comment]
@keyvanelhami Could you look into this?

**Comment by keyvanelhami** [comment]
@henrikstranneheim sure, I will ask Patrik if we can help me extracting the affected cases

**Comment by Mropat** [comment]
Un-storable cases:
fineroughy
upwardhawk
heroicgar
fastpossum
tighthog
newwahoo
nearbytetra
apttapir
proudweevil
raremullet
grandkoala
immunefinch
activepanda
smarthermit
sacredowl
wholehermit
betterinsect
fitbeagle
savedmole
nicebaboon
awakekoala
manyakita
fleetmouse
petcivet
smartjennet
actualsloth
kindweevil
sweetgnat
lightemu
unitedaphid
majorpony
guidedboxer
fastnewt
movedferret
crackkoala
realboa
aptyeti
pureshrew
richcoral

**Comment by hassanfa** [comment]
Nice!

Keyvan, please be careful of not "rerunning"  or deleting analysis case. These are old runs, and we'd like to keep the old results.

**Comment by keyvanelhami** [comment]
New config cases have been created for all 39 cases and they are now also stored in HK.

Closing issue

**Comment by hassanfa** [comment]
Underbar!
