### ISSUE TITLE
Properly instruct BALSAMIC to run QC workflow for MH cases

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#825]
BALSAMIC is capable running in `qc` only mode since release `3.X.X`. And `cg` is supporting it since couple of month ago: https://github.com/Clinical-Genomics/cg/pull/687

Related prio 3 project: https://github.com/Clinical-Genomics/cgp-mh-fastq-delivery

MH samples can be problematic and break variant calling runs for various reasons (it is outside of scope of this issue), so we preferably want to run only QC for these samples so we can deliver trimmed fastq files.

1. Run QC only for BALSAMIC cases, so it can finish workflow properly.
2. Store qc trimmed fastq files 

This is related to AMDoc 1046 (fastq delivery MH).

I'm fully aware of Trailblazer can mark cases as finished, but BALSAMIC won't prepare a delivery file unless it is properly finished (the feature to deliver without finishing workflow will be **deprecated**, i.e. if there is any file missing, it won't prepare the file. This is due to refactoring I'll be doing to prepare unique tags for sake of housekeeper store smoothness).

**Comment by Mropat** [comment]
So what is the proposed solution?
Do we want to introduce a delivery field in Status to indicate delivery type and handle these cases accordingly?

**Comment by vwirta** [comment]
There will be many cases in future where we would like to run only QC part of Balsamic.
This would be cases where customer expects to get raw data only, but we would like to run QC to get data on success of library prep and sequencing.

**Comment by hassanfa** [comment]
> So what is the proposed solution?

Temporary solutions:
1. Find out through production which customers are are only fastq delivery. Example: molecular health
2. We have fastq delivery (they are not BALSAMIC, MIP, nor microsalt) for some samples. They will all automatically be run through QC workflow.

> Do we want to introduce a delivery field in Status to indicate delivery type and handle these cases accordingly?

This exists to some extent. Probably @annagellerbring or @elevu know how it is defined in orders. Maybe even @patrikgrenfeldt can help on order portal side.

**Comment by elevu** [comment]
As I understand, now in the order portal for Balsamic there is no way to specify the delivery type. But it definitely can be added.

**Comment by hassanfa** [comment]
How about analysis type? Are all analysis only `"BALSAMIC" | "MICROSALT" | "FASTQ" | "MIP"`?

**Comment by henrikstranneheim** [comment]
Nice!
