### ISSUE TITLE
Possibility to instruct TB (feature doesn't exist yet) to hide an analysis

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#838]
Ref: https://github.com/Clinical-Genomics/trailblazer/issues/155

I do run lots of analysis and re-analysis on various samples for reinvestigation or data aggregation. Or Keyvan can run downsampled cases as analysis for various projects and investigations.

This clutters TB production and @emmser doesn't appreciate it.

Right now there is no way to overcome this easily. It'd be great to have a feature to instruct TB (if that feature exists) to hide these type of analysis.

`cg workflow --hide-trailblazer <mip|balsamic|microsalt> start <case_id|project_id>`

**Comment by hassanfa** [comment]
@keyvanelhami  here is the issue.

**Comment by Mropat** [comment]
Ways to do this in the meantime while we have a permanent solution:

Route A:
1. Start analysis
2. Go to Trailblazer
3. Make failed & Hide analysis

Route B:
1. Use stage - this will not prevent analysis from being tracked on stage, but it wont submit to prod trailblazer or store in Housekeeper automatically

**Comment by hassanfa** [comment]
I did route A, and hid all the analysis.

Route B is desirable, but stage can get wiped (as it should). 

Best solution is to have an alternative output-dir or provide a support for long-term-stage utilization, using production version of all tools.

**Comment by Mropat** [comment]
Same, will be reworked when staging is reworked
