### ISSUE TITLE
feat/fix request: Allow for multiple analyses to be placed at the same time on a case

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#840]
In its current state, orders are placed through the orderportal for a family/case. If the customer then wants to add more samples to this family, per say adding parents to proband sample, they would do so by placing a new order on the samples they want to add and refer to the old family/case

Problem: 
If an analysis has not been done yet on the family/case (because of queue into prep and time to sequence) and then the customer adds more samples to this family this will cause and issue. Even if the first sample is finished, the new samples will not be. This will cause the current workflow to not pick the case up, thus halting the delivery of the first analysis.

This will happen if the following events happen chronologically:
* A family is created start of week 1
* The sample to said family is sequenced on the Friday
* On the same Friday new samples are added to the family through a new order
* On Monday when the sequencing is done for the first sample mip cg notices that the newly added samples has no reads
* Result: analyses are not initiated.  

Expected outcome / suggested solution:
I think by adding samples connected to an analysis we are able to circumvent said problem. We would also have to move the action of the family to the analysis instead, which makes sense because the action is not occuring on the family but the analysis. This would allow us to start analyses for a case and let the customer place a new analysis on the same case without halting the workflow.

**Comment by karlnyr** [comment]
@emmser @henningonsbring @talnor What do you think about this? Is it worth the thought or should I put this down?

**Comment by henningonsbring** [comment]
We have discussed to block the possibility to add new samples to an old case, and my understanding is that the consensus is that we should prevent this behaviour. Instead, customers should in the future just get a new family with the cases from the old family added together with the new samples.

**Comment by Mropat** [comment]
I think this discussion is resolved? Closing, reopen if I'm wrong
