### ISSUE TITLE
Use a middleman between cg/tb and SLURM

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#847]
I'd like to have a SLURM interface for our applications. I described it here: https://github.com/Clinical-Genomics/project-planning/issues/70

To focus as a project.

I was planning to do this only for Vogue but knowing current challenges with FastQ compression, it could be a nice addition after project intensity cools down.

**Comment by hassanfa** [comment]
Maybe something for @Mropat and @moonso are also interested to join ranks for this project.

**Comment by hassanfa** [comment]
My suggestions is too look into the following:

- https://github.com/ohsu-comp-bio/funnel
- PySlurm or SlurmPy
- https://github.com/ga4gh/workflow-execution-service-schemas
- https://github.com/EMBL-EBI-TSI/TESK/

All above, except PySlurm/SlurmPy are SLURM agnostic and can be added to our microservice/monolith setup

**Comment by hassanfa** [comment]
(I'm slightly biased towards funnel, since I've tried it with SnakeMake and it works quite well)

**Comment by moonso** [comment]
Sound great, we already had some discussions in this direction right @Mropat ? Great if there is a plug and play tool out there already 💯

**Comment by Mropat** [comment]
Funnel sure does seem nice! SO much functionality, and I'm sure we could adapt it to monitor case progress :+1:

**Comment by Mropat** [comment]
Ok, so this more of an idea/suggestion and not technically an issue that can be addressed immediately.
Closing, reopen when this can be implemented
