### ISSUE TITLE
Move deliver package into cg

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#86]
Contact: KB

As a member of TTN, I would like to absorb the python part and the deliver_* bash functions of the deliver repo, so that maintenance becomes possible. Once maintenance becomes possible, we can extend the functionality to automation.

Problem: now, the python part of the deliver repo has following problems:
- written in py27
- uses an old internal package called 'access' to connect to mysql (see `deliver/modules/demux.py`)
- uses mysql-python which clashes with pymysql used in all other packages. deliver cannot be installed alongside other packages and now needs its own conda env
- breaks one of the rules on how we develop with 'apps', nl that all apps are not aware of each other and that the glue should be created in `cg`. (imports `cglims` and `cgstats`)
- now bash functions are gluing cgstats to deliver, meaning that we use cgstats to find which samples are on a FC or in a project. We have been increasingly been relying on `cg` as the one true source for what samples belong to which FCs and projects. Glue should be `cg`.

Suggested solution:
For manual delivery `cg` would need a CLI. Something along these lines:

`cg deliver [inbox|auto] --type [fastq|bam|...] [--customer custXXX] [--sample XXX] [--external-name XXX] [--project XXX]` 

with
- `--type` a HK tag. Maybe `--type` is a bad name then?
- ~~`auto`:  what we have in statusdb. For this US: skip it.~~

We can go two way to create the CLI:
1. we make deliver into a proper agnostic package
  - py3
  - data coming from cglims and cgstats should be given as a string to a new CLI of deliver
  - `cg` would act as glue and call the deliver package with correct params
  - `cg` would need to have a CLI as well
  - advantage would be to take some complexity out of the bulky `cg`
  - disadvantage: a lot of overhead. Automation and looping would be done in `cg`
2. we move deliver functionality into `cg`
  - create a `cg` CLI
  - advantage: less work. Nice and concise.

Q1: what does the deliver package do now?
A1: FRom `deliver --help`
```
  ext        Linking files from externally sequenced...
  inbox      links files to cust/INBOX/project
  ls         List the fastq files.
  microbial  Link FASTQ files to microbial substructure.
  mip        Links from DEMUX to MIP_ANALYSIS and customer...
  pooled     Return whether or not this lane is pooled.
```
- mip linking is not needed anymore.
- ls is used in cleaning up X FCs. Will be made redundant once we have fastq files in HK.
- As far as I can tell, `pooled` is only used in the `deliver_*` bash functions and can be removed.
- microbial should be moved to `cg`. discussions about this ar part of the TB discussions.

Q2: Is the `deliver ls` available in some form in the `cg` package?
A2: Maybe. When we start using HK as the sole source for fastq files, there is no need for a `deliver ls` or `cg deliver ls`. I would drop the command in the rewrite.

DoD:
major: changing the way we deliver.

**Comment by patrikgrenfeldt** [comment]
Could we describe this issue further?

**Comment by ingkebil** [comment]
;)

**Comment by emiliaol** [comment]
Is this what we want to do?

**Comment by patrikgrenfeldt** [comment]
Suggestion: As a (role) I'd like (thing to happen) so that (I get reward)
BR

**Comment by ingkebil** [comment]
So, this is technical debt from wen we switched fom cg to cg2, from bash to python.
What I would like to achieve is to gain the same functionality from the bash functions but moved into the cg package, so that we can do `cg deliver fastq --customer cust001 --sample XXX --external-name XXX --project XXX`.

Additionally, deliver is written for py27 and uses mysql-python as dependency, which clashs with pymysql we are using everywhere else.

I would leave the bash written delivery scripts in here (mh-delivery, concat, ...) but absorb the python part.

I realize this is written from the perspective of a technical lead perspective and not from an end user. For solving technical debt, I think that is fine.

I'll add a proper US and title.

**Comment by ingkebil** [comment]
... ok. This needs to be split up :) More to come!

**Comment by emiliaol** [comment]
@ingkebil You mentioned something about creating new US for this? What's the progress on that? Should we archive this card?

**Comment by ingkebil** [comment]
I'll have a look and split it up if needed

**Comment by emiliaol** [comment]
@ingkebil @patrikgrenfeldt Do we have this somwhere else? I'd like it to happen at some point :)

**Comment by henrikstranneheim** [comment]
Stale and not very well defined and also a duplicate of #794. Closing
