### ISSUE TITLE
In order to make life easier under GDPR we need to move AWS services back in-house

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#88]
We have both the **cgstats** and **microbial QC** databases on AWS now. These probably don't contain any personal data but should still be moved to in-house storage for safety reasons and to not even run the risk of this being a problem under GDPR.

Actions:
* Create or move the databases to suitable server
* Update processes that write and read data from these databases
 * mwgs
 * demultiplexing
 * other?
* Document the changes

**DoD:**
* Changes in code reviewed and merged
* All affected processes have passed Acceptance tests
* Document has been updated and approved
* End users (production bioinfo team) has been informed about the changes.

**Comment by emiliaol** [comment]
Moved this user story to the GDPR epic as storage on cloud services might be an issue under GDPR.

**Comment by emiliaol** [comment]
@ingkebil We did this already, right?

**Comment by ingkebil** [comment]
yup, done
