### ISSUE TITLE
Coverage report missing for cancer scout

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/cg#880]
Hi (from cust087, do I have to write the cust no everytime?) 

We have seen from the 2 first myeloid samples that we have analysed in cancer scout, that the quality metrics are missing from the pdf report. How do we conclude that the data presenterd is approved technically from a coverage point of view?
According to Bianca Tesi, for GMCK panel the coverage of genes is represented in the PDF file, and for the other panels/runs there is a summarized coverage for the specific panel/run. 

Hälsningar Hero

**Comment by heronikdin** [comment]
> > But can someone please tell me what does chanjo provides that mosdepth can't? Seems like double work to use an external heavy designed tool to just read coverage data.
> 
> Since one of our masters students made it, and the present solutions we have use it? 😉
> 
> But if there are issues with Sambamba (that we currently use) we should definitely consider replacing it. Perhaps make an issue on chanjo (or Sambamba), specifying the problems, and we see if or when they can be solved?
> 
> The real advantage with loading to chanjo is that the data goes into an aggregate database, and can be queried online later, so we can generate e.g. custom coverage reports for HPO panel searches on the fly via Chanjo-report in Scout.
> 
> Anyway, this is a sample coverage report:
> ![Screenshot 2020-12-10 at 16 29 36](https://user-images.githubusercontent.com/758570/101792707-4f862a00-3b05-11eb-8994-a8bb4ebb7782.png)
> 
> This can be interactively customised since its a Chanjo-report, but I think Hero would be very happy also with a static html or pdf delivery report with coverage% at a few set coverage levels. For panels I imagine the current fixed fold coverage levels would be rather low. Say 30x, 90x, 150x, 1500x, 3000x, 6000x instead? Or @heronikdin, any levels you would you like to see?
> 
> It is similar on the static delivery reports (html) from cg. Why not have a look in Scout on an RD case yourself: I couldn't find a delivery report for a demo case off the bat.

hi, sorry I am a bit lost in everything that has been written here, I dont think I understand it all. But it would be very nice to see the coverage % for 500X and above.

**Comment by hassanfa** [comment]
@heronikdin you can check coverage in MultiQC report in the side left panel: 
![image](https://user-images.githubusercontent.com/1086877/102220966-d4948900-3ee1-11eb-88dc-4b38c0548bb5.png)

and check mosdepth in MultiQC report:
![image](https://user-images.githubusercontent.com/1086877/102221010-e6762c00-3ee1-11eb-9b56-9002f4ae32da.png)

Coverage distribution example:
![image](https://user-images.githubusercontent.com/1086877/102221099-04dc2780-3ee2-11eb-81fb-cf8f0e8cf9ff.png)

I know it is not close to what you want, but this plot can show coverage drop and how good/bad it is.

**Comment by heronikdin** [comment]
> @heronikdin you can check coverage in MultiQC report in the side left panel:
> ![image](https://user-images.githubusercontent.com/1086877/102220966-d4948900-3ee1-11eb-88dc-4b38c0548bb5.png)
> 
> and check mosdepth in MultiQC report:
> ![image](https://user-images.githubusercontent.com/1086877/102221010-e6762c00-3ee1-11eb-9b56-9002f4ae32da.png)
> 
> Coverage distribution example:
> ![image](https://user-images.githubusercontent.com/1086877/102221099-04dc2780-3ee2-11eb-81fb-cf8f0e8cf9ff.png)
> 
> I know it is not close to what you want, but this plot can show coverage drop and how good/bad it is.

Thank you Hassan for this, it helps a bit, but we still would like to see some quality metrics in the report in order to be able to decide wether or not we should dismiss samples based on quality. 
A table as the one shown above would be good, this way it is in the scout report also for the clinicans here to see. 

Regarding the coverage of genes being presented, is this something that can be done? Again, I didnt really understand all the conversations above, so sorry for the repeated question..

**Comment by hassanfa** [comment]
Yes, we need to tune the software we have to generating the report to provide gene level coverage report.

The reason is the genes are partially covered, and sometimes there are intronic or intergenic regions in the panel data. And our software is not aware of that.

**Comment by hassanfa** [comment]
This is linked to issue https://github.com/Clinical-Genomics/cg/issues/930 

report looks like this and @heronikdin agreed with this as a good working start: 
![image](https://user-images.githubusercontent.com/1086877/106614777-0504b500-656c-11eb-9ba7-2f2262c201d1.png)

**Comment by Mropat** [comment]
@hassanfa is this solved?

**Comment by dnil** [comment]
Not really - unless this is one of a number of duplicate issues. The static reports are a really nice workaround, but actually uploading to chanjo will add useful functionality already available on the RD side, like checking a particular gene, transcript or panel. The issue may or may not be blocked by https://github.com/Clinical-Genomics/project-planning/issues/81.

**Comment by hassanfa** [comment]
Regarding providing coverage to customers this is done.

But as chanjo thing, it is not. I suggest we close this and have a more concise issue elsewhere maybe? Long issues start to get vague in my simple brain 🥲
