### ISSUE TITLE
bug/Unable to set data analysis on family from available options

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#883]
Currently there is a bug in the web ui for cg where one is not able to set the data analysis on a family from the vialable presets. This is a bug that appeared as the data analysis column was moved to family from sample.

Attempt to set the analysis to mip-dna:

![image](https://user-images.githubusercontent.com/45558267/101890503-100d1b80-3ba1-11eb-8a4d-501fa4428d32.png)

Result:

![image](https://user-images.githubusercontent.com/45558267/101890604-316e0780-3ba1-11eb-99e0-af7cef087ffe.png)

**Comment by Mropat** [comment]
is this done @patrikgrenfeldt ?

**Comment by patrikgrenfeldt** [comment]
resolved by #885
