### ISSUE TITLE
Upload MicroSalt and BALSAMIC data to Vogue

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#893]
Anna Ly, Isak, and I had a meeting today looking into Vogue data. This is related to multiple fairly high priority issues that were not moved in the past. And mostly related to missing Vogue data that needs to be loaded via `cg`.

It would be wonderful to prioritize loading QC data into Vogue for all workflows. BALSAMIC and MIP are same procedure.

Related issue: https://github.com/Clinical-Genomics/cg/issues/787 and https://github.com/Clinical-Genomics/cg/issues/800

Related PR for MicroSalt: https://github.com/Clinical-Genomics/cg/pull/664

It would be great to prioritize loading data into Vogue via `cg`

**Comment by hassanfa** [comment]
@annaengstrom @sylvinite any thing more, please add them here.

**Comment by hassanfa** [comment]
@Mropat dankeschön! 🙏🏽

**Comment by Mropat** [comment]
Steps to implement:
- [ ] Create a new field in StatusDB Family table for tracking Vogue upload status 
- [ ] Create VogueUploadAPI for uploading data to Vogue via cg

**Comment by annaengstrom** [comment]
There are too many samples going through production now for lab staff to be able to manually look at data, it is not feasible. We need microbial and balsamic data in vogue asap for us to be able to troubleshoot, follow robustness and to optimize our methods.

**Comment by henrikstranneheim** [comment]
@emmser Would you consider this part of the cancer-in-weekly-production project or outside of the scope of this project?
