### ISSUE TITLE
Bam files missing for mtDNA

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/cg#898]
I have noticed that BAM files for mtDNA are missing for several cases. I have now checked and all cases uploaded in Scout after 20th of November miss BAM files for mtDNA. Could you please check what has happened.

**Comment by dnil** [comment]
See eg 
```
$ cd /home/proj/production/housekeeper-bundles/rarewombat/2020-12-05
$ ls *MT.ba*
ACC7308A4_lanes_1234_sorted_md_brecal_subsample_MT.bam  ACC7308A4_lanes_1234_sorted_md_brecal_subsample_MT.bam.bai
$ grep mt_bam scout_load.yaml 
$ grep cram scout_load.yaml 
  alignment_path: /home/proj/production/housekeeper-bundles/rarewombat/2020-12-05/ACC7308A4_lanes_1234_sorted_md_brecal.cram
```

**Comment by dnil** [comment]
I don't quite know how to categorise the urgency: someone else may be better at that.. The feature has apparently not been used for a couple of months, but on the other hand it can potentially be rather urgent if there is a finding in a particular patient. If that happens before we have it fixed @1ctw, just let us know: the files are there so we should be able to arrange something temporary very quickly for a few cases if need be!

**Comment by northwestwitch** [comment]
I think the urgency is quite high, and we might need to write a script to update the MT alignment field for all the cases which are missing it

**Comment by dnil** [comment]
Yes, very likely: it is that or have production reload all cases from then til now after it is fixed in cg.

**Comment by 1ctw** [comment]
The mtDNA BAM files are only important for the cases run on muscle DNA so it is not necessary to reload all cases.

Do you need information about which samples need to be reloaded? It is okey if you fix it for all new samples and for muscle samples from 20th of November. It could not be that many samples?


Från: Daniel Nilsson <notifications@github.com>
Skickat: den 17 december 2020 10:33
Till: Clinical-Genomics/cg <cg@noreply.github.com>
Kopia: Helene Bruhn <helene.bruhn@sll.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/cg] Bam files missing for mtDNA (#898)


Yes, very likely: it is that or have production reload all cases from then til now after it is fixed in cg.

**Comment by dnil** [comment]
That sounds like a good plan! We fixed the cg issue now, so we could just reupload those case and call it a day. Just looking at what is flagged as tissue_type: muscle in the scout db that would be like 10 cases, right?

**Comment by 1ctw** [comment]
Yes, I think it would be these eleven samples:

20224-I-2A
15130-I-1A
20225-I-1A
20228-I-1A
20232-I-1A
20234-I-1A
20235-I-2A
20236-I-1A
20237-I-1A
20238-I-2A
20242-I-2A

Thanks!

**Comment by dnil** [comment]
💯 
I got these:
![Screenshot 2020-12-17 at 16 44 32](https://user-images.githubusercontent.com/758570/102510122-920cb100-4087-11eb-8373-a4a8302a5338.png)

Likely 20236 and 20242 will arrive later? If so, they will be correctly loaded off the bat.

**Comment by 1ctw** [comment]
Yes, sorry that´s correct. The two last ones are not uploaded in Scout yet.
