### ISSUE TITLE
New field "ticket" in Family table in StatusDB

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#918]
Problem: 
Family table in StatusDB has no ticket field. Since all families are created at order submission, when ticket is known, this is possible to set right away. Currently ticket number is only available on Sample level. 
Moving ticket to family level makes it easier to build queries, and allows us to use "name" field in family table for order/pool names

(This has to be in place in order for fluffy workflow start to work properly)

**Comment by vwirta** [comment]
Hmm...Do you mean move or copy?  I think the ticket on sample level is very useful. Also, we have some times families where the samples have been submitted on different tickets.

**Comment by Mropat** [comment]
Duplicated!
The logistics need to be discussed. Perhaps we don't need to duplicate this, but it concerns the way we process fluffy RML and store the samplesheet

**Comment by henrikstranneheim** [comment]
@Mropat Could you add the effort and urgency labels?

**Comment by Mropat** [comment]
This is not needed. Solved in a different way now

**Comment by henrikstranneheim** [comment]
Nice! One down....
