### ISSUE TITLE
Remove fastq-files from cg deliver analysis -d balsamic 

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/cg#922]
Since the fastq-files are very large, we would like to remove fastq-files to be delivered when using `cg deliver analysis -d balsamic `

Customers are very rarely requesting the fastq-files. If they also need the fastq-files, the `-d balsamic-qc` could additionally be used after  `-d balsamic`

**Comment by henrikstranneheim** [comment]
@keyvanelhami Could you add a gain and urgency label?

**Comment by Mropat** [comment]
Done
