### ISSUE TITLE
Upload workflow specific data into Vogue

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#926]
## Problem
We'd like to only upload workflow specific data to Vogue. This is important to rapidly upload MicroSalt, BALSAMIC, and MIP (dna and rna).

## Why
The reason is that it can be useful to upload data to Vogue by restricting date, workflow, and case name. As a Vogue developer, sometimes I might want to reupload specific cases due to various reasons such as missed data, change of models in Vogue, or flat out rebuilding the database (which will be rare).

Also, limiting based on workflow and date can help handle large uploads by setting a date limit.

## How
If it is ok, I can explain by example:
1. Upload only a certain workflow: `cg upload vogue --workflows mip-rna,mip-dna`
- [x]  Upload only starting from a certain date for all workflows: `cg vogue --start-date 2020-01-01`
  - `cg upload vogue bioinfo-all`
2. Upload only a workflow and a certain date: `cg upload vogue --start-date 2021-01-01 --workflows microsalt`
- [x] Upload only a certain case: `cg upload vogue --case-name angrybird`
  - `cg upload vogue bioinfo --case-name`

**Comment by Mropat** [comment]
Hi!
Can you please clarify the feature you want in a feature request/ bug report format?

**Comment by barrystokman** [comment]
@hassanfa Can you add more information to this issue? We have looked at it, but need more info to plan this, and work on it.

**Comment by hassanfa** [comment]
Apologies for not noticing your message @Mropat . Thanks for the reminder @barrystokman !

I updated the text. If this is not helpful, we can discuss on Slack and I'll update the text accordingly.

**Comment by Mropat** [comment]
Note to self: break up into multiple issues

**Comment by henrikstranneheim** [comment]
@hassanfa Let's create new issue for workflow features
