### ISSUE TITLE
BALSAMIC status command update

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#930]
BALSAMIC CLI command for report delivery will be updated according to the example below ONLY for "TGA" and "WES" runs:

1. Tumor-normal:
```
balsamic report deliver \
--sample-config /home/proj/stage/cancer/cases/angrybird/angrybird.json \
--sample-id-map lims_id_tumor:tumor:customer_id_tumor,lims_id_normal:normal:customer_id_normal 
--case-id-map target_panel_short_name:customer_case_id:app_tag
```

2. Tumor-only:
```
balsamic report deliver \
--sample-config /home/proj/stage/cancer/cases/angrybird/angrybird.json \
--sample-id-map lims_id_tumor:tumor:customer_id_tumor
--case-id-map target_panel_short_name:customer_case_id:app_tag
```

HTML report will be in the following path: 

`/home/proj/{stage..production}/cancer/cases/<case_name>/analysis/delivery_report/<case_name>_qc_report.html`

Example: `/home/proj/{stage..production}/cancer/cases/angrybird/analysis/delivery_report/angrybird_qc_report.html`

**Comment by moonso** [comment]
Nice job!

**Comment by hassanfa** [comment]
The following should happen:
1. Add balsamic delivery report to standard set of deliveries
2. Communicate with Scout team to make sure this is added as a tag and existing in case page
3. `cg` to provide this file to Scout

Multiple small moving parts, but making `cg` to generate these files is the first step.

Also, `S_BALSAMIC` has a working branch installed. Feel free to test it, as soon as PR is ready to merge in `cg`, I'll install it in Prod as well.

**Comment by moonso** [comment]
So CG is generating the files by running BALSAMIC?

**Comment by hassanfa** [comment]
Yes. cg is already running that command. It just needs to provide  the newly added cli options to balsamic.

**Comment by hassanfa** [comment]
Store also should work. The following tag is added:
```
            "path": "/home/proj/stage/cancer/cases/actualgecko/analysis/delivery_report/actualgecko_qc_report.html",
            "step": "balsamic_delivery",
            "format": "html",
            "tag": [
                "delivery_report"
            ],
            "id": "actualgecko"
```

**Comment by hassanfa** [comment]
Scout and BALSAMIC are both updated and ready. This is ready to implement in cg @Mropat

**Comment by Mropat** [comment]
done and done
