### ISSUE TITLE
Automate Balsamic data delivery

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#931]
note: Break up into multiple issues

**Comment by henrikstranneheim** [comment]
@Mropat Could you split this and make new issues and then close this one

**Comment by Mropat** [comment]
Relevant features:

- [ ]  cg deliver -d balsamic <case_id> links analysis output to cust folder on hasta (DOne)
- [ ]  cg deliver -d fastq <case_id> links raw fastq data to cust folder on hasta (Done)
- [ ]  cg deliver rsync <ticket_id> uploads all cases of given ticket to caesar (worked on by @henningonsbring )

- [ ] cg upload scout <case_id> uploads case to scout (Done)

A crontab could automatically upload latest analyses depeding on data_delivery value. Is it safe to do without production looking at something manually? @hassanfa @emmser @keyvanelhami 

All data delivery actions should be logged and timestamped. It should be decided how and where to store this information @henrikstranneheim @barrystokman @patrikgrenfeldt 

When a delivery is made automatically to caesar, a report should be generated containing dir structure uploaded and size of files uploaded. This report can be mailed. Or perhaps uploaded to Vogue (or any service on CIGRID?) to enable production to view automatic deliveries retrospectively, perhaps in contest of trailblazer analysis and delivered message. 

This issue needs further research and discussion, to establish how the desired feature should be implemented
 @henningonsbring @henrikstranneheim @hassanfa @mayabrandi @emmser

**Comment by henrikstranneheim** [comment]
@henningonsbring and @Mropat The `cg deliver rsync` is complete right? 

I think we should discuss the crontab and logging, next monday improvements session

**Comment by henningonsbring** [comment]
@henrikstranneheim yes it is complete!

**Comment by Mropat** [comment]
@henrikstranneheim everything is completed except for the cronjob/systemctl unit file to perform all the steps automatically
We also need to settle on a way to keep track of what has been delivered/needs to be delivered, for all workflows

**Comment by henrikstranneheim** [comment]
@Mropat Since this is done, let us close this and open up new issues for the crontab and delivery
