### ISSUE TITLE
Refactor Vogue upload and move it into its own service

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#933]

**Comment by hassanfa** [comment]
Does this concern Vogue repo or only cg part of it?

**Comment by barrystokman** [comment]
That's one of the things we need to discuss. I'll gladly move it to the vogue repo if/when needed!

**Comment by hassanfa** [comment]
Ideally for anything that involves Vogue base, please involve me as well.

I'd like to avoid repetitive work and prioritize Vogue development. I'll be working more on Vogue in the near future, and plans are sort of set.

**Comment by moonso** [comment]
I think this has to do with how cg or the infrastructure talks to the Vogue app, so it should not affect the code in vogue. We are discussing to split out the functions in CG, such as `upload scout` and `upload vogue` etc, to be its own services.

**Comment by Mropat** [comment]
Vogue app currently not maintained, no new features are planner or prioritized urgently
