### ISSUE TITLE
Decouple lims fom cg

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cg#941]
Decouple lims from cg
---------------

- [ ] move the lims code in cg into cg_lims
- [ ] make the rest endpoint for cg to query
- [ ] make a lims api in cg to query the cg_lims rest api

The limsAPI in cg should get its data via cg_lims-REST api. 
cg should not depend on the genologics package

Steps to reproduce
  1. Identify the logical loauts that cg will use. Probably sample, family, pool..
  2. Create the first minimal rout in cg_lims and replace the affected functions in limsAPI in cg. Make them query the new rout.

**Comment by mayabrandi** [comment]
Could the following be sample level udfs?
prep_method
sequencing_method
delivery_method
capture_kit

Discuss with @emmser

**Comment by mayabrandi** [comment]
GET - ROUTS:
Project
Pool
Sample 
Family

PUT - ROUTS:
Sample

**Comment by mayabrandi** [comment]
![Skärmavbild 2021-02-03 kl  15 17 36](https://user-images.githubusercontent.com/1306333/106759371-f92ff600-6632-11eb-9fbb-991cb5c39f04.png)
![Skärmavbild 2021-02-03 kl  15 17 15](https://user-images.githubusercontent.com/1306333/106759376-faf9b980-6632-11eb-9357-f106f26cbf1c.png)

**Comment by Mropat** [comment]
Solving this requires large-scale architectural alterations, will not be fixed in this version of cg/orderportal
