### ISSUE TITLE
cg upload doesn't replace coverage data for re-runs

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/cg#95]
Whenever a re-run analysis is completed and cg upload uploads it to scout, then the coverage subroutine is invoked from cg upload without the (replace) -r True parameter, so the coverage data is not uploaded in chanjo db and chanjo-report uses old analyses when used to create coverage reports from scout. For more info check https://github.com/Clinical-Genomics/scout/issues/699.

**Comment by ingkebil** [comment]
Pushed to prod
