### ISSUE TITLE
Add downsampled mitochondrial bam file to scout load config

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#96]
MIP will produce a bam file with a reduced number of reads for chr MT. This file needs to be fed into scout via the load config. Scout will look for a key called `'mt_bam'` and display from that when users look at MT alignment.
More in https://github.com/Clinical-Genomics/scout/issues/608

**Comment by ingkebil** [comment]
Thanks!

**Comment by henrikstranneheim** [comment]
@emiliaol This done I think. Right?

**Comment by emiliaol** [comment]
It's done
