### ISSUE TITLE
Validate orders when pushing submit in orderportal

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#961]
Orders should be validated with same validation models in the backend when pressing `submit` as the ones that is used when uploading an orderform (#924 ).

## This can be closed when

- [x] Orders are validated with pydantic models in CG when pressing "submit" in the orderportal

**Comment by henrikstranneheim** [comment]
@moonso What is the status of this one? Could you add a better description? What validation is missing (front-end or back-end)

**Comment by moonso** [comment]
Updated

**Comment by henrikstranneheim** [comment]
Can this be considered complete as now have implemented this: https://github.com/Clinical-Genomics/cg/pull/1313

**Comment by henrikstranneheim** [comment]
Checking with @patrikgrenfeldt and this is done
