### ISSUE TITLE
Add start-available for cg workflow mip-rna 

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#969]
Enabling starting of all available rare disease RNA case via cg would save time and reduce the effort in starting mip-rna analyses

**Problem:** 
This functionality is currently not implemented in cg

**Expected outcome / suggested solution:**
- `cg workflow mip-rna start-available` will start all rare disease RNA cases that are ready to be analysed

**Comment by Mropat** [comment]
Implemented in #986 

```
cg workflow mip-rna start-available --help
Usage: cg workflow mip-rna start-available [OPTIONS]

  Start full analysis workflow for all cases ready for analysis

Options:
  -d, --dry-run  Print to console instead of executing
  --help         Show this message and exit.

```
