### ISSUE TITLE
Add resolve-compression for cg workflow mip-rna

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#971]
Enabling start of a rare disease RNA case without performing preprocessing, such as decompression from SPRING and addition to Housekeeper via cg would save time and reduce the effort in starting a mip-rna analysis.

**Problem:**
This functionality is currently not implemented in cg

**Expected outcome / suggested solution:**
- `cg workflow mip-rna resolve-compression` will start a rare disease RNA cases that are ready to be analysed without having to manually run cli commands for decompressing SPRING files and adding corresponding fastq files to Housekeeper

**Comment by Mropat** [comment]
Fixed in #986 

Resolve compression is added to EVERY workflow

```
cg workflow mip-rna --help
Usage: cg workflow mip-rna [OPTIONS] COMMAND [ARGS]...

  Rare disease RNA workflow

Options:
  --help  Show this message and exit.

Commands:
  config-case          Generate a config for the case_id
  link                 Link FASTQ files for all samples in a case
  resolve-compression  Handles cases where decompression is needed...
  run                  Run the analysis for a case
  start                Start full MIP-RNA analysis workflow for a...
  start-available      Start full analysis workflow for all cases...
  store                Store results from MIP in housekeeper

```
