### ISSUE TITLE
API for NIPT Tool

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cg#977]
We need a API for communicating with [NIPTool](https://github.com/Clinical-Genomics/NIPTool)

## Problem: 
Cg needs to communicate with NIPTool to upload data.

## This issue can be closed when

There is a NIPTool api in CG that can communicate the relevant information with NIPT

**Comment by henrikstranneheim** [comment]
I think this was done here: https://github.com/Clinical-Genomics/cg/pull/1182/files. @mayabrandi Correct?
