### ISSUE TITLE
cant see coverage report 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/cg#987]
hi,

I have created an issue in the "orderportal" of github aswell, but I thought I would create on here as well..... 

We do not see the coverage report from the samples uploaded in scout. I have been told to create an issue on here regarding this issue. Please see below.

![image](https://user-images.githubusercontent.com/62098218/108713792-039a2d00-7519-11eb-95e5-dfccc0d2bbba.png)

**Comment by dnil** [comment]
Something not quite working with https://github.com/Clinical-Genomics/cg/issues/930?

**Comment by heronikdin** [comment]
Thank you for forwarding!

**Comment by dnil** [comment]
And thank you right back for reporting!

**Comment by dnil** [comment]
Hi @heronikdin! After some debate (thanks @Mropat and @moonso) a we ended up with showing the nice new Balsamic QC report from Balsamic (thank you @hassanfa and @keyvanelhami) as the de facto delivery report for the cancer cases.

There you will find overall coverage statistics. You will find the reports on the same menu in Scout:
<img width="163" alt="Screenshot 2021-02-24 at 13 56 37" src="https://user-images.githubusercontent.com/758570/109004200-b8168900-76a8-11eb-8e24-db48c2713108.png">

And the reports look like this:
<img width="867" alt="Screenshot 2021-02-24 at 13 31 38" src="https://user-images.githubusercontent.com/758570/109003594-ecd61080-76a7-11eb-83d7-97ea5f19c76f.png">

It will be a longer project getting the customisable coverage reports that you are used to from RD for Balsamic, but we will get there. Hopefully the coverage qc report will be enough for you for some time. They should start appearing for new or rerun cases soonish.

I will close this issue now, but we will get back later with more on the dynamic coverage reports (chanjo) for Balsamic!
