### ISSUE TITLE
The "deliver_fastqs_project"-command will create links for fastq-files for delivery that failed QC, leading to samples that failed QC are getting rsynced to customer

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#989]
## Description
The "deliver_fastqs_project"-command will collect fastq-files that failed QC. Should we change these old bash-scripts?

Old issue:
20ET100908 was used as name twice (ACC7453A23 and ACC7610A16). After demux ACC7610A16 had 0 reads in lims and statusDB, and could not be found in housekeeper. Running microsalt (`cg workflow microsalt start -t 154135`) lead to a QC report that did not have ACC7610A16. Also ACC7610A16 ended automatically up in the "define run format and calculate volumes"-step in lims (i.e. queued for a top-up).

This is an error since data can be found in `/home/proj/production/demultiplexed-runs/210219_A00689_0234_AHWHMWDMXX/Unaligned-Y151I10I10Y151/Project_154135/Sample_ACC7610A16`

**Comment by henrikstranneheim** [comment]
@henningonsbring @barrystokman @karlnyr Would this be solved by the checks here: https://github.com/Clinical-Genomics/demultiplexing/issues/143 or is this a new check that should be added?

**Comment by henrikstranneheim** [comment]
@henningonsbring Could you add the urgency label?

**Comment by karlnyr** [comment]
@henningonsbring This is not an error though? The quality of the reads of the said sample failed.

**Comment by karlnyr** [comment]
Whether or not the data exists in the path you gave, the facts stand that the read quality of assigned reads is too low and should thus not be added to housekeeper.

**Comment by henningonsbring** [comment]
You are right. Then the only question left is if we should do something with the automated delivery-script that deliver this data?

**Comment by karlnyr** [comment]
I agree that the automated script should not, but that would probably be implemented when the delivery is implemented into cg. Which this issue could be connected to?

**Comment by henrikstranneheim** [comment]
@henningonsbring Could you clarify the issue header more? I have a hard time following what is the actual issue and what needs to be done.

**Comment by henningonsbring** [comment]
I will start working on an automated solution to send files to customers, to goal is that one command should be enough to identify the files that should be sent, then all the processing that might be needed should be done and finally the rsync. As it is right now multiple commands are done after each other manually by production, and many checks are done manually, and we rely on remembering several things that can be forgotten. So this should change!

Before I start writing the code I would like to discuss with @moonso.

**Comment by Mropat** [comment]
@henningonsbring  is this done?

**Comment by henningonsbring** [comment]
With `cg delivery` this is not a problem anymore
