### ISSUE TITLE
Unable to upload cancer case to Scout

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/cg#996]
## Description
**Please prioritize this issue since it's a high prio clinical production sample**

Case `comicdonkey` did first fail the analysis, and the analysis was then restarted and is now completed. The `analysis_finish` is also created.

Now, when running `cg upload scout comicdonkey`, below error appear:

```
----------------- UPLOAD ----------------------
----------------- SCOUT -----------------------
----------------- CREATE CONFIG -----------------------
Fetching family object
Create load config
Could not find analyses for comicdonkey
```

## This can be closed when

When the case is uploaded in Scout

**Comment by Mropat** [comment]
Case comicdonkey was completed in Cigrid, but the crontab for storing analyses in Housekeeper runs every 4h. The case completed, but the upload was attempted before the files were added to Housekeeper. 
Solution:
- Check if bundle exists in Housekeeper
- Run cg workflow balsamic store comicdonkey
- Retry scout upload
Long-term solution:
- Discuss decreasing the interval for running crontab to 10min
