### ISSUE TITLE
Problematic case in statusdb "ideamutt" possibly with bad Data analysis field

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#997]
`ideamutt` seems to be problematic. When retrieving it from Statusdb, workflow_name is NoneType

Exmaple:

```Python
def get_workflow_name(status_api:Store, case_name:str) -> str:
     case_obj = status_api.family(case_name)
     workflow_name = None
     if case_obj.analyses:
         workflow_name = case_obj.analyses[0].pipeline
     return workflow_name


store = context.obj["status_db"]
workflow_name = get_workflow_name(store, "ideamutt")
print(workflow_name.lower())
```

Error:
```
    return workflow_name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

Above works for other cases, example: "actualgecko"

This error is despite of idealmutt is being set to MIP_DNA in statusdb:
![image](https://user-images.githubusercontent.com/1086877/109487609-bcfe8280-7a84-11eb-8918-fd76fc83e78f.png)

**Comment by hassanfa** [comment]
Any idea what would cause this? I'm trying to get list of all cases from statusdb for each workflow for crosschecking them with what Vogue has.

Did we update statusdb recently?

**Comment by Mropat** [comment]
No, i think the problem is that if there are no analyses, you will get None as return

easier to get the workflow name as case_obj.data_analysis

**Comment by hassanfa** [comment]
And how can I retrieve workflow_version?

**Comment by Mropat** [comment]
Workflow version can be retrieved from analysis object. But also, only when analysis exists

**Comment by hassanfa** [comment]
Ta!
